### ISSUE TITLE
childreneditor clientlib issue on author dispatcher

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#1001]
## Bug Report

**Current Behavior**
Currently childreneditor clientlib does not have allowProxy property on it. Because of this, Children Editor does not show up on Core components when accessed through dispatcher URL on author.

**Expected behavior/code**
Chidren Editor should show for Tabs and Accordion on Dispatcher URL it these contain children.

**Environment**
- AEM version and patch level (e.g. AEM 6.3 SP1 CFP2)
- Core Components version (e.g. 2.0.4)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Possible Solution**

All allowProxy=true on childreneditor clientlib so that this clientlib is accessible on dispatcher.

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by numirov** [comment]
Hi @rajeevyadav2 

If i am not mistaken `allowProxy` just makes clientlib accessible through `etc.clientlibs`. So with this property clientlib will be accessible by anonymous users on `publish` env. But it shouldn't matter on author as you are always logged in there. I reckon it has something to do with dispatcher, it might be blocking some requests.

**Comment by rajeevyadav2** [comment]
@numirov : if allowproxy is not available then request will try to load the clientlibs from /apps path. /app path is blocked on dispatcher and therefore it never loads.

**Comment by rajeevyadav2** [comment]
As a workaround we need to embed this clientlib which has allowproxy true but ideally it should be available through etc.clientlibs as well.

**Comment by numirov** [comment]
Hi @rajeevyadav2 

Most of the editor clientlibs don't have allowProxy, so I believe you better change your dispatcher config to allow /apps for author only.

**Comment by jckautzmann** [comment]
> Most of the editor clientlibs don't have allowProxy, so I believe you better change your dispatcher config to allow /apps for author only.

That's correct, thx. I'll close this issue for now.
