### ISSUE TITLE
[Question] Custom attributes for tracking on container components

### ISSUE THREAD

**Issue by fraudoudou** [adobe/aem-core-wcm-components#1025]
I need to add custom data-attributes to container components (container, accordion, …) for tracking. These data-attributes contain dynamic values, so using the decoration tag is imho not possible.

What I'm doing now:
`<div data-region-id="${trackingModel.trackingRegionUuid}" data-sly-resource="${ resource.path @ resourceType='core/wcm/components/container/v1/container'}"><div>`

Result:
```
<div class="container style-container--fixed">
    <div data-region-id="my-region-id">
        <div class="cmp-container"> … </div>
    </div>
</div>
```

This solution adds **another wrapper div**. So I'd like to do something that generates this result:
```
<div class="container style-container--fixed" data-region-id="my-region-id">
    <div class="cmp-container"> … </div>
</div>
```

Or this result:
```
<div class="container style-container--fixed">
    <div class="cmp-container" data-region-id="my-region-id"> … </div>
</div>
```

Is there any possibility to achieve this behaviour? Any ideas?

**Comment by fraudoudou** [comment]
Maybe interesting for someone else. Adding another wrapper div definitely was a bad idea, the core components are pretty sensitive about their structure. The wrapper div breaks:
- Allowed children list in editable template editor
- Reading styles from the policy within a component model (injected currentStyle no longer contains properties)

**Comment by vladbailescu** [comment]
@fraudoudou , you have at least two options:

1. Use the [Adobe Client Data Layer](https://github.com/adobe/aem-core-wcm-components/blob/master/DATA_LAYER_INTEGRATION.md) and add custom data there.

2. Override the templates for the container: [responsive](https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/responsiveGrid.html) & [simple](https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html).

I would recommend you try the first option though as it's more flexible, you might be interested to follow this email thread: [DataLayer Extension Pattern](https://groups.google.com/g/aem-core-components-dev/c/kvhg-OQITIY?pli=1) for a nicer way to build your custom Data Layer object.
