### ISSUE TITLE
Annotate fields as Nullable when InjectionStrategy is OPTIONAL

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1030]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When the injection strategy is marked as optional in a SlingModel, the field should be annotated at potentially nullable. There are numerous cases in the sling models where an injected field is treated as being not null where the strategy is optional.

One example is in `AbstractContainerImpl.currentStyle`, which is marked as optional, but later assumed to be non-null in `AbstractContainerImpl.populateStyleProperties()`.

**Describe the solution you'd like**
For safety, the fields should either 
1) be marked as potentially null and any resolve any warnings that may occur as a consequence
2) make the injection strategy required if the value must not be null

**Are there alternatives?**
No.

**Documentation**
N/A

**Comment by jckautzmann** [comment]
@ky940819 Thx for your feedback. It would be nice if you could provide a pull request with the desired changes.

**Comment by ky940819** [comment]
I already have a local branch with the changes and it does reveal a few possible NPEs which I have solutions for as well. I was holding off on the PR because it causes conflicts with other approved PRs that have now been merged. 

I will clean up the branch and submit a PR shortly.

**Comment by jckautzmann** [comment]
@ky940819 Really cool, thx!

**Comment by ky940819** [comment]
In the processes of correcting possible NPEs that might occur if optional fields are null, I have come across an issue that might need some input. 

[EmptyContentFragment#getNull()](https://github.com/adobe/aem-core-wcm-components/blob/4fb41533640060a5c65dd166cb0b38749896d855/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentImpl.java#L239) must not be annotated `@Nullable` because the interface is annotated `@NotNull`.

Any thoughts on a preferred approach to handle that?
