### ISSUE TITLE
AEM Core components examples ZIP File missing in Repo for 2.9.0

### ISSUE THREAD

**Issue by nhirrle** [adobe/aem-core-wcm-components#1034]
The AEM Core components examples ZIP File is missing in the mvn repo:

1. Open https://repo.maven.apache.org/maven2/com/adobe/cq/core.wcm.components.examples/2.9.0/
2. You do find the pom.xml file there but the ZIP file is missing. 
3. When opening another version, e.g. https://repo.maven.apache.org/maven2/com/adobe/cq/core.wcm.components.examples/2.8.0/ you do see the ZIP File

**Impact**
When adding the examples as a dependency you do get the follwoing error:
```
            <dependency>
                <groupId>com.adobe.cq</groupId>
                <artifactId>core.wcm.components.examples</artifactId>
                <type>zip</type>
                <version>2.9.0</version>
            </dependency>
```
```
[ERROR] Failed to execute goal on project <YOUR-PROJECT>.ui.apps: Could not resolve dependencies for project <<YOUR-PROJECT>-: Could not find artifact com.adobe.cq:core.wcm.components.examples:zip:2.9.0 in adobe-public-releases (https://repo.adobe.com/nexus/content/groups/public) -> [Help 1]

```

**Comment by vladbailescu** [comment]
@nhirrle , starting with 2.9.0 release, we split the examples into:
* https://repo.maven.apache.org/maven2/com/adobe/cq/core.wcm.components.examples.ui.apps/2.9.0/
* https://repo.maven.apache.org/maven2/com/adobe/cq/core.wcm.components.examples.ui.content/2.9.0/

This aligns with the [structure needed for AEM as a Cloud Service](https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html)
