### ISSUE TITLE
[ID] Add validation in order to prevent same HTML-ID on page

### ISSUE THREAD

**Issue by nhirrle** [adobe/aem-core-wcm-components#1041]
## Feature Request

**Is your feature request related to a problem? Please describe.**
With latest core components release 2.9 an AEM author is able to add HTML IDs to all components.
This is a nice feature but error prone as IDs must be unique on the HTML site. Otherwise HTML is invalid and it often leads to JavaScript issues.

**Describe the solution you'd like**
Validation should be performed before submitting the dialog to prevent multiple IDs.
Therefor a custom validator in a clientlib needs to be implemented calling a servlet which accepts page-path + id-value to check if below that page any ID-properties with same value are already added.

**Are there alternatives?**
Yes, various:
* A check within all Sling Models --> lot of queries while rendering. Placeholder-Message needs to be rendered than.
* HTML Transformer Factory could be implemented to prevent duplicate IDs --> Goes pretty deep in the system and question is what should be than done? Rewriting the ID to sth unique? 

**Documentation**
Could look like this:
![grafik](https://user-images.githubusercontent.com/46745410/84008557-53789a00-a972-11ea-8a18-76da39a20b49.png)

**Comment by jckautzmann** [comment]
As a first step, we could implement some client side validation by checking the IDs in the DOM and preventing the dialog to close in case the custom ID is already used in the page.

**Comment by ky940819** [comment]
This issue could get very messy where XFs are concerned.
Performing in-dialog validation might actually make it worse because it gives the impression that anything that passes validation is valid.

**Comment by nhirrle** [comment]
@ky940819 : I do agree that XF or Reference components or any other custom code might lead to errors as well. 
However I believe it is better having a bit of validation covering at least the most common usecases. E.g. copy/paste of a component with an ID should be covered to avoid having invalid HTML.
