### ISSUE TITLE
[Breadcrumb] Start level cannot be zero

### ISSUE THREAD

**Issue by jordanlong610** [adobe/aem-core-wcm-components#1054]
## Bug Report

**Current Behavior**
The breadcrumb uses ./startLevel to determine the root level of the list. The field description states: "The level at which to start the breadcrumb: 0 = /content, 1 = /content/site, etc." However the dialog only allows the minimum level to be 1. 

![image-2020-06-11-18-48-39-000](https://user-images.githubusercontent.com/16962338/84394798-633eeb00-abcb-11ea-8870-448677f87e93.png)
![image-2020-06-11-18-49-25-069](https://user-images.githubusercontent.com/16962338/84394827-6cc85300-abcb-11ea-9508-dffd72ad6661.png)

**Expected behavior/code**
An author should be able to input zero as the starting level

**Environment**
- Adobe Experience Manager, Version 6.5.3.0
- Core Components 2.8.0
- Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)

**Possible Solution**
Updating the min value of the field to be zero in both cq dialog and cq design dialog

**Comment by msagolj** [comment]
Hi @jordanlong610 `/content` is not a page, so breadcrumb would not be able extract any title. That's why it starts at 1, The mentioning of 0 index in the help text is just to inform where the level numbering starts.

**Comment by jordanlong610** [comment]
@msagolj good to know, thanks for clearing that up.
