### ISSUE TITLE
Switch to more inclusive language

### ISSUE THREAD

**Issue by macdonst** [adobe/aem-core-wcm-components#1057]
Could you please take some time in the next few days to make changes to some terminology in your repos and content as much as is possible:

- Whitelist/blacklist to Allowed List and Blocked List (or Approve List/Deny List - some software uses this instead) respectively. Google and many developers are formalizing allowlist and blocklist. You might want to lobby for those terms to be used in the UI.
- Master/Slave to master and replica (or subordinate, if that makes more sense) respectively.

If you cannot remove the term because the writing for example reflects the UI or the code, please make a note and send me an email to Grp-opensourceoffice@adobe.com so we can bring it that team’s attention. Thanks for your efforts in this matter.

**Comment by vladbailescu** [comment]
Closed by f85ef190e378e23e65424dcd76f8b3204eb3b3c1
