### ISSUE TITLE
Experience Fragment - Edit Config - REFRESH PAGE on insert

### ISSUE THREAD

**Issue by mmange** [adobe/aem-core-wcm-components#1069]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Adding an experience fragment to page causes refresh. This is happening due to edit config of experience fragment. 

**Describe the solution you'd like**
Remove the REFRESH_PAGE behavior. I can submit a PR.

**Comment by msagolj** [comment]
Hi @mmange thank you for your feedback. You are right, I checked and couldn't find a reason why on initial drop it requires a REFRESH_PAGE, so please go ahead and submit a PR.
