### ISSUE TITLE
[PDFViewer] Potential NPE

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1071]
## Bug Report

**Current Behavior**
A Null Pointer Exception can occur in `PdfViewerImpl#getDocumentFileName()` ([link](https://github.com/adobe/aem-core-wcm-components/blob/2c1bed6ccb0e63ca971be699fdff73d7fa582ad1/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PdfViewerImpl.java#L109))

This NPE is caused because the `documentPath` field in the sling model is optional, thus it may be set to null. 
No null check is performed before dereferencing.

**Expected behavior/code**
NPEs should not be possible

**Environment**
- AEM version and patch level: 6.5.5.0
- Core Components version: 2.9.0
- JRE version: JDK 11

**Possible Solution**
Do a null check. Will submit PR.

**Comment by msagolj** [comment]
@ky940819 thank you for reporting and providing an PR. Verified and merged the PR.
