### ISSUE TITLE
[Page] Getting child page modals of a page

### ISSUE THREAD

**Issue by rohanraj14** [adobe/aem-core-wcm-components#1083]
## Page to get child pages models

**Is your feature request related to a problem? Please describe.**
We are trying to get list of pages and list of subpages with listing and filtering them as a page for autors.

**Describe the solution you'd like**
We like the Page model should have the public method to get child pages models and the children resources in those child pages.

**Documentation**
I can see there is a related commit- https://github.com/adobe/aem-core-wcm-components/pull/373/files/b24c042756fe9ce6368f2261a3233f7d0a90bcfa
Is this Page v3 going to be available as part of 2.11.0? Or should have to wait till 3.0.0 for it? if yes what's the release date for 3.0.0?

**Comment by sumantapakira** [comment]
This is the [one](https://github.com/adobe/aem-sample-we-retail-journal/blob/master/bundles/core/src/main/java/com/adobe/cq/sample/spa/journal/internal/models/HierarchyPageImpl.java) you are looking for?

**Comment by rohanraj14** [comment]
> This is the [one](https://github.com/adobe/aem-sample-we-retail-journal/blob/master/bundles/core/src/main/java/com/adobe/cq/sample/spa/journal/internal/models/HierarchyPageImpl.java) you are looking for?

I know we can write custom code to get list and properties of the sub pages, but if we have v3 of page component availble we can use that directly without customization. I mean https://github.com/pfauchere/aem-core-wcm-components/blob/b24c042756fe9ce6368f2261a3233f7d0a90bcfa/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/PageImpl.java

Is it going to shipped with 2.11.0 or, 3.0.0?

**Comment by sumantapakira** [comment]
> Is it going to shipped with 2.11.0 or, 3.0.0?
I cannot answer

> I do not want to create my version of page '.model.json' 
You do not have to write your own model.json, just adapt to HierarchyPage

**Comment by rohanraj14** [comment]
But does it requires dependency of AEM sample Journal dependency? 
com.adobe.cq.sample.spa.journal.models.HierarchyPage;
you mean adapt this correct? Or some other class in Core 6.5 package?

**Comment by vladbailescu** [comment]
There are no plans to work on this at the moment. As per https://github.com/adobe/aem-core-wcm-components/discussions/1509, closing to icebox.
