### ISSUE TITLE
[Image] Lazy threshold should be configurable in policy

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1090]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Lazy loading images only load when the image is visible.
There is a property `LAZY_THRESHOLD = 0` in the v2 image.js that can be used to configure this such that values >0 allow the image to begin preloading before the image is in view.

Sometimes it is useful to allow images to begin to load slightly before coming into view so as to anticipate them coming into view without a jarring delay.

**Describe the solution you'd like**
Allow the value of this threshold to be configured in the policy for the image component.

**Are there alternatives?**
Copy the JS and override the value of `LAZY_THRESHOLD`.

**Comment by joerghoh** [comment]
I would recommend to even change the default, so that the picture is loaded a moment before it's going to be displayed.
