### ISSUE TITLE
core.wcm.components.commons.datalayer.v1 Client Library not compatible with AEM 6.4.8.1

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#1092]
## Bug Report

When deploying core component 2.10 to AEM 6.4.8.1 and activating the data layer, the generation of the client library `core.wcm.components.commons.datalayer.v1` fails with a long list of compilation errors in the error.log (see attachment [200706_datalayer-js_aem6481.zip](https://github.com/adobe/aem-core-wcm-components/files/4880359/200706_datalayer-js_aem6481.zip))

The problem is that in AEM 6.4.8.1 the default JS compile is still `min:yui`, and that does not support "modern" JS language.

The client definition should come with a specific jsProcessor definition to ensure `min:gcc` is used instead.

**Environment**
- AEM 6.4.8.1
- Core Components 2.10
- Java 8

**Comment by bpauli** [comment]
@stefanseifert, Thank you for reporting this issue and for the PR!
