### ISSUE TITLE
[Container] Control Container Layout via Content Policy

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#1094]
the container layout can be switched between "Simple" and "Responsive Grid".
this is currently only possible in the *edit dialog* of the component, allowing content authors to switch the layout mode in the page at will, the template authors do not have any control.

the content policy/design dialog of the container component should be extended:
* to specify the default layout mode
* to disable changing the layout mode in the edit dialog by content authors

this problem applies to core components 2.10 and below.

**Comment by bpauli** [comment]
@stefanseifert, Thank you for this enhancement. It will be included in the upcoming 2.11.0 release.
