### ISSUE TITLE
[Teaser] Title is not clickable or hyperlink when external link (outside AEM) is configured in the call to actions link

### ISSUE THREAD

**Issue by satishkumarjadhav** [adobe/aem-core-wcm-components#1102]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Title of the teaser component is clickable or has hyperlink when the first call to actions link is configured with internal link/page within AEM.
If the first call to actions link configured is external link like https://www.adobe.com/ then the title is not clickable or is not hyperlink
This is inconsistent experience on the page where we have multiple teaser component configured with both internal or external link configured in the first call to actions link.

**Describe the solution you'd like**
Update the TeaserImpl.java file to support external link configured in the first call to actions link.

**Are there alternatives?**
As work-around, it has been handled through CSS  but this would be custom implementation that needs to be implemented whoever needs this feature.

**Documentation**
If you can, explain how users will be able to use this and possibly write out a version of the docs.
Maybe a screenshot or design?
There is no change in content authoring or dialog. Only change is in TeaserImpl.java which would take care to support external link in call to actions link.

**Comment by satishkumarjadhav** [comment]
PR https://github.com/adobe/aem-core-wcm-components/pull/1103  raised.

**Comment by jckautzmann** [comment]
This has been fixed with #1106 .
