### ISSUE TITLE
[LayoutContainer] Possible NPE in LayoutContainer model initializer

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1112]
## Bug Report

**Current Behavior**
There exists a possible NPE in the `LayoutContainer` model initializer.
The NPE is encounters only when the following conditions are met:

1. The layout type is not defined in the component properties; and,
2. The layout type is not defined in the style properties; and,
3. The value map provided by the current resource does not support using null as a default value

**Expected behavior/code**
No NPE should occur. The default layout type of `SIMPLE` should be used.

**Environment**
- AEM version: 6.5.5.0
- Core Components version: 2.10.0
- JRE version: JDK 11

**Possible Solution**
Will submit a PR.

**Comment by vladbailescu** [comment]
Merged to master in https://github.com/adobe/aem-core-wcm-components/commit/cddf02b86d2d94b1d865a776eb5d30470e3f53fe
