### ISSUE TITLE
[AMP] Multiple style amp-custom elements per page

### ISSUE THREAD

**Issue by kiransg89** [adobe/aem-core-wcm-components#1116]
## Bug Report

**Current Behavior**
With AMP selector none of the example site are working as expected

**Expected behavior/code**
Should render AMP page

**Environment**
AEM 6.4

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by msagolj** [comment]
@kiransg89 this a very wage description of your issue :) Please add more context: exact AEM version, Core Comp Version, what errors do you observe, reproducible steps ?

The AMP extension has been tested with example project on 6.4.8.1 and 6.5.5, see also working example page at:
https://www.aemcomponents.dev/content/core-components-examples/library/page-authoring/text.amp.html

**Comment by kiransg89** [comment]
Hi @msagolj ,
I am currently working on AEM 6.4.8 and I am using core components version 2.11.0 (Recent release).
I am seeing following issue in AMP for image page:
![image](https://user-images.githubusercontent.com/20896827/88344187-0b8ab800-cd11-11ea-9b87-cffe5d2fa1d8.png)

**Comment by vladbailescu** [comment]
Indeed, as per https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/:

> Define CSS within the <style amp-custom> tag inside the head of the document. **There is only one <style amp-custom> tag allowed on each AMP page.**

**Comment by kiransg89** [comment]
Hi @vladbailescu ,

I did some work around,
like created the clientlib(amp) under page component and embedded all the global clientlibs:
![image](https://user-images.githubusercontent.com/20896827/88397227-a5924500-cd91-11ea-8628-f362e0718a6b.png)

**Comment by vladbailescu** [comment]
@kiransg89 , that's nice but we will still need to fix our library to be compliant to the spec. Thanks for discovering the issue.
