### ISSUE TITLE
all package 2.11.0-b001 not available in Maven Central

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1122]
In https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.11.0 the version 2.11.0-b001 is mentioned containing principal-based authorization. 
I guess this is the preferred version over 2.11.0 as there is usually some performance penalty in case you don't use principal-based service user mapping.
That version is not available on Maven Central though: https://search.maven.org/artifact/com.adobe.cq/core.wcm.components.all

**Comment by vladbailescu** [comment]
Tha [change](https://github.com/adobe/aem-core-wcm-components/commit/f6220676147808d25f4d92f6278b810b7381d93e) only affects two packages.  The updated packages can be found at: https://repo1.maven.org/maven2/com/adobe/cq/core.wcm.components.config/2.11.0-b001/ and https://repo1.maven.org/maven2/com/adobe/cq/core.wcm.components.extensions.amp.content/2.11.0-b001/

**Comment by kwin** [comment]
Does this mean that deployment via https://github.com/adobe/aem-core-wcm-components/blob/master/all/pom.xml is no longer supported?

**Comment by vladbailescu** [comment]
It is, but switching to principal-based authentication is optional.

**Comment by kwin** [comment]
Is it a problem to push a 2.11.0-b001 all artifact?

**Comment by vladbailescu** [comment]
I pushed *2.11.0-b001* `all` a while ago. We also released 2.11.1 which includes all the changes.
