### ISSUE TITLE
(minor) ver 2.9 Incorrect Version in Example Content Package

### ISSUE THREAD

**Issue by tjameswhite** [adobe/aem-core-wcm-components#1123]
## Bug Report
This is very minor, but it caught me off guard -- I though I had installed 2.9.0 but it still showed as 2.8.0. Finally realized that the title had not been updated before being packaged. 

**Current Behavior**
The content package for ver 2.9 (core.wcm.components.examples.ui.content-2.9.0.zip) Component Library page (`/core-components-examples/libary`) still identifies the package as 2.8.0

**Expected behavior/code**
Content should be updated to reflect current version being install (2.9.0)
Content should always be updated with the current version number to avoid user confusion. 

**Additional context / Screenshots**
Incorrect
![should-be-2 9](https://user-images.githubusercontent.com/2693135/88849586-f396b680-d19e-11ea-833c-1cce02e0083a.png)

**Comment by vladbailescu** [comment]
You're right, we missed updating those before the 2.9.0. Since then we put more emphasis on this in our pre-release checklist and 2.10.0 and 2.11.0 should be ok.

**Comment by vladbailescu** [comment]
I've closed this as I don't think it makes sense to go back and do a 2.9.x release just to fix this. At some point we had an idea about getting this information automatically from the installed Core Components bundle/packages. If you would like to contribute such an improvement, we would be thankful to review and add it.
