### ISSUE TITLE
[Accordion/Carousel/Tabs] Adding items doesn't work with the SPA Editor

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#1124]
Steps to reproduce the issue:

1. Create an angular project with the archetype (version 23):
```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=23 \
 -D aemVersion=cloud \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
 -D frontendModule=angular \
 -D includeExamples=n
```
2. Deploy the new project to an AEM instance.
3. Go to the home page of the new project, edit the template and make the Accordion component available to the author.
4. Add an Accordion component to the home page.
5. Open the dialog and click the `Add` button:
![Screenshot 2020-08-06 at 15 57 38](https://user-images.githubusercontent.com/6152300/89540733-bdd87a00-d7fd-11ea-913e-ee19089f41ca.png)

Result: nothing happens when clicking the `Add` button, no new item is created.

The same issue happens with the Carousel and the Tabs component.

**Comment by jckautzmann** [comment]
The pull request #1075 seems related to this issue but after applying the changes, the issue is still available.

**Comment by jckautzmann** [comment]
@pfauchere Hi patrick, could someone from your team have a look at this issue as it relates to the SPA editor?

**Comment by pfauchere** [comment]
The Carousel AEM component needs to have an Angular component counterpart to manage the presentation. Until a frontend component library is available, customers have to implement that frontend component
