### ISSUE TITLE
[Experience Fragment] Method getExportedItemsOrder order is incorrect

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1135]
## Bug Report

**Current Behavior**
The ExperienceFragment component was extended in PR #1117 (as part of #943).
This implementation uses a `HashMap` to store the child items.
`HashMap` does not guarantee any sort order, therefore relying on the keys of this `HashMap` to derive the exported items order leads to an ambiguous order.

The exporter test data demonstrates this issue, to pass the tests the expected exporter data has the items in the reverse order as they exist in the content.

As an additional aside that can be tackled with a little refactoring: the XF model initializer performs some heavy lifting when it constructs all the models for the children of the XF. The intent of #943 was to expand the content of the JSON serialization; however, the models are constructed even when not doing JSON serialization, which has a performance impact that can be avoided by refactoring that logic outside of the model initializer and directly into the appropriate getter methods.

**Expected behavior/code**
The expected result should be that the order reflects the JCR order.

**Environment**
- AEM 6.5.5.0
- Core Components version 2.11.1-SNAPSHOT (current development)
- JRE version JDK11

**Possible Solution**
The `ContentFragmentUtils.getComponentExporters(Iterator, ModelFactory, SlingHttpServletRequest)` uses a `LinkedHashMap`. The return value of this method should be changed from `Map` -> `LinkedHashMap` as an indication that the ordering is important. The XF model should then use a `LinkedHashMap` itself when storing the child items. By doing this the keyset can be used to determine the item ordering.

Will submit pull request!

**Comment by jckautzmann** [comment]
Fixed with:
https://github.com/adobe/aem-core-wcm-components/pull/1138
https://github.com/adobe/aem-core-wcm-components/pull/1360

@ky940819 Thx a lot for your valuable work!
