### ISSUE TITLE
Random id not appened to multiple core components in a parent component

### ISSUE THREAD

**Issue by abukhan** [adobe/aem-core-wcm-components#1137]
Nested core components inside a parent component via sightly/HTL @ resource

<div>
	<sly data-sly-resource="${'image' @resourceType='/apps/weretail/components/content/image' , decorationTagName='div'}"><sly>
</div>
 above code works with a single instance of the core component exists.
If two or more components are nested in the same parent , it does not work due to the _radnom number not available to the nested component node.

**Does not work** (_inside a parent component_)
```
<div>
	<sly data-sly-resource="${'image' @resourceType='/apps/weretail/components/content/image' , decorationTagName='div'}"><sly>
</div>
<div>
	<sly data-sly-resource="${'image' @resourceType='/apps/weretail/components/content/image' , decorationTagName='div'}"><sly>
</div>
```

**Works** (_inside a parent component_)
```
<div>
	<sly data-sly-resource="${'image-a' @resourceType='/apps/weretail/components/content/image' , decorationTagName='div'}"><sly>
</div>
<div>
	<sly data-sly-resource="${'image-b' @resourceType='/apps/weretail/components/content/image' , decorationTagName='div'}"><sly>
</div>
```

How to iterate same core components in a multifield if the _random ID is not appeded to the node of the multiple child components

**Comment by bpauli** [comment]
@abukhan, Can you please explain a bit more what your limitations are with nested components? Node names are unique for the same parent node. https://docs.adobe.com/docs/en/spec/jcr/2.0/22_Same-Name_Siblings.html

**Comment by abukhan** [comment]
@bpauli ,As seen in the below image

![image](https://user-images.githubusercontent.com/18185558/90549403-17508980-e1ac-11ea-8c47-64c5ed24daa3.png)

When same components are dragged in a root responsive grid the sibling nodes are assigned a _numberID. as seen in the category_teaser component or any other component  in AEM authoring/edit mode.
While using @sly Resource, the node name has to be explicitly defined unlike which happens in the edit/page authoring the random number is appended with the underscore for the node name.

Using the same implementation the core components can unwrap with HTL. An ideal usecase would be using a multi-filed and having multiple image core components unwrap on the page via a common dialog

**Comment by ky940819** [comment]
If you have an indeterminate number of child images, then perhaps the _parent component_ is actually a container, which would allow you to just drag-and-drop any number of images into the component and not worry about the node names.

**Comment by gabrielwalt** [comment]
This is not a bug. For questions, please use mailing lists or internet forums instead of opening issues:
* https://groups.google.com/forum/#!forum/aem-core-components-dev
* https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/ct-p/adobe-experience-manager-community
