### ISSUE TITLE
[Text] Text Component RTE Plugins Policy gets overwritten.

### ISSUE THREAD

**Issue by babusankars** [adobe/aem-core-wcm-components#1145]
## Bug Report

**Current Behavior**
The Text Component RTE Plugins Policy gets overwritten when selection of new/different policy.

**Steps to reproduce**
1. Install a AEM instance Version 6.5.5 (6.5 + SP-5)
2. Create a Template with standard templates types (eg:) We-retail project.
3. Open the created Template in Structure mode.
4. Ensure in "Layout Container", the Text component is allowed.
5. Lock the Root "Layout Container" component.
6. Add a "Text" Component in the "Layout Container".
7. Open the "Policy" of Text Component and create 2 policies
eg: 
**_Policy-A_**: only featured Plugin options enabled
**_Policy-B_**: only formatting Plugin options enabled
8. Select the Policy-A for this Text Component and Save.
9. Now add a new "Text" Component in the "Layout Container".
10. Open the "Policy" of new "Text" component.
**_Observation_**: The Select policy (drop down) is preselected with default "New policy" which have default plugin properties selected.
11. Select the Policy-A that was created in Step#7 and save.
12. Now Open the "Policy" of first Text Component.
_**Expected**_: The properties of Policy-A selected with its corresponding Plugin Options being selected.
_**Actual**_: The default New Policy Plugin options are over written over Policy-A (globally).

This affects all the Text Components which were selected with Policy-A previously.

**Expected behavior/code**
The Author should be able to choose any Policy for Text Component and Policy Options should not be overwritten with one another. 

**Environment**
- AEM Version and Patch - AEM 6.5 SP5
- Core Components version - 2.11.0
- JRE version - Java(TM) SE Runtime Environment (build 1.8.0_251-b08)

**Comment by jckautzmann** [comment]
@babusankars This is actually not an issue of the Core Components but the Rich Text Editor (RTE) plugin provided by AEM. So please contact the official Adobe support channels so you will be able to track its resolution.

https://helpx.adobe.com/contact/enterprise-support.ec.html
