### ISSUE TITLE
[Container] Children are no longer rendered on the page when layout is responsiveGrid

### ISSUE THREAD

**Issue by habansal** [adobe/aem-core-wcm-components#1151]
## Bug Report

**Current Behavior**
With the latest fix (reverted temporarily) -
_CQ-4294035: Layout properties coming from XF Template not observed inside of a Page_
The V1 Container children are no longer rendered on the page, if you use `layout=responsiveGrid`

Steps to reproduce -
* Use latest Cloud ready Quickstart and install fix from CQ-4294035
* Install latest Core components Examples package on the quickstart - https://github.com/adobe/aem-core-wcm-components/tree/master/examples
* Open http://localhost:4502/content/core-components-examples/library.html

No components are shown on the page below 'Search Components'.

**Expected behavior/code**
Templating - Navigation, Breadcrumb etc. components should be rendered.
The page should look like - https://www.aemcomponents.dev/content/core-components-examples/library.html

**Environment**
- AEM version and patch level - AEM 6.6 latest Cloud ready quickstart (26th August) + fix from CQ-4294035
- Core Components version - latest development/master branch
- JRE version - Java8/Java11

**Possible Solution**
https://github.com/adobe/aem-core-wcm-components/pull/1150

**Additional context / Screenshots**
<img width="1680" alt="Screen Shot 2020-08-27 at 6 20 00 PM" src="https://user-images.githubusercontent.com/38317539/91444148-f5cd5d00-e891-11ea-9d42-a6fc8c15a2d8.png">

<img width="1680" alt="Screen Shot 2020-08-27 at 6 19 27 PM" src="https://user-images.githubusercontent.com/38317539/91444155-f9f97a80-e891-11ea-94a5-4696f0c92819.png">

**Comment by ky940819** [comment]
Is a fix for CQ-4294035 available anywhere to test this?

**Comment by jckautzmann** [comment]
@ky940819 The fix for CQ-4294035 will be available with in a future release of AEMaaCS, which will also contain a new release of the Core Components (including the fix for this issue).

**Comment by habansal** [comment]
This change is now being reverted via https://github.com/adobe/aem-core-wcm-components/pull/1163
as the issue has now been fixed via the CQ code, which seems like a more proper way.
