### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by henrykuijpers** [adobe/aem-core-wcm-components#1159]
Invalid

**Comment by henrykuijpers** [comment]
There also seems to be a difference between the current codebase and the previous codebase, as in:

Previous way of obtaining WCMMode:
```
(WCMMode) request.getAttribute(WCMMode.REQUEST_ATTRIBUTE_NAME) // returned null
```
Current way of obtaining runmode:
```
WCMMode.fromRequest(request) // returns DISABLED
```

**Comment by ky940819** [comment]
I think this bug report might belong in the [acs-aem-commons](https://github.com/Adobe-Consulting-Services/acs-aem-commons) project instead.
