### ISSUE TITLE
Expose WCMMode and run mode in dataLayer's page object 

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1171]
Currently only the data from https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/PageDataImpl.java is exposed on the dataLayer per page. Sometimes it is desirable to know whether a page has been loaded in edit/preview or disabled mode. For that an additional boolean attribute like `isAuthorMode` on the data layer would be really helpful. That should return `true` for any `WCMMode` but Disabled.

In addition an attribute exposing the run modes or a boolean attribute `isAuthor` would be good to conditionally do something only on the publish with Adobe Launch.

**Comment by gabrielwalt** [comment]
It would indeed be nice to expose this information in the data layer.
