### ISSUE TITLE
Transitive dependencies should be ignored for calculating `appResourcesPath` for favicons

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1172]
## Bug Report

**Current Behavior**
The calculation of the `appResourcesPath` in https://github.com/adobe/aem-core-wcm-components/blob/ddca43abc8079106904dd0368ca80c57a3615f53/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImpl.java#L144 might return the wrong path in case the clientlib category used in `appResourcesClientlib` has some dependencies.
It just takes the first clientlib including transitive ones.

**Expected behavior/code**
The calculation should disregard transitive libraries

**Environment**
- AEM version and patch level: 6.5.6
- Core Components version: 2.11
- JRE version: OpenJDK Runtime Environment(build 1.8.0_222-b10) 

**Possible Solution**
Just disregard transitive clientlibs but using `HtmlLibraryManager.getLibraries(...)` with the third argument being `false`

**Comment by msagolj** [comment]
PR merged, closing.
