### ISSUE TITLE
ckEditor.js plugin oEmbed - giving error while converting Youtube short-url to long-url

### ISSUE THREAD

**Issue by tarunprakash11** [adobe/aem-core-wcm-components#1174]
## Bug Report

**Current Behavior**
We am overlaying AEM-communities Journal component and using ckEditor in that. There is a media embed plugin where we can put youtube url and it adds the video onto the blog. But the issue arises when we use Youtube-shortUrl and the jQuery call happens to convert it to longURL over http protocol. And that API call is being blocked on our website as it serves only **https**. 
Also, it works fine when we use YT long-url.
 
![Blogs_embed_video_issue2_new](https://user-images.githubusercontent.com/41415694/93587289-4c2c4800-f9c7-11ea-8235-e765eb1e7ea9.jpg)

**Expected behavior/code**
Expected that is should convert YT shortUrl to longUrl over https call and embed the video onto blog
**Environment**
- AEM-communities on AEM version 6.4.2.0

Looks like there is code change required in `/libs/clientlibs/ckeditor/resources/ckeditor/plugins/oembed/libs/jquery.oembed.min.js `
![youtube embed issue on blogs site 15sept_new](https://user-images.githubusercontent.com/41415694/93588510-243de400-f9c9-11ea-8d39-f71879bae65e.jpg)

Adobe consultant directed to raise this as a bug here. Thanks in advance.

**Comment by msagolj** [comment]
@tarunprakash11 this is the wrong project you are reporting the issue to :) This is core components and has nothing to do with communities.

**Comment by tarunprakash11** [comment]
Its an issue with oembed.js where we are extending version of embed core components which is not working for youtube shortlinks. This change in this ticket is suggested by Adobe support team and they asked me to raise the issue under 'aem-core-wcm-components'.  
Can anyone provide inputs on this?
