### ISSUE TITLE
Favicons should support resource mapping and references should only be emitted if file is there

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1177]
## Bug Report

**Current Behavior**
All favicons listed at https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/head.resources.html are currently neither mapped nor are they emitted conditionally

**Expected behavior/code**
Only links to existing files should be emitted and all links should be properly mapped

**Environment**
- AEM version and patch level: 6.5.6
- Core Components version: 2.11
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`): irrelevant

**Possible Solution**

**Additional context / Screenshots**

**Comment by vladbailescu** [comment]
The way this was designed was that once the resource path for the icons is defined, all these files are provided. Mapping is deferred to link rewriter. We don't currently plan to enhance this. As, per https://github.com/adobe/aem-core-wcm-components/discussions/1509, closing this to `icebox`.
