### ISSUE TITLE
Working Hyper Links are erased from RTE-Description field of Teaser component after updating the content in the RTE-Description field

### ISSUE THREAD

**Issue by satishkumarjadhav** [adobe/aem-core-wcm-components#1180]
## Bug Report

**Current Behavior**
Edit the Teaser component, navigate to 'Text' tab. 
1. In the Description field (RTE component), add the content  -> "This is Adobe" with hyper link to Adobe text -> https://www.adobe.com/
2. Save the dialog and preview the page. You will find hyper link to 'Adobe' text with below html code
	`<div class="cmp-teaser__description"><p>This is <a href="https://www.adobe.com">Adobe</a></p></div>`
3. Now edit the same dialog and add site to the end of the line as "This is Adobe Site"
4. Save the dialog and preview the page. You will find hyper link is erased from the text and below is the html code
`	<div class="cmp-teaser__description"><p>This is <a>Adobe</a>&nbsp;site</p>                                                                                                                                </div>`

**Expected behavior/code**
From above point 4, the expectation is hyper link is retained after editing/updating the content in RTE - Description field with below html code
`<div class="cmp-teaser__description"><p>This is <a href="https://www.adobe.com">Adobe</a> site</p></div>`

**Environment**
- AEM version and patch level AEM 6.5 SP2
- Core Components version 2.10.0
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Comment by msagolj** [comment]
Hi @satishkumarjadhav, this is not reproducible for me, see attached video:

[TeaserRTE.zip](https://github.com/adobe/aem-core-wcm-components/files/5266730/TeaserRTE.zip)

so closing the issue for now. If you still have the issue related to RTE, please open a ticket with Adobe support (https://helpx.adobe.com/contact/enterprise-support.ec.html) instead as core components doesn't own the RTE widget.

**Comment by satishkumarjadhav** [comment]
@msagolj  : Could you please let us know the core bundle and AEM version, where you tried to reproduce the issue ?

**Comment by msagolj** [comment]
How I tested:
- AEM 6.5.5
- Core Components 2.10.0
- Used content page from examples library
- Tested with teaser from examples library and core teaser v1

=> both worked as demonstrated in video
(I also tested on cloud ready quickstart where the video was recorded, but that uses a new version of core comp)

Re-reading the issues I just realized that you use 6.5.2 and not 6.5.5. Please note that for 2.10.0 the required minimum version is 6.5.5+,  see release notes:
https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.10.0
