### ISSUE TITLE
[IE11] Dragged components are not configurable unless page is refreshed

### ISSUE THREAD

**Issue by abhishekagg19** [adobe/aem-core-wcm-components#1181]
## Bug Report

**Current Behavior**
In IE 11 browser, When a component is dropped in container, its not editable/configurable immediately. An explicit page refresh is required to select and configure the new component.
Steps:
1. in IE 11, Navigate to http://localhost:4502/editor.html/content/core-components-examples/library/separator.html
2. Try to add Button component
3. Verify that newly added component is not configurable, unless the page is refreshed.

**Expected behavior/code**
Component should be configurable when dropped/inserted int container

**Environment**
- AEM 6.5 SP5
- Core Components version 2.4.7
- Java 1.8

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by msagolj** [comment]
Hi @abhishekagg19 , just to clarify, there is no core component version 2.4.7, can you please check again what version you are using , thank you.

**Comment by msagolj** [comment]
@abhishekagg19 Checked the dev console in IE11, the error is in the page editor not core components and 6.5.5 does not support IE11, see:

https://docs.adobe.com/content/help/en/experience-manager-65/deploying/introduction/technical-requirements.html#supported-client-platforms

As you can see from the list, Microsoft Edge Browser is supported and there it works.
