### ISSUE TITLE
[Data Layer] Inconsistent ResourceTypes for navigation items

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-core-wcm-components#1182]
## Bug Report

**Current Behavior**
When the data layer is enabled for out of the box Core Components some of the `@type` are unexpected. This makes it difficult to filter events based on resource type. For example:

**Breadcrumb Item**:

```
breadcrumb-b7e3652ecf-item-574994a074:
@type: "wknd/components/page"
dc:title: "Climbing New Zealand"
parentId: "breadcrumb-b7e3652ecf"
repo:modifyDate: "2020-01-10T08:54:42Z"
xdm:linkURL: "/content/wknd/us/en/adventures/climbing-new-zealand.html"
```

**Language Navigation link**:

```
languagenavigation-c35513ec9b-item-c0b9aff709:
@type: "wknd/components/page"
dc:title: "Deutsch"
parentId: "page-574994a074"
repo:modifyDate: "2020-01-10T08:54:43Z"
xdm:language: "de-DE"
xdm:linkURL: "/content/wknd/de/de.html"
```

Should the type really be page? I would have expected it to be `wknd/components/breadcrumb` and `wknd/components/languagenavigation`...

**Teaser CTA button**:

```
teaser-da32481ec8-cta-adf3c09db9:
@type: "nt:unstructured"
dc:title: "Surf's Up"
parentId: "teaser-da32481ec8"
xdm:linkURL: "/content/wknd/us/en/magazine/san-diego-surf.html"
```
Type `nt:unstructured` is also unexpected...

**Expected behavior/code**
Items that are listed separately in the data layer but originate from a component should have the resource type for that component, otherwise it is difficult to filter events or understand the component that the event came from...

**Environment**
1. Navigate to https://wknd.site/us/en.html 
1. Open browser console and run `adobeDataLayer.getState()`

**Comment by gabrielwalt** [comment]
I fully agree, we need to rework those resource types.

**Comment by jckautzmann** [comment]
The `@type` property of an item is set with the API `Resource.getResourceType()` property:
- for a breadcrumb or a language navigation component, the item is a page and its resource type is e.g. `wknd/components/page`
- for a teaser component, the CTA is a JCR node with `nt:unstructured` node type

If this is confusing, we may want to introduce a specific `@type` property for items:
- for a breadcrumb item: `<breadcrumb-resource-type>/item`
- for a navigation item: `<navigation-resource-type>/item`
- for a teaser CTA: `<teaser-resource-type>/cta`

**Comment by ky940819** [comment]
Potentially related to #1081 as well.

**Comment by gabrielwalt** [comment]
I think that as a user it's odd that the resource type of a navigation item is a page. An example: as multiple components trigger the same events, like `cmp:show`, it's often needed to verify in the callback that the resource type that triggered the event is the desired component. But if multiple components identify themselves with the page resource type, this won't allow to reliably listen to events of specific components.

I like you suggestion, @jckautzmann of specify `@type` properties, like `<navigation-resource-type>/item`.

**Comment by godanny86** [comment]
+1 to the notation like `<navigation-resource-type>/item`

**Comment by ky940819** [comment]
Do we want to take it a step further and make `<navigation-resource-type>/item` an actual resource type? I.e move the rendering scripts for an item into an item component, and then avoid the @type sometimes being a real resource type and other times being something synthetic.

**Comment by godanny86** [comment]
Nice! Awesome that this is being worked on so quickly!

One other thing I found confusing as a user was the treatment of items within a Carousel and Tab. The `cmp:show` event for a carousel made of teasers would give you something like so:

```
carousel-43c8d133ed-item-da32481ec8:
 @type: "wknd/components/teaser"
 dc:title: "San Diego Surf Spots"
 parentId: "carousel-43c8d133ed"
 repo:modifyDate: "2020-07-11T22:17:55Z"
```

However the above data isn't an actual Teaser component/schema. The Teaser component is captured in the data layer and looks like this:

```
teaser-da32481ec8:
@type: "wknd/components/teaser"
dc:description: "From the hippie beaches of Ocean Beach to the ritzy shores of La Jolla and everywhere in between. Discover the San Diego surf scene."
dc:title: "San Diego Surf Spots"
parentId: "carousel-43c8d133ed-item-da32481ec8"
repo:modifyDate: "2020-07-11T22:17:55Z"
xdm:linkURL: "/content/wknd/us/en/magazine/san-diego-surf.html"
```

Using `parentId` you could traverse and find that the parent component was in fact a carousel at `wknd/components/carousel`. However how do you get to the Teaser content?

**Comment by msagolj** [comment]
For consistency reasons I would suggest that all components having items follow this new naming convention for items, including carousel, accordion and tabs. 

Maybe it would also make sense to give them a more meaningful name instead of just item e.g. `/link `for navigation items, `/panel` for carousel items etc.

**Comment by gabrielwalt** [comment]
@godanny86: The reason why we only have a `parentId` to move up in the tree, and nothing like a `childId` to move down, is that usually, the events are registered on the leaf nodes of the tree. Moving up the tree is required typically to understand in which context the event happened (e.g. to figure out if the shown image is in a carousel, or in a teaser). If there's a use-case for moving down the tree, then please open a separate issue with a description of the specific use-case. We could probably also add a `childId` property without too much effort if that's of value.

**Comment by jckautzmann** [comment]
> it would probably also make sense to give them a more meaningful name instead of just item e.g. /link for navigation items, /panel for carousel items etc. so that a component can have multiple distinguishable item lists.
I would suggest to use the same suffix as the one that is used for the item ID: for accordion, tabs and carousel, the suffix used of the item ID is `item` (e.g. accordion-96bc1a6527-item-831c5ecd0f)

**Comment by bpauli** [comment]
@godanny86 @msagolj In https://github.com/adobe/aem-core-wcm-components/pull/1184/commits/6ea1a6e3f684881527203c784223735a0fecccf3 I added the item suffix for panel container items.

**Comment by bpauli** [comment]
> Do we want to take it a step further and make `<navigation-resource-type>/item` an actual resource type? I.e move the rendering scripts for an item into an item component, and then avoid the `@type` sometimes being a real resource type and other times being something synthetic.

@ky940819 Basically I like the idea but this would require some refactoring and I don't think that this changes would be possible without creating new versions of the related components.

**Comment by msagolj** [comment]
PR got merged, closing
