### ISSUE TITLE
[Data Layer] Update to latest version

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#1185]
When the Data Layer has fixed the bug with the [getState method that returns no data in the event callback](https://github.com/adobe/adobe-client-data-layer/issues/100), we should bump the ACDL dependency of the core components to use that version.

**Comment by bartoszglow** [comment]
Updated DL version to `1.1.1` with PR: https://github.com/adobe/aem-core-wcm-components/pull/1211
