### ISSUE TITLE
Not able to extends PageImpl.java

### ISSUE THREAD

**Issue by rwoess** [adobe/aem-core-wcm-components#1186]
I have to extend the existing implementation of com.adobe.cq.wcm.core.components.internal.models.v2.PageImpl, because I have to provide an additional css class to getCssClassNames method based on some new settings in page properties. But its not possible to extend this class because this class is in the "internal" package. And as I know this will not be exported to other OSGi bundles.
For me this means, I have to copy the code from v2.PageImpl, v1.PageImpl and a lot of other classes which are also in "internal" package to my project. In my opinion this kind of implementation of core components does not make any sense, because it blocks developers to reuse existing code.
Another solution would be to copy page.html to my project and extend this file with an additional model. But I also do not like this solution because its again a copy of already existing code. 

My preferred solution would be to export the whole code (or most code) to other OSGi bundels so that everybody can reuse core components in every project not only in really simple projects.

**Comment by ky940819** [comment]
An option is to create your own model that implements the page interface, and then delegate all methods to the model created for the resource super type (except for the methods you want to change).


https://github.com/adobe/aem-core-wcm-components/wiki/Delegation-Pattern-for-Sling-Models

**Comment by thomasmorf** [comment]
The style system can also inject CSS classes into the page, if you have a defined list of classes. Did you consider that approach already?

**Comment by rwoess** [comment]
Thank you very much @ky940819. This is the solution for my problem.
