### ISSUE TITLE
[Container] Simple mode broken when using Sling Model Delegation Pattern

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#1187]
## Bug Report

**Current Behavior**
Scenario: A custom container component extends the container component by extending the Java logic using the Sling Model Delegation Pattern. It delegates the fetching of the container items (`getItems()`) to the original implementation. In Simple mode this logic is used to fetch the container children to render them.

This is broken in most recent AEM cloud service versions (both in the cloud and locally in AEM cloud SDK quickstart) with the result that no children are found and the paragraph is rendered empty (although there are children).

**Expected behavior/code**
The container should always render it's children, regardless of the selected render mode and AEM (cloud) version.

**Environment**
- AEM 2020.9.4245.20200921T202853Z-200827
- Core Components 2.11.1

**Possible Solution**
The reason is:
- the container component uses the [getEffectiveResource()](https://github.com/adobe/aem-core-wcm-components/blob/f8784d226e6b2fec53aafb5df712465519535688/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/AbstractContainerImpl.java#L264-L269) method to get the resource to fetch its children
- this works well if the original LayoutContainerImpl is used without "subclassing" it using the delegation pattern. in most recent AEM cloud service versions `this.resource` is already a `TemplatedResource` instance.
- however, when the delegation pattern is used the `this.resource` is not a `TemplatedResource` but some wrapper instance, and the logic adapts the *current request* to `TemplatedResource`.
- Adapting a request to `TemplatedResource` fetches it's resources and creates a templated resource from it.
- However in most recent AEM cloud versions request.getResource() already returns a templated resource, leading to create a templated resource from a templated resource. A check in the templated resource implementation detects that the source resource is already a synthetic resource (it extends it), and it skips fetching the children. This result is an empty children list and an empty container.

Probably this is a bug in AEM itself and should be fixed in the adapter factory for templated resources. However i think the code in core components is also not correct, instead of adapting the current request the current resource should be adapted to `TemplatedResource`. I will provide a PR for this.

**Comment by msagolj** [comment]
PR merged. closing issue.

**Comment by msagolj** [comment]
We have to revert this in 2.12.2 as it was breaking page rendering when using the simple container on the root node thats coming from a template.

**Comment by stefanseifert** [comment]
i was able to reproduce the problem with the root container - provided new PR #1255

**Comment by ky940819** [comment]
@stefanseifert : 

Do you think that this would be a sufficient alternate solution to resolve the issue with wrappers:

```JAVA 
    /**
     * Gets the effective {@link TemplatedResource} for the specified resource.
     *
     * @param resource The resource for which to get the TemplateResource.
     * @return The TemplatedResource, or the current resource if it cannot be adapted to a TemplatedResource.
     */
    @NotNull
    public static Resource getEffectiveResource(@NotNull final Resource resource) {
        if (resource instanceof TemplatedResource) {
            return resource;
        }

        Resource res = resource;
        while (res instanceof ResourceWrapper) {
            res = ((ResourceWrapper) resource).getResource();
            if (res instanceof TemplatedResource) {
                return res;
            }
        }

        return Optional.ofNullable((Resource) resource.adaptTo(TemplatedResource.class)).orElse(resource));
    }
```

This is similar logic to what sling does for the `ResourceUtil#isSynthetic()` method.
The benefit here is that it doesn't limit the `#getEffectiveResource()` to the current request page.
