### ISSUE TITLE
[Page] og:image:width & og:image:height are missing from the og:image definition

### ISSUE THREAD

**Issue by henrykuijpers** [adobe/aem-core-wcm-components#1189]
In `SocialMediaHelperImpl`, useful fields such as `og:image:width` and `og:image:height` are not added to the list of the social media attributes that will appear in the `<head>`-section of the HTML-page. Also, other useful properties such as `og:image:alt` and `og:image:type` are also not output.

https://github.com/adobe/aem-core-wcm-components/blob/8acaa6d82a9dc4692af90eb61088d97bbc387441/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/SocialMediaHelperImpl.java#L206

**Comment by msagolj** [comment]
@henrykuijpers what are you referring to ? Can you please give more context, thank you.

**Comment by henrykuijpers** [comment]
Updated the initial post, even though I thought it already was pretty clear. :)

**Comment by msagolj** [comment]
@henrykuijpers thank you for the update. It always helps to have a bit more context and explanation, makes it easier for others to understand and find this issue if looking for infos :)

**Comment by gabrielwalt** [comment]
In the new page component, we won't have a specific sharing capability anymore, but rather output by default the OG meta tags (with the featured image defined at page level for `og:image`, along with `og:image:alt` `og:image:width` and `og:image:height`). Therefore, closing this issue as it's being solved by #663.
