### ISSUE TITLE
Embed servlet requires override to use and avoid dialog errors for url validation

### ISSUE THREAD

**Issue by irishgator** [adobe/aem-core-wcm-components#1190]
Current best practice and existing documentation for core components recommend that the components are proxied before use in a project. The current core component samples package for the Embed component does not use a proxy and references the V1 directly and functions correctly.  If you try to create a proxy instance and then use it the validation of your URL fails and the servlet is never called because the proxied component is using a combination of a selector along with the v1 resource type to be called. This prevents saving the dialog because there is an error.

 The documentation for the Embed component does not indicate any custom steps are needed to create a new servlet to use the component as-is. Nor does the servlet use resourceSuperType in its annotations instead so that you can just simply proxy the component.  I'm raising a bug because if you try to use the component following existing documentation it will not work with urls defined in the url radio button selection.  Can we just change the servlet to use the SuperType annotation instead or update the documentation to properly indicate how to proxy and use the component?

**Comment by msagolj** [comment]
Hi @irishgator, the way to extend the embed works a bit differently and is described in its README.md, see:

https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed#extending-the-embed-component

Does this help/answer your question ?

**Comment by irishgator** [comment]
no. The docs only address creating a custom url processor. It does not address the issue of this servlet which the dialog and component : [https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbedUrlProcessorServlet.java](https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbedUrlProcessorServlet.java)

That servlet gets called only when your component is core/wcm/components/embed/v1/embed. If its any other type i.e. a proxy instance that servlet and its logic never get called. So does the documentation need to update to indicate that you need to override the servlet or does the servlet need to be updated to account for components that inherit from the v1 instance.

**Comment by msagolj** [comment]
> So does the documentation need to update to indicate that you need to override the servlet or does the servlet need to be updated to account for components that inherit from the v1 instance.

Neither should be required :) I created a project using [aem-project-archetype ](https://github.com/adobe/aem-project-archetype) that creates proxies for all core components including embed. There is no override for the servlet and the proxy embed component works as intended when using registered URL types like Facebook, YouTube or Instagram and showing an error for others as expected. See attached Video.

[testembed.zip](https://github.com/adobe/aem-core-wcm-components/files/5305702/testembed.zip)

**Comment by irishgator** [comment]
You are correct. It does appear that the proxy we had in place had an error that was resolved once we made sure it matched the one from the archetype. Thanks for confirming.
