### ISSUE TITLE
Update aem-mock -> 3.1.0 & deprecate `MockLanguageManager`

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1193]
## Feature Request

**Is your feature request related to a problem? Please describe.**
General upkeep.
The latest version of aem-mocks offers a more feature complete version of `MockLanguageManager`.

**Describe the solution you'd like**
Update the aem-mocks dependency and deprecate the `MockLanguageManager` offered via the testing package.

**Are there alternatives?**
No.

**Comment by msagolj** [comment]
PR has been merged, closing issue.
