### ISSUE TITLE
[Data Layer] PR #976 causes "TypeError: Cannot read property 'hasAttribute' of null" in Core Components 2.11.1

### ISSUE THREAD

**Issue by Andrew-Cottrell** [adobe/aem-core-wcm-components#1205]
Pull Request #976 added 

```var dataLayerEnabled = document.body.hasAttribute("data-cmp-data-layer-enabled");```

to several components (e.g. Accordion at https://github.com/adobe/aem-core-wcm-components/blob/core.wcm.components.reactor-2.11.1/content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js#L19).

This statement is executed _before_ waiting for the `DOMContentLoaded` event, so `document.body` is _not_ guaranteed to be non-null.

When the accordion clientlib script is included in the `<head>` element, `document.body` is `null` and the browser throws
```TypeError: Cannot read property 'hasAttribute' of null```

**Comment by Andrew-Cottrell** [comment]
A quick & simple improvement would be to replace

```var dataLayerEnabled = document.body.hasAttribute("data-cmp-data-layer-enabled");```

with 

```var dataLayerEnabled = Boolean(document.body) && document.body.hasAttribute("data-cmp-data-layer-enabled");```

**Comment by jckautzmann** [comment]
Thx for reporting. I created a pull request at:
https://github.com/adobe/aem-core-wcm-components/pull/1207
