### ISSUE TITLE
Reuse Abstract & Util classes that are part of *.internal for custom components

### ISSUE THREAD

**Issue by chetanyajain** [adobe/aem-core-wcm-components#1206]
Hi Team,

There's a lot of purposeful code in the abstract & Util classes that we will like to reuse for our own custom components. These classes are not exported and hence we cannot define our custom component models to extend from them. Can we please export these classes and the Component interface for better reusability outside the WCM core project?

Thanks,
Chetanya

**Comment by rajeevyadav2** [comment]
I don't think exporting implementation classes is good idea. We should not allow these to be directly used/inherited by others. It will limit the capability of refactoring the implementations if others directly use these classes. 



Thanks,
Rajeev

**Comment by chetanyajain** [comment]
In that case, we land up writing the same code again. Eg: getID() which will be required for all components.

**Comment by ky940819** [comment]
With respect to the `getId()` logic; the recently merged PR #1115  should expose utility functions for generating the ID.
I suspect that will be included in an upcoming release since it was merged into development.

Would that address your need?

**Comment by rajeevyadav2** [comment]
getID is available through delegation of the model and also alternatively, component interface can be used in HTL and getID from this interface returns the id for the component. Hope this helps.

Thanks,
Rajeev

**Comment by chetanyajain** [comment]
@rajeevyadav2 you meant to say use something link this to access getID?
`data-sly-use.component="com.adobe.cq.wcm.core.components.models.Component"`

Can I not use `data-sly-use.cust="com.proj.components.models.CustomComponent" ${cust.id}`?

How do I access getID if I have my own custom component sling model?

**Comment by chetanyajain** [comment]
> With respect to the `getId()` logic; the recently merged PR #1115 should expose utility functions for generating the ID.
> I suspect that will be included in an upcoming release since it was merged into development.
> 
> Would that address your need?
> 
> Edit for clarification:
> What exists in the development branch right now would expose this:
> https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/util/ComponentUtils.java

We will have to wait until its released. However with the current situation how will be able to access getID from within the sling model java code?

**Comment by rajeevyadav2** [comment]
Not customComponent. Use  component interface from core to get id.

Alternatively, If your custom model uses delegation to core then getId will be available from core component model.

Thanks,
Rajeev

**Comment by chetanyajain** [comment]
@rajeevyadav2 can you please help on how to create a custom model with delegation to the core?

**Comment by chetanyajain** [comment]
com.adobe.cq.wcm.core.components.internal.Utils has lot more other methods that can be reused, but its internal.

**Comment by chetanyajain** [comment]
@rajeevyadav2 I was reading this https://github.com/adobe/aem-core-wcm-components/wiki/Delegation-Pattern-for-Sling-Models but this will not work since we don't have superresourcetype for Component.  I have a component that is created from scratch and it needs to reuse getId, getData, Utils.getURL in sling model.

**Comment by ky940819** [comment]
If your custom component does not list `Component.class` as an adapter, then you can probably inject Self as a `Component` object without using the via resource super type. This should get you the default Component implementation. 

Alternatively, If your component does not list Component.class as an adapter, you should be able to use data-sly-use in your front end html, and use both your custom model as well as the Component model. 

But, it does sound like what you really want is actually part of an upcoming release, which would make it a bit more straight forward to provide the functionality directly in your own component without having to delegate.

If you can't wait for this, then I would either 
1) not implement the Component interface and then data-sly-use both the Component model and the CustomComponent model; or
2) implement the Component interface but don't mark it as adaptable to a Component, then inject Self as Component and delegate to that, or use the model manager to adapt the request to a Component. 

Those two options only differ by if you merge the data you need in your model, or in your front end from two different models.

**Comment by chetanyajain** [comment]
@ky940819 thank you so much for the pointers.

Currently, I cannot wait, so I am moving ahead by deligating, the below code worked out

`	@Self
	@Delegate(types = Component.class) //Using Lombok 
	private Component delegate;`
