### ISSUE TITLE
Style box getting displaced with 'afteredit' cq:listener added to component editconfig

### ISSUE THREAD

**Issue by vrk-tfs** [adobe/aem-core-wcm-components#1214]
**Description**

We are proxying OOTB core components for our application and noticed an issue with Adobe core components. Whenever we add 'afteredit' listener to component cq:editconfig and try changing the styles, the style box gets displaced and sticks to the top of the page  after page refresh.

Steps to reproduce:

1. Add cq:listener - afteredit: REFRESH_PAGE to the proxied Teaser component under /apps/core-components-examples/components/teaser/cq:editConfig/cq:listeners
2. Now open the Teaser.html under /content/core-components-examples/library/page-authoring/teaser.html
3. Navigate to Teaser component and try selecting different style variations like component, document.
4. Upon selection the page will refresh (due to afteredit: REFRESH_PAGE listener) 
5. Once the page load, observe the style dialog, which gets displaced at the top of the page

**Current Behavior**
Style dialog gets displaced to the top of the page

**Expected behavior/code**
Upon page load, style edit dialog should gets positioned at the accurate component location which gets edited

**Environment**
-  AEM v6.4.8.0
- Core Components v2.9.0
- Java(TM) SE Runtime Environment(build 1.8.0_131-b11)

**Possible Solution**
As a workaround, we have implemented a site script which hides the style dialog box. But this kind of limit the content authors ability to easily toggle with different styles and also make use of Close (X) icon.

**Additional context / Screenshots**
![Issue](https://user-images.githubusercontent.com/72936812/96159046-d4076280-0f31-11eb-85e9-a6e7ea1d3c92.PNG)
![step1](https://user-images.githubusercontent.com/72936812/96159056-d5d12600-0f31-11eb-920d-8ea8eaf43999.PNG)
![Step2](https://user-images.githubusercontent.com/72936812/96159059-d7025300-0f31-11eb-9f5a-369c26f4af0a.PNG)

**Comment by bpauli** [comment]
Hi @vrk-tfs, thank you for reporting this issue. This is issue is already known and was fixed in version 6.5.4. In case you're not able to upgrade you instance it would be required to create a support ticket at Adobe and to ask for backport of this fix as this needs to be done inside of the product. Can you please refer to the internal id CQ-4294027 in your request? Thanks!

**Comment by vrk-tfs** [comment]
Thanks @bpauli for the inputs, i will get in-touch with Adobe to take this further.
