### ISSUE TITLE
[DataLayer] The bundle should export DataLayerSupplier

### ISSUE THREAD

**Issue by laurentiumagureanu** [adobe/aem-core-wcm-components#1219]
## Feature Request

**Is your feature request related to a problem? Please describe.**

In Core CIF Components project we enabled the dataLayer population for most components.
We were able to generate custom attributes not included in the ComponentData interface.

The new builder pattern is a bit eremitic when it comes to custom dataLayer attributes.
For example, for our Product component we need to add SKU, price and currency.

To achieve this with the builder pattern, a few things are needed:

1. A new interface and implementation extending `ComponentData` that has new methods.
2. A custom interface and class extending `DataLayerSupplier` in order to include the new needed attributes.
3. A custom builder extending `GenericComponentDataBuilder` that includes the new attributes.

```java
public interface CustomDataLayerSupplier extends DataLayerSupplier {
    //Custom methods
    ...
}

public class ProductDataImpl extends ComponentDataImpl implements ProductData {
    public ProductDataImpl(final CustomDataLayerSupplier supplier) {
        super(supplier);
    }

    @Override
    public String getSKU() {
        return this.getDataLayerSupplier()
            .getSku()
            .map(Supplier::get)
            .orElse(null);
    }
...
} 

public final class ProductDataBuilder extends GenericComponentDataBuilder<ProductDataBuilder, ProductData> {
    ProductDataBuilder(final CustomDataLayerSupplier supplier) {
        super(supplier);
    }

    // Custom methods
    ....

    @Override
    public ProductData build() {
        return new ProductDataImpl(this.getDataLayerSupplier());
    }
}
```
The problem is that `DataLayerSupplier` is not exported by the bundle so it can't be used like this.

**Describe the solution you'd like**

The bundle should export `DataLayerSupplier`

**Comment by jckautzmann** [comment]
PR #1220 was merged into the `development` branch.
