### ISSUE TITLE
[Teaser] The image authored in the Teaser react core component is not rendered in the webpage

### ISSUE THREAD

**Issue by khn2475** [adobe/aem-core-wcm-components#1223]
## Bug Report

**Current Behavior**
I configured an image in the teaser react core component but the image is not being rendered in the webpage. The teaser core component model is not returning the imagePath value and hence the teaser typescript code is failing the render the image.

**Expected behavior/code**
When the image is authored in teaser component, it has to be displayed in the webpage. 

**Environment**
- AEM Cloud
- Core Components version 2.11.1
- JRE version Java(TM) SE Runtime Environment (build 11.0.6+8-LTS)

**Additional context / Screenshots**
![Screenshot (140)](https://user-images.githubusercontent.com/73276680/96868664-02ce8d00-148c-11eb-8fda-d2493199c47e.png)
![Screenshot (136)](https://user-images.githubusercontent.com/73276680/96868689-08c46e00-148c-11eb-8ca2-5e02fd004fc6.png)

**Comment by bpauli** [comment]
Hi @khn2475, this issue seems so be related to the React enabled components. Can you please create a new issue at the repo https://github.com/adobe/aem-react-editable-components? Thanks!
