### ISSUE TITLE
oEmbed JS - giving error while converting Youtube short-url to long-url

### ISSUE THREAD

**Issue by tarunprakash11** [adobe/aem-core-wcm-components#1236]
## Bug Report

**Current Behavior**
We am overlaying Journal component and using ckEditor in that. There is a media embed plugin where we can put youtube url and it adds the video onto the blog. But the issue arises when we use Youtube-shortUrl and the jQuery call happens to convert it to longURL over http protocol. And that API call is being blocked on our website as it serves only **https**. 
Also, it works fine when we use YT long-url.
 
![Blogs_embed_video_issue2_new](https://user-images.githubusercontent.com/41415694/93587289-4c2c4800-f9c7-11ea-8235-e765eb1e7ea9.jpg)

**Expected behavior/code**
Expected that is should convert YT shortUrl to longUrl over https call and embed the video onto blog
**Environment**
- AEM version 6.4.2.0

Looks like there is code change required in `/libs/clientlibs/ckeditor/resources/ckeditor/plugins/oembed/libs/jquery.oembed.min.js `
![youtube embed issue on blogs site 15sept_new](https://user-images.githubusercontent.com/41415694/93588510-243de400-f9c9-11ea-8d39-f71879bae65e.jpg)

Adobe consultant directed to raise this as a bug here. Thanks in advance.

refer: https://github.com/adobe/aem-core-wcm-components/issues/1174

**Comment by vladbailescu** [comment]
@tarunprakash11 , Please don't alter title and description of old closed issues!

If i understand correctly, you are using a component (not Core Components) and CKEditor with oEmbed plugin (presumably from https://ckeditor.com/cke4/addon/oembed). How is this related to the Core Components?

**Comment by msagolj** [comment]
@tarunprakash11 As mentioned in the other issue this has nothing to do with core components. The Adobe consultant that directed you here, again, is probably confusing our [Embed Component](https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed) with the oEmbed plugin available for the ckeditor as @vladbailescu mentioned above.

This ckeditor was added as part of Communities , so please open an ticket with Adobe support and ask them to report this to Social-Commons or Communities.
