### ISSUE TITLE
Socket leak in FormHandlerImpl.java

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1246]
The response in https://github.com/adobe/aem-core-wcm-components/blob/1b9662c71d448e7ee4a92fc4faa4747de88738ea/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/form/FormHandlerImpl.java#L76 is never closed leading to unclosed sockets.

To allow connection pooling the HttpClient should be reused for all requests (and should be closed with `deactivate`) and the individual `CloseableHttpResponse` should only be used with https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html to prevent the sockets from not being released to the thread pool.
In addition 201 status codes should also be accepted..

**Comment by msagolj** [comment]
Hi @kwin thank you for reporting and providing a PR.
