### ISSUE TITLE
Failed to collect dependencies at com.adobe.cq:core.wcm.components.core 

### ISSUE THREAD

**Issue by AntonValadzko** [adobe/aem-core-wcm-components#1252]
## Bug Report

**Current Behavior**
Getting an error during the project build if dependency version range is being used (was fine yesterday):

`No versions available for com.adobe.cq:core.wcm.components.core:jar:[2.11.0,2.12.0)`

![image](https://user-images.githubusercontent.com/6346581/98799682-79720100-2420-11eb-822d-767da12013b4.png)

Looks like the versions got lost in the https://repo1.maven.org/maven2/com/adobe/cq/core.wcm.components.all/maven-metadata.xml after yesterday's 2.12.2 release

![image](https://user-images.githubusercontent.com/6346581/98799814-a9b99f80-2420-11eb-88ff-fe5bd403df8f.png)

**Expected behavior/code**
Should be able to use version range in the dependency section

**Environment**
- AEM version 6.5.6
- Core Components version (e.g. 2.11.1)

**Comment by vladbailescu** [comment]
Thanks @AntonValadzko  for reporting the issue. Core Components uses OSSRH for hosting of artifacts. I openend https://issues.sonatype.org/browse/OSSRH-61953 for this problem.

**Comment by vladbailescu** [comment]
@AntonValadzko , this should be fixed now thanks to @jorlina at Sonatype's OSSRH.
