### ISSUE TITLE
[Form Text & Form Options] Change About & Element Name to be consistent

### ISSUE THREAD

**Issue by dhardtke** [adobe/aem-core-wcm-components#1259]
## Feature Request

**Is your feature request related to a problem? Please describe.**
No problem here, but the dialogs of the two components are structured a little bit differently.

<img src="https://user-images.githubusercontent.com/1360135/99071321-33e53d80-25b2-11eb-8166-7444acaac807.png" width="49%"> <img src="https://user-images.githubusercontent.com/1360135/99071347-43fd1d00-25b2-11eb-9977-4638f9e7ca32.png" width="49%">

**Describe the solution you'd like**
For consistency reasons I think it would be better if the two dialogs were structured in the same way, i.e., _Form Options_ should have an _About_ tab (similar to _Form Text_) and _Form Text_'s _Element Name_ should simply be called _Name_ to be in line with _Form Options_.

**Are there alternatives?**

**Documentation**
If you can, explain how users will be able to use this and possibly write out a version of the docs.
Maybe a screenshot or design?

**Comment by bartoszglow** [comment]
Issue fixed with PR: #1349

**Comment by bartoszglow** [comment]
To be released in Core Components `2.14`
