### ISSUE TITLE
Simplify re-deploying `cloud` artifacts to a running AEM instance that already includes them

### ISSUE THREAD

**Issue by vladbailescu** [adobe/aem-core-wcm-components#1262]
At the moment, if you have deployed your `cloud` artifacts to a running AEM instance and you want to quickly redeploy them while developing, you need to install both `core.wcm.components.content-version-cloud.zip` and `core.wcm.components.extensions.amp.content-version-cloud.zip` manually.

It would help if:
1. The `cloud` profile also generates an `-all` package that embeds the artifacts with `cloud` classifier.
2. The `content-package-maven-plugin` would install the `cloud` classifier artifact when using `cloud` profile and one of the auto-install profiles.

**Comment by msagolj** [comment]
Has already been merged into master. closing. Further improvements can be discussed in #1290.
