### ISSUE TITLE
[Page] Skip to main content fails on RTL

### ISSUE THREAD

**Issue by fraudoudou** [adobe/aem-core-wcm-components#1265]
The "skip to main content"-link causes wide horizontal overflow on RTL languages.
Caused by `left: -999px;` on cmp-page__skiptomaincontent-link. In the case of a RTL-language, the property should be right instead of left.

**Comment by vladbailescu** [comment]
Thanks @fraudoudou for raising the issue. Since our bandwidth is limited at the moment, we would be thankful if you could also submit a pull-request for this.

**Comment by fraudoudou** [comment]
@vladbailescu, the pull request now considers the text-direction if the dir-attribute is set. Adding this attribute to the core component's page would be another feature request in my eyes.
Also, the "skip to main content"-link is not BEM compliant because of its nesting. I don't see any reason to do so, so I removed the nested CSS in this PR as well.

**Comment by gabrielwalt** [comment]
Let's apply this PR to all versions of the page component.

**Comment by fraudoudou** [comment]
@gabrielwalt skip to main content was added with page v2, so nothing to do for v1. In the WIP page v3 skiptomain is still missing.

**Comment by bpauli** [comment]
fixed in fraudoudou:issue/1265
