### ISSUE TITLE
AdaptiveImageServlet does not change quality if resize is not needed

### ISSUE THREAD

**Issue by marcschiely** [adobe/aem-core-wcm-components#1266]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We have authors that upload images to Assets which are already in the correct dimensions but with a quality that is too high for the web. 

In AdaptiveImageServlet there is the check for the width: `if (originalWidth > resizeWidth)`. In case this condition is false then the original image is streamed directly without change of the quality: 

`LOGGER.debug("Found rendition {}/{} has a width of {}px and does not require a resize for requested width of {}px",
                            asset.getPath(), rendition.getName(), dimension != null ? dimension.getWidth() : null, resizeWidth);`

This leads to the issue that streamed images have a file size which is too high for the web.

**Describe the solution you'd like**
There might also be the case that images are uploaded in the correct dimensions and quality. So in my opinion it makes sense to extend the API with another parameter to be able to force the compression. This way the application can decide if compression should be done or not, based on some metadata. 

**Are there alternatives?**
As reading of the compression level of a JPG is not possible I didn't find an alternative way, except the application (or the author) to decide if compression should be applied or not.

**Comment by kwin** [comment]
I think this is a duplicate of #472

**Comment by marcschiely** [comment]
Yes, you are right, it's already described in that ticket.

**Comment by vladbailescu** [comment]
@marcschiely , just FYI: #472 is closed and will not be fixed.

**Comment by marcschiely** [comment]
@vladbailescu : as I understood there will be a new image component v3, handled in #496 in which #472 will be discussed as well. So waiting for the outcome of this discussion.
