### ISSUE TITLE
Breadcrumb microdata

### ISSUE THREAD

**Issue by omhattekar** [adobe/aem-core-wcm-components#1267]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have just upgraded AEM 6.4 to AEM 6.5. We used JSON+LD for SEO but it has micro data available 

**Describe the solution you'd like**
Any option must be there to eneable/disabled microdata for SEO

**Are there alternatives?**
Is it affect if I remove itemtype attribute from core component?

**Comment by vladbailescu** [comment]
@omhattekar , I'm sorry but I do not understand. Could you please try to explain in more detail?

**Comment by omhattekar** [comment]
@vladbailescu 
<nav class="cmp-breadcrumb"
     data-sly-use.breadcrumb="com.adobe.cq.wcm.core.components.models.Breadcrumb"
     data-sly-use.template="core/wcm/components/commons/v1/templates.html"
     data-sly-test="${breadcrumb.items.size > 0}">
    <ol class="cmp-breadcrumb__list"
        **itemscope itemtype="http://schema.org/BreadcrumbList"**
        data-sly-list.navItem="${breadcrumb.items}">
        <li class="cmp-breadcrumb__item${navItem.active ? ' cmp-breadcrumb__item--active' : ''}"
            itemprop="itemListElement" **itemscope itemtype="http://schema.org/ListItem"**>
            <a href="${navItem.URL}"
               class="cmp-breadcrumb__item-link"
               itemprop="item"
               data-sly-unwrap="${navItem.active}">
                <span itemprop="name">${navItem.title}</span>
            </a>
            <meta itemprop="position" content="${navItemList.count}" />
        </li>
    </ol>
</nav>

We are using json+ld for gtm.Due to this we got an issue in analytics.
Is it ok to remoe two attributes itemscope and itemtype?
Does it affect component if I remove it?

**Comment by ky940819** [comment]
If i understand correctly, you are already providing the information using JSON+LD and so do not want duplicate microdata?

If so, yes you should be able to remove the itemscope, and itemtype. 
You should probably remove all of the microdata properties from this component in your wrapper HTL

See: https://schema.org/docs/gs.html#microdata_itemprop

**Comment by omhattekar** [comment]
ok
thanks @ky940819
