### ISSUE TITLE
Issue with Image Alt text when Alt text is Empty

### ISSUE THREAD

**Issue by rsonth** [adobe/aem-core-wcm-components#1268]
Hi Team,

As part of accessibility issue we have introduced alt=" " when alt text field is empty. Below are the changes carried out to achieve the fix in image.html using escaping characters.
/apps/core/wcm/components/image/v2/image/image.html
<sly data-sly-test.empty= '\''></sly> 
            <img src="${image.src}" class="cmp-image__image" itemprop="contentUrl" data-cmp-hook-image="image"
                data-sly-attribute.usemap="${image.areas ? usemap : ''}"
                alt="${image.alt ? image.alt : " "}" title="${image.displayPopupTitle && image.title}"/>
                <sly data-sly-test="${image.alt}">

functionality works as per our requirement but build is getting failed due to HTL validation.

Any lead would be highly appreciated.

Thanks.

**Comment by vladbailescu** [comment]
`"${image.alt ? image.alt : " "}"` looks wrong, you cannot use quote marks inside quote marks. You should use apostrophe: `"${image.alt ? image.alt : ' '}"`

**Comment by rsonth** [comment]
Thanks for your quick response @vladbailescu. Yes you are correct and i had tried with quote marks and apostrophe.
 
With above piece of code alt = " " isnt appearing on page load when alt text field is empty.

So If you have observed my piece of sightly script i have introduced escaping character <sly data-sly-test.empty= '\''></sly> on top this i have used "${image.alt ? image.alt : " "}" or "${image.alt ? image.alt : ' '}". In both case our scenario works as expected.

but now i'm able to see same exception when you try to build the workspace,

[WARNING] C:\AEM\Local Repos\adobe\repo\ADOBE-CORE-COMPS\content\src\content\jcr_root\apps\core\wcm\components\image\v2\image\image.html [53:21]: ${templates.placeholder @ isEmpty = !image.src, classAppend = 'cmp-image cq-dd-image'}: Unknown option 'isEmpty'.
[WARNING] C:\AEM\Local Repos\adobe\repo\ADOBE-CORE-COMPS\content\src\content\jcr_root\apps\core\wcm\components\image\v2\image\image.html [53:21]: ${templates.placeholder @ isEmpty = !image.src, classAppend = 'cmp-image cq-dd-image'}: Unknown option 'classAppend'.
[INFO] Processed 91 files in 3569ms

Failed to execute goal org.apache.sling:htl-maven-plugin:1.3.4-1.4.0:validate (validate-htl-scripts) on project core.wcm.components.content: Compilation warnings were configured to fail the build. -> [Help 1]

**Comment by vladbailescu** [comment]
@rsonth , it would help if you shared the changes you made (you can fork the repo and push the changes to a branch). From the errors, it seems you're either:
1. Not properly defining the common templates; it should be done like: https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html#L18
2. Overlaying it with something that does not have those two options. The original templates are at https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/commons/v1/templates.html#L17

**Comment by rsonth** [comment]
Hi @vladbailescu ,

As suggested by you i have just raised PR with changes.

https://github.com/adobe/aem-core-wcm-components/pull/1270

Thanks,Ramesh.

**Comment by rsonth** [comment]
Hello @vladbailescu 

Did you get a chance to look into this issue?

Thanks,Ramesh

**Comment by gabrielwalt** [comment]
This has been fixed with version 2.16 of the Core Components:
https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html#L42

`alt="${image.alt || true}"` will render a boolean `alt` attribute (without the `=""`) if the alt text is empty, which satisfies accessibility requirements.

**Comment by juliavoortman-silktide** [comment]
> This has been fixed with version 2.16 of the Core Components: https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/image.html#L42
> 
> `alt="${image.alt || true}"` will render a boolean `alt` attribute (without the `=""`) if the alt text is empty, which satisfies accessibility requirements.

Apologies if this is the wrong spot for this question; I have a customer who wants to know if it's possible to have an empty alt attribute added to images categorised as decorative in AEM. As far as they can tell, they can either add some alt text, or if they mark it as decorative, AEM removes the alt attribute entirely.
