### ISSUE TITLE
[Image] Improve error message when "Get alternative text from DAM" is used on an image bound to an asset not having a description

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1276]
## Bug Report

**Current Behavior**

1. add a image component
1. link with asset from DAM which does have its (optional) description property empty
1. open edit dialog
1. click on tab "meta data"
1. check "get alternative text from DAM"
1. try to submit dialog by clicking on "Done"
1. this is not possible as the disabled mandatory field "Alternative Text*" is empty

**Expected behavior/code**
A clear error message stating that the referenced asset does not have a description which can be used as alt text.

**Environment**
- AEM version and patch level: AEMaaCS, 2020.11.4506.20201112T235200Z
- Core Components version: 2.11.1
- JRE version: Java 11

**Possible Solution**
The validation should be improved in a way that the (disabled) input field "Alternative Text*" is only mandatory in case "get alternative text from DAM" is not set. In addition some custom validation must be added which checks if the linked DAM asset has a valid description.

**Additional context / Screenshots**
![Screenshot 2020-11-23 at 10 49 56](https://user-images.githubusercontent.com/185025/99949359-334f6280-2d7b-11eb-895c-0f008d920d17.png)

**Comment by kwin** [comment]
One would probably optionally need to inject a custom validator (https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/reference-materials/granite-ui/api/jcr_root/libs/granite/ui/components/coral/foundation/clientlibs/foundation/js/validation/index.html#example) in https://github.com/adobe/aem-core-wcm-components/blob/dc2fd8a98f2002c8af824cfee1ccff0f1f2797e7/content/src/content/jcr_root/apps/core/wcm/components/commons/v1/clientlibs/editor/checkboxTextfieldTuple/checkboxTextfieldTuple.js#L124. That would allow to overwrite the error message in case "Get alternative text from DAM" is selected and the seed value is empty!

**Comment by comanV** [comment]
@adobe export issue to Jira project SITES
