### ISSUE TITLE
[Page] Prevent loading any JS from Facebook before user triggered the sharing

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1281]
## Feature Request

In https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/clientlibs/site/sharing/js/sharing.js you automatically load `//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7` during page load. That allows Facebook to track users potentially before they have been giving any consent.

Please rather rely on a two-click based solution like https://github.com/heiseonline/shariff to be compliant with GDPR!

**Comment by gabrielwalt** [comment]
In the new page component, we won't have a specific FB or Pinterest sharing capability anymore, but rather output by default the OG meta tags (with the featured image defined at page level for og:image) – see: https://github.com/adobe/aem-core-wcm-components/issues/663. Therefore, the sharing component won't work anymore for the time being on that new page component, and no FB/Pinterest library will be loaded on it.
