### ISSUE TITLE
Form Options multiselect dropdown in android mobile device.

### ISSUE THREAD

**Issue by sainathkoth** [adobe/aem-core-wcm-components#1286]
## Bug Report

**Current Behavior**
We have leveraged OOTB options (core/wcm/components/form/options/v2/options) component, multiselect dropdown does not show selected values in mobile devices of Android. It is working fine in IOS. We have not added any custom css or html. Attaching screenshots for reference.
The issue is replicated in Browser stack tool while testing mobile behavior.
![multiselect-dropdown](https://user-images.githubusercontent.com/75063095/100320370-19b25300-2fe7-11eb-8bf6-996cd12266c5.png)
![multiselect-dropdown-selected](https://user-images.githubusercontent.com/75063095/100320376-1c14ad00-2fe7-11eb-8999-d0469cebcdbd.png)

**Expected behavior/code**
Should be same in IOS and andriod.

**Environment**
AEM 6.5 SP5
Core Components version 2.11.0 (issues exists in 2.12.2)
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)

**Comment by sainathkoth** [comment]
@msagolj ...
Thanks for the update.
Looks like its an issue with Browser stack. Our testing team verified in actual devices and its working fine there.

**Comment by msagolj** [comment]
@sainathkoth ok then i close the issue.
