### ISSUE TITLE
[Image] Image preview/placeholder while loading

### ISSUE THREAD

**Issue by brunob15** [adobe/aem-core-wcm-components#1291]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Display something nice and based on the image while it is being loaded.

**Describe the solution you'd like**
Using [blurha.sh](https://blurha.sh/).

**Are there alternatives?**
It could also be a solid or gradient background with the dominant colors of the image.

**Documentation**
A checkbox in the dialog to enable the feature.

Similar work:
https://using-gatsby-image.gatsbyjs.org/background-color/

Thoughts?

**Comment by ky940819** [comment]
I'm not sure if that solution is reasonable to import into AEM. 
I also like the concept of this, especially with lazy-loading images. 

An idea would be to create a servlet, or use the adaptive image servlet to get a lower quality image, perhaps with a blur filter, that image could be very small (in data, not in actual size) and load until the deferred image is ready. This will also help interface jitter.jump when lazy-loading images load. 

I'd also like to consider adding progressive JPEG images in the Adaptive Image Servlet, but that could be a different issue.
