### ISSUE TITLE
Improve RTE usability in the Text Component

### ISSUE THREAD

**Issue by olenaslyshkova** [adobe/aem-core-wcm-components#1293]
In order to improve RTE usability in the Text Component it would be beneficial to include the following changes:

1. Provide a possibility to enable anchor links via policies.
Currently, it's not possible to enable anchor links without development.
		
2. Provide the same plugins/features in the inline compact toolbar as in the dialog compact toolbar.
It is confusing for editors to see different sets of plugins/features availabled in the inline toolbar and the dialog one.
		
3. Add the missed text-align justify to the dialog compact toolbar.
The justify#justifyjustify feature is missed in the dialog compact toolbar, but present in the inline compact/full-screen and the dialog full-screen toolbars.

**Comment by msagolj** [comment]
@olenaslyshkova thank you for reporting and providing a PR as well.
