### ISSUE TITLE
[Teaser][Download] - the description area of the dialog is not editable on a Cloud instance

### ISSUE THREAD

**Issue by angelmerkle** [adobe/aem-core-wcm-components#1295]
## Bug Report

**Current Behavior**
When opening the dialog of the Teaser and the Download components, the description area remains greyed out on various cloud environments.

This issue does not happen on local instances.

**Comment by msagolj** [comment]
@angelmerkle I took the freedom to remove the template text from your issue description to make it more readable.

**Comment by msagolj** [comment]
@angelmerkle Can you please provide more context ? Teaser Description for various teaser components in various customer projects ? or just one teaser (i guess proxied) for one customer project on stage , dev, cloud ?

**Comment by angelmerkle** [comment]
Hi, Sorry about the lack of detail. So, I am seeing the same issue on all of our Cloud environments (i.e. Dev/Dev 2/Stage and Production).  Also, we kept our original Adobe repository content set up (so that I could use it for things like this to ensure it's not my code that's conflicting) -- and here's what we are seeing for the description.
![image](https://user-images.githubusercontent.com/68657774/101214915-ad140580-3631-11eb-8077-6503d957b718.png)

**Comment by angelmerkle** [comment]
Also, that is calling core/wcm/components/teaser/v1/teaser (not thru any proxy), but the proxy versions do the same behaviors as well.  And to be clear, this is calling it on a blank page that doesn't contain any of my own clientlibs.  This is only calling what Adobe had set up for us within the Adobe Cloud Repo.  which is supposed to come with the proper setup for the Adobe core components. It is also functioning the same way within our code repo as well (but again only on the cloud servers, not on my localhost) - works normally on my local host with the exact same set up as above.

**Comment by angelmerkle** [comment]
Sorry again, I am using version: 2.12.1 of the core components and haven't figure out how to determine which version of AEM I am using within the cloud, because Adobe updates that.

**Comment by cmwdeve** [comment]
hi @msagolj.
we are also experiencing that on the cloud. **This is blocker for us, as this is throwing JS error and blocking further authoring**.

Please find my investigation:
1. On cloud for last couple releases we can see that loading RTE in dialog takes very long. This is reproducable on Core Compontent Text component. Opening dialog, you can see no RTE for 1-2 sec. and then it loads. I haven't investigated why RTE is so slow now.
2. The same problem is with all RTE instances so also in Teaser
3. In checkboxTextfieldTuple there is race condition. 
https://github.com/adobe/aem-core-wcm-components/blob/64bf7857f3fcec24ab9745d6592ae731c92e151e/content/src/content/jcr_root/apps/core/wcm/components/commons/v1/clientlibs/editor/checkboxTextfieldTuple/checkboxTextfieldTuple.js#L44-L47
`self._isRichText` is true but `$(self._textfield).data("rteinstance");` is `undefined`. So couple lines below 
https://github.com/adobe/aem-core-wcm-components/blob/64bf7857f3fcec24ab9745d6592ae731c92e151e/content/src/content/jcr_root/apps/core/wcm/components/commons/v1/clientlibs/editor/checkboxTextfieldTuple/checkboxTextfieldTuple.js#L80
 reading `$element` from `self. _richTextInstance` it's a JS error. RTE is never loaded and further authoring gets blocked.

I think (except of investigation why RTE is so slow) couple things has to be done:
1. Investigate why RTE is not loaded and `dialog-loaded` event was fired 
2. move initialization of Tuple inside editing-start event
https://github.com/adobe/aem-core-wcm-components/blob/64bf7857f3fcec24ab9745d6592ae731c92e151e/content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js#L40-L55


This is reproducable now on every env with 100% cases error rate

**Comment by angelmerkle** [comment]
If needed, I can try changing the version number of my core components to determine if the break is only within this version.  Our team noticed the issue only recently.  We had been using this teaser before on the cloud with success, but we did update our version recently.  So, I don't know if the issue began when I updated the version or if it was due to one of Adobe's recent updates on the servers.

**Comment by jckautzmann** [comment]
Available in Core Components 2.13.2

**Comment by angelmerkle** [comment]
Thanks, I will upgrade my version.

**Comment by angelmerkle** [comment]
Does anyone know when the packages will be available for me to get in the cloud? Currently, it fails my build.

**Comment by bpauli** [comment]
As X-Mas shutdown is approaching daily updates for cloud are paused until 4th of January.
