### ISSUE TITLE
[Accordion] [Carousel] [Tabs] Checkmark icon overlaying text when opening 'Select panel' dropdown

### ISSUE THREAD

**Issue by NelisThomas** [adobe/aem-core-wcm-components#1297]
**Repro steps**
Create a new Core Components Accordion, Carousel or Tabs component. Add at least 2 children. Click the component and choose the 'Select panel' option. The selected panel will have a checkmark icon on top of the text when the panel node is :focus.

**Environment**
- AEM 6.5.6.0
- Core Components version 2.12.2
- Java 11.0.6

**Additional context / Screenshots**
![image](https://user-images.githubusercontent.com/11172558/100849438-dc384480-3482-11eb-8a97-4efd85421f50.png)

**Comment by larsvanpoucke** [comment]
+1
