### ISSUE TITLE
UI kit for Adobe XD link broken in README.md

### ISSUE THREAD

**Issue by davidrmckinnon** [adobe/aem-core-wcm-components#1302]
## Bug Report

**Current Behavior**
The UI kit for Adobe XD link in the project [README.md](https://github.com/adobe/aem-core-wcm-components/blob/master/README.md) under [Features](https://github.com/adobe/aem-core-wcm-components/blob/master/README.md#features) is broken.

**Expected behavior/code**
The link goes to https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/assets/overview/AEM_UI-kit_Wireframe.xd, but this redirects to https://experienceleague.adobe.com/#home

It looks like the link has been lost in moving the documentation to the Experience League Site

**Comment by bohnertchris** [comment]
Thanks for reporting this, @davidrmckinnon. I think you are right about this being a side-effect of the migration. @davidjgonzalez, since you have done a lot of work on the tutorial, can you have a look at this?
