### ISSUE TITLE
[DataLayer] How to add custom key/value pairs?

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-core-wcm-components#1323]
## Feature Request

Utilities like the DataLayerBuilder and other features make it really easy to [enable the data layer for custom components](https://github.com/adobe/aem-core-wcm-components/blob/master/DATA_LAYER_INTEGRATION.md#enabling-the-data-layer-for-custom-components). However is it possible to add properties to the json model that are not part of the pre-defined Core Component data schema? 

**Describe the solution you'd like**
Take for example the [Byline Component](https://github.com/adobe/aem-guides-wknd/blob/master/core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/BylineImpl.java). This component extends the Image component but has additional properties **Occupation** and **Name**. I can implement something like so:

```java
public ComponentData getData() {
        if (ComponentUtils.isDataLayerEnabled(this.resource)) {
            return DataLayerBuilder.extending(getImage().getData()).asImageComponent()
                .withTitle(this::getName)
                .withDescription(() -> 
                    getOccupations().toString()
                )
                .build();
        }
        return null;
    }
```

Resulting in a data layer object like:

```json
byline-ddaf91e9a9:
@type: "wknd/components/byline"
dc:description: "[Artist, Photographer, Traveler]"
dc:title: "Stacey Roswells"
image:
  @type: "image/jpeg"
  repo:id: "142658f8-4029-4299-9cd6-51afd52345c0"
  repo:modifyDate: "2020-12-15T21:19:34Z"
  repo:path: "/content/dam/wknd/en/contributors/stacey-roswells.jpg"
  xdm:tags: []
parentId: "page-b583179409"
repo:modifyDate: "2019-10-18T20:17:24Z"
```

But what if I wish to generate an object like the following:

```diff
byline-ddaf91e9a9:
@type: "wknd/components/byline"
- dc:description: "[Artist, Photographer, Traveler]"
+occupation: ["Artist", "Photographer", "Travler"]
-dc:title: "Stacey Roswells"
+bylineName: "Stacey Roswells"
image:
  @type: "image/jpeg"
  repo:id: "142658f8-4029-4299-9cd6-51afd52345c0"
  repo:modifyDate: "2020-12-15T21:19:34Z"
  repo:path: "/content/dam/wknd/en/contributors/stacey-roswells.jpg"
  xdm:tags: []
parentId: "page-b583179409"
repo:modifyDate: "2019-10-18T20:17:24Z"
```

Can that be achieved? It seems like using the `DataLayerBuilder` there is just a set of `.withXXX` methods to extend an existing Data Layer object.

**Are there alternatives?**
Alternatively I suppose you could generate the JSON String manually but then you wouldn't be re-using the existing utilities...

**Documentation**
https://github.com/adobe/aem-core-wcm-components/blob/master/DATA_LAYER_INTEGRATION.md would include an additional example showing a custom property and value...

**Comment by godanny86** [comment]
@kwin I know you worked on a lot of this, perhaps this is already achievable with the existing implementation?

**Comment by kwin** [comment]
It is possible to extend the data layer. The API was modified in the context of https://github.com/adobe/aem-core-wcm-components/issues/1114. You find an example e.g. in https://github.com/adobe/aem-core-cif-components/pull/415/files.

**Comment by godanny86** [comment]
I suppose I was hoping for a simpler solution that didn't involve creating a new Java interface / impl. I noticed that the https://github.com/adobe/aem-core-cif-components/pull/415/files doesn't use the DataLayerBuilder or any of the utilities. So it seems that these utilities are really for when you extend/overwrite a Core Components logic but not as useful for completely custom data layer schema. Unless I'm misreading the PRs/code?
