### ISSUE TITLE
AEM Core Component Lazy Loading breaks replace asset in Target

### ISSUE THREAD

**Issue by riosmart** [adobe/aem-core-wcm-components#1330]
Issue referenced in https://jira.corp.adobe.com/browse/CQ-4312621

**Current Behavior**
Images cannot be replaced in Target because of same AEM image components lazy load feature

**Expected behavior/code**
Customer can use lazy load while still being able to replace assets in their Target experiences.

**Environment**
- AEM 6.4 (AMS)+ Target
- Core Components version 
- JRE version (e.g. `Java(TM) SE Runtime Environment 

**Possible Solution**
Provide an alternate way to possibly lazy load image
**Additional context / Screenshots**
Screenshots are included in the JIRA referenced above

**Comment by jckautzmann** [comment]
@riosmart @andrewmkhoury How can this issue be tested/verified? Could you please list the exact steps to verify it?

**Comment by riosmart** [comment]
@jckautzmann @bpauli The steps to replicate are included in the JIRA as for replicating the customer's code behavior all you would need is javascript that swaps the image.  Just swap the value of the img src attribute via javascript and scroll the page to see that the image doesn’t get swapped back,

**Comment by andrewmkhoury** [comment]
@jckautzmann

1. Load a page that has the adaptive image component on it then use JS to swap the img src.

For example:
`document.getElementById("myImage").src = 'img/new-image.jpg';`

2. Then use the mouse wheel or scrollbar to scroll down or up on the page and see that the image gets swapped back.

After applying the fix the image will no longer get swapped back to the original.

**Comment by jckautzmann** [comment]
@andrewmkhoury thx for the steps to verify this issue.

**Comment by jckautzmann** [comment]
@andrewmkhoury I was not able to reproduce the issue with the above steps: when scrolling up or down, the image is not swapped back to the original.
Could you please provide a package so I can replicate the issue?

**Comment by andrewmkhoury** [comment]
@jckautzmann  I tested it locally.  I forgot, of course you must enable the lazy loading feature in the template editor first:
https://experienceleague.adobe.com/docs/experience-manager-core-components/using/components/image.html?lang=en#design-dialog
The problem only seems to occur the first time you swap the image and requires no scrolling.  The event listener gets removed there-after so the second time you swap it then it works.

**Comment by jckautzmann** [comment]
@andrewmkhoury Thx for the hint. I had forgotten to enable lazy loading in the template policy.
I was now able to reproduce the issue and to verify that the fix [0] fixed the issue.

[0] https://github.com/adobe/aem-core-wcm-components/pull/1331/files
