### ISSUE TITLE
Core Container - Responsive Grid including through the Sightly data-sly-resource

### ISSUE THREAD

**Issue by Daniil-Zaitsau** [adobe/aem-core-wcm-components#1334]
## Bug Report

**Current Behavior**
Core Container Component, which was added with the data-sly-resource, does not have the ability to add components inside if the responsive layout is selected in policies.

**Expected behavior/code**
I should be able to add components inside.

**Environment**
- AEM 6.5 SP 6.5.6
- Core Components version 2.13.2

**Additional context / Screenshots**
Steps to reproduce:

1. Create a component, that will only extend the Core Container Component (by the sling:resourceSuperType) and will not override any file
![image](https://user-images.githubusercontent.com/44928584/103576992-0c8d5b80-4ee5-11eb-9d09-f2fef7f3c759.png)
2. Create a component, that will include a component from the first stage on the test page using data-sly-resource
![image](https://user-images.githubusercontent.com/44928584/103577272-89b8d080-4ee5-11eb-8cbd-13dfae7fdc17.png)
3. Add a component from the second step to the test page
![image](https://user-images.githubusercontent.com/44928584/103577561-1c596f80-4ee6-11eb-9d24-faa3514a1927.png)
4. Go to the page template editor
![image](https://user-images.githubusercontent.com/44928584/103577819-8540e780-4ee6-11eb-8276-632f8e420fd7.png)
5. Open the design dialog for the component from the first step (container)
![image](https://user-images.githubusercontent.com/44928584/103580052-8411b980-4eea-11eb-8289-f227b4382502.png)
6. Go to the 'Container Settings' tab and select the Responsive Grid as the layout value
![image](https://user-images.githubusercontent.com/44928584/103580377-2467de00-4eeb-11eb-82f0-9acaf94a3a0e.png)
7. Return to the test page. The component has lost the ability to add other components inside
![image](https://user-images.githubusercontent.com/44928584/103578059-f6809a80-4ee6-11eb-8f09-c6ff85c6be2d.png)

**Comment by bpauli** [comment]
@adobe export issue to Jira Project SITES as Bug

**Comment by gabrielwalt** [comment]
Is there a reason why the container cannot be included by path as the page component does [1], as opposed to include the container by resource? Without a use-case, there's no clear reason why this should be necessary.

[1] https://github.com/adobe/aem-core-wcm-components/blob/main/content/src/content/jcr_root/apps/core/wcm/components/page/v3/page/body.html#L18

**Comment by bpauli** [comment]
Closing this issue as mentioned by @gabrielwalt the container can be included by path
