### ISSUE TITLE
[Page ] Adding PWA support

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#1354]
As we're adding Progressive Web App (PWA) support to AEM in the form of it generating a manifest JSON file and a service worker JS file that can be configured via a dialog, we also need to add this capability to the page component. Among other things, the page component must include this additional PWA tab in its edit dialog, and it must render a few related meta tags in the HTML head.

**Comment by bpauli** [comment]
merged in https://github.com/adobe/aem-core-wcm-components/commit/c3ff114f0913edf9f2228c389f059eda629c8680
