### ISSUE TITLE
https://aemcomponents.dev/ left-side navigation broken

### ISSUE THREAD

**Issue by wimsymons** [adobe/aem-core-wcm-components#1366]
## Bug Report

**Current Behavior**
The left-side navigation of https://aemcomponents.dev/ falls of the screen. Happens in Firefox, as well as Chrome and Safari.

**Expected behavior/code**
Left-side navigation is visible/usable.

**Environment**
- Core Components version: 2.13.0

**Possible Solution**
?

**Additional context / Screenshots**
<img width="1636" alt="Schermafbeelding 2021-01-25 om 11 53 18" src="https://user-images.githubusercontent.com/1419117/105696734-ff6ff500-5f03-11eb-8771-30f9602feb80.png">

**Comment by msagolj** [comment]
@wimsymons thx for reporting. We are already aware of that, its an issue with AEM itself. A fix has already been provided. We are currently waiting for it to rollout.

**Comment by wimsymons** [comment]
Thanks for the info :-)
