### ISSUE TITLE
[Teaser] broken links within description field upon editing

### ISSUE THREAD

**Issue by robertbrestle** [adobe/aem-core-wcm-components#1370]
## Bug Report

**Current Behavior**
When modifying any text within a teaser description that contain hyperlinks, the `href` property is removed from existing links upon saving.

**Expected behavior/code**
The links in the description field should persist through future content updates.

**Environment**
- AEM 6.5.5
- Core Components 2.8.0 + 2.13.2
- JRE
    - Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
    - OpenJDK Runtime Environment 18.9 (build 11.0.7+10-LTS)

**Additional context / Screenshots**

Steps to reproduce:
1. Add a teaser component to the page.
2. Add text to the teaser description, then select it and create a hyperlink.
3. Save the teaser. The link should now render as expected.
![image](https://user-images.githubusercontent.com/68937744/105923405-ed747c00-6001-11eb-8d81-a7989e48862a.png)
4. Edit the same teaser.
5. Modify the description with new text - do not modify the existing hyperlink.
6. Save the teaser. The link will now render without an `href` property.
![image](https://user-images.githubusercontent.com/68937744/105923490-10069500-6002-11eb-836d-bae28ea8a7d8.png)

Disabling the Link Checker produces the same results.

**Comment by msagolj** [comment]
Hi @robertbrestle, This is an issue with the RTE widget which is not owned by the core component team.

But I took a quick look as this seems to be the same issue as reported a while ago in #1180. I couldn't reproduce the issue then and I still can't now. I tried different kind of text additions in your step 5, but the link never disappeared (See one attached example). I tested with plain AEM 6.5.0 + Core Comp 2.3.2 and fully patched 6.5.7 with 2.13.2 on Chrome, Edge, Firefox.

If this is continues to be an issue for you, please open a ticket with Adobe support (https://helpx.adobe.com/contact/enterprise-support.ec.html) instead.

[TeaserRTE.zip](https://github.com/adobe/aem-core-wcm-components/files/5881977/TeaserRTE.zip)
