### ISSUE TITLE
Convert Hobbes Tests to JUnit5/Selenium

### ISSUE THREAD

**Issue by anagarwa** [adobe/aem-core-wcm-components#1389]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Existing Test Suit is using hobbes framework, it should move to selenium or junit framework

**Describe the solution you'd like**
Test cases should be on Selenium Framework

**Are there alternatives?**
NA

**Documentation**
Once Test Cases has been adapted to Selenium base framework, a README should explain how to run them

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-core-wcm-components/commit/75511ba9020b34e06a2f222a183d18093a981f15
