### ISSUE TITLE
[Data Layer] When the setting value of Context-Aware Configuration is changed and published multiple times, it is not reflected in publish.

### ISSUE THREAD

**Issue by tos57765** [adobe/aem-core-wcm-components#1396]
## Bug Report

**Steps to reproduce**
1) Set the enabled value of com.adobe.cq.wcm.core.components.internal.DataLayerConfig/.content.xml to "{Boolean} false".
2) Select "Data Layer" in the CA Config Configuration Editor, check "Data Layer enabled", and click the "Save" button.
　(http://localhost:4502/content/[pj-name]/config.html#/com.adobe.cq.wcm.core.components.internal.DataLayerConfig)
3) Click the "Publish this page" button in the CA Config Configuration Editor to publish.
　⇒ When checking the publish instance with CRXDE, it is replicated with "true" as expected.
4) On the screen of 2), uncheck "Data Layer enabled" and click the "Save" button.
5) Click the "Publish this page" button on the screen of 3) to publish.
　⇒ When I check the publish instance with CRXDE, it remains "true".

**Expected behavior/code**
If I checked the public instance in 5), the value of enabled is "false".

**Environment**
- AEM version and patch level (AEM 6.5 SP6)
- Core Components version (2.13.0)
- JRE version (Java(TM) SE Runtime Environment (build 1.8.0_241-b07))
- io.wcm.caconfig.editor.package version (1.6.0 or 1.8.0)

**Additional context / Screenshots**
[Default Context-Aware Configuration settings]
`/conf/[pj-name]/ca-config/_sling_configs/com.adobe.cq.wcm.core.components.internal.DataLayerConfig/.content.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:mix="http://www.jcp.org/jcr/mix/1.0"
    jcr:primaryType="cq:Page">
    <jcr:content
        jcr:isCheckedOut="{Boolean}true"
        jcr:mixinTypes="[mix:versionable]"
        jcr:primaryType="cq:PageContent"
        enabled="{Boolean}false"/>
</jcr:root>
```

The same event occurs for Context-Aware Configuration of PDF Viewer. 
(com.adobe.cq.wcm.core.components.internal.services.pdfviewer.PdfViewerCaConfig)

**Comment by bpauli** [comment]
Hi @tos57765, there is currently no official support for the WCM.io ca config editor by the core components project. However it should work if you also make use of the WCM.io CAConfig extension and enable the Page persistence strategy https://wcm.io/caconfig/extensions/persistence-strategies.html. By enabling this strategy the required `jcr:lastModified` property is set and changes get detected.

cc @jckautzmann @vladbailescu

**Comment by tos57765** [comment]
Hi @bpauli, I appreciate it.
I will try it.
