### ISSUE TITLE
[Embed] Default Embeddable Options are not supported in Editable Templates

### ISSUE THREAD

**Issue by anubajaj23** [adobe/aem-core-wcm-components#1409]
When I am trying to author embed component. In"embeddable" tab I don't see any options available. According to Embed Core component documentation. YouTube has to show up by default

https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed

In our case, We do have editable templates. So will the dropdown always be an empty list?

**Expected behavior/code**
Work for regular page templates.

**Environment**

AEM 6.5.6
Core Components version 2.13

**What i did is:**
Created a component named as 'embed' and added a sling:resourceSuperType="core/wcm/components/embed/v1/embed" in content.xml file.

But the Embeddable options are not available. Can someone please help me out on this?

<img width="676" alt="Screenshot 2021-02-22 at 5 23 11 PM" src="https://user-images.githubusercontent.com/51432815/108704929-ab702480-7532-11eb-8973-e0ab32349b54.png">

**Comment by msagolj** [comment]
Hi @anubajaj23 ,See[ last line](https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed#component-policy-configuration-properties) in section `Component Policy Configuration Properties` and [official docs](https://experienceleague.adobe.com/docs/experience-manager-core-components/using/components/embed.html?lang=en#design-dialog), you first have to go the policy of the embed component and define which embeddables are allowed:

![image](https://user-images.githubusercontent.com/37147400/109004201-b8af1f80-76a8-11eb-9b4a-6f5591c64c9d.png)
