### ISSUE TITLE
[Brand Slug] Allow user to configure the separator

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1416]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When using the brand slug, the separator is always the pipe character "|".
It may be desirable to use a character other than a pipe to separate the page title from the brand slug.

**Describe the solution you'd like**
Allow the character (or string of characters) to be defined either in page properties or in policy.

**Are there alternatives?**
Override the component HTL or live with it.

**Comment by gabrielwalt** [comment]
We're currently not planning to work on that.
