### ISSUE TITLE
[Teaser] Delete `linkURL` if `Enable Call-To-Actions` is checked

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1417]
## Bug Report

**Current Behavior**
If the link field is set prior to the `Enable Call-To-Actions` field being checked, then the link URL is retained.
The effect of this is that the image is still linked to the linked URL even though the field is disabled (greyed out) in the editing interface. 

There is no intuitive way for the author to correct this issue; they must disabled the CTA links, delete the link URL, then save and close the dialog, then open it again re-enable the CTA links without modifying the primary link field.

**Expected behavior/code**
When the user selects to "Enable Call-To-Actions" and the "Link" field is disabled; the [now non-editable] "Link" field should have no effect on the rendering of the teaser

**Environment**
- AEM 6.5.7.0
- Core Components 2.15.0
- Java 11

**Possible Solution**
Clear the "Link" field, or set a delete hint, or some combination of the two. 
Alternatively, allow access to the image resource model directly from the teaser model - wrap that resource and suppress the linkURL field, 

If desired, the wrapped resource could also add the `linkURL` field and set it to the value of the first CTA such that its behaviour would be consistent with how the Teaser title takes the first CTA as it's link value. 

If done this way then:

```
if (first CTA URL is set) ; then :
    use first CTA URL as first CTA href
    use first CTA URL as Title href
    use first CTA URL as Image link href
else if (`linkUrL` is set); then :
    use first CTA URL as Title href
    use first CTA URL as Image link href
else :
    no links
```

**Comment by gabrielwalt** [comment]
This is in line with https://github.com/adobe/aem-core-wcm-components/issues/1712 to avoid duplicate links on title and CTA that usually are problematic for accessibility.
