### ISSUE TITLE
AMP Mode not showing in template properties

### ISSUE THREAD

**Issue by jpringdev** [adobe/aem-core-wcm-components#1422]
## Bug Report

**Current Behavior**
At the moment we have installed version 2.13.4 core components in the hopes to start leveraging the AMP mode for our editable templates. However once installing and pointing our superType to the amp page component we are still not seeing the AMP Mode appear within the template properties. We have raised this issue with AEM support who have tried multiple things including taking our package and testing against a working configuration but there has been no joy. 

I have also seen a similar forum which mention performing a maven build on the source code which I have also tried but there is still no change. 

**Expected behavior/code**
We are expecting to see the AMP Mode appear within the page properties of our AEM editable templates. 

**Environment**
- AEM 6.5.6
- Core Components version 2.13.4

![Screenshot 2021-03-02 at 15 06 00](https://user-images.githubusercontent.com/79911883/109668321-f8727d00-7b68-11eb-8312-370a5424a8c4.png)
![Screenshot 2021-03-02 at 15 06 30](https://user-images.githubusercontent.com/79911883/109668341-fd373100-7b68-11eb-8489-828c1c274667.png)

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by msagolj** [comment]
Hi @jpringdev,, looking at the screenshot it seems you added the `sing:resourceSuperType` as a property to your template node which is not the right location. Instead you should replace the supertype in the page component of your project e.g.

`/apps/<yourproject>/components/page/sling:resourceSuperType`

and set it to `core/wcm/extensions/amp/components/page/v1/page`.
