### ISSUE TITLE
[Tabs][Accordion] Deep Linking not working

### ISSUE THREAD

**Issue by tim-white-esri** [adobe/aem-core-wcm-components#1432]
## Bug Report

**Current Behavior**
When deep linking to a tab in Core Tab, the tab itself is selected, but the tab panel does not get activated. 

**Expected behavior/code**
When deep linking to a specific tab, page should scroll to tab component and activate the selected tab. 

**Environment**
- AEM 6.5.7.0
- Core Components version 2.13

**Additional context / Screenshots**
Using URL - `core-components.html#Configure-item-a69da3a1fc-tab`

Third tab ('Controls') shows highlight, but active panel is still 'Calendar'
![tab-selected-not-active](https://user-images.githubusercontent.com/26779414/110173336-48dd1b00-7db3-11eb-90e0-a1db1fa9edad.png)

Console showing first tab still has `aria-selected="true"` and `cmp-tabs__tab--active`. Should be on third tab instead
![tab-not-active](https://user-images.githubusercontent.com/26779414/110173377-5692a080-7db3-11eb-8ce8-19f587fa607a.png)

**Comment by tim-white-esri** [comment]
Installed Core 2.15, problem still present. Also tested Accordion; it has the same issue.

**Comment by msagolj** [comment]
@tim-white-esri thx for reporting, i was able to reproduce the issue with the tabs component. The accordion seems to have a similar issue, as you mentioned. First time it just scrolls to the accordion, requesting again opens the accordion tab. see attached movie.
[accordion_deeplink.zip](https://github.com/adobe/aem-core-wcm-components/files/6108557/accordion_deeplink.zip)

**Comment by tim-white-esri** [comment]
@msagolj -- Thank you for verification. I haven't checked, but I wouldn't be surprised if the behavior was the same for Carousel.

**Comment by tjameswhite** [comment]
@vladbailescu -- I just tested core 2.16 and this issue does not seem to be resolved. 
@msagolj have you tested v2.16 yet? 

Adding the Tab or panel ID to the URL is not producing desired effect. 
Tested tab ID:
- page with Core Tab
- Add tab id to URL: `/core-components#MyTabs-item-e0b77b625b-tab`

Expected: 
- page to anchor to tab, activate the selected tab and panel

Actual:
- Page anchors to Core Tab, desired tab briefly hightlights, then resets to default tab. 
- Selected panel is never active, only the tab

Tested panel ID:
- page with Core Tab
- Add panel id to URL: `#MyTabs-item-e0b77b625b`

Expected:
- page to anchor to Core Tab, activate selected panel

Actual:
- page anchors to Core Tab, default panel active

**Comment by comanV** [comment]
> @vladbailescu -- I just tested core 2.16 and this issue does not seem to be resolved.
> @msagolj have you tested v2.16 yet?
> 
> Adding the Tab or panel ID to the URL is not producing desired effect.
> Tested tab ID:
> 
> * page with Core Tab
> * Add tab id to URL: `/core-components#MyTabs-item-e0b77b625b-tab`
> 
> Expected:
> 
> * page to anchor to tab, activate the selected tab and panel
> 
> Actual:
> 
> * Page anchors to Core Tab, desired tab briefly hightlights, then resets to default tab.
> * Selected panel is never active, only the tab
> 
> Tested panel ID:
> 
> * page with Core Tab
> * Add panel id to URL: `#MyTabs-item-e0b77b625b`
> 
> Expected:
> 
> * page to anchor to Core Tab, activate selected panel
> 
> Actual:
> 
> * page anchors to Core Tab, default panel active


> @vladbailescu -- I just tested core 2.16 and this issue does not seem to be resolved.
> @msagolj have you tested v2.16 yet?
> 
> Adding the Tab or panel ID to the URL is not producing desired effect.
> Tested tab ID:
> 
> * page with Core Tab
> * Add tab id to URL: `/core-components#MyTabs-item-e0b77b625b-tab`
> 
> Expected:
> 
> * page to anchor to tab, activate the selected tab and panel
> 
> Actual:
> 
> * Page anchors to Core Tab, desired tab briefly hightlights, then resets to default tab.
> * Selected panel is never active, only the tab
> 
> Tested panel ID:
> 
> * page with Core Tab
> * Add panel id to URL: `#MyTabs-item-e0b77b625b`
> 
> Expected:
> 
> * page to anchor to Core Tab, activate selected panel
> 
> Actual:
> 
> * page anchors to Core Tab, default panel active


The new PR should solve the potential issues with the Tabs and Accordion components.  Adding the tab `/core-components#MyTabs-item-e0b77b625b-tab` or the accordion `/core-components#Myaccordion-6c8513b5eb-item-ac52ebd13f` item to the URI should produce the desired effect.
