### ISSUE TITLE
[Teaser] Allow title heading levels to be restricted by policy

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1458]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The teaser component allows a template editor to enable the author to select the heading level for a teaser title.
However, unlike other components that also allow this (e.g. Title, Text) the teaser component does not allow the list of available heading options to be restricted via policy. If the author is given the ability to select the heading level, then they might be presented with heading levels that are not suitable for the use case.

**Describe the solution you'd like**
Allow the template editor to restrict the list of available heading levels by policy.
The exact same solution that is used for the Title component can be employed for the Teaser component - including the same data source for providing the options.

**Are there alternatives?**
Override the component for each use case and hide the options in the dialog.

**Comment by comanV** [comment]
@adobe export issue to Jira project SITES
