### ISSUE TITLE
[Container] Background image with whitespace do not work

### ISSUE THREAD

**Issue by marekczajkowski** [adobe/aem-core-wcm-components#1468]
### Expected Behaviour
Image with whitespace in it's path should work
### Actual Behaviour
Image with whitestaces in it's path do not work
#### Steps to Reproduce
1. Create a container
2. Set background image using file that have 'space' in it's name
3. Verify that no background image is displayed
#### Platform and Version
Core components 2.13.2

**Comment by msagolj** [comment]
@marekczajkowski thx for reporting, I was able to reproduce it by uploading an asset with spaces as an background image in latest version.

According to [W3C Standard](https://www.w3.org/TR/2011/REC-CSS2-20110607/syndata.html#uri) the URI values should either be in single or double quotes or special characters like whitespace should be escaped.
