### ISSUE TITLE
[Accessibility][Container] Allow to define ARIA labels and role attributes on the container

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#1469]
As an author, I want to be able to add ARIA labels on the container, so that my site structure has accessible landmarks.

To avoid requiring a new version, insert the "Label" field to the current tab of the edit dialog.

**Comment by gabrielwalt** [comment]
We actually also need a "Role" text field in the dialog that outputs a `role` attribute on the container element.

**Comment by comanV** [comment]
> We actually also need a "Role" text field in the dialog that outputs a `role` attribute on the container element.

I opened PR for the enhancement: https://github.com/adobe/aem-core-wcm-components/pull/1507

**Comment by gabrielwalt** [comment]
Thanks @comanV, your PR looks good to me, just very quickly looking at it!
