### ISSUE TITLE
[Embeddable] Design Dialog for the custom embeddable not working as expected

### ISSUE THREAD

**Issue by techforum-repo** [adobe/aem-core-wcm-components#1481]
## Bug Report

[custom-embed-1.0.zip](https://github.com/adobe/aem-core-wcm-components/files/6237134/custom-embed-1.0.zip)

<img width="936" alt="Embed-Policy" src="https://user-images.githubusercontent.com/59318496/113085327-392fd700-91a5-11eb-9f1c-e153fffd930b.png">

**Current Behavior**
 Created an additional embeddable for Vimeo(copied YouTube embeddable and modified the required properties)
 - The design dialog tab for the additional embeddable(Vimeo) is always displayed
 - The design dialog tab for the YouTube is not visible while the additional embeddable is selected(Vimeo)

**Expected behavior/code**
The design dialog tab should be displayed based on the embeddable selection
 - YouTube tab should be displayed on selection of YouTube
 - Additional tabs should be displayed based on the custom embeddable(Vimeo) selection
 - Multiple tabs displayed on selecting multiple embeddable

**Environment**
- AEM version and patch level - aem-sdk-quickstart-2021.2.4887.20210204T154817Z-210128
- Core Components version -  2.15.2
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`) - "11.0.9"

**Possible Solution**

**Additional context / Screenshots**
Attaching the package with custom embeddable(Vimeo) along with the screenshot

**Comment by ky940819** [comment]
On a side note, I'd like to see Vimeo OOTB supported if possible.

**Comment by tjameswhite** [comment]
Agree that Vimeo should be handled by the URL field. We are in the process of manually adding it (https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/extending-embed-component/qaq-p/364974)

**Comment by bpauli** [comment]
@tjameswhite I provided a fix for the design dialog in #1524. Can you please check if this is working for you as expected?

It would be great if you could also contribute your custom Vimeo embeddable to the core components project. Thanks!

**Comment by techforum-repo** [comment]
> @tjameswhite I provided a fix for the design dialog in #1524. Can you please check if this is working for you as expected?
> 
> It would be great if you could also contribute your custom Vimeo embeddable to the core components project. Thanks!

@tjameswhite 

Thanks for addressing the issue, let me validate.

I am so hapy to contribute, let me clean up the vimeo embeddable code and folllow the merge process
