### ISSUE TITLE
[Library] Update component titles and group names

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#1484]
There are discrepancies between the component and group names and those displayed on the component library on [aemcomponents.dev](https://aemcomponents.dev/). It would be expected that all names and titles of the component library match the component titles and group names. The updates listed below would make it overall more consistent.

**Groups**

* Rename title "Templating" => "Core Structure"
* Move path "/content/core-components-examples/library/templating" => "core-structure"
* Rename title "Page Authoring" => "Core Content"
* Move path "/content/core-components-examples/library/page-authoring" => "core-content"
* Move content of "/content/core-components-examples/library/container" => "core-content"
* Rename title "Form" => "Core Form"
* Move path "/content/core-components-examples/library/form" => "core-form"

**Components**

* Move path "/content/core-components-examples/library/core-content/progressbar" => "progress-bar"
* Rename title "Social Sharing" => "Social Media Sharing" - excepted for the teaser on the homepage where we can keep the shorter text "Social Sharing"
* Move path "/content/core-components-examples/library/core-content/social-sharing" => "sharing"
* Rename title "Container" for form container => "Core Form Container" (and delete navTitle)
* Move path "/content/core-components-examples/library/core-form/container" => "../page-authoring/form-container"
* Rename title "Input" => "Form Text" (and delete navTitle)
* Move path "/content/core-components-examples/library/core-form/input" => "text"
* Rename title "Options" => "Form Options" (and delete navTitle)
* Rename title "Hidden" => "Form Hidden" (and delete navTitle)
* Rename title "Button" => "Form Button" (and delete navTitle)

**Ordering**

* As all container components are moved into the "Core Content" section, move them to the very top of the list.
* As the "Core Form Container" is moved into the "Core Content" section, move it right after the other container components, so between the "Accordion" and the "Title" components.

**Misc**

* The adobe.com/go/ URLs from the docs need to be updated accordingly to the pages that are moved.

Here's the full list of component titles and group names that might help:
![core-components](https://user-images.githubusercontent.com/130083/113141910-95890a00-922a-11eb-8d8a-95757397db0f.png)

**Comment by rismehta** [comment]
cc: @virresh

**Comment by virresh** [comment]
@gabrielwalt @vladbailescu I'd like to work on this issue, but I'm not entirely sure how to go about the Misc (i.e `adobe.com/go` urls).
 
Should this be a change done after code with modified paths is released or it can be done simultaneously?

**Comment by virresh** [comment]
@jckautzmann @gabrielwalt @vladbailescu is there something remaining to be done in this issue?

Was curious about the timelines for these changes to make it to a release. (it's a pre-requisite for https://github.com/adobe/aem-core-forms-components/pull/42 and I don't see it in the [next release milestone](https://github.com/adobe/aem-core-wcm-components/milestone/47) 😅  )

**Comment by jckautzmann** [comment]
@virresh Thx for following up on this ticket. The fix will be available with the 2.18 release which is coming up in a few days. I just updated the milestone to reflect it.
