### ISSUE TITLE
[Accordion] Style System selection is being ignored for accordion

### ISSUE THREAD

**Issue by vladbailescu** [adobe/aem-core-wcm-components#1510]
Selected styles do no apply for accordion component, it always uses de default style class.

Steps to reproduce:
- Create a content policy for Accordion component and add some styles
- Add an Accordion to a page that uses the content policy
- Select one of the styles for the accordion

Expected:
- The selected style is applied

Actual:
- The selected style is not applied. It's not selected in the styles panel and the class does not get added in the markup. Instead, the default style class gets added (if defined).

**Comment by vladbailescu** [comment]
Investigation shows all styles defined for accordions are missing `cq:styleId` property because an exception thrown at https://github.com/adobe/aem-core-wcm-components/blob/8e9280e9241e63face5a81a5b4744888ef24a0e1/content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/editor/js/accordion.js#L252 prevents the `dialog-ready` to bubble up in the content policy editor and breaks the functionality that computes the ids.

**Comment by tjameswhite** [comment]
We've seen this behavior randomly whenever using style systems. Sometimes they get applied, other times they don't. We have to delete, move, re-add... basically we try all sorts of things to get them to take.
