### ISSUE TITLE
Embed Core Component Customisation Issue 

### ISSUE THREAD

**Issue by anubajaj23** [adobe/aem-core-wcm-components#1514]
I have also raised a Support Ticket for this.(E-000356775)

We are trying to extend the AEM Embed Core Component (v2.15.0) to include a custom URL processor. The PinterestUrlProcessor was used as reference, and similar files were added for the custom Url Processor: 

## Bug Report

**Current Behavior**
1. DotDigitalUrlProcessor.java (similar to PinterestUrlProcessor.java, it returns a new instance of UrlProcessorResultImpl with dotdigital as processor name.)
2. com.bp.navitas.cms.embed.DotDigitalUrlProcessor.xml for the OSGi config (similar to com.adobe.cq.wcm.core.components.internal.services.embed.PinterestUrlProcessor.xml)
3. Added embed node under project directory under apps (in crx/de/) and added a dotdigital.html file under the processors folder (Screenshot 1)

When the embed component is added on a page with a custom url, it is observed that the custom DotDigitalUrlProcessor is added in the list of processors in the servlet (EmbedUrlProcessorServlet.java), and the code inside the custom processor is indeed executed. (Screenshot 2)

However, on saving the component, the content is not rendered in the embed component. On debugging, it is seen that in EmbedImpl.java, the custom processor is not present in the list of url processors. (Screenshot 3)

Also, it is observed that after deployment of these changes, two entries of each of the core components are available in Felix console (Screenshot 4)

Can you please let us know what is missing in this implementation? This is a critical implementation for our project and there are multiple such custom processors that need to be created to support various features.

**Expected behavior/code**
Should be able to add custom URL Processor

**Environment**
- AEM v6.5.8
- Core Components version (2.15.0)

**Additional context / Screenshots**

<img width="920" alt="Screenshot 1" src="https://user-images.githubusercontent.com/51432815/114655663-481c9a80-9d0a-11eb-8513-7ff8909c0812.png">

<img width="1617" alt="Screenshot 2" src="https://user-images.githubusercontent.com/51432815/114655711-61bde200-9d0a-11eb-9289-ae6d6c26f4d8.png">

<img width="1631" alt="Screenshot 3" src="https://user-images.githubusercontent.com/51432815/114655723-6b474a00-9d0a-11eb-9ec2-782949d7f28c.png">

<img width="1297" alt="Screenshot 4" src="https://user-images.githubusercontent.com/51432815/114655750-74381b80-9d0a-11eb-8077-0352ad136684.png">

**Comment by vladbailescu** [comment]
> Also, it is observed that after deployment of these changes, two entries of each of the core components are available in Felix console (Screenshot 4)

Can you, please, check if you have the Core Components bundle installed multiple times by any chance? You might be hitting https://github.com/adobe/aem-core-wcm-components/issues/1290#issuecomment-737744892

**Comment by anubajaj23** [comment]
We dont install core components bundle manually, it is added as dependency via pom xml and it is being rendered only once.

**Comment by vladbailescu** [comment]
@anubajaj23, The steps you took seem correct. I wasn't able to reproduce it on our end; if you're sure the instance is in a healthy state, I will need to check if it's something in your implementation of the `UrlProcessor`.

Could you upload a minimal bundle  & package (custom UrlProcessor, OSGI config and embed HTL script) for reproducing the issue? If you cannot share one publicly, work with customer support to get a request-for-help and have them ping me on the issue.

**Comment by vladbailescu** [comment]
@anubajaj23, I found the class and OSGi configuration that you shared with customer support. I see several potential issues:

1. You are importing an internal Core Components class (`com.adobe.cq.wcm.core.components.internal.services.embed.UrlProcessorResultImpl`). I'm wondering how you are doing this. If you imported or copied over all the code from Core Components into your bundle, that might explain why you see the OSGi Component duplicates.
2. You seem to define the OSGi Component for your `UrlProcessor` with an XML OSGi config. That's not necessary if the bundle plugin is properly configured (see https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/pom.xml#L42-L89)
3. The HTL script was not shared and I don't know if you are using a proxy component for the Embed and if it's properly placed in the `processors` folder. But from your description you don't appear to get that far.

Using the class you shared I was able to create a small bundle that does not need an OSGi config to register your custom `UrlProcessor`. I created a test HTL script as well and everything worked as expected.

**Comment by meetgds** [comment]
@vladbailescu  Thanks for sharing the info. 

- We have added the core components dependency in our code (in pom.xml). That is how we imported the class `com.adobe.cq.wcm.core.components.internal.services.embed.UrlProcessorResultImpl `. We took clues from the PinterestUrlProcessor class which also imports the above class. We are following steps mentioned in (https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed) under Extending the Embed Component section.
- I think we did use a proxy component for the Embed and it is placed in processors folder. I'm attaching a screenshot for the same, can you have a look and confirm if it is correctly configured?

![image](https://user-images.githubusercontent.com/16129018/114829081-49bc9000-9de8-11eb-9cd8-faa69b54b6a1.png)

- Also, can you please share the bundle that you created with our UrlProcessor with the HTL script, so we can compare it with ours and debug, please?

**Comment by anubajaj23** [comment]
Hi @vladbailescu,

Thanks for your reply!

But still we are not able to achieve Custom URL Processor. Can you please reply on the above comment? or if possible can you please share the bundle that you created.

**Comment by vladbailescu** [comment]
@anubajaj23 , @meetgds , to be able to deploy the code as a minimalistic bundle I had to get rid of the `internal` package import, by changing:

```
                    return new UrlProcessorResultImpl(
                        NAME,
                        new HashMap<String, Object>() {
                            {    
                                try {
                                    this.put("dotDigitalUrl", buildScriptUrl(dotdigitalUrl, domain.get()));
                                } catch (UnsupportedEncodingException e) {
                                    LOGGER.error("Got error while building script url  ", e);
                                }
                            }
                        });
```
to
```
                    return new UrlProcessor.Result() {
                        @Override
                        public String getProcessor() {
                            return NAME;
                        }

                        @Override
                        public Map<String, Object> getOptions() {
                            return new HashMap<String, Object>() {
                                {
                                    try {
                                        this.put("dotDigitalUrl", buildScriptUrl(dotdigitalUrl, domain.get()));
                                    } catch (UnsupportedEncodingException e) {
                                        LOGGER.error("Got error while building script url  ", e);
                                    }
                                }
                            };
                        }
                    };
```
I attached the minimalistic bundle and a sample content package:
* [dotdigital-bundle-0.0.1-SNAPSHOT.zip](https://github.com/adobe/aem-core-wcm-components/files/6323216/dotdigital-bundle-0.0.1-SNAPSHOT.zip)
* [dotdigital-package-0.0.1-SNAPSHOT.zip](https://github.com/adobe/aem-core-wcm-components/files/6323217/dotdigital-package-0.0.1-SNAPSHOT.zip)

Hope this helps!

**Comment by anubajaj23** [comment]
Hi @vladbailescu,

Much appreciated, it is working now. 

Can i ask one more question please, Can we disable default URL processor(Piinterest,oEmbed) functionally for our custom project ?

We have tried by making a custom copy of PinterestUrlProcessor.java (and returning null) doesn't help, it doesn't replace the existing pintrest processor, but adds an additional.

Can you please help me on this as well ?

**Comment by vladbailescu** [comment]
@anubajaj23 , there is currently no way to disable the built-in processors. You could add another processor that has a higher `@ServiceRanking` and accepts the same URL but provides empty response, as a workaround.

**Comment by anubajaj23** [comment]
Hey @vladbailescu,

Yes i have tried by doing that only, attaching two different version but the core PinterestUrlProcessor class is still executed.

[Archive.zip](https://github.com/adobe/aem-core-wcm-components/files/6325321/Archive.zip)

Can you please look into this ?

**Comment by vladbailescu** [comment]
You will need to not return `null` (because that basically means the UrlProcessor cannot process the URL) but rather a `UrlProcessor.Result` that points to a different HTL script that does nothing. This will cause the URL to be accepted in the editor but not render anything. Like I said, a (rather ugly) workaround.
