### ISSUE TITLE
[RTE Link] - Provide an option to add `aria-label` when links authored with imperceptible text

### ISSUE THREAD

**Issue by thomsebastin** [adobe/aem-core-wcm-components#1525]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When a link is present in RTE and is not provided with a meaningful text It can cause accessibility issues. Screen reader users need to know where a link is pointing. Inner link text provides this information.

**Describe the solution you'd like**
Having an option to include `aria-label` attribute optionally to such links will help in solving this issue.

UPDATE: After discussing this with the customer, I realize that there's a certain risk attached to giving the author the ability to add `aria-label` as this can be abused by the authors by adding them in places where they are not required. 

It's worth discussing though as to how this can be tackled in an efficient way.

**Are there alternatives?**
RTE may be customized to include this behavior, but I am not sure about it.

**Documentation**
```*.html
 <h4>Neighborhood News</h4>
 <p>Seminole tax hike: Seminole city managers are proposing a 75% increase in 
 property taxes for the coming fiscal year.
     <a href="taxhike.html" aria-label="Read more about Seminole tax hike">[Read more...]</a>
 </p> 
 <p>Baby Mayor: Seminole voters elect the city's youngest mayor ever by voting in 3 year
 old Willy "Dusty" Williams in yesterday's mayoral election.
     <a href="babymayor.html" aria-label="Read more about Seminole's new baby mayor">[Read more...]</a>
 </p>
```

**Comment by richardhand** [comment]
This feature request is related to the RichText Editor and is outside the scope of the Core Components project.
