### ISSUE TITLE
[Image] Use browser native image lazy loading where supported

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-core-wcm-components#1529]
## Feature Request

The Image Core Component supports lazy loading today. In meantime, browser vendors have started adding native support for lazy loading. See https://caniuse.com/loading-lazy-attr 

**Describe the solution you'd like**

Use the browser native lazy loading where possible, and fallback to our current custom solution were that is not yet the case.

**Comment by vladbailescu** [comment]
Maybe this would be a good update to https://github.com/adobe/aem-core-wcm-components/issues/496#issuecomment-475210979. We have a feature branch already for Image v3: https://github.com/adobe/aem-core-wcm-components/pull/1423
