### ISSUE TITLE
[Tabs] [Accordion] Deep Linking not working

### ISSUE THREAD

**Issue by tjameswhite** [adobe/aem-core-wcm-components#1542]
Issue with deep linking to tabs/panels does not seem to have been resolved. 

@vladbailescu -- I just tested core 2.16 and this issue does not seem to be resolved. 
https://github.com/adobe/aem-core-wcm-components/issues/1432
@msagolj have you tested v2.16 yet? 

Adding the Tab or panel ID to the URL is not producing desired effect. 
Tested tab ID:
- page with Core Tab
- Add tab id to URL: `/core-components#MyTabs-item-e0b77b625b-tab`

Expected: 
- page to anchor to tab, activate the selected tab and panel

Actual:
- Page anchors to Core Tab, desired tab briefly highlights, then resets to default tab. 
- Selected panel is never active, only the tab

Tested panel ID:
- page with Core Tab
- Add panel id to URL: `#MyTabs-item-e0b77b625b`

Expected:
- page to anchor to Core Tab, activate selected panel

Actual:
- page anchors to Core Tab, default panel active

_Originally posted by @tjameswhite in https://github.com/adobe/aem-core-wcm-components/issues/1432#issuecomment-827753502_

**Comment by msagolj** [comment]
hI @tjameswhite , i had a quick check with Tabs and Accordion using 2.16.0 on a SDK QS and it working for me, see attached video.

[tabs_accordion.zip](https://github.com/adobe/aem-core-wcm-components/files/6453902/tabs_accordion.zip)

**Comment by tjameswhite** [comment]
Thank you @msagolj -- I'll double check. We have some default styles on our end - including some JS; I'll bet something is interfering. 

If I can verify the issue on our end I'll close this out in the next day or two.

**Comment by mpanecki-wundermanthompson** [comment]
The issue that I had was connected to Tabs component and the keyboard navigation. Before you interact with a mouse tab into the first tab and use keyboard navigation. Then when the deeplinking is called it returns value from session storage as `string` and the keyboard navigation concatenates it like `"0" + 1` -> `"01"` or something similar. The easiest fix for it is to modify existing function to look like this:
```
getDeepLinkFromSessionStorage() {
        return this._config.element.id
            ? parseInt(sessionStorage.getItem(LAST_TAB_INDEX_PREFIX + this._config.element.id))
            : null;
    }
```
Then it will be always a number. Then the `parseInt` at this code is not required: 
```
refreshActive() {
        var tabpanels = this.elements["tabpanel"];
        var tabs = this.elements["tab"];

        if (tabpanels) {
            if (Array.isArray(tabpanels)) {
                for (var i = 0; i < tabpanels.length; i++) {
                    if (i === parseInt(this._active)) { 
```
I also checked `CQ.CoreComponents.container.utils.getDeepLinkItemIdx(this, "tabpanel")` but it seems to always return `number`

**Comment by tjameswhite** [comment]
Just a follow-up. We took out all the custom code we have that affects Core components and the deep linking still does not work for us. When linking to the tab as @msagolj 's video does, it will highlight the tab, but not activate the panel. 

We are going to pull the latest version (1.17.10) and test again.

**Comment by tjameswhite** [comment]
Tested 2.17.10 without out our code and it appears to be working. v2.16 does not work with our without our custom code. 

Closing this issue and will further test 2.17.10 implementation.
