### ISSUE TITLE
Container: Code Quality: Redundant data-sly-test

### ISSUE THREAD

**Issue by VikashKotharyWork** [adobe/aem-core-wcm-components#1557]
### Actual Behaviour

Redundant line of code in Simple Container HTL.

#### Sample Code that illustrates the problem

You have a data-sly-test that controls whether a template should be rendered.

https://github.com/adobe/aem-core-wcm-components/blob/b949dd87e666424938d9a684d72e412b6ec5802e/content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html#L24

But a line after there is another data-sly-test that uses the reference from the above. This is completely redundant, correct?

https://github.com/adobe/aem-core-wcm-components/blob/b949dd87e666424938d9a684d72e412b6ec5802e/content/src/content/jcr_root/apps/core/wcm/components/container/v1/container/simple.html#L25

### Expected Behaviour

If the above is correct, then that line of code should be removed as it does nothing.

**Comment by msagolj** [comment]
Hi @VikashKotharyWork yes, your right its redundant.  We will remove it or you can provide a PR.

**Comment by msagolj** [comment]
@VikashKotharyWork  thanks for the PR , verified and merged.
