### ISSUE TITLE
CaConfigReferenceProvider added with Core Components 2.12 doesn't provide references properly

### ISSUE THREAD

**Issue by makro2400** [adobe/aem-core-wcm-components#1558]
## Bug Report

Reference provider added in 2.12 doesn't provide references correctly, and it's impossible to disable it
**Current Behavior**
I can see three issues with it, besides of already reported ones:
1. It finds references under /conf however in some scenarios it checks _jcr:lastModified_ property on cq:Page node, which is wrong. The result is that it provides list of references, which will always be in up-to-date state for AEM, causing that references won't get published, as next reference providers won't be able to provide the same references properly (see also 3rd point)
2. CaConfigReferenceProvider  is checking **only** jcr:lastModified, where even Page object is checking also _cq:lastModified_ property
3. There is no way to disable CaConfigReferenceProvider, which causes that the reference providers provided by the project or third party libraries may be executed after this one. AEM doesn't provide any way to define reference providers order (it cannot be achieved through _service.ranking_ property)

**Expected behavior/code**
1. CaConfigReferenceProvider checks if reference is of type _cq:Page_, and if yes, it reads last modified date from jcr:content node
2. CaConfigReferenceProvider should check for both properties, _jcr:lastModified_ and _cq:lastModified_ properties, as AEM does it
3. There should be possibility to disable CaConfigReferenceProvider through OSGI configuration. It should be enabled by default

**Environment**
- AEM version and patch level: AEM 6.5 SP8
- Core Components version: 2.15.0
- Java 11

**Possible Solution**
As a workaround, one could disable the reference provider delivered by Core Components. ACS Commons has ComponentDisabler service which allows to disable OSGI services automatically whenever they are started (also after restart)

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES
