### ISSUE TITLE
[Text] RTE Features in Edit Dialog are not controlled by Component Policies

### ISSUE THREAD

**Issue by drj101687** [adobe/aem-core-wcm-components#158]
V1 Text Component does not have an Edit Dialog, it only provides in-line editing with fullscreen view. When customizing a Content Policy for the V1 Text component, all enabled features are available within the fullscreen view.

The V2 Text Component introduced a cq:dialog node which allows the Author to open an Edit Dialog. The Content Policies are not controlling the RTE features available within the Edit Dialog. This produces a conflicting Author Governance experience. 

summary:
I can control the RTE features in in-line fullscreen mode using Content Policies, but I cannot control the Edit Dialog RTE features with Content Policies.

desired results:
I can control the RTE features both within in-line fullscreen mode and within an Edit Dialog.

I'm not sure if controlling Edit Dialog features with Content Policies is even possible or intended, but there's definitely a conflict here. This could be an architectural problem rather than a code problem.

Screenshot of the Content Policy for a V2 Text Component:
![screen shot 2018-04-05 at 4 58 40 pm](https://user-images.githubusercontent.com/16684869/38391602-ac8b5fda-38f2-11e8-9375-e6a8fa75f9e1.png)

Screenshot of the in-line fullscreen RTE with features defined in above Policy:
![screen shot 2018-04-05 at 4 57 46 pm](https://user-images.githubusercontent.com/16684869/38391639-d017aef4-38f2-11e8-8188-1f268d002dbc.png)

Screenshot of the Edit Dialog RTE with incorrect features defined in the above Policy, instead using the defined cq:dialog node for the V2 Text Component:
![screen shot 2018-04-05 at 4 56 58 pm](https://user-images.githubusercontent.com/16684869/38391689-f30dcbbe-38f2-11e8-8a2f-3ebc2884036d.png)

Tested with We.Retail on AEM 6.3.1 with Featurepack-20593-1.8

**Comment by bpauli** [comment]
@drj101687 Thank you for bringing up this issue!

Indeed, this is not the expected behaviour. The edit options for the RTE should be the same in the edit dialog as for the inplace editing.

We will provide a fix for this bug in one of the future versions of the core-components.

**Comment by gabrielwalt** [comment]
This will be fixed with 6.3.3.2.

**Comment by kwin** [comment]
@gabrielwalt Can you also say, which version of AEM 6.4 contains this fix?

**Comment by bpauli** [comment]
@kwin It will be part of SP 6.4.3

**Comment by msagolj** [comment]
Quick update: it will already be part of 6.3.3.1.

**Comment by MadhuSamala7189** [comment]
The RTE plugins missing on Core Text v2 component is still happening on both static and editable templates, we are currently on AEM 6.3.3.3.
Is there any fix for this. 
Thanks.

**Comment by richardhand** [comment]
As @MadhuSamala7189 reports, I still see inconsistencies between the inline fullscreen options and edit dialog fullscreen options in the rich text editor on latest master and when testing `AEM 6.3.3.3`. For example if all "features" and "formatting" options are enabled via the content policy:

<img width="488" alt="Screenshot 2019-07-16 at 20 19 31" src="https://user-images.githubusercontent.com/25616660/61319250-2295f080-a807-11e9-9e54-9c1d94b233f5.png">

<img width="491" alt="Screenshot 2019-07-16 at 20 23 27" src="https://user-images.githubusercontent.com/25616660/61319503-a059fc00-a807-11e9-96d2-48c6f62354b3.png">

Result -> Inline Full Screen

<img width="1218" alt="Screenshot 2019-07-16 at 20 18 11" src="https://user-images.githubusercontent.com/25616660/61319278-32153980-a807-11e9-8bc5-9f3a4204f2af.png">

Result -> Fullscreen Edit Dialog

<img width="1215" alt="Screenshot 2019-07-16 at 20 17 40" src="https://user-images.githubusercontent.com/25616660/61319291-39d4de00-a807-11e9-9a58-37bcbdd0d15e.png">

**Comment by gabrielwalt** [comment]
This should be fixed by CQ-4269576.

**Comment by jckautzmann** [comment]
This was fixed with #841. The fix will be available in the next release of the Core Components.

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
