### ISSUE TITLE
[Teaser] The linked image is not clickable

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#1590]
When a link is defined for a teaser component, the image is not clickable, only the text. 
See e.g. the linked teaser of the Teaser page from the component library [0].

Core Components version: 2.16.4

[0]  https://aemcomponents.dev/content/core-components-examples/library/page-authoring/teaser.html

**Comment by jckautzmann** [comment]
@adobe export issue to Jira project SITES as Issue

**Comment by jckautzmann** [comment]
@adobe export issue to Jira project SITES as Bug

**Comment by jckautzmann** [comment]
@adobe export issue to Jira project SITES as Story

**Comment by gabrielwalt** [comment]
This might get fixed by #1712, especially if we remove the capability to have the link on the image.
