### ISSUE TITLE
[bug] containerUtils window.location.reload() overbroad

### ISSUE THREAD

**Issue by tjameswhite** [adobe/aem-core-wcm-components#1597]
## Bug Report

**Current Behavior**
In Core 2.16 a change was made for deep linking tabs and panels. 
containerUtils.js line 77 : `window.location.reload()` is overbroad and is affecting any hash on the site, not just Core Tab or Accordion 

https://github.com/adobe/aem-core-wcm-components/pull/1451/files#diff-0eac5f3605c01e5a29d66f89ee7a14b32e21bc04dc5971bfa92345eeb97d8a58

**Expected behavior/code**
Javascript to control Core Components should not affect anything outside those core components.
Any hash usage outside of Core components should not be affected by Core components. 

**Environment**
- AEM version and patch level (e.g. AEM 6.3 SP1 CFP2): 6.5.8
- Core Components version (e.g. 2.0.4): 2.16

**Additional context / Screenshots**
PR change was introduced: https://github.com/adobe/aem-core-wcm-components/pull/1451

**Comment by msagolj** [comment]
This issue was fixed with #1617 and should be in 2.17.0, can you please check.
