### ISSUE TITLE
[Button] Allow to open links in new tabs

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-core-wcm-components#1600]
As an author, I want to configure whether links do open in a new tab for the visitors.

Requirements:
- Authors need a checkbox to select whether the link is to be opened in a new tab or not.
- When selected, the generated link element gets the attribute target="_blank".
- By default, the checkbox would be unchecked.
- This behavior doesn't need to be configurable via the policy.

SITES-925

**Comment by dasj001** [comment]
Is there an ETA on this feature?

**Comment by bpauli** [comment]
This feature was added to the v2 button component. The v2 button component is still in progress but a "tech preview" is available since 2.17.0
