### ISSUE TITLE
Provide width and height properties for images to reduce layout shift

### ISSUE THREAD

**Issue by Tylopilus** [adobe/aem-core-wcm-components#1602]
## Feature Request

As of now the image does not provide any width and height attributes resulting in layout-shift if no further style has been applied. Users should be presented with as little content shift as possible. This is also one of the core web vitals metrics from google for a good web experience.

Since all images are run through the adaptiveImageServlet the width and the height should be known and should be slotted in to the image-tag itself. This will reserve the space for the image.
```
<img src="${img.src}" width="${img.width}" height="${img.height}" alt.../> 
```
This is supported by all browsers.

No alternatives until page has been rerendered with additional css-styles applied

**Documentation**
Further information can be gathered here:
https://web.dev/optimize-cls/

**Comment by vladbailescu** [comment]
@Tylopilus , this is already being considered for the future version of the Image component, see https://github.com/adobe/aem-core-wcm-components/pull/1594/files#diff-e03189360e4e500e308dbd22f8eb6e2df0d5a5c64c24e678158448f6d0db3829L40

**Comment by Tylopilus** [comment]
Fantastic. How far in are we with v3?

**Comment by gabrielwalt** [comment]
We're working on merging a PR for image v3 very soon, which will do that for images that are DAM assets:
https://github.com/adobe/aem-core-wcm-components/pull/1686

ETA for v3 is still to be defined, but we're working on it.
