### ISSUE TITLE
Remove the e2e Test Module

### ISSUE THREAD

**Issue by msagolj** [adobe/aem-core-wcm-components#1609]
Now that all Hobbes tests have been converted to Selenium, we no longer need the e2e test module, which was meant as starting point to write your own UI test without Hobbes. But now with a full set of test based on Selenium that can now serve as the starting point.

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-core-wcm-components/commit/b837e515b769930ba3df3f8f0fc6b0db71694cde
