### ISSUE TITLE
Using AEM Core component 2.16.4 causes cloud deploy failed (CQBP-84)

### ISSUE THREAD

**Issue by riosmart** [adobe/aem-core-wcm-components#1627]
## Bug Report

 

**Current Behavior**
 We are using AEM Core component 2.16.4 in our project (Specified in maven project). The cloud build is failed recently when it running the code scan (Critical level bug).

Error Message: 
 'The product interface com.day.cq.dam.api.Rendition annotated with @ProviderType should not be implemented by custom code. Detected in com.adobe.cq.wcm.core.components.internal.servlets.EnhancedRendition contained in /apps/mrm-cloud-platform/install/core.wcm.components.core-2.16.4.jar.

**Expected behavior/code**
 Removal of @providertype in the enhancedrendition class to alleviate the error and allow the build to deploy

**Environment**
 - <https://experience.adobe.com/#/@mrmworldwide/cloud-manager/pipelineexecution.html/program/14111/pipeline/664011/execution/481336>
##  

 - Core Components version 2.16.4

**Possible Solution**
 Removal of the @providertype annotation

**Additional context / Screenshots**
 Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jckautzmann** [comment]
(SITES-1238)

**Comment by bpauli** [comment]
@riosmart The Core Component project is already part of the AEMaaCS (located in /libs/core/wcm) and doesn't have to be embedded in the project as dependency. Therefore it should also not be validated by CM Pipeline

**Comment by maciusio** [comment]
AEM as a Cloud Service is not the only option out there. There are AMS deployments that are also using the Cloud Manager.
What's the recommendation now that the core components should never be deployed as submodule/embed and deployed manually?

This is still a valid bug, please reopen it.

**Comment by Jack-Jin-TD** [comment]
I can confirm this is happening for my account as well.
