### ISSUE TITLE
[Image] inherit image from page component

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#1629]
As an author, when adding an empty image component to the page, I want it to reuse the page image, so that I don't need to set it again, unless I want something else.

**Comment by jckautzmann** [comment]
(SITES-212)

**Comment by jckautzmann** [comment]
Available on `master` branch as tech preview.

**Comment by irishgator** [comment]
I know this is a tech preview currently but is there a reason the fallback isn't the existing thumbnail or an option to flag it to use thumbnail? Would seem like that would provide the most compatibility with existing installations and it should be a simple conditional. Maybe in some of the latest commits that behavior is in place but I couldn't tell for sure. Happy to submit a feature request.
