### ISSUE TITLE
Embeddable component - Not able to use Image upload and Richtext

### ISSUE THREAD

**Issue by nishneo** [adobe/aem-core-wcm-components#1632]
## Bug Report

**Current Behavior**
Trying to extend the Embed component by adding newly embeddable. When creating new embeddable we are adding Richtext (cq/gui/components/authoring/dialog/richtext) or Image Upload (cq/gui/components/authoring/dialog/fileupload). But dialog for Embeddable doesn't function properly. Switching between radio buttons (URL, Embeddable, HTML) shows wrong fields in Tabs.

**Expected behavior/code**
The expectation was Richtext and Image Upload would work. 

**Environment**
- AEM Cloud
- Core Components version - 2.16.4
- JRE version (e.g. `Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)`)

**Comment by jckautzmann** [comment]
@adobe export issue to Jira project SITES as Story

**Comment by jckautzmann** [comment]
(SITES-1232)
