### ISSUE TITLE
Form Container dialog issues

### ISSUE THREAD

**Issue by anjalibiddanda** [adobe/aem-core-wcm-components#1634]
## Bug Report

**Current Behavior**
The form container dialog duplicates the email in the 'To' multifield everytime you OK the dialog. Based on the ActionType chosen from dropdown, these fields are loaded dynamically. Looks like an issue with the dialog JS.

The form container component's dialog does not do validations of emails you enter in the 'From' input field to notify the author on dialog OK. Author may incorrectly enter "Testing" in the 'from' input field of dialog. And on form submission, this will fail with an 500 error, because of an incorrect email. Some basic validation here would be helpful.

**Expected behavior/code**
Multifield should not duplicate the 'To' email everytime the dialog is OK'ed.
Some basic email validation for the 'From' and 'To' field.

**Environment**
- AEM 6.5.8
- Core Components version 2.7.0
- Java(TM) SE Runtime Environment (build 1.8.0_291-b10)

**Additional context / Screenshots**
![image](https://user-images.githubusercontent.com/43427033/122193497-e1695800-ced7-11eb-8887-51c4ea435d64.png)

**Comment by comanV** [comment]
@adobe export issue to Jira project SITES as Story
