### ISSUE TITLE
[Image][JS] Don't update image `src` with same value

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#1662]
## Bug Report

**Current Behavior**
Due to recent changes in the JS for the Image component, when lazy-loading images are used the image is re-fetched on every scroll event. 

This is caused because the `src` attribute is set on ever scroll event even if the attribute is the same as the current value. 
This causes the browser to act as if the `src` attribute for the image has changed (even though it has not).

The problem occurs due to repeated calls to line 246:
https://github.com/adobe/aem-core-wcm-components/blob/e3b725d62509499778ccb21c21ba60f115abd0b6/content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/clientlibs/site/js/image.js#L233-L251

To observe this behaviour:
1. Set a policy allowing lazy-loading for images. 
2. Add a bunch of images to the page.
3. Scroll up and down the page and observe the "Network" tab in dev tools. 

**Expected behavior/code**
If the image `src` attribute will not be changed, then the `setAttribute('src', url)` function should not be called.

**Environment**
- AEM version: 6.5.9.0
- Core Components version: 2.17.0
- JRE version: 11

**Possible Solution**
If `url === imgSrcAttribute` then the effect of lines 236-251 is irrelevant because it would only ever end up setting the `src` attribute to the current value. This block could be wrapped in a simple if statement to be skipped if there will be no effect.

**Comment by msagolj** [comment]
@ky940819 The constant reloading only happens because in dev tools usually cache is disabled. With enabled cache, the default case when normal browsing, there is no constant reloading on scroll events in the network tab.

But your right it still unnecessary to run the code on every scroll event if there is no change. Thank you for the PR.
