### ISSUE TITLE
[Search] How to hide specific page from search results?

### ISSUE THREAD

**Issue by GonzaloCalandria** [adobe/aem-core-wcm-components#1667]
Is there a way to hide specific pages from search results without having to deactivate the page?

**Comment by avitripathy01** [comment]
@GonzaloCalandria What could be the use case to hide a page in search result on publish ?

**Comment by GonzaloCalandria** [comment]
@avitripathy01 first of all, thank you for your answer! My use case is that we have some pages that work as a reference to display a card component, and those pages have dispatcher redirects when the user access to them. So we don't want to appear under search results. (One thing to mention is that this project is a SPA project.

Since I was a little bit hurry.. I had to copy most of search feature content to my project and modify SearchResultsServlet's predicates to include hideInNav property.

```JSON
Map<String, String> predicatesMap = new HashMap<>();
        predicatesMap.put(FulltextPredicateEvaluator.FULLTEXT, fulltext);
        predicatesMap.put(PathPredicateEvaluator.PATH, searchComponent.getSearchRootPagePath());
        predicatesMap.put(TypePredicateEvaluator.TYPE, NameConstants.NT_PAGE);
        predicatesMap.put("group.p.or", "true");
        predicatesMap.put("group.1_property", "jcr:content/hideInNav");
        predicatesMap.put("group.1_property.operation", "like");
        predicatesMap.put("group.1_property.value", "false");
        predicatesMap.put("group.2_property", "jcr:content/hideInNav");
        predicatesMap.put("group.2_property.operation", "not");
```

**Comment by avitripathy01** [comment]
hi @GonzaloCalandria, thank you for the inputs.I understand the context now. 
An alternative to modifying the default SearchResult servlet could be to add a filter and route the request to project specific search servlet. wdyt ?

**Comment by josephh** [comment]
@avitripathy01, @GonzaloCalandria 
We would like to exclude pages from the search results that have a `noindex` page property set. 
Is that possible with the current Quick Search core component, or is that an upcoming feature/ enhancement?

**Comment by avitripathy01** [comment]
@josephh The current search result functionality doesn't support the functionality that you have stated. I am not sure if there are any feature enhancements to that. I had suggested an alternate solution to intercept the search result request with a filter and redirect it to project specific Search Servlet that drives the custom functionality.

**Comment by gabrielwalt** [comment]
This is not supported for the time being.
Before adding such features to the quick search component, we would probably rather start with providing a search result component.
The request to hide specific pages from the results is too far out for now, closing the issue.
