### ISSUE TITLE
[Accessibility][Quick Search] No announcement that search results have changed

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1673]
**Steps to Reproduce**
1. With NVDA operating, navigate to the "Search Components" input.
2. Enter "Bread". Visually note change in page contents and observe whether screen reader user is notified of this change. 

**Current Behavior**
No notification is provided to screen reader users that search results on the page have changed in response to their text input in the search field.

**Expected behavior/code**
Ensure screen reader users are notified of the change that occurs visually on the page. This can be accomplished with an ARIA live region.

**Environment**
Chrome 91, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Screen reader users

**WCAG SC**
4.1.3 Status Messages

**Possible Solution**
Consider adding a visible status message near the search field identifying the change in results, such as the number of items in the list. This message may additionally help users with low vision and users with cognitive disabilities to identify the change in results, and if an `aria-live` attribute (with value set to `polite`) or a role of `status` is added to the container for the message, when text is injected into the container an announcement will be triggered for screen reader users.

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES
