### ISSUE TITLE
[Accessibility][Quick Search][Advisory] Search triggered on input

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1674]
**Steps to Reproduce**
1. Enter a search term in the search input (e.g. "Nav").
2. Observe search being executed as text is entered.

**Current Behavior**
Search is executed as the user types a value into the search input field, rather than after they expressly execute a search (e.g. with a "Search" button). Many users may be unaware that the search results have changed, particularly screen reader users, users with low vision who may be zoomed in to the search input and not see the visual cue of changing search results, and users with cognitive impairments who may not expect search to be executed as they type and who may need additional cues to identify the changed result set. 

**Expected behavior/code**
Ensure the context of a page is not changed by changing the setting of a user interface control (e.g. by entering text in a text input). 

While the change in the result set is not strictly a change in context, it may be disorienting for many users. 

**Environment**
Chrome 91, Windows 10
AEM Core Components v. 2.17  

**Affected Users**
Screen reader users, users with low vision, users with cogitive disbilities

**WCAG SC**
3.2.2 On Input

**Possible Solution**
If possible, provide a submit button to execute the search, or inform users in some way that the results will be filtered as they type.

**Additional context**
https://www.w3.org/WAI/WCAG21/Techniques/general/G80

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES

**Comment by gabrielwalt** [comment]
This is functioning as an auto-complete and shouldn't typically be an accessibility issue, as long as the issue #1673 gets correctly fixed.
