### ISSUE TITLE
[Accessibility][CSS][Teaser] Keyboard focus not visually indicated on linked image

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1679]
**Steps to Reproduce**
1. Use TAB to navigate to the linked image.

**Current Behavior**
When focused, the linked image has no visual indication of focus.

**Expected behavior/code**
When focused, the linked image should provide sighted users a visual indication that it has focus.

Interactive elements' visual focus indication should meet a minimum contrast ratio of 3:1 with the background.

**Environment**
Chrome 91, Windows 10
AEM Core Components v. 2.17  

**Affected Users**
Sighted keyboard users

**WCAG SC**
2.4.7 Focus Visible

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES

**Comment by gabrielwalt** [comment]
This can be fixed with the correct policy configuration on the teaser component: "Don't link the image".
However, in the new teaser version, we should make this the default, and not allow any option to change this in the policy.
