### ISSUE TITLE
Image | Authoring dialog | component is allowing author to save edit changes without configuring Alternative text

### ISSUE THREAD

**Issue by hcl36741** [adobe/aem-core-wcm-components#1683]
**Current Behavior**
Steps :
We are using Proxy component of image v3 version(/apps/core/wcm/components/image/v3/image).
Steps to reproduce :
1. In design dialog of image component unchecked "Get alternative text from DAM" and "Image is decorative" checkboxes.
2. Add proxy image component on a page.
3. Drag and drop the image in the first tab and save.
4. Image Component is allowing author to save edit changes without configuring Alternative text* , but same thing works fine if user navigates to metadata tab and then try to click on save.

**Expected behavior/code**
System should highlight metadata tab which is having mandatory fields i,e Alternative text*

**Environment**
- AEM as a Cloud Service (2021.6.5561.20210622T143945Z-210600)
- Core Components version (e.g. 2.17.2)
- JRE version - Java 11

**Comment by jckautzmann** [comment]
Thx for reporting this issue. It will be fixed with:
https://github.com/adobe/aem-core-wcm-components/pull/1664
