### ISSUE TITLE
Provide bundled scripts

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1706]
## Feature Request

AEMaaCS ships with bundled scripts (including the ones from Core WCM Components) while AEMonPrem requires manual installation of the Core WCM Components. That release only ships with regular resource scripts instead of bundled scripts though.
Both for performance reasons and also to make it easier to write bundled extended components (https://issues.apache.org/jira/browse/SLING-10689) the Core Components release should (at least optionally) provide the precompiled HTL scripts in a bundle

Bundled scripts are described at https://github.com/apache/sling-org-apache-sling-servlets-resolver#how. The necessary metadata can be generated with the help of https://sling.apache.org/components/scriptingbundle-maven-plugin/index.html.

**Comment by kwin** [comment]
@raducotescu Can you come up with a PR to generate the bundle containing precompiled scripts (at least during release)?

**Comment by raducotescu** [comment]
I'm not sure if this is something we need to implement, as the Core Components are already precompiled in AEMaaCS, like all the scripts coming from `/libs`. When using the Core Components on-prem or on AMS, there's no need to precompile them, as those deployments do not officially support precompiled bundled scripts.

**Comment by kwin** [comment]
Why are precompiled bundles not supported on AEM 6.5.x? There is nothing mentioned in https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/archetype/precompiled-bundled-scripts.html related to that and IMHO they should be theoretically supported since servlets resolver 2.7.0 (https://sling.apache.org/documentation/bundles/scripting.html#bundled-scripts) while AEM 6.5.10 ships with 2.7.10.

Nevertheless there seem to be some bugs in precompiled bundles on AEM 6.5.10 currently:
1. Order seems to be inverted (resource scripts ranked higher than bundled scripts)
2. Output flushing does not work (a simple "Hello World" does not end up in the response body)

@raducotescu Can you clarify the support for precompiled bundles in 6.5.x?

**Comment by kwin** [comment]
@raducotescu 6.5.21 shipped with updated scripting bundles (https://experienceleague.adobe.com/docs/experience-manager-65/assets/65210-bundles.txt?lang=en). Is it safe to use precompiled bundled scripts with 6.5.21+?

**Comment by raducotescu** [comment]
I haven't tested whether the precompiled bundled scripts work ok on 6.5.21.
