### ISSUE TITLE
[Accessibility][Embed] YouTube embed does not resize proportionally at 320px wide

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1725]
**Steps to Reproduce**
1. Open page in Google Chrome.
2. View YouTube iFrame in developer tools panel to see the iframe width.
3. View the page at 320 CSS px wide and 256px high.
4. Play the video; hover over the video with a mouse or tab to the video controls and visually observe the location of the video controls.

**Current Behavior**
At 320 CSS pixels width, the video controls fall well below the video, making it difficult to interact with the controls. (With a width of 320px and a viewport height of 256px, as required by WCAG 1.4.10 Reflow, if the video is fully in view the controls may be off screen.) The YouTube iFrame has a height="390" attribute, which defines the height with absolute units. 

**Expected behavior/code**
Video and controls resize appropriately and proportionally at 320 px width.

**Environment**
Chrome 91, Windows 10
AEM Core Components v. 2.17  

**Affected Users**
Users with low vision.

**WCAG SC**
1.4.10 Reflow

**Code snippet**
```
<iframe data-cmp-data-layer="{&quot;youtube-9b77a6082e&quot;:{&quot;@type&quot;:&quot;core/wcm/components/embed/v1/embed/embeddable/youtube&quot;,&quot;embeddableProperties&quot;:{&quot;youtubeVideoId&quot;:&quot;f7hbWvHKns0&quot;}}}" width="100%" height="390" src="https://www.youtube.com/embed/f7hbWvHKns0?origin=https%3A%2F%2Faemcomponents.dev&amp;hl=en" frameborder="0" allowfullscreen="" allow="autoplay; fullscreen" aria-label="YouTube Video"></iframe>
```

**Screenshot**
![At 320px wide and 256px high, video controls are cut off at the bottom of the screen.](https://user-images.githubusercontent.com/86849351/128233694-c31a12fc-dcee-4834-bce5-a0cd77276254.png)

**Possible Solution**
Use percentage units to define height of the iFrame (or another responsive embed technique) to ensure no loss of functionality or content upon resize.

**Additional context**
Responsive Embed CSS example: https://embedresponsively.com/

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by gabrielwalt** [comment]
Maybe this could be an option: https://avexdesigns.com/blog/responsive-youtube-embed
