### ISSUE TITLE
[Accessibility][Social Sharing] Pinterest link is announced by NVDA as "zero save"

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1726]
**Steps to Reproduce**
1. Enable NVDA screen reader.
2. Open page in Google Chrome.
3. Move focus to Pinterest link.

**Current Behavior**
The Pinterest sharing link has an accessible name of "zero save"; no indication is provided to screen reader users that the link will save the resource to Pinterest.

**Expected behavior/code**
The purpose of the link is clear (e.g. "Save to Pinterest, zero saves")

**Environment**
Chrome 91, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Screen reader users

**WCAG SC**
2.4.4 Link Purpose

**Possible Solution**
Ensure that the accessible name includes the word "Pinterest" as well as any on-screen text. If it is not possible to change the text of this 3rd party link, consider whether text (either visible or visually-hidden) can be added before the link so screen reader users who explore the surrounding content can find some context for the link.

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by gabrielwalt** [comment]
The Pinterest embed code is not generated by the Core Components, but by Pinterest.
We'll anyway be dropping the Pinterest page features in the new version: see #1918.
