### ISSUE TITLE
[Accessibility][Content Fragment][Sample Content] Inappropriate heading structure

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1729]
**Steps to Reproduce**
1. With NVDA running, open page in Chrome.
2. Read through sample content for the Standard example and note heading structure.
and/or
1. View heading markup in developer tools panel.

**Current Behavior**
In the Standard example, within an article, a level 3 heading ("Simple Fragment") which appears to label the article content precedes a level 2 heading ("Lorem Ipsum").

**Expected behavior/code**
Headings follow a logical order and represent the structure of the content. The "Simple Fragment" heading is marked up as an `<h2>`, followed by the "Lorem Ipsum" heading marked up as `<h3>` (or, if "Simple Fragment" is an `<h3>`, "Lorem Ipsum" is an `<h4>`).

**Environment**
Chrome 91, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Screen reader users

**WCAG SC**
Advisory (1.3.1 Info and Relationships)

**Code snippet**
```
<h3 class="cmp-contentfragment__title">Simple Fragment</h3>
...
<h2>Lorem Ipsum</h2>
```

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES
