### ISSUE TITLE
[Accessibility][PDF Viewer] "Enable accessibility for screen readers" control is not adequately described/labelled

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1735]
**Steps to Reproduce**
1. Enable NVDA screen reader.
2. Open page in Google Chrome.
3. Use TAB to navigate to the "Enable accessibility for screen readers" control. (The control is visually hidden, and follows the "Undock" icon button.)

**Current Behavior**
It is unclear what features will be enabled by the "Enable accessibility for screen readers" control or why they need to be enabled.

**Expected behavior/code**
Accessible names for controls provide adequate information about the control. 

**Environment**
Chrome 91, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Users of assistive techology

**WCAG SC**
2.4.6 Headings and Labels

**Possible Solution**
Consider whether accessibility for screen readers can be enabled by default, rather than requiring users to enable it. 

If it is not possible to enable this setting by default, consider providing additional context to explain how this control will affect the user experience. This context can be associated with the control with an aria-describedby attribute referencing the ID of an element with text providing more information about the functionality.

**Comment by glasert** [comment]
This issue won't be fixed as the acrobat team is working on a modern viewer which addresses accessibility and will replace the current viewer in 2022. Therefore we defer and close this issue
