### ISSUE TITLE
[Accessibility][PDF Viewer] Activating the Show/Hide Dock button causes focus to change

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1736]
**Steps to Reproduce**
1. Open page in Google Chrome.
2. Use TAB to navigate to the show/hide dock button.
3. Activate the show/hide dock button.
4. Notice the focus change.

**Current Behavior**
When activating the show/hide dock button, the focus falls to the body element of the page and, when a user presses the TAB key, goes to the first focusable element of the dock.

**Expected behavior/code**
When the show/hide button is activated, focus should remain on the button and the control should remain visible until the user navigates away from the control.

**Environment**
Chrome 91, Windows 10
AEM Core Components v. 2.17  

**Affected Users**
Keyboard-only and assistive technology users

**WCAG SC**
2.1.1 Keyboard

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by glasert** [comment]
This issue won't be fixed as the acrobat team is working on a modern viewer which addresses accessibility and will replace the current viewer in 2022. Therefore we defer and close this issue
