### ISSUE TITLE
[Accessibility][PDF Viewer] When an activated dialog is closed, focus does not return to the triggering control

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1739]
**Steps to Reproduce**
1. Open page in Google Chrome.
2. Using the keyboard, activate the menu (3 dots).
3. Navigate to and activate "Legal Notices".
4. In the active dialog, activate "Close".

**Current Behavior**
When a user deactivates the modal dialog for "Legal Notices," the focus is returned to the top of the PDF viewer rather than the triggering element.

**Expected behavior/code**
When a user closes a dialog, focus should return to the triggering element- in this case, the "Legal Notices" link. 
**Environment**
Chrome 91, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Keyboard users

**WCAG SC**
2.1.1 Keyboard

**Possible Solution**
Focus can be managed and returned appropriately by utilizing the document.activeElement property of the DOM API.

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by glasert** [comment]
This issue won't be fixed as the acrobat team is working on a modern viewer which addresses accessibility and will replace the current viewer in 2022. Therefore we defer and close this issue
