### ISSUE TITLE
[Accessibility][PDF Viewer] The clear search ("X") does not provide sufficient indication of focus visually

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1740]
**Steps to Reproduce**
1. Open page in Google Chrome.
2. Activate search button to expand search controls.
3. Enter text into the search field.
4. Navigate to the clear search button ("X") using TAB on the keyboard.

**Current Behavior**
When focused, the clear search "X" font-weight increases, but the difference from the focused state to blurred state is almost imperceptible visually.

**Expected behavior/code**
When focused, use clear visual indicators. The best solution in this case would be an outline around the clear search "X" that exceeds a 3:1 contrast ratio with the white background.

**Environment**
Chrome 91, Windows 10
AEM Core Components v. 2.17  

**Affected Users**
Users with limited vision, keyboard users

**WCAG SC**
2.4.7 Focus Visible

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by glasert** [comment]
This issue won't be fixed as the acrobat team is working on a modern viewer which addresses accessibility and will replace the current viewer in 2022. Therefore we defer and close this issue
