### ISSUE TITLE
[Accessibility][PDF Viewer] In the In-line example of the PDF Viewer, the menu (3 dots) button is not keyboard operable

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1741]
**Steps to Reproduce**
1. Open page in Google Chrome.
2. Press the TAB key to navigate to the menu (3 dots) button in the toolbar of the In-line example.
3. Attempt to activate the menu with the enter or space key.

**Current Behavior**
When a user attempts to activate the menu, nothing happens.

Note: with NVDA operating, the button can be triggered and focus is set to the first option in the associated menu ("Legal Notices"), but the control then disappears visually and can no longer be interacted with. Without NVDA operating, when the button is triggered with the Enter or Space bar, the associated menu does not become visible.

**Expected behavior/code**
All functionality is available to users regardless of input modality. Buttons can be activated using both Enter and Space bar keys.

**Environment**
Chrome 91, Windows 10
AEM Core Components v. 2.17  

**Affected Users**
Keyboard users

**WCAG SC**
2.1.1 Keyboard

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by glasert** [comment]
This issue won't be fixed as the acrobat team is working on a modern viewer which addresses accessibility and will replace the current viewer in 2022. Therefore we defer and close this issue
