### ISSUE TITLE
[Accessibility][PDF Viewer] Focus is not managed correctly when PDF Search controls are expanded

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1744]
**Steps to Reproduce**
1. Open page in Google Chrome.
2. TAB to search button.
3. Activate search button.
4. TAB out of activated search controls; note that focus moves from Search input to Cancel button to Properties tab outside of the component, skipping the control dock (pagination etc.)
5. Use SHIFT + TAB to move focus back into search controls. Note that continuing to tab backwards past the search controls moves focus to the control dock. 

**Current Behavior**
Search controls remain activated when a user uses TAB to navigate away from the search controls. These controls visually precede the PDF in the reading order, but follow the PDF and the control dock in the focus order. Once search controls are expanded, neither the search controls nor the control dock are in a logical position in the focus order.

**Expected behavior/code**
Focus order of all interactive elements is logical, generally following the reading order. 

**Environment**
Chrome 91, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Keyboard users

**WCAG SC**
2.1.1 Keyboard

**Possible Solution**
If possible, place the expanded search controls above the PDF in the DOM. If this is not possible, ensure focus is managed correctly so when a user presses TAB to move out of the search input and Cancel button control, their focus will move to the top of the PDF document as expected.

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by glasert** [comment]
This issue won't be fixed as the acrobat team is working on a modern viewer which addresses accessibility and will replace the current viewer in 2022. Therefore we defer and close this issue
