### ISSUE TITLE
[Accessibility][PDF Viewer] "Enable accessibility for screen readers" control is not in a logical place in the tab order

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1746]
**Steps to Reproduce**
1. Enable NVDA screen reader.
2. Open page in Google Chrome.
3. Use TAB to navigate to the "Enable accessibility for screen readers" control. (The control is visually hidden, and follows the "Undock" icon button.)

**Current Behavior**
The "Enable accessibility for screen readers" control follows the content that it affects in the tab order. As a result, users who enable the control must explore backwards through the tab order to locate the content that has been enabled, and may be unaware that their action has had an effect on the content.

**Expected behavior/code**
The "Enable accessibility for screen readers" control is in a logical place in the tab order, preceding the content that it enables.

**Environment**
Chrome 91, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Screen reader users

**WCAG SC**
2.4.3 Focus Order

**Possible Solution**
Consider whether accessibility for screen readers can be enabled by default, rather than requiring users to enable it. 

If it is not possible to enable this setting by default, ensure this control precedes the content that it affects, rather than following it.

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by glasert** [comment]
This issue won't be fixed as the acrobat team is working on a modern viewer which addresses accessibility and will replace the current viewer in 2022. Therefore we defer and close this issue
