### ISSUE TITLE
[Accessibility][Core Form][Sample Content] Placeholders are identical to the programmatic form field labels

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1771]
**Steps to Reproduce**
1. With NVDA running, navigate to Email input. 
2. Observe the announcement "Email edit email".

**Current Behavior**
Placeholder values are identical to the form field labels, resulting in duplicate announcements for screen reader users. 

**Expected behavior/code**
A placeholder is meant to be used as a brief hint of the expected information. For example, an email input field might use a placeholder of "e.g. John@Website.com". 

**Environment**
Chrome 91, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Screen reader users

**WCAG SC**
Advisory only (2.4.6 Headings and Labels)

**Possible Solution**
Consider removing the placeholder attribute.

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES
