### ISSUE TITLE
Automate npm package version sync with pom version

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#178]
We originally used https://www.npmjs.com/package/sync-pom-version to sync the npm package version with the pom version but found it to break the build on windows machines due to the way it spawns npm.

So, it was removed in https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/commit/4cda807a44fe573eaddf9d47b893931e7b8e2627.

Task is to fix (contribute to the module?) and reintroduce automation of the package version sync so that we don't have to manage it manually when doing a release.

(CQ-4244061)

**Comment by vladbailescu** [comment]
Fixed in #1303
