### ISSUE TITLE
PGP signature verification fails

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1780]
The signatures e.g. in https://repo1.maven.org/maven2/com/adobe/cq/core.wcm.components.all/2.17.8/core.wcm.components.all-2.17.8.pom.asc use the PGP public key `2EE7899D`. I don't find the public key though on any public keyserver.
Sonatype requires every signature on Maven central using a public key which is available on a public keyserver (https://central.sonatype.org/publish/requirements/gpg/#distributing-your-public-key).

Verifying the signature with

```gpg --keyserver-options auto-key-retrieve --verify ./core.wcm.components.all-2.17.8.pom.asc ./core.wcm.components.all-2.17.8.pom``` fails against keyserver keys.openpgp.org because the public key 1F9CF1652EE7899D can't be retrieved

Also please make sure to publish the public key used for signing releases in a safe place (e.g. the readme) so that one can be certain that this is really the official release....

**Comment by gabrielwalt** [comment]
It didn't seem that this issues has been recurring with the latest releases, therefore closing this.
