### ISSUE TITLE
Property "java.version" collides with system property of the same name

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1781]
As custom Maven properties and Java system properties share the same namespace (https://books.sonatype.com/mvnref-book/reference/resource-filtering-sect-properties.html and https://maven.apache.org/pom.html#properties), the property value set in https://github.com/adobe/aem-core-wcm-components/blob/6a294b0483c711a0283474f962a4643234e47c6e/parent/pom.xml#L64 is never effective, as it being overwritten by the same named system property (https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html).  You have to rename that custom Maven property to not collide with the system property.

**Comment by bpauli** [comment]
I think the `<java.version>` property is never used in the maven build. Maybe we can just remove it?
