### ISSUE TITLE
[Accessibility][Accordion] Configurable heading levels

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1784]
**Steps to Reproduce**
1. Enable NVDA screen reader.
2. Open page in Google Chrome.
3. Use TAB and SHIFT + TAB to navigate to the nested accordions component.
4. Not the accordion trigger heading level.
5. Activate the accordion.
6. Navigate to a nested accordion trigger and note the heading level.

**Current Behavior**
Both parent accordion triggers and the nested accordion triggers use a heading level 3 (`<h3>` tag). The content structure is not correctly conveyed to screen reader users.

**Expected behavior/code**
Authors should use proper markup to convey a hierarchal heading structure based on their importance. A "child" of an `h3` heading would be an `h4` heading.

**Environment**
Chrome 92, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Screen reader users

**WCAG SC**
1.3.1 Info and Relationships

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by glasert** [comment]
@adobe export issue to Jira project SITES as Story

**Comment by bpauli** [comment]
The heading level can already configured for each accordion. I case of a nested accordion the child accordion can have a higher heading level than the parent accordion. In #1937 I changed the existing example of a nested accordion in the component library.

The configuration can be done in the Edit Dialog of the Accordion (Tab -> Properties)
![image](https://user-images.githubusercontent.com/689884/149962272-b05d5894-0689-4bf3-8dbe-90b65ede5c46.png)
