### ISSUE TITLE
[Accessibility] [Commerce Navigation] Focus does not move to or return from menu dialog when opened and closed, respectively.

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1788]
**Steps to Reproduce**
1. Open page in Google Chrome.
2. Use TAB or TAB + SHIFT to navigate to the menu dialog trigger.
3. Activate menu dialog.

**Current Behavior**
When the menu dialog button is activated, focus remains on the triggering menu button. When the dialog is closed, focus defaults to the body element. This can be disorienting for screen reader users, and requires extra keystrokes by keyboard-only users to navigate back to their intended location on the page.

**Expected behavior/code**
Ensure that focus moves into the dialog when activated. Typically, the logical element to move focus to is the first actionable element. In this case, the first actionable element is the close dialog button. 

Additionally, ensure that focus returns to the triggering element when the dialog is closed. Using Javascript, you can store the triggering element with `document.activeElement` and return focus by calling the `focus()` method.

**Environment**
Chrome 92, Windows 10
AEM Core Components v. 2.17  

**Affected Users**
Keyboard-only users, screen reader users

**WCAG SC**
2.1.1 Keyboard

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by mhaack** [comment]
This applies to V1 of the navigation component which is not used any more.
