### ISSUE TITLE
[Accessibility] [Commerce Navigation] The dialog close buttons, forward navigation (right arrow) and previous navigation (left arrow) buttons are not provided with an accessible label.

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1790]
**Steps to Reproduce**
1. Enable NVDA screen reader.
2. Open page in Google Chrome.
3. Use TAB or TAB + SHIFT to navigate to the menu dialog trigger.
4. Activate menu dialog.
5. Navigate to the close dialog button and/or the arrow navigation buttons within the dialog.

**Current Behavior**
The close button and navigation arrow buttons use `svg` icons to communicate their purpose without textual alternatives. It is unclear to screen reader users that some buttons within the navigation will expand a subnavigation or return to the previous navigation level, or how to close the navigation.

**Expected behavior/code**
Ensure that all operable controls have accessible names. In the case of the `button` elements, inline text will suffice. This text can be visually hidden with CSS, although authors should not use `display:none`.

Note that the svgs should also be hidden from assistive technology with `aria-hidden="true"` and `focusable="false"`, e.g.:
```
<button class="trigger__root clickable__root trigger__root--close" type="button">
    <span class="icon__root">
        <svg aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
        </svg>
    </span>
    <span class="visually-hidden">Close</span>
</button>
```

**Environment**
Chrome 92, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Screen reader users, users of speech input 

**WCAG SC**
4.1.2 Name, Role, Value

**Comment by richardhand** [comment]
@adobe export issue to Jira project SITES

**Comment by mhaack** [comment]
This applies to V1 of the navigation component which is not used any more.
