### ISSUE TITLE
com.adobe.cq.wcm.core.components.testing.mock.ContextPlugins.CORE_COMPONENTS is not exposed as part of version 2.17.10

### ISSUE THREAD

**Issue by hsinghal06** [adobe/aem-core-wcm-components#1813]
## Bug Report

**Current Behavior**
As per current version 2.17.10, `com.adobe.cq.wcm.core.components.testing.mock.ContextPlugins.CORE_COMPONENTS` not publicly accessible. 

**Expected behavior/code**
`com.adobe.cq.wcm.core.components.testing` should be accessible publicly
<img width="430" alt="Screenshot 2021-09-02 at 15 12 12" src="https://user-images.githubusercontent.com/47110052/131851102-b88dc9cf-7f8b-415c-90ff-fc7d6cf3575c.png">

**Environment**
- AEM Cloud SDK
- Core Components version (e.g. 2.17.10)

**Comment by stefanseifert** [comment]
not really - as outlined in https://github.com/adobe/aem-core-wcm-components/tree/master/testing/aem-mock-plugin this is only in unit tests, and you need to add the artifact `com.adobe.cq:core.wcm.components.testing.aem-mock-plugin` as test dependency to your project to use it.
i will prepare a PR to the adobe project archetype in the next days to make it clear and directly usable for new projects.

**Comment by hsinghal06** [comment]
@stefanseifert Thank you. It worked.

**Comment by stefanseifert** [comment]
for the sake of completeness, here it the PR for the archetype: https://github.com/adobe/aem-project-archetype/pull/799
