### ISSUE TITLE
Allow <link rel="preload" as="style"..> for links injected with HtmlPageItemsConfig

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#1823]
recommendation as per google for google lighthouse - https://web.dev/defer-non-critical-css/

SITES-2581

**Comment by vladbailescu** [comment]
To effectively use this, one should use `rel="preload stylesheet" as="style"`

**Comment by gabrielwalt** [comment]
This has been fixed by SITES-2581.
