### ISSUE TITLE
Cannot mock some models with mockito

### ISSUE THREAD

**Issue by GonzaloCalandria** [adobe/aem-core-wcm-components#1834]
**Current Behavior**
I'm not able to mock Teaser and Image (and maybe some other models that I haven't tested yet)

**Expected behavior/code**
A mocked version of the sling model.

**Environment**
- AEM as a Cloud Service SDK Version 2021.8.5755.20210819T230729Z-210700
- Core Components version 2.17.8
- JDK 11
- Mockito core version: 3.8.0 (I even tried with 2.22.0)

Hello everyone, I'm trying to perform some unit testings but I'm not able to mock some core component classes and I would like to know if there are some issues with mockito and core components.

What I'm trying to do is something easy such as
`Teaser teaser = Mockito.mock(Teaser.class)`
I even tried with Image with the same problem.

The error I'm getting is the following
```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface com.adobe.cq.wcm.core.components.models.Teaser.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.12+8-LTS-237
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 11.0.12+8-LTS-237
JVM info           : mixed mode
OS name            : Windows 10
OS version         : 10.0


Underlying exception : java.lang.IllegalStateException: Type not found: com.adobe.cq.wcm.core.components.internal.jackson.ComponentDataModelSerializer
```

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug
