### ISSUE TITLE
Teaser Core Component dialog issue

### ISSUE THREAD

**Issue by acc05618** [adobe/aem-core-wcm-components#1875]
1. drag and drop the Teaser core V1 component on to page.
2. edit the dialog for image configuration.
3. click on the Image Asset field label.
4. even though the "allowUpload" property is set to "false" it is allowing the upload of image from local system.
5. Even though file is selected from local system, that is not storing in dialog/crx.

## Bug Report

**Current Behavior**
When "allowUpload" is false then it should not allow the file upload from local file system but it is allowing.

**Expected behavior/code**
When "allowUpload" is false then it should not allow the file upload from local file system

**Environment**
AEM as a Cloud SDK
- Core Components version - 2.17.8
- JRE version - jre1.8.0_291

**Possible Solution**

**Comment by bpauli** [comment]
@acc05618 I was not able to reproduce the issue. Can you please provide some more details of your example configuration? It would be great if you can also provide a content package with your component configuration of the image and teaser component.

Please make sure that the ```allowUpload``` property is set for the image component at ```core/wcm/components/image/v2/image/cq:dialog/content/items/tabs/items/asset/items/columns/items/column/items/file``` as the image behaviour of the teaser is delegated to this component.

Thanks!
