### ISSUE TITLE
Components in XF does not have data Layer

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#1878]
When we author any core component on XF, it does not add data layer on it. If this XF need to be exported to Target and then injected into page through target then it does not contain the data layer on this component. 

Most likely this issue might be happening because data layer generation relies on ca flag which is available for pages and not for XF.

**Comment by bpauli** [comment]
@rajeevyadav2 To support DataLayer in the components which are placed in XFs you have to point to the ca config in one of the root folders of the XF page tree. You can find an example in the archetype project at [1]. HTH

[1]. https://github.com/adobe/aem-project-archetype/blob/develop/src/main/archetype/ui.content/src/main/content/jcr_root/content/experience-fragments/__appId__/.content.xml#L8
