### ISSUE TITLE
[Teaser] Teaser description inherited from page properties needs to be HTML-escaped

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#1882]
## Bug Report

**Steps to reproduce the problem**
* Create a teaser component linking to a page with a page description
* Enter a page description that contains some special chars which need to be escaped in HTML e.g. "<" and ">"
* Activate "Get description from linked page"

**Current Behavior**
The teaser used the description from page properties dialog without any escaping. Thus, special chars like "<" or ">" are interpreted as HTML code and will likely produce invalid markup or display the description incompletely.

**Expected behavior/code**
The teaser should display the page description exactly as entered in the plain text field in the page properties dialog.

**Environment**
- Core Components 2.17.12

**Possible Solution**
PR provided.

**Comment by bpauli** [comment]
@stefanseifert Thank you for reporting this issue and moreover for the provided PR!

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug

**Comment by bpauli** [comment]
merged in https://github.com/adobe/aem-core-wcm-components/commit/86eea6a485ad58633c0f777114fa23c241d89440
