### ISSUE TITLE
[DMAssetPostProcessor] Property 'imageServerUrl' is created on every resource where a property 'fileReference' is saved

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#1884]
## Bug Report

**Current Behavior**

The current Dynamic Media implementation contains a [DMAssetPostProcessor](https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/DMAssetPostProcessor.java) that is implemented as SlingPostProcessor.

It listenes to *every* POST that is done on the AEM instance, and kicks in if it finds a changed property `fileReference` in the updated properties *whatever component or action has triggered this POST*. if the referenced asset is a dynamic media asset, it stores an additional `imageServerUrl` property in each and every content resource where that asset is referenced.

The result is that any component, also custom components, that use a `fileReference` property in their edit dialog get this additional property written into the resource. This is completely unexpected and usually not what is desired.

In general, it is *very bad practice* to write instance/domain-specific stuff directly into the content. If this content is transferred to other environments all those properties might need to be updated because the target environment might be configured to a different DM catalog using a different host name. Additionally, this host name is already stored in each DM asset itself and can just be read from there (also on publish instances).

**Expected behavior/code**

Ideally, the implementation of the core component's DM support should be updated to get completely rid of the DMAssetPostProcessor, e.g. reading the DM host name from the references asset.

If this is not possible or desired, the DMAssetPostProcessor should be updated to handle only posts for a configurable list of resource types, by default only the resource types of the core components that have DM support enabled.

**Environment**
- Core Components 2.17.12

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug
