### ISSUE TITLE
[Accessibility][Image][Dialog] Alt text only required when current dialog tab has focus

### ISSUE THREAD

**Issue by sabberworm** [adobe/aem-core-wcm-components#1892]
## Bug Report

**Current Behavior**
The image component (both v2 and v3 versions), when configured to require an alt text, will let you save the dialog without providing this alt text when switching to a different tab before saving.

### V2 Steps

1. Open the image component dialog
2. Switch to “Metadata” tab
3. Uncheck “Image is decorative”
4. Uncheck “Get alternative text from DAM”
5. Set empty “Alternative Text *”
6. Hit save
7. Notice the field gets a red border and the dialog stays open
   ![image](https://user-images.githubusercontent.com/47652/142021696-f19b0cbb-f44c-4487-836a-e76e607004d9.png)
8. Change nothing and switch to the “Asset” tab
9. Hit save again
10. Notice the values are saved and the dialog closes

### V3 Steps

1. Open the image component dialog
2. Uncheck “Don’t provide an alternative text”
3. Uncheck “Inherit from description of asset”
4. Set empty “Alternative text for accessibility *”
5. Hit save
6. Notice the field gets a red border and the dialog stays open
   ![image](https://user-images.githubusercontent.com/47652/142022635-559b9b51-8537-4bd4-9201-dd0816d5e15b.png)
7. Change nothing and switch to the “Metadata” tab
8. Hit save again
9. Notice the values are saved and the dialog closes

**Expected behavior/code**
The dialog should refuse to save/close since there is an invalid field in the other tab.

**Environment**
- AEM 6.4.8-cfp-3.0
- Core Components 2.17.12
- Java HotSpot(TM) 64-Bit Server VM(build 25.291-b10, mixed mode)

**Additional context / Screenshots**
Notice that this is not a problem with other mandatory fields. To my knowledge it only affects the one for the alt text. Other fields retain their ability to mark the dialog as invalid even when in a background dialog tab.

**Comment by gabrielwalt** [comment]
@adobe export issue to Jira project SITES

**Comment by bpauli** [comment]
This was fixed in #1976 and the fix is part of the 2.18.0 release
