### ISSUE TITLE
[Teaser] Enable inheritance by default

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#1896]
When adding a new teaser (v2) to a page, the different inheritance features of the edit dialog are disabled by default. For an author, it be more efficient if those were enabled by default, so that only the link to a page must be configured, and (provided that page defines a page image) the teaser would then automatically display the page title, description, image (and alt text).

**Comment by gabrielwalt** [comment]
@adobe export issue to Jira project SITES

**Comment by gabrielwalt** [comment]
The inherit checkboxes should always be checked on opening the dialog for the first time, but be unchecked when switching to the 2nd ("Text") or 3rd ("Asset") tab and no link has been provided in the 1st ("Link") tab.

**Comment by bpauli** [comment]
@gabrielwalt The provided PR #1953 will not disable the inheritance automatically if no link or action is provided. Instead it makes sure that the title and description will also get inherited from the current page as this is already in place for the featured image. We also have the following description on the Link field
![image](https://user-images.githubusercontent.com/689884/151037878-d152df60-cba5-409e-a52e-21792584556a.png)

**Comment by gabrielwalt** [comment]
For the sake of simplicity, we should not make the main teaser link and the CTA mutually exclusive, so that we can decouple how the main teaser link and the first CTA impact the inheritance of the title, description and image from that link.

### Teaser title, description and image
The teaser title, description and image are inherited from the current page when no main teaser link is defined (regardless of what CTA are configured), and from the main teaser link when that is defined. Inheritance of those title, description and image elements is enabled by default when there's no link (inheriting them from the current page) or a link to an AEM page (inheriting them from the linked page), but disabled by default when the link is to an external URL (we probably should entirely disable the inheritance checkbox when the link doesn't point to an AEM page as inheritance won't work).

###  Enabling CTA
We therefore don't need anymore a checkbox "Link to destination with call to action" as adding checkboxes isn't replacing the main link anymore. Instead, we should add a label for the multi-field called "Call to actions". So, enabling call to actions is done by simply adding an entry to the multifield

### CTA default title
When setting a CTA link via the page picker, and the title of the CTA is empty, then then CTA title is pre-filled with the title of the linked page, which can then freely modified (not using an explicit inheritance checkbox for that). Setting the CTA link to an external URL wouldn't pre-fill anything in the CTA title. Keeping the CTA link empty should not be allowed, and be highlighted as an error in the dialog (the CTA title will therefore never be inherited from the current page when no CTA link is provided).

###  First CTA
When adding the first call to action, if the main teaser link is defined, then that link should be copied into the CTA link, because the first CTA is likely to go to the same page as the main link. Also, if that link points to an AEM page, then the CTA title should also be pre-filled with the title of that page. However, if the main teaser link is empty or pointing to an external page, then the first CTA link and the CTA title should default to empty values.
When adding further CTA items, this logic to default to the value of the main teaser link doesn't apply.
