### ISSUE TITLE
Carousel component how to set min and max number of children

### ISSUE THREAD

**Issue by pawee-del** [adobe/aem-core-wcm-components#1898]
## Feature Request

**Is your feature request related to a problem? Please describe.**
i want to set min and max on the number of children in carousel, i look at wcm code codebase, the dialog are in html how do i customise it?

**Describe the solution you'd like**
able to set min and max

**Are there alternatives?**

**Documentation**
If you can, explain how users will be able to use this and possibly write out a version of the docs.
Maybe a screenshot or design?

**Comment by gabrielwalt** [comment]
Hi @pawee-del, we don't intend to add such a limitation, therefore placing this issues into the "Icebox" milestone.
But if you plan to contribute such an enhancement, we'd welcome your pull request.
