### ISSUE TITLE
[ContainerUtils] Scroll to anchor logic fails for invalid ID hashes

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#1900]
The handling at [0] fails if there exists a URL hash which represents an invalid selector, for example "https://localhost:4502/content/mysite/mypage.html#/invalid". This leads to a console error as follows:

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#/invalid' is not a valid selector.
```

See: SITES-3853

[0] https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/container/js/containerUtils.js#L84

**Comment by bpauli** [comment]
fixed in 53b35201a925d7de1b3cbe64de379e2525e79581
