### ISSUE TITLE
[Image] issue with adaptive renditions of small tiff images

### ISSUE THREAD

**Issue by jdelannoy** [adobe/aem-core-wcm-components#1911]
## Bug Report

**Current Behavior**
When using tiff images in the Image Core Component the AdaptiveImageServlet will convert this into jpeg renditions according to the widths configured in the Image component policy.  This works fine when the original tiff image is large enough, but when the requested rendition width is bigger than the original image this breaks.  

For example, in the We.Retail example site, the image policy has the following widths configured: 128, 256, 512, 1024, 1280, 1440, 1920, 2048.  If you upload a small image to AEM (example [autumn.tif.zip](https://github.com/adobe/aem-core-wcm-components/files/7694825/autumn.tif.zip), dimensions: 345 × 206) and drag this onto an Image component in the We.Retail site, the image component will only render widths that are smaller than the original width (so in the example only 128 and 256) but larger renditions (e.g. 512 or higher) fail and return a jpeg file of 0 bytes.

Example URL that works for me: http://localhost:4502/content/we-retail/language-masters/en/about-us/_jcr_content/root/responsivegrid/image.coreimg.82.256.jpeg/1639159783293/autumn.jpeg

Example URL that fails for me: http://localhost:4502/content/we-retail/language-masters/en/about-us/_jcr_content/root/responsivegrid/image.coreimg.82.512.jpeg/1639159783293/autumn.jpeg

The problem seems to be that when a larger rendition is requested, the AdaptiveImageServlet is reverting to the original file, but this is then not converted into a jpeg rendition.

**Expected behavior/code**
I would expect that AdaptiveImageServlet to fallback on the largest available jpeg rendition (typically the 1280x1280 web rendition) instead of the tiff original.

**Environment**
Tested on:
- AEM 6.5.0.11 **and** AEMaaCS SDK 2021.11.6058.20211123T163652Z
- Core Components version 2.3.2 **and** 2.17.12
- Java version 8 **and** 11

**Possible Solution**

**Additional context / Screenshots**

**Comment by vladbailescu** [comment]
@adobe export issue to Jira project SITES as Bug
