### ISSUE TITLE
[Accessibility][Accordion] Capability to fold single item expansion

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#1917]
**Current Behavior**
When an accordion is configured with the "Single item expansion" option and only one item can be open at a time, then clicking on the collapse button has no effect.

**Expected behavior/code**
It would be expected that it's possible again to collapse the single expanded item.
This is especially true because of following facts:
1. The initial state can be configured so that all items are collapsed (if no expanded items are configured).
2. Without the "Single item expansion" option, it is possible to collapse all expanded items.

**Possible Solution**
Make the expand/collapse button to allow collapsing the expanded item again also when the "Single item expansion" option is enabled.

**Comment by glasert** [comment]
@adobe export issue to Jira project SITES as Story
