### ISSUE TITLE
Forked builds with GHActions immediately fail

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1933]
Due to the usage of secret keys not available in forks (https://github.com/adobe/aem-core-wcm-components/blob/c6756447df4ebcfd66d133385502cae3135f87be/.github/workflows/maven-test-push.yml#L55) the action does immediately fail (https://github.com/kwin/aem-core-wcm-components/actions/runs/1707799665).

There should be an action provided which allows a simple build and test on forks. Additional actions like signing should be restricted to the original repo.

**Comment by bpauli** [comment]
I think we can just unify the GH actions for push and pull_requests.

cc @vladbailescu WDYT?
