### ISSUE TITLE
Switch default branch to "development"

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#1934]
According to https://github.com/adobe/aem-core-wcm-components/blob/master/CONTRIBUTING.md every PR should target branch "development". Currently the default branch is "master" though, so by default 

1. Clones will end up in branch "master"
2. Every new PR creation in the GH UI targets "master"

To ease contributing switching the default branch to the one developers should primarily work with would be highly appreciated.

**Comment by bpauli** [comment]
Done.
