### ISSUE TITLE
Delete component on page edit does not work with precompiledScripts bundle included

### ISSUE THREAD

**Issue by sagarm-cm** [adobe/aem-core-wcm-components#1973]
When creating AEM project using archetype 35 for AEMaaCS with precompiledScripts = y, not able to remove a component added on page in edit mode.

**Current Behavior**
As an author, when clicking on remove button on a component (previously added), it throws JS error in console and button does not get removed.
If we stop the precompiledScripts bundle in OSGi console or install the project with -DskipScriptPrecompilation=true then component removal works fine.  

**Expected behavior/code**
.infinity.json should return valid JSON output and component removal should work as expected with precompiledScripts bundle.

**Environment**
- AEMaaCS SDK - 2021.11.6023.20211111T113531Z-211000 as well as the latest
- Core Components version - 2.17.12
- JRE version - 1.8.0_311

**Possible solution:**
This can be fixed, by adding "org.apache.sling.bnd.models.ModelsScannerPlugin" in the bnd-process execution steps of ui.apps/pom.xml

**Additional context / Screenshots**
Here is the error,
![image](https://user-images.githubusercontent.com/93796895/152881459-31373c66-a946-4fe0-975f-a3c3b67f3f9a.png)

The parent container's .infinity.json request is producing the invalid (includes HTML) JSON.
![image](https://user-images.githubusercontent.com/93796895/152881342-a5ac421a-f9a3-46d3-a964-e298f3fd3461.png)

**Comment by bpauli** [comment]
This is an issue of the sling servlet resolver and was fixed in https://issues.apache.org/jira/browse/SLING-11155. The internal reference is GRANITE-38314
