### ISSUE TITLE
Ability to disable image lazy loading in the Component Dialog 

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-core-wcm-components#1979]
Images that are in the initial viewport (LCP view) should not use lazy loading. Given that we by default enable lazy loading - which make sense - there needs to be a way to avoid lazy loading for images that are in the initial view.

One way to do that would be to allow the user to disable image lazy loading in the Component Dialog - or a smart way to disable the lazy loading for images at the beginning of the page?

**Comment by bpauli** [comment]
This feature was recently added to the image V3 component in https://github.com/adobe/aem-core-wcm-components/pull/2249 and will be part of the next release.
