### ISSUE TITLE
[Accordion] Possibility to edit a single container

### ISSUE THREAD

**Issue by stratosdw** [adobe/aem-core-wcm-components#2023]
## Bug Report

**Current Behavior**
After creating an Accordion component and adding a container we don't have the possibility to edit that component.

**Expected behavior/code**
We should be able to edit when only a single component is added.

**Environment**
- AEM as Cloud Service latest version (v2022.2.6276.20220205T222203Z-220100)
- Core Components version 2.17.14

**Possible Solution**
Allow the single component to be selected or enabling the "Select Panel" action when only 1 component exists.

**Additional context / Screenshots**
![image](https://user-images.githubusercontent.com/8149798/154468824-175fe6f9-71ea-485d-a631-7e6b1173bbb7.png)

It works with more than 1 component, because then we have access to the "Select panel" action.
There is a workaround, if we change tabs in Content Side Panel (From Assets to Content Tree for example) and go to the Content tree and click inside the Accordion container > Created component, we will be able to edit it, but that's not really author friendly.

**Comment by bpauli** [comment]
@stratosdw I was not able to reproduce the issue with the core component library and also not with a new project created with the aem-project-archetype [1]. Can you please also test the accordion with a new project based on the archetype? Just to make sure that this issue is not caused by some custom CSS on project level. 
If you see this issue also with the new project it would be helpful to provide a screen recording.

Thanks!



[1] https://github.com/adobe/aem-project-archetype

**Comment by bpauli** [comment]
@stratosdw As I can't reproduce this issue can you please share your client details (Browser, OS)? Thanks!

**Comment by stratosdw** [comment]
@bpauli , macOS Monterey 12.2.1, Chrome/Brave/Safari latest versions
This is also reported by colleagues with different OS/browsers.

Got a screen record about it so maybe it can help clarify the issue:

https://user-images.githubusercontent.com/8149798/154932029-13e25bd9-25c5-4f67-a6f8-b84b7ef7c4d9.mp4

**Comment by AlexanderEggersDivae** [comment]
I have the same issue in MS Edge. Reports from my teammates leads me to believe this is a deeper issue than just the accordion, and in fact presents itself in any similarly component using panels.

**Comment by AlexanderEggersDivae** [comment]
@bpauli I have reproduced this with the archetype you linked. Changing the file `apps/core/wcm/components/commons/editor/clientlibs/panelselect/js/panelselect.js:415` to `return (children.length > 0 && isPanelContainer);` fixes the issue. This seems sensible to me, forcing a single panel open to edit it and then undoing that checkbox again feels like a workaround.

**Comment by stratosdw** [comment]
@bpauli was the additional information helpful enough to help clarify the situation?

**Comment by bpauli** [comment]
@stratosdw Thank you for your effort and patience. I was able to reproduce the issue.

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as a Bug

**Comment by bpauli** [comment]
In the PR #2060 I made the change as suggested by @AlexanderEggersDivae and enable the panel selector for container with only one element. Thanks @AlexanderEggersDivae for this suggestion.

**Comment by chillinPanda** [comment]
Hi @bpauli ,

this fix is not included in [Core Components 2.18.8](https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.18.8) release.

The commit was done prior to the release date. I am wondering why this change is not included.

Is it going to be in the next one?

**Comment by bpauli** [comment]
@chillinPanda right, this fix will be included into the next regular release (2.19.0) which will be done from the main branch. 2.18.x were only hotfix releases. 2.19.0 is scheduled for this week.
