### ISSUE TITLE
Content Fragment Component - The Search option is removed after updating to latest sdk [AEM RELEASE: 2022.2.6276.20220205T222203Z]

### ISSUE THREAD

**Issue by shibinose** [adobe/aem-core-wcm-components#2026]
The Search option is removed in the Content Fragment component after updating to latest sdk [AEM RELEASE: 2022.2.6276.20220205T222203Z].

This seems to be related to generic lucene index removal changes. We tried just adding "nodeTypes" property to dam/cfm/components/cfpicker, but it did not work. 

We got it working after overlaying the "/libs/dam/cfm/components/cfpicker/render.jsp" to fetch and pass nodeTypes in the query.

Is this something which can be fixed as part of Core components release?

*
![image](https://user-images.githubusercontent.com/7383082/154649829-db87b6ad-8afd-46b3-98f6-38dd581516a9.png)

**Comment by vladbailescu** [comment]
This will need to be fixed in the product, please reach out to Customer Support to log a ticket for the issue.
