### ISSUE TITLE
Incorrect use of soand wcmmode.preview in HTL files

### ISSUE THREAD

**Issue by gquintillan** [adobe/aem-core-wcm-components#2031]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior, including steps that are repeatable, and your setup; if applicable, proxy component pattern and component version.

Please do not rely on any other wcmmode but 'disabled'. With Touch UI a change of the layer/​mode does no longer lead to a page reload, except for mode 'disabled', therefore you should only use that mode on server-side (even with negation). Every other mode/​layer needs to be treated on client-side.

**Expected behavior/code**

**Environment**
- AEM version and patch level (e.g. AEM 6.3 SP1 CFP2)
- Core Components version (e.g. 2.0.4)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ahmadjubair33** [comment]
Hi, @adobe @gquintillan Assign this issue to me I will update the HTML file.Thank you

**Comment by ncordeiro** [comment]
This issue also occurs with embeddables like youtube etc and any custom embeddable written. Kindly suggest
