### ISSUE TITLE
[Teaser][Property] Property actionsEnabled is not set

### ISSUE THREAD

**Issue by fahol-coop** [adobe/aem-core-wcm-components#2033]

**Comment by LucaNerlich** [comment]
Seems to be removed in commit 0730456fe2414935e6d41c7502ebdc5b9c2f6554

**Comment by vladbailescu** [comment]
As per https://github.com/adobe/aem-core-wcm-components/issues/1896#issuecomment-1023061391 we dropped the need for enabling the actions in the Teaser (v2) edit dialog. Now they are are enabled by default (unless disabled in the content policies).

**Comment by LucaNerlich** [comment]
> As per [#1896 (comment)](https://github.com/adobe/aem-core-wcm-components/issues/1896#issuecomment-1023061391) we dropped the need for enabling the actions in the Teaser (v2) edit dialog. Now they are are enabled by default (unless disabled in the content policies).

Hi Vlad,

it is however still referenced in https://github.com/adobe/aem-core-wcm-components/blob/main/content/src/content/jcr_root/apps/core/wcm/components/teaser/v2/teaser/actions.html and therefore leads to our teasers with 2.18 not displaying any ctas.
