### ISSUE TITLE
Page V3 body htl is not rendering structure resources

### ISSUE THREAD

**Issue by bhines01** [adobe/aem-core-wcm-components#2039]
Hello,

The body.html in page v3 is not rendering the containers after I upgraded from page v2.

The following htl code:
data-sly-resource="${child @ resourceType=child.resourceType, decorationTagName='div'}"

should be updated to:
data-sly-resource="${child.path @ resourceType=child.resourceType, decorationTagName='div'}"

or am I missing something?

Core Component Version: 2.18.0
AEM Version: 6.5.11

Thanks!

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as bug

**Comment by bpauli** [comment]
https://github.com/adobe export issue to Jira project SITES as Bug

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug

**Comment by bpauli** [comment]
@bhines01 Thank you for the hands up. I was able to reproduce the issue. We will provide a fix asap.

**Comment by bhines01** [comment]
@bpauli Thank you!!
