### ISSUE TITLE
CC 2.18 Page V3 jQuery is not defined, _g is not defined

### ISSUE THREAD

**Issue by LucaNerlich** [adobe/aem-core-wcm-components#2040]
## Bug Report

**Current Behavior**
When loading a Page V3, I assume due to the async clientlib integration, multiple javascript errors are being thrown on page refresh.

This can be reproduced by setting up a fresh 6.5.12 instance, installing the 2.18 Core Components and the Guides WKND pages.
Open a page, check the console, refresh the page and check the console again.

**Expected behavior/code**
The ootb code, without any customers / custom modification should not throw any javascript errors.

**Environment**
AEM 6.5.12
Core Components 2.18
Guides WKND 1.1.0

**Additional context / Screenshots**
![image](https://user-images.githubusercontent.com/5942270/156019531-8eee2ed9-3a37-4cf5-af85-1ec13325e86e.png)

Slight differences, depending on which core component is used / page composition. I do not have exact component setups on hand right now - sorry.

![image](https://user-images.githubusercontent.com/5942270/156020319-9f9f1bff-9e37-462d-95fb-08ac23aa99a3.png)

Ive found this Adobe Internal Slack link with the same issue: https://cq-dev.slack.com/archives/CR18QAQ75/p1646026384899809

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug
