### ISSUE TITLE
Style tab is blank on components without styles / policies

### ISSUE THREAD

**Issue by DriftingSands** [adobe/aem-core-wcm-components#2045]
## Bug Report

**Current Behaviour**
The updated core components have a 'style' tab in the settings. This tab also appears when there are no styles/policies set, the resulting tab is blank.
Additionally the components without a new version have no style tab.

**Expected behaviour/code**
It would be more clear if the style tab would not appear / have an error message when there are no styles to select from instead of a blank page.
It would be nice if the older components also get a style tab at some point

**Environment**
- aem-sdk-quickstart-2022.2.6433
- Core Components version 2.18.0
- Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)

**Comment by LucaNerlich** [comment]
yep. Very annoying. Getting tons of "bug tickets" from our POs and have to add sling:hideChildren=[styleTab] to many components.

Also, why has the naming changed? No other cc dialog tab has "tab" prefix in its node name.

**Comment by bpauli** [comment]
The PR at #2059 will add the styles tab to all components.

The render condition to hide the styles tab if no style is applicable will be added in one of next SDKs and SP for AEM 6.5
