### ISSUE TITLE
Core Extension Bundle 1.0.2 doesn't start

### ISSUE THREAD

**Issue by cmrockwell** [adobe/aem-core-wcm-components#205]
## Bug Report

**Current Behavior**
Bundle does not activate. 
com.adobe.cq.core.wcm.components.extension.contentfragment.bundle
Seems to have a dependency issue
com.adobe.cq.dam.cfm,version=[1.1,2) -- Cannot be resolved

> 07.06.2018 11:07:32.198 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleStartTask Could not start bundle com.adobe.cq.core.wcm.components.extension.contentfragment.bundle [2134]. Reason: {}. Will retry.
org.osgi.framework.BundleException: Unable to resolve com.adobe.cq.core.wcm.components.extension.contentfragment.bundle [2134](R 2134.3): missing requirement [com.adobe.cq.core.wcm.components.extension.contentfragment.bundle [2134](R 2134.3)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.dam.cfm)(version>=1.1.0)(!(version>=2.0.0))) Unresolved requirements: [[com.adobe.cq.core.wcm.components.extension.contentfragment.bundle [2134](R 2134.3)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.dam.cfm)(version>=1.1.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4112)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2118)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:97)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:894)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:729)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:286)
	at java.lang.Thread.run(Thread.java:745)

**Expected behavior/code**
This is causing issues when reviewing the WKND demo site

**Environment**
- AEM version and patch level (e.g. AEM 6.3 SP2)
- Core Components version (e.g. 2.0.6)
- core.wcm.components.extension-1.0.2.zip
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_112-b16)`)

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by gknobloch** [comment]
Hi @cmrockwell 

Thanks for raising the issue.
I think this is due to the missing Content Fragments feature pack, that you can get through https://helpx.adobe.com/experience-manager/6-3/release-notes/fp-22818-content-services-fragments-featurepack.html

Would that help?

**Comment by josephh** [comment]
@gknobloch 
I'm following your adobe GEMs online talk on content fragments.

I'm running and have installed 
* AEM 6.3 + SP1
* cq-6.3.0-featurepack-19008-1.0.6.zip (content fragments)
* picked up the source https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/releases/tag/core.wcm.components.extension-1.0.0  installed zip (built with maven) i.e. `aem-core-wcm-components-core.wcm.components.extension-1.0.0/extension/target/core.wcm.components.extension-1.0.0.zip`
Osgi console system/console/bundles shows Adobe Experience Manager Core WCM Components Extension - Structured Content Fragment Bundle v1.0.0 installed but not active - 
> com.day.cq.wcm.api.policies,version=[1.6,2) -- Cannot be resolved

I see from your above comment it looks like i've picked up the wrong feature pack - the FP link is on the Adobe website https://helpx.adobe.com/experience-manager/6-3/release-notes/content-services-fragments-featurepack.html

**Comment by josephh** [comment]
Actually @gknobloch it looks like I've got a different combination of service pack and components.extension, compared to the link you've included above.  Should I switch to an earlier version of the components.extension?

**Comment by josephh** [comment]
Think I missed the note I missed the note at the top of https://helpx.adobe.com/experience-manager/core-components/using/content-fragment-component.html which points out,
> https://helpx.adobe.com/experience-manager/core-components/using/content-fragment-component.html

I had version 1.0.2 of the core components 😒 But bumping up to 1.1.0 didn't solve the dependency resolving issue.  So i've gone for the earlier sandbox zip you use in the demo - looks good so far (core.wcm.components.sandbox.extension-0.0.1-SNAPSHOT.zip)

**Comment by cmrockwell** [comment]
@gknobloch I cannot find cq-6.3.0-featurepack-22818 in the package share.

![screen shot 2018-06-20 at 1 27 33 pm](https://user-images.githubusercontent.com/1811207/41674608-881be30e-748e-11e8-9db1-629b5e2521d2.png)

**Comment by gknobloch** [comment]
@cmrockwell, thanks for the feedback.
The Package Share team apparently experienced some issues under investigation.
In the mean time, I'd recommend you to contact AEM Support to get the package.
