### ISSUE TITLE
[Image] Not able to set width and image quality on static template

### ISSUE THREAD

**Issue by leonso** [adobe/aem-core-wcm-components#2095]
## Bug Report

**Current Behavior**
1. Create a static template under /apps/xx/template
2. Create a proxy component to have resourceSuperType of "core/wcm/components/image/v2/image" or use we-retail image components. 
3. Add an image to image components and change width and image quality on design dialog.
4. Image fail to generate thought AdaptiveImageServlet.java5. 

**Expected behavior/code**
Expect to be getting design dialog valve if using static template

**Environment**
- AEM version and patch level AEM 6.5 SP9
- Core Components version 2.18.8
- JRE version Java(TM) SE Runtime Environment (build 1.8.0_202-b08)

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by vladbailescu** [comment]
@adobe export issue to Jira project SITES as Story
