### ISSUE TITLE
[Navigation] Inconsistent isActive behavior in V3 (#688 regression)

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#2105]
## Bug Report

**Current Behavior**
In V3 Navigation component the `aria-current` HTML attribute is set on all links that are the current or ancestor of the current page.
This is explained and resolved in #688 for V2. 

Specifically, in V2 navigation the check was changed from:
```aria-current="${item.active && 'page'}"``` 
to:
```aria-current="${item.current && 'page'}"```
(See 2860b72)

In V3 the issue reoccurs because `item.active` is still used. 

**Expected behavior/code**
`aria-current` should only be set to `page` when the link points to the current page.

**Environment**
- AEM version: 6.5.12.0
- Core Components version: 2.18.8
- JRE version: 11

**Possible Solution**
Change the Navigation V3 HTL in the same way that V2 was changed.

**Comment by vladbailescu** [comment]
Thanks, @ky940819! I guess v1 was fixed after v2 was forked.
