### ISSUE TITLE
Style system not working for Container/Layout Container

### ISSUE THREAD

**Issue by kapil-gahlawat** [adobe/aem-core-wcm-components#2112]
**Environment**
- 6.5.12.0
- Core Components version - 2.18.8
- JRE version - openjdk version "11.0.13"
- Implementation - SPA (React)

This issue was reported earlier: https://github.com/adobe/aem-core-wcm-components/issues/1889

This issue was marked as fixed in 6.5.12.0, which was released last month. It is working in this particular case. However, there is a corner case where it is not working. Here are the steps to reproduce:

**Steps to reproduce the issue**:

1. We are using 6.5.12.0 and SPA react.
2. Create an Experience fragment template and LOCK the container in the template structure. Apply style to the container in the template structure. I added a couple of components inside this container. Make sure to LOCK the container and apply the style to the container in the template structure.
3. Now, create an experience fragment from the template created above. Experience fragments will have the style that we applied in the structure. So, it is working as expected.
4. Now create a normal page using spa-page-template or any template that you like and drag and drop Experience fragment component inside the page. Now, configure the path to the experience fragment that we created in the step 2. Now experience fragment inside your page will not look the same as the style that we applied in the step 1 are not being applied in the page.

**Summary**: Applied style is working fine inside the experience fragment but when you consume this same experience fragment in a page using the Experience Fragment Component, style is not being applied.

**Note**: If you drag and drop the container inside Experience fragment and apply style and then use this experience fragment on a page, this style is working absolutely fine. The only specific case it is not working is: Container is in the structure of experience fragment template and Locked.

**Additional context / Screenshots**

Experience Fragment template structure (I have applied the style fixed-width to the layout container):

<img width="1788" alt="Screenshot 2022-03-25 at 18 06 06" src="https://user-images.githubusercontent.com/4212284/160177201-75b0d47f-adf0-4d6e-ac6f-fd14592d9613.png">

After creating the experience fragment using the above template, this is how experience fragment looks like (**Notice margin on the left and right**. We have applied a CSS class fixed-width using container style to the template structure above):

<img width="1787" alt="Screenshot 2022-03-25 at 17 59 56" src="https://user-images.githubusercontent.com/4212284/160176489-8115aa60-68cf-4e3d-8c5a-fa9249578b98.png">

This is how the same experience fragment in a page looks like (Please notice there is **no margin on the left and right** of breadcrumb and image. CSS class applied using container style is not present when we include the experience fragment on the page):

<img width="1786" alt="Screenshot 2022-03-25 at 18 00 52" src="https://user-images.githubusercontent.com/4212284/160176856-409ea1ca-fd95-47d1-a333-1a9a016ef5f5.png">

**Comment by bpauli** [comment]
@adobe export issue to Jira project Sites as Bug

**Comment by bpauli** [comment]
@adobe export issue to Jira Project SITES as Bug

**Comment by bpauli** [comment]
@kapil-gahlawat Thank you for the hands up. Can you please verify if the PR at https://github.com/adobe/aem-core-wcm-components/pull/2116 will fix the issue? Thanks!

**Comment by bpauli** [comment]
@kapil-gahlawat The change just got merged to the main branch and will be included in the next release.
