### ISSUE TITLE
v2.8.16 and 2.8.18 do no publish release assets on Github

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-core-wcm-components#2115]
## Bug Report

**Current Behavior**

**Expected behavior/code**

I expect to be able to download the release artifacts from this projects' Github releases section.

**Environment**
- AEM version and patch level (e.g. AEM 6.3 SP1 CFP2) N/A
- Core Components version (e.g. 2.0.4) 2.18.6, 2.8.18
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`) N/A

**Possible Solution**

Upload the release assets for these 2 releases.

**Additional context / Screenshots**

v2.8.16 and 2.8.18 do no publish release assets on Github
![2022-03-29 at 9 11 AM](https://user-images.githubusercontent.com/1451868/160619020-e71bf0c3-d2cd-4bcb-b178-620515e2054b.jpg)

**Comment by bpauli** [comment]
@davidjgonzalez Thank you for the hint! I just uploaded the released artifacts to the GitHub release section.
