### ISSUE TITLE
[ContentFragment] "Edit in New Tab" action does not showup

### ISSUE THREAD

**Issue by ugeshreddy** [adobe/aem-core-wcm-components#2147]
**Current Behavior**
We have extended Content Fragment Core Component (Super type) and customized on top of that and we copied cq:editConfig node also to our custom component edit button should not show up.

Basically cq:editConfig node is responsible to show up edit button, even though we added that node it doesn't show up. 

**Expected behavior/code**
The edit button should show up and open the Content fragment in the content fragment editor.
This is the behavior of the OOTB vanilla CF component. 

**Environment**
- AEM version and patch level (e.g. AEM 6.5 SP8)
- Core Components version (e.g. 2.17.8)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Comment by ugeshreddy** [comment]
![image](https://user-images.githubusercontent.com/73253213/165338138-2c618967-b5e2-46a1-bb29-01ecdc4b8f38.png)
edit icon missing

**Comment by ugeshreddy** [comment]
![image](https://user-images.githubusercontent.com/73253213/165791969-e05dfda2-2513-4566-bbf1-33c71cb0d54f.png)

**Comment by bpauli** [comment]
@ugeshreddy The edit button is enabled via a custom editor hook in the contentfragment component [1]. To reuse this hook for your custom contentfragment component you have to make sure that the root element has the attributes 

```data-sly-attribute.data-cmp-contentfragment-path="${fragmentPath}"
        class="cmp-contentfragment"
```

Please let me know if you have further questions. Thanks!

[1] https://github.com/adobe/aem-core-wcm-components/blob/main/content/src/content/jcr_root/apps/core/wcm/components/contentfragment/v1/contentfragment/clientlibs/editor/authoring/js/editAction.js
