### ISSUE TITLE
Support content in multiple languages within a page

### ISSUE THREAD

**Issue by GrimaceDoesA11y** [adobe/aem-core-wcm-components#2151]
## Feature Request

**Is your feature request related to a problem? Please describe.**
- Marketing campaigns have words and phrases presented in multiple languages than the language of the page.
- Make it possible, OOTB, for user agents and assistive technologies to present content according to the presentation and pronunciation rules for that language.  (WCAG Language of Parts 3.1.2 Level AA)

**Describe the solution you'd like**
A way for content authors to apply a language attribute to a phrase or word in the editor.
System-wide language dictionary that can be referenced by authors and/or by the system in which defined phrases get wrapped in a <span lang=" "> element.

**Are there alternatives?**
Project-level with either JavaScript or with a server-side HTML output rewriter

**Documentation**
WCAG Language of Parts URL: https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html

Example: The language of the page is set to English.  An editor is using the RTE component and type a word or phrase, highlight it and set the language of the content.

**Comment by gabrielwalt** [comment]
This is an accessibility enhancement request to the RTE widget that the core components are using. Please open a corresponding support request.

I'm closing this issue for the time being as this cannot be fixed meaningfully within the scope of this GitHub repository.
