### ISSUE TITLE
[Accessibility][Carousel] Pause / Play buttons not available when automatic transition is disabled

### ISSUE THREAD

**Issue by GrimaceDoesA11y** [adobe/aem-core-wcm-components#2152]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In authoring, disabling the "Automatic transition" of the slides, removes the play and pause buttons in the environment. 

**Describe the solution you'd like**
When automatic transition is disabled, the play / pause button remain to allow site visitors who do wish for the carousel to transition access to that navigation method. 

**Are there alternatives?**
Show/Hide carousel controls option in the dialog.

**Documentation**
In the design dialog for the Carousel Component, under the properties tab, option is available for authors to choose which carousel controls show.

**Comment by gabrielwalt** [comment]
@adobe export issue to Jira project SITES

**Comment by GrimaceDoesA11y** [comment]
Hi @gabrielwalt 
Great question!  This is more usability and inclusion, because there's not a barrier for the users to access the content; everyone has to manually the move the slides. 

In this scenario, when motion is pause by default, the more slides added to the carousel, the more physical interactions content authors are asking from visitors. Humans have varying degree of mobility. This functionality gives users a single interaction to move though the slides and reduces the amount of interactions they have to perform to view the content.

**Comment by gabrielwalt** [comment]
I'd like to say that the current purpose of the carousel isn't to act as a slideshow component. A carousel component, unlike a slideshow component, isn't something that a user would want to start playing. If this component were thought for slideshow use-cases it should also feature a full-screen toggle, which it doesn't. Not that this would be a bad idea - it's an excellent idea actually - but it's then a feature request. When a component is used for use-cases that it hasn't been thought for, it will indeed cause usability and accessibility issues, but the underlying issue then aren't usability and accessibility issues and rather the fact that we should extend the carousel to also support slideshow use-cases.

However, it might be useful to also highlight that the carousel can be rotated with the keyboard arrows, which might help to mitigate the usability issues for when a user would like to start auto-rotation via a play button.

**Comment by GrimaceDoesA11y** [comment]
Hi @gabrielwalt 
This is noted as a feature request. I disagree that highlighting the usage of keyboard arrows, will help improve usability. Every stroke on a key is an interaction a customer has to take.  There's still the challenge of a single interaction versus repeated strokes.
