### ISSUE TITLE
Image V3 Core Component not working on AEMaaCS SDK

### ISSUE THREAD

**Issue by suryakand** [adobe/aem-core-wcm-components#2159]
## Bug Report

**Current Behavior**
When Image from  Core Components version (e.g. 2.18.0) is used it does not renders the selected image. 
When the image URL (from HTML source) is accessed directly from a browser, it throws below error (also see screen shot attached):

`class com.adobe.cq.wcm.core.components.internal.link.LinkHandler cannot be cast to class com.adobe.cq.wcm.core.components.internal.link.LinkHandler (com.adobe.cq.wcm.core.components.internal.link.LinkHandler is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @3072a278; com.adobe.cq.wcm.core.components.internal.link.LinkHandler is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @461e7519)`

**Expected behavior/code**
Selected image from image component's dialog should display.

**Environment**
- AEM version: AEMaaCS SDK version 2022.4.7138.20220427T075748Z-220400
- Core Components version  2.18.0
- JRE version openjdk version "11.0.14" 2022-01-18 LTS
- OS - Both Windows and Mac

**Possible Solution**
NO

**Additional context / Screenshots**
![image](https://user-images.githubusercontent.com/3459040/167232691-4bc34d0b-9c3a-4c4d-96a8-4c859567362d.png)

**Comment by ChristianLapinig** [comment]
I am running into the same issue.

**Comment by epsilon-bsaikiran** [comment]
I am facing this issue too.

**Comment by bpauli** [comment]
Ok, I just installed 2.18.0 on top on my SDK and can see the same error. The SDK and AEMaaCS have the Core Components already installed `at /libs`. You can't install the Core Components on you own in a different version. This is only necessary for OnPrem Customer which are using AEM 6.5.
