### ISSUE TITLE
Teaser duplicate id for teaser div and image tag.

### ISSUE THREAD

**Issue by Rahul-Kumar-AIG** [adobe/aem-core-wcm-components#2164]
If you view-source the page with teaser component and configured with teaser id, and search for the teaser id that is configured, you will find two occurrence. The id is provisioned for teaser component but its duplicating for image as well. So whenever we add id to teaser component then only one id should be displayed and that too for outer div and not for image div.

**Comment by gabrielwalt** [comment]
@adobe export issue to Jira project SITES

**Comment by bpauli** [comment]
@ky940819 Thank you for your contribution!

**Comment by rajeevyadav2** [comment]
@gabrielwalt @Rahul-Kumar-AIG @bpauli  -  I looked into the code fix for this issue and it might be partial fix. id inside image data-cmp-data-layerThe is also having same  id as teaser and the code change in HTML does not address this issue.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/17505312/173175225-e59d0a0f-41c8-4d58-8277-ae3b9e8858c7.png">
