### ISSUE TITLE
[Page][v3] Featured Image properties are overwritten after rollout

### ISSUE THREAD

**Issue by sozores** [adobe/aem-core-wcm-components#2166]
## Bug Report

**Current Behavior**
In a MSM site structure, the Featured image properties (Page Properties > Images Tab > Featured Image) do not observe the same behavior as other page properties: there is no possibility to cancel or revert the inheritance in the live copies.

If a live copy has a feature image configured then, after rolling out from the blueprint this image is overwritten by the master page featured image.

**Expected behavior/code**
Allow cancel/revert inheritance for Feature Image properties (image and alternate text).

**Environment**
- AEM version and patch level: 2022.4.7138.20220427T075748Z
- Core Components version: 2.19.0
- JRE version: OpenJDK Runtime Environment 18.9 (build 11.0.2+9)

**Possible Solution**
Adding `cq-msm-lockable` property to the feature image.

**Comment by gabrielwalt** [comment]
@adobe export issue to Jira project SITES

**Comment by gabrielwalt** [comment]
This issue has been made part of our current sprint.
