### ISSUE TITLE
[RTC] Download Component

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#217]
**[Request To Comment]** To anybody who intends to use the Core Components, please provide your feedback about the following requirements. We want to make sure that we build a component that fits your needs, so don't hesitate to tell us how that component should work, so that you will be able to use it.

## User Story

As a page or template author, I need a component to share documents on the page, so that visitors can download them.

## Acceptance criteria

* Display a single document to download
* Take the source from DAM, or allow it to be uploaded from the local file system to the component instance
* Ability to provide meta-data:
  * Title (inherited from DAM when existing)
  * Description (inherited from DAM when existing)
  * File name (displayed in a SPAN)
  * File format (displayed in a SPAN, also available as class name for adding an icon if desired)
  * File size (displayed in a SPAN)
* Policy dialog:
  * Disable local file system upload
  * Options to hide
    * Description
    * File name
    * File format
    * File size
* Download links must be cacheable by the dispatcher
* Download links must also work with templates (similar to the image component)
* Microdata from schema.org

**Comment by kwin** [comment]
It would be nice to support different ways of viewing (e.g. for PDF): inline vs. attachment. The content disposition header should be set accordingly. Also this header should be used to set the proposed filename. For that the Dispatcher would need to be configured to cache headers as well.

**Comment by gabrielwalt** [comment]
Great comment, thanks @kwin!

This highlights the need for a file download servlet that is bound to the resource type of the the download component, like we have for images. This servlet would allow to set the headers accordingly, and then stream the data of the file as-is.

**Comment by kwin** [comment]
For me the decision between download and view should be with the content editor. The site visitor should see whatever has been defined on that component by the editor. For me one option is enough, but there might be edge cases where the editor explicitly allows both options.

**Comment by reusr1** [comment]
it would be nice to also support a thumbnail view of the file to download (either from a rendition of the asset from DAM or uploaded through the component)

**Comment by rajeevyadav2** [comment]
It would be nice to provide an option to preview the downloadable document/asset.

**Comment by rajeevyadav2** [comment]
I guess there should 3 options for download component:
1. Download as File
2. Preview the document in browser
3. Print the Document using preview mode

Also, if there is an default icon based on document mime type. User should be able to override the icon.

**Comment by pauldrago** [comment]
So this is great when we are talking about one asset-- but there are instances (technical specifications for example) where a "Download List" component would be useful.   Same kind of logic that people have requested on [#392](https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser)

**Comment by alexanderbethke** [comment]
Maybe this could be integrated into a global link component that could be used from within the Rich Text Editor?

**Comment by richardhand** [comment]
Adding the requirements here posted the duplicate #518 issue by @kweku5:

As an author, I want to add a download link to a page, so I can provide links to files that can be downloaded from the page.

• Author is able to add a download component to parsys
• Author is able to navigate to an asset and select as target
• File in the local DAM
• Should accept any file in the DAM
• Author is able to optionally add a url (external to the site) that points to a file as the target download
• Author is able to add download link text/label (mandatory)
• Text becomes link to download
• Text limit max 256 characters
• If more restrictive character count is required, it should be controlled by CSS.
• Author is able to add (optional) image to represent the download
• Image becomes link to download
• Display/format be controlled by CSS
• When user selects link text or image link dialog opens to "save file as"
• Leveraging the browse settings of the user (whatever it's set to)
• User is able to download file.

**Comment by kwin** [comment]
Please also add support for Conditional Request as defined by [RFC-7232](https://tools.ietf.org/html/rfc7232) via `LastModified` or `ETag` headers.
