### ISSUE TITLE
[RTC] Social Media Component

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#219]
**[Request To Comment]** To anybody who intends to use the Core Components, please provide your feedback about the following requirements. We want to make sure that we build a component that fits your needs, so don't hesitate to tell us how that component should work, so that you will be able to use it.

## User Story

As a page or template author, I want to embed 3rd party social objects on the pages, so that they can be displayed to visitors.

The idea of this component is that authors simply paste the URL of a social object into the component's dialog, the component then recognizes if this kind of social objects is supported, and if it is, it inserts the corresponding embed code. Projects could extend it as needed to support the social objects needed by authors. This model allows to avoid that authors can paste HTML embed codes that might need to contain JavaScript, which would cause security issues.

## Acceptance criteria

* Edit dialog
  * Display the list of supported and allowed social objects (just as a piece of information to the author).
  * The dialog allows to enter the 3rd party URL of the social object.
  * If the URL can be processed, an indication shows that, else a meaningful error message is shown.
* A preview is displayed on the page once the dialog is closed/saved.
* The policy allows to restrict the list of supported social URLs.
* Extension points:
  * Capability to register a supported URL pattern
  * Capability to provide a rendition for that URL

Some social objects could be supported OOTB, others would be contributed by the community or implemented on projects. Example of what kind of social objects can be supported:
 * YouTube video/playlist
 * Facebook page/post/feed/video
 * Twitter tweet/feed
 * SoundCloud track/playlist
 * Instagram post/feed

**Comment by anthonycaccese** [comment]
Hi @gabrielwalt it's Anthony from Discovery (we use AEM to power a large amount of our web properties such as HGTV and Foodnetwork).

Speaking to the Social Media Component we have built something similar in 2016 for our instances.

We ended up building each social embed as a different component for 2 reasons:
1) Our content creators see each platform independently and it made sense for each to be represented as individual components for selection
2) We had a need to provide component properties to set the specific embed options of each provider (more than the URL) and weren't sure of the best way to offer those properties contextually in a single component

So the main questions I would have are around the second reason (as I think we would be ok with it being one component as long as optional settings were contextually displayed in the dialog based on the social platform being embedded)

Some examples (screenshots are attached below)
* In our Instagram Embed we offer an option to hide/display the associated post's caption
* In our Tweet Embed we offer the option of hiding/displaying/ media (if we want to minimize the display in a given article) and/or hiding/displaying the conversation associated with a given tweet

Do you have a authoring pattern to expose/hide a property based on the value of data in another property in the same dialog?

Other considerations I would recommend adding to the acceptance criteria are:
* Allowing the embedding of multiple of a given component on a single page (e.g. more than one instagram post or combination of social embeds)
* If multiple are added to a single page making sure that the required JS is only added once for performance considerations

Here is an example from HTGV - https://www.hgtv.com/design-blog/design/interior-design-instagram-hashtags that has both of the above considerations in place

Hope this is helpful

![instagram embed](https://user-images.githubusercontent.com/1454947/41979748-d2110a70-79f2-11e8-9f90-a0c14b1a5d7c.png)
![pinterest embed](https://user-images.githubusercontent.com/1454947/41979749-d21e1242-79f2-11e8-872b-d9e65a774e4e.png)
![tweet embed - hide media](https://user-images.githubusercontent.com/1454947/41979750-d229feae-79f2-11e8-9ed8-6b012023a712.png)
![tweet embed](https://user-images.githubusercontent.com/1454947/41979751-d2379fbe-79f2-11e8-963d-02ba38f144f9.png)

**Comment by gabrielwalt** [comment]
Great feedback again, thank you @anthonycaccese!

We also thought that we might need further options per social provider, but as we were unsure of the need we dropped it again. But as there is a real need for it, I'm perfectly fine to add it back!

I think that we can figure out a way for each provider to provide a partial dialog that gets displayed when the corresponding URL is detected, but this remains TBD.

It's also good to know that we also need to take care that multiple includes don't make multiple includes of the corresponding libraries. That makes sense!

**Comment by bcmoney** [comment]
@gabrielwalt 
What is the release plan for this one and how/why (if at all) is it tied to the Embed Component proposal? 

I noticed the Embed Component thread was updated to indicate it'd be available in the next release, where this one still seems a bit ambiguous about where its at exactly. The ability to embed content from external sources like YouTube, Vimeo, Twitter, Facebook, etc... in a consistent way through Core Components will be an excellent feature (and selling point to management, along with the many others of course) for our upgrade.

**Comment by nc-andreashaller** [comment]
Hi, 
I see that it was planned to add YouTube, Instagram and others to the component, but as far as I can see only Facebook and Pinterest are supported nowadays (https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/sharing/v1/sharing). Was there a reason for not supporting others or might I open a ticket for it?
Best,
Andreas

**Comment by jckautzmann** [comment]
@nc-andreashaller The Social Sharing component supports sharing content from AEM with Facebook and Pinterest. There are currently no plan to support other platforms.
The discussion in this ticket also mentions the Embed component which enables embedding content into your pages from any other platforms that provide this functionality. It currently supports Pinterest and Youtube but it can be easily extended to support other platforms.

**Comment by nc-andreashaller** [comment]
Thanks for your quick response. Does "There are currently no plan to support other platforms." mean it makes sense to open an enhancement ticket or was it already discussed that it should not be supported.

**Comment by jckautzmann** [comment]
You can for sure create a ticket describing the feature that you would like to have. The quickest way to get the features added is to provide a pull request with the desired changes.
