### ISSUE TITLE
Tab Component | Newly added Component is not getting added in Tab component

### ISSUE THREAD

**Issue by hcl36741** [adobe/aem-core-wcm-components#2199]
## Bug Report

**Current Behavior**
In Tab component, newly added component is not getting displayed in the tab component dialog and when we reopened the dialog then component get added in the starting of the dialog.

Steps to reproduce :
1. Add a component in tab component dialog.
2.  Newly added component not coming in the Tab component dialog click on "OK".
3.  reopen the dialog, newly added component will come in the top of the dialog.

**Expected behavior/code**
When I add a component in tab component, then that component should be displayed in the Tab component dialog.

**Environment**
- AEM as a Cloud Service (SDK - aem-sdk-2022.5.7493.20220524T082827Z-220401)
- Core Components version (2.19.2)
- JRE version (Java 11)

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
[Rec 5-31-2022.zip](https://github.com/adobe/aem-core-wcm-components/files/8805630/Rec.5-31-2022.zip)

**Comment by jtneves** [comment]
same has this one I've opened a couple of hours earlier - https://github.com/adobe/aem-core-wcm-components/issues/2198

**Comment by msagolj** [comment]
as @jtneves mentioned this is a dublicate of #2198, so closing this one.
