### ISSUE TITLE
AdaptiveImageServlet isn't respecting the contentPolicyDelegatePath

### ISSUE THREAD

**Issue by ravkiran** [adobe/aem-core-wcm-components#2209]
## Bug Report

**Current Behavior**
In the past, there's support for contentPolicyDelegatePath in AdaptiveImageServlet (AIS) which helps in deleting the resolution of the image content policy to a specific resource. I think it was added for supporting targeting on Image component. Once the image component is targeted, the default rendering is part of the page, but the targeted experiences are stored under /content/campaigns, where we can't specify the content policies. Through contentPolicyDelegatePath, we can tell AIS to use the content policy of the default component inside the page.

I'm working on adding the support for Targeting inside the Experience Fragments and the image component has a defined content policy that sets allowedRenditionWidths. When the image component is targeted, Image component is making this call to request the adaptive rendition for the screen size
http://localhost:4502/content/campaigns/wknd/master/TestActivity/chrome-experience/master-image/jcr:content/par.html?contentPolicyDelegatePath=/content/experience-fragments/wknd/language-masters/en/contributors/kumar-selveraj/master/jcr:content/root/container/image/default&_=1654621623364

But this request is failing with 404 and the below error
```
07.06.2022 10:09:42.768 *ERROR* [[0:0:0:0:0:0:0:1] [1654621782763] GET /content/campaigns/wknd/master/TestActivity/chrome-experience/master-image/_jcr_content/par/image.coreimg.75.1200.jpeg/1654020856124/adobestock-241578158.jpeg HTTP/1.1] com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServlet Invalid image request
java.lang.IllegalArgumentException: Third selector must contain a valid width information (selector > 0)

```
Further investigation in the AIS, showed that content policy for this request isn't being set as we're not passing the `request` object to 
`policyManager.getPolicy(imageResource)` since this [commit ](https://github.com/adobe/aem-core-wcm-components/pull/754)

Is the support for `contentPolicyDelegatePath` dropped deliberate? Is there a better way to achieve the same?

**Expected behavior/code**
As the targeted experiences of the image component can't have the content policy itself, Please provide an alternate way to delegate the content policy of specific resource.

**Environment**
- AEM CS SDK aem-sdk-quickstart-2022.5.7493.20220524T082827Z-220401
- Core Components version - core.wcm.components.content-2.19.2.zip
- JRE version - openjdk version "11.0.7" 2020-04-14 LTS

**Possible Solution**
I've tried to add the `request` object like
```
policyManager.getPolicy(imageResource, request);
```
and also added the request object in all other calls where this is required to be able to pass this to [getContentPolicy](https://github.com/adobe/aem-core-wcm-components/blob/main/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java#L852)
This worked, as the `policyManager` reads the `contentPolicyDelegatePath` request parameter and able to resolve the content policy from the `contentPolicyDelegatePath` value

**Comment by jckautzmann** [comment]
@adobe export issue to Jira project SITES as Story

**Comment by jckautzmann** [comment]
@ravkiran Could you please list the steps how to reproduce this issue on a vanilla instance?

**Comment by jckautzmann** [comment]
https://github.com/adobe export issue to Jira project SITES as Story

**Comment by jckautzmann** [comment]
@adobe export issue to Jira project SITES as Story

**Comment by jckautzmann** [comment]
@adobe export issue to Jira project SITES as Story

**Comment by jckautzmann** [comment]
I was able to reproduce the issue as follows:
- image1 at `/content/mysite/mypage/jcr:content/root/container/image1` does not have a policy configured
- image2 at `/contentexperience-fragments/mysite/myxfj/master/jcr:content/root/container/image2` has a policy with: `quality` = 80, `allowed widths` = [1000,1200]

Following GET request:
```
http://localhost:4502/content/mysite/mypage/jcr:content/root/container/image1.coreimg.80.1200.png/1655121857114/screenshot-2022-06-09-at-14.26.45.png?contentPolicyDelegatePath=/contentexperience-fragments/mysite/myxfj/master/jcr:content/root/container/image2
```
triggers the error. Instead it should render the image.
