### ISSUE TITLE
Remove embedded Sling Models Impl

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#2212]
According to the [README](https://github.com/adobe/aem-core-wcm-components/blob/main/README.md)

> Since version 2.11.0 org.apache.sling.models.impl version 1.4.12 or higher is required (due to [SLING-8781](https://issues.apache.org/jira/browse/SLING-8781)). This will be provided for AEM 6.4 and 6.5 in a future Service Pack. Until then, the Sling Models bundle is included in the core.wcm.components.all package.

At least AEM 6.5.10 (prerequisite of 2.19.2) ships with org.apache.sling.models.impl-1.4.16 already so I think the embed from https://github.com/adobe/aem-core-wcm-components/blob/2f5c89e08a3f806ba5bd0cd5f09f3f138b4dd91c/all/pom.xml#L70-L75 can be safely removed together with the remark from the README.

**Comment by kwin** [comment]
Indeed although this was merged this commit never ended up in a release (https://github.com/adobe/aem-core-wcm-components/pull/2218#issuecomment-1527317055). @vladbailescu Can you check what went wrong?

**Comment by bpauli** [comment]
@kwin Thank you for the pointer and sorry for that! Will be reverted in #2497
