### ISSUE TITLE
Link can't be created using button component

### ISSUE THREAD

**Issue by arunpatidar02** [adobe/aem-core-wcm-components#2222]
## Bug Report

**Current Behavior**
Link(a) cannot be created using Button component(v2)

**Expected behavior/code**
Link should be created using Button component

**Environment**
- AEM version and patch level (e.g. AEMaaCS)
- Core Components version (e.g. 2.19.0)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 11)`)

**Possible Solution**
The Button dialog uses "linkURL" property https://github.com/adobe/aem-core-wcm-components/blob/f7433a6bb0955349aecbe17bd747aaeb03823ef8/content/src/content/jcr_root/apps/core/wcm/components/button/v2/button/_cq_dialog/.content.xml#L68 
but ButtonImpl uses "link" property to validate the link https://github.com/adobe/aem-core-wcm-components/blob/f7433a6bb0955349aecbe17bd747aaeb03823ef8/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ButtonImpl.java#L83 

If property value can be changed to link then it worked or property can be changed in Model when validate and get link. 

**Additional context / Screenshots**
The inconsistency between dialog property name and Model property for button link, lead to this issue.

**Comment by jckautzmann** [comment]
hi @arunpatidar02 , thx for your feedback. I added a Button v2 component to a page, configured a link through the edit dialog: the  link was correctly displayed. Could you please list the exact steps you went through and the outcome so that we can reproduce the issue?

**Comment by arunpatidar02** [comment]
Hi @jckautzmann 
I am also configuring via dialog.

![image](https://user-images.githubusercontent.com/35201853/175249190-30eea392-6166-4915-b347-329941c5805d.png)

![image](https://user-images.githubusercontent.com/35201853/175249453-2fe9551c-67a9-4bf6-b274-e57734b9ce83.png)

It could be an issue with my instance but I am not sure, Meanwhile I will try on vanilla instance to check this again.

**Comment by arunpatidar02** [comment]
working in vanilla
![image](https://user-images.githubusercontent.com/35201853/184339408-24b5ecea-edfe-4210-8e1e-2de756ab1220.png)
