### ISSUE TITLE
Breadcrumb component doesn't show arrow icon (>)

### ISSUE THREAD

**Issue by RasenderS** [adobe/aem-core-wcm-components#2228]
## Bug Report

**Current Behavior**
### Steps to reproduce:

- Start new AEM instance

- Create an AEM archetype project 
`mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=37 \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
-D aemVersion="cloud"`

- Create a page under us/en and add breadcrumb component. It will not show > as shown in https://www.aemcomponents.dev/content/core-components-examples/library/core-structure/breadcrumb/hidden/level-1/level-2/breadcrumb.html#tabs-2eaa4242cf-item-32b23b5e9d-tab
![Screenshot 2022-06-27 at 4 35 34 PM](https://user-images.githubusercontent.com/94722821/176060094-4a4fd965-1e03-4333-83f5-c5bb78ca841c.png)

**Expected behavior/code**
arrow icon(>) should display between different breadcrumb levels

**Environment**
- AEM version : AEM Cloud sdk latest
- Core Components version - Tried latest
- JRE version : JDK11

**Comment by ky940819** [comment]
I think that different people are going to want to display different things.
So it either has to be configurable, or this issue can just be solved in CSS:

Try something like the following:

```
.cmp-breadcrumb__item:after {
    word-wrap: normal;
    content: ">";
    display: inline-block;
    margin: 0 0.5rem;
    white-space: nowrap;
}
```

**Comment by bpauli** [comment]
I totally agree with @ky940819. This is also how it is done for the component library theme

https://github.com/adobe/aem-core-wcm-components/blob/main/examples/ui.apps/src/content/jcr_root/apps/core-components-examples/clientlibs/clientlib-themes/core-components-clean/styles/components/breadcrumb/dark.skin.less#L22

@RasenderS Please use the CSS and pseudo selectors for the delimiter of the breadcrumb items.
