### ISSUE TITLE
Content Fragment List component OrderBy field doesn't find the data in the JCR due to missing path

### ISSUE THREAD

**Issue by jfoxx** [adobe/aem-core-wcm-components#2231]
**Steps to recreate:**  Add a CF List to your page and build the list from a model.  The model should contain a date field.  Select the date field in the List dialog to sort by that date. 
**Expected outcome:** CF List should be sorted by the field that contains the date referenced in the property
**Actual outcome:** CF List always sorts by default jcr:created date. 

The model is building a query that just references the orderBy property value directly, but the actual property is found in jcr:content/data/master/ .  Changing the stored value in the orderBy property to include "jcr:content/data/master/" makes the list work as expected.

https://github.com/adobe/aem-core-wcm-components/blob/5aa8330cfa5ea6d15a62d465f01b784209485c7c/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java#L147

**Comment by bpauli** [comment]
Issue got fixed in https://github.com/adobe/aem-core-wcm-components/pull/2294
