### ISSUE TITLE
Remove usage of Granite.I18n.get for JS that is used on published site

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-core-wcm-components#2236]
https://github.com/adobe/aem-core-wcm-components/blob/0875847c6cfbe56717a7022cb7e228e04a395ccb/content/src/content/jcr_root/apps/core/wcm/components/commons/site/clientlibs/link/js/link.js#L22

`Granite.I18n.get `requires `granite.utils` clientlib which we should NOT load on public facing sites - we use it for areas that are when the pages is edited - in the editor.

When I change the line to

`var linkAccessibilityHtml = "<span class='" + linkAccessibilityClass + "'>opens in a new tab</span>";`

I can remove the `granite.utils` clientlib and the site loads ok

**Comment by keepthebyte** [comment]
This is a regression from https://github.com/adobe/aem-core-wcm-components/issues/1967

**Comment by jckautzmann** [comment]
@adobe export issue to Jira project SITES as Story

**Comment by vdua** [comment]
@keepthebyte We need to update the public documentation as well. Or this issue is specific only for the cloud service ?

https://experienceleague.adobe.com/docs/experience-manager-65/developing/components/internationalization/i18n-dev.html?lang=en
