### ISSUE TITLE
[Image, Teaser] Validation inconsistencies in dialog Asset tab

### ISSUE THREAD

**Issue by sozores** [adobe/aem-core-wcm-components#2254]
## Bug Report

**Current Behavior**
With image v3 and teaser v2, I've come up with some inconsistencies during dialog input validation. These are my test cases:
1. [Image, Teaser] Set up linked page with featured image (or a featured image in current page) but no alternative text is set in the linked page page properties: then setting the alternative text in the corresponding input of the Asset tab of the dialog, does not validate.
2. [Image] Check input "Don't provide an alternative text" in the Asset tab of the dialog: then the Link input is not visible.

**Expected behavior/code**
For each test case:
1. Allow an alternative text to be manually defined by the user
2. Enable the Link input field even if alternative text is not provided 

**Environment**
- AEM version and patch level: 2022.6.7904.20220629T070041Z
- Core Components version: 2.20.4
- JRE version: OpenJDK Runtime Environment 18.9 (build 11.0.2+9)

**Comment by bpauli** [comment]
We need to fix test case 1. I don't think we should provide the link capability for images without alt text for accessibility reasons.

**Comment by BrianAva** [comment]
And lack of alt text hurts page experience: engines track UX accessibility metrics.
https://www.searchenginejournal.com/google-alt-text-only-a-factor-for-image-search/442865/

**Comment by EssersB** [comment]
We are experiencing similar problems with the teaser and image components.
Steps to reproduce:

1. Put an image component on a page.
2. Open the author dialog of the image component.
3. Deselect the checkbox "Inherit featured image from page".
4. Drag an image file from the sidebar in the author dialog.
5. (leave checkbox "Inherit from description of asset" selected)
6. Select the checkbox "Don’t provide an alternative text".
7. Try to save the image component (click on "Done") --> It is not possible and the tab asset is marked as incorrect.

The same will happen when trying to save a teaser with an image and both checkboxes selected.

I would expect that if "Don’t provide an alternative text" is selected, it doesn't matter whether "Inherit from description of asset" is selected or not.
![image](https://user-images.githubusercontent.com/111497399/185424941-875f09b6-8a46-4ee7-8929-4dcd3d12aae9.png)
