### ISSUE TITLE
Container background color doesn't work

### ISSUE THREAD

**Issue by jfoxx** [adobe/aem-core-wcm-components#2260]
When the Container is configured with a background color, the color swatch is defined without a # for hex color. If RGB color is used, the dialog converts to hex color. But the style is being added inline as background-color: value without the hex so the color doesn't get rendered.

https://github.com/adobe/aem-core-wcm-components/blob/a07a9d54fb32e3a6219478b3313d68fa867f7862/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/Container.java#L70

**Comment by bpauli** [comment]
Hi @jfoxx, I tried to reproduce the issue with the latest SDK but was not able to reproduce it. 

In my case the color swatch is always using an rgb value which is added inline and working as expected. Can you please share your setup regarding AEM version and patch level? Thanks!

**Comment by jfoxx** [comment]
yes this is working now. I'm not sure what was going on before.  I was using HEX colors and it was stripping the # from the value.

**Comment by barani-ramakrishnan-ey** [comment]
@bpauli 
I am using aem sdk version (2022.10.9398.20221020T071514Z) and applied background color to the container. Still color is not applied to the container div.   
'#' is stripped out in the style. Same is occurred after removed the 'Swatches only' option.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/77850384/207951582-0ad1e920-056c-444a-a00e-7ed24d00eede.png">
