### ISSUE TITLE
Sorting of items in the ContentFragmentList component has stopped working

### ISSUE THREAD

**Issue by nikunjjariwala** [adobe/aem-core-wcm-components#2262]
The Order By and the Sort Order fields are not updating the order of the items in the ContentFragmentList (V2) component. 

Is this a known issue?

**Environment**
- AEM version and patch level ( AEM 6.5.13 )
- Core Components version (2.20.6)
- JRE version (Java 11)

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug

**Comment by royteeuwen** [comment]
@bpauli  this fix does not work for dates. When a content fragment model contains a date, the value is not available to sort on
