### ISSUE TITLE
[Image] AdaptiveImageServlet should serve SVGs as `Content-Disposition: attachment`

### ISSUE THREAD

**Issue by vladbailescu** [adobe/aem-core-wcm-components#2268]

**Comment by satishkumar-jadhav** [comment]
Thanks @vladbailescu.

I see the difference between line no. 701 and 704 and already URLEncoder.encode was being used at line 701 so just curious to know if any other changes being carried ?

![image](https://user-images.githubusercontent.com/24198568/188928284-23290805-c70d-4dba-875e-5ae92ec4cb6a.png)

**Comment by satishkumar-jadhav** [comment]
@vladbailescu  : Could you please help to update ?
