### ISSUE TITLE
WEBp not working in WKND Demo (Teaser Hero) 

### ISSUE THREAD

**Issue by frappierer** [adobe/aem-core-wcm-components#2275]
## Bug Report

**Current Behavior**
When activating Webp via the Core Components Image Policies it works in Chrome but not fully in IE11.
When taking a look at the network tab you see that the picture in the hero teaser does not have any parameters. (preferwebp is missing)
In the other components/pictures its working.

Network tab:
https://jmp.sh/5gVOjAS

Error on IE11:
https://jmp.sh/ooIldZ2

That leads to 

**Expected behavior/code**
That unsupported browsers will not show the webp versions.

**Environment**
- 2022.7.8144.20220729T033827Z-220700-PRERELEASE
- Core Components 2.20.8

**Possible Solution**
Check why the image in the teaser (hero Teaser style) that is placed in a carousel does not get the needed params, since in the other teasers it is working as expected.

**Comment by bpauli** [comment]
Hi @frappierer, I'm not able to reproduce this issue on my environment. Can you please try to update to the latest version of the WKND site and make sure the asset got synced to dynamicmedia? Please come back if this doesn't help. Thanks!

![image](https://user-images.githubusercontent.com/689884/188192160-2a6b3e94-d1c8-42a4-81c2-b44f3898bec2.png)
