### ISSUE TITLE
List Component child pages

### ISSUE THREAD

**Issue by udayvg** [adobe/aem-core-wcm-components#2279]
I can the child pages inclusion option/checkbox in the list component dialog. But I don't see this feature being implemented in the code. So, even if I enable child pages, the child pages are not being rendered on the page.

**Comment by bpauli** [comment]
@udayvg Can you please provide a screen recording of the issue? I'm not able to reproduce it. The child pages options work for me as expected in the list component. Thanks!

**Comment by bpauli** [comment]
@udayvg Can you please provide an update or can I close this issue? Thanks!

**Comment by udayvg** [comment]
Hi @bpauli,

Thanks for replying. You can close this issue.
I will check this once again in my AEM author.
