### ISSUE TITLE
[RTC][Architecture] Core Component Data Layer

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-core-wcm-components#228]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When working in the website analytics and target business, lots of data points should be measured and tracked in order to optimize the page or create an optimized experience for a visitor. At the moment these data points are not provided in a comprehensive way, so when you want to add tracking to the page, it must be thoroughly analyzed to extract the relevant data from the DOM; this is typically not a very reliable solution, as the DOM structure might change with every release.

**Describe the solution you'd like**
A CEDDL compliant datalayer allows the analytics consultant to access these data points directly (provided they are attached to the datalayer). For details regarding the datalayer see https://www.w3.org/2013/12/ceddl-201312.pdf.
The implementation should add the relevant Javascript objects (JSO) and prepopulate the datalayer as much as possible. The implementation should provide 2 extension points:
* a directly manipulation of the JSO via javascript (which should require no implementation at all, but rather only documentation)
* a "server-side" way to add data to the datalayer, which in turn creates proper javascript to manipulate the JSO.

**Scope**
This is just the basis for the datalayer itself and the relevant extension points. I would raise more issues to make individual components providing data to the datalayer.

**Are there alternatives?**
Nope!

**Documentation**
This is a feature which is not targetting end-users or authoring users directly, but helps Analytics or targeting folks to make their work easier. And please note, that this datalayer implementation is technology and vendor independent.

**Comment by bpauli** [comment]
@joerghoh, thank you for bringing up this feature request.

**Comment by vladbailescu** [comment]
Maybe something to consider for the future: https://www.ceddlbyexample.com/getting-started

**Comment by gabrielwalt** [comment]
(CQ-4256701)

**Comment by vladbailescu** [comment]
Initial proposal https://github.com/adobe/aem-core-wcm-components/pull/619

**Comment by janexner** [comment]
Might be better to be "EDDL", rather than CEDDL-compliant. CEDDL has not really been the success we all hoped for.
See https://jimalytics.com/tag-management/the-event-driven-data-layer/ for some info/opinion on EDDL

**Comment by gabrielwalt** [comment]
+1 to @janexner's comment:
* we shouldn't blindly follow the CEDDL spec where it is bloated.
* we should make the data layer event driven.

**Comment by ararat** [comment]
I think from experience with the implementation of https://github.com/araraty/aem-63-datalayer we need to have flexibility of 2 elements
1. the datalayer object format
2. Server side top of the page build vs allowing the components to inject to the DL as they render the page.
Top of the page seeding is good for some use cases but component might be affected when rendering thus need to indicate certain change.

**Comment by jckautzmann** [comment]
@gylesfohl hi, yes, this is being worked on in PR #949 .
