### ISSUE TITLE
Dynamic Media - Not working for Smart Crop

### ISSUE THREAD

**Issue by sowmyapp** [adobe/aem-core-wcm-components#2284]
**Current Behavior**
When we drag and drop Dynamic Media component in parsys, and edit the dialog we can see 'Viewer Preset' option selected for Preset type radio button by default. When we select 'Smart Crop' radio button and click Ok to save the changes and open the dialog again, we cant see Smart Crop change is reflected, its still showing the default 'Viewer Preset' as selected. Hence we are not able to use Smart Crop feature in Dynamic Media.

**Expected behavior/code**
When we change the selection of Preset type to Smart Crop, that change should persist. It should not show the default 'Viewer Preset' option as selected.

**Environment**
- AEM version and patch level with SDK 2022.7.8085.20220725T140323Z-220700
- Core Components version - 2.18
- JRE version - Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)

**Additional context / Screenshots**
Along with this we have another issue with image core v3 component. When we are using image component with DM enabled, and when Smart crop option is selected in dialog, we will get a renditions dropdown with the available renditions. When we select 'Auto' rendition, the image is not resizing or adapting to the selected device(desktop/mobile/tablet).
Thus image is showing the same rendition always for different devices or screen resolutions.
![dm-issue](https://user-images.githubusercontent.com/108067568/186878750-5da85b6e-4321-4977-b38a-a8d80d2c6aa6.png)

![image-issue](https://user-images.githubusercontent.com/108067568/186878828-3ea0f2a7-030e-4554-b6ea-663a03150958.png)

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug

**Comment by bpauli** [comment]
@sowmyapp The Dynamic Media component is not part of the core component project. Please reach out to customer support if you have an issue with this component.

The Auto SmartCrop functionality of the Image V3 component is currently broken and will be fixed in the next release https://github.com/adobe/aem-core-wcm-components/pull/2249

**Comment by sowmyapp** [comment]
Hi bpauli, thanks for the update. But I have tested with image v2 component as well and even its not working fine with Smart Crop Auto option selected.
Can you please let us know if we there is anything we can do for it.

Thanks,
Sowmya.
