### ISSUE TITLE
Veracode Findings - CWE-79 Cross-site scripting

### ISSUE THREAD

**Issue by satishkumar-jadhav** [adobe/aem-core-wcm-components#2290]
description=core.wcm.components.core is vulnerable to cross-site scripting. The vulnerability exists because the `stream` function of `AdaptiveImageServlet.java` does not properly encode the `imageName` attribute, allowing an attacker to inject and execute malicious javascript through the crafted SVG image.;

**Comment by vladbailescu** [comment]
This potential attack vector should be mitigated by #2268
