### ISSUE TITLE
[TOC] Improve exit condition for TableOfContentsFilter

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#2300]
During the analysis of the issue #2229  it was detected that the ToC Filter can be optimised. The filter should fist check if the ToC request attribute is available in the current request before doing anything else.

(SITES-6841)

**Comment by ky940819** [comment]
@jckautzmann, can you take a look at PR #2301 and see if that solves the issue you identified?

Kyle
