### ISSUE TITLE
[Content Fragment List] Order By not working

### ISSUE THREAD

**Issue by btaymaz** [adobe/aem-core-wcm-components#2309]
## Bug Report

**Current Behavior**
When you change "Order By" and "Sort Order" fields items order is not changing.

**Expected behavior/code**
Component should display content fragments based on selected order.

**Environment**
- N/A

**Possible Solution**
ContentFragmentListImpl generates this query:

`/jcr:root/content/dam/myapp/contacts//element(*, dam:Asset)[(jcr:content/data/@cq:model = '/conf/myapp/settings/dam/cfm/models/contact')] order by @firstName`

This should be something like this:

`/jcr:root/content/dam/myapp/contacts//element(*, dam:Asset)[(jcr:content/data/@cq:model = '/conf/myapp/settings/dam/cfm/models/contact')] order by jcr:content/data/master/@firstName`

**Additional context / Screenshots**
N/A

**Comment by btaymaz** [comment]
I think there is a design issue here. It is always pulling "Master" variant.

**Comment by bpauli** [comment]
@btaymaz This issue was fixed in https://github.com/adobe/aem-core-wcm-components/issues/2262 and the fix is part of the latest release (2.21.0)
