### ISSUE TITLE
Removing Page's Navigation Title Creates Blank Entry in Navigation Component

### ISSUE THREAD

**Issue by DigiLiviu** [adobe/aem-core-wcm-components#2316]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A page's entry in the nav component can be modified by changing its Navigation Title property. That being said, the navigation title is an optional field and, if not set, the page's entry in the nav will be created using the page's Title property. What we found was that if we set a Navigation Title, and then want to unset it to revert to using the page's Title as its entry in the nav component, we cannot. What ends up happening is that once we set and unset the Navigation Title, the page's entry is actually blank. It appears as though once we set and unset the Navigation Title, an empty navigationTitle property is left on the page's jcr:content node. That is interpreted as a purposeful blank Navigation Title instead of one that's been removed with the purpose of resetting to the page Title property.

**Describe the solution you'd like**
Adjust the rendering logic such that a blank navigationTitle property is interpreted as an non-existent navigationTitle that defaults back to the page title.

**Are there alternatives?**
The only alternative is to force someone to edit the page's properties manually via crx/de or vault, which is not an Authoring task.

**Documentation**
Should be mostly the same, just adjust so that an empty navigation title property is ignored altogether

**Comment by ky940819** [comment]
Hello, are you sure there isn't a whitespace character left in the dialog?
I tried to recreate this, but could not (unless I left a whitespace character). 

A potential option for resolving this (Caution, off the top of my head completely untested) is changing `PageListItemImpl#getTitle()` to the following:

```JAVA
public static String getTitle(@NotNull final Page page) {
    return Stream.<Supplier<String>>of(page::getNavigationTitle, page::getPageTitle, page::getTitle)
        .map(Supplier::get)
        .filter(StringUtils::isNotBlank)
        .findFirst()
        .orElseGet(page::getName);
}

````

This would not only filter out null titles, but also blank titles (empty string, or only whitespace strings), which would eliminate the ability for an author to (intentionally or unintentionally) force the list item to have no title by adding a whitespace character.

**Comment by ky940819** [comment]
> @ky940819 I think your proposal makes sense. Are you going to create a PR with your proposal? Thanks!

I will create a PR.

**Comment by DigiLiviu** [comment]
Thanks for looking into this @ky940819!
