### ISSUE TITLE
[Accessibility] Embed - Accessibility - all iFrames have the same name

### ISSUE THREAD

**Issue by GrimaceDoesA11y** [adobe/aem-core-wcm-components#2336]
## Bug Report

**Current Behavior**
When using the embed component, YouTube settings, the IFrame has a default aria-label with the value "Youtube Video".  If there are multiple videos on the page, they will all have the same name.

**Expected behavior/code**
Content Authors can provide the aria-label for each iFrame.
Code Example
<iframe data-cmp-data-layer="{"youtube-e5c1436307":{"@type":"core/wcm/components/embed/v1/embed/embeddable/youtube","repo:modifyDate":"2022-01-13T06:44:21Z","embeddableProperties":
{"youtubeVideoId":"o8kGdPkTero"}
}}" width="100%" height="390" src="https://www.youtube.com/embed/o8kGdPkTero?origin=https%3A%2F%2Fwww.mcdonalds.com&hl=en&mute=0&loop=0&rel=0&playsinline=1" frameborder="0" allowfullscreen allow="autoplay; fullscreen" aria-label="YouTube Video"></iframe> 

**Environment**
- AEM version and patch level (e.g. AEM 6.5)
- Core Components version Embed v2

**Possible Solution**

Allow content author the ability to change the name of iframes via aria-label.

**Additional context / Screenshots**

**Comment by gabrielwalt** [comment]
Created Jira issue SITES-9356
