### ISSUE TITLE
[Accordion] Adding new panels in the edit dialog works, but is not shown in the dialog until it is re-opened

### ISSUE THREAD

**Issue by AlexanderEggersDivae** [adobe/aem-core-wcm-components#2349]
### Expected Behaviour
When you add a new item to the accordion, such as Text, it should appear in the list of existing items at the bottom.
### Actual Behaviour
Adding a new item will visibly affect the active page under the edit dialog modal, but it will not be shown in the list. Closing and opening the dialog will show the panels accurately.

#### Steps to Reproduce
- Open any page in WKND project. 
- Add a wcm Accordion component
- Open edit dialog
- add new panel item

#### Platform and Version
Tested on 

- Local cloud jar v. 2022.9.8630.20220905T184657Z
- Adobe Cloud Platform v. 2022.9.8722.20220912T101352Z

#### Sample Code that illustrates the problem
Reproducible in WKND example project

**Comment by rajeevyadav2** [comment]
Team any update on this? This is impacting authoring experience.

**Comment by rinkle25** [comment]
Hi Team, By when this will get fixed? Authoring experience is getting hampered!

**Comment by vladbailescu** [comment]
This is the same issue as 2198 and should be fixed in Core Components 2.21.0+
