### ISSUE TITLE
Showing duplicate error messages in core content fragment component

### ISSUE THREAD

**Issue by Deepthi-Prapulla** [adobe/aem-core-wcm-components#2353]
## Showing duplicate error messages in core content fragment component

**Current Behavior**
Core Content Fragment Component(core/wcm/components/contentfragment/v1/contentfragment) is showing duplicate error messages.

**Steps to reproduce**

1. Go to the any page and add Core Content Fragment Component(core/wcm/components/contentfragment/v1/contentfragment) in it.
2. Select a content fragment path and choose display mode as "Single Text Element".
3. Click "Done" without selecting the element. The component will display validation message for Element field.
4. Now, change the fragment path and click "Done" without selecting Element. We could see that the validation message is getting appended again for Element field as in the below screenshot.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/116648645/197781596-de2f8c7c-d66c-4d85-8da9-a1244920ffae.png">

**Expected behavior/code**
Shouldn't display duplicate error messages.

**Environment**
- AEM version and patch level (AEM Cloud and aem-sdk-2022.9.8722.20220912T101352Z-220800)
- Core Components version (V1)
- JRE version (JDK 11.0.15`)

**Comment by bpauli** [comment]
SITES-8801
