### ISSUE TITLE
Pages not updated with components nested 3 deep in Container Component in Template Structure

### ISSUE THREAD

**Issue by DigiLiviu** [adobe/aem-core-wcm-components#2394]
## Bug Report

**Current Behavior**
When components are added to a Template's Structure in a Container Component that's nested in other Container Components at a depth of 3, existing pages created with that template will not receive the change.

**Expected behavior/code**
Regardless of the depth that a component is added at in a Template's Structure, existing pages created with that template should receive the update.

**Environment**
- AEM version and patch level - Latest AEMaaCS - 2022.10.9398.20221020T071514Z
- Core Components version - Latest in AEMaaCS: 2.20.8
- JRE version - Java(TM) SE Runtime Environment (build 11.0.13+10-LTS-370)

**Additional context / Screenshots**
This is reproducible with the WKND project as follows:
1. Open the page at /content/wknd/language-masters/en/adventures/ski-touring-mont-blanc
2. Edit its template at /conf/wknd/settings/wcm/templates/adventure-page-template/structure.html and make sure you're in the "Structure" mode.
3. Lock the main Container so that components may be added in it
4. Add an *unlocked* Button component to the bottom of the Container. 
5. Refresh the page we open in Step 1 and notice the Button component does show up
6. Return to the template and, under the Button we added, add another Container component and nest an unlocked Button in it.
7. Refresh again the page. Notice that this nested Button did not get added to the page.

** Additional Note **
This bug not occur when using the legacy container component at `wcm/foundation/components/responsivegrid`. To confirm:
1. Change the `sling:resourceType` property of the `/apps/wknd/components/container` component to `wcm/foundation/components/responsivegrid`
2. Refresh the page we've been working with and notice now that both buttons do show up.

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug
