### ISSUE TITLE
New version release request

### ISSUE THREAD

**Issue by senn** [adobe/aem-core-wcm-components#2438]
There is change in the PDF Viewer component (https://github.com/adobe/aem-core-wcm-components/commit/1b26afc95916af8b6152b49b99d2c766c18483b4) that we urgently require.

We are currently doing an implementation using the PDF Viewer but the old URL (documentcloud.adobe.com) is blocked by our internal firewall because it is a Personal Network Storage.

Best case scenario: fast release of new version so we can use official core components
Worst case scenario: we have to change the URL ourselves in our code

**Comment by adamzwoniarski** [comment]
+1
looking forward to seeing the clientdata dates fix too.
https://github.com/adobe/aem-core-wcm-components/pull/2386

**Comment by bpauli** [comment]
@senn , 2.22.0 has just been released.
