### ISSUE TITLE
Home/End and Left/Right arrow keys are not working as expected on Experience fragment - variation field

### ISSUE THREAD

**Issue by anushapaul91** [adobe/aem-core-wcm-components#2444]
## Bug Report

**Current Behavior**
Home/End and Left/Right arrow keys are not working as expected on experience fragment - variation field with latest SDK versions.
Reverse behavior observed. On click of End key, focus is going to start and on click of start, it is focused to end of variation path.
Same behavior on click of left and right arrows, left arrow is moving towards right and right towards the left.

**Expected behavior/code**
Home/End and Left/Right arrow keys  should behave as expected.

**Environment**
- AEM version : 2023.1.10675.20230113T110236Z-220900, 2023.1.10675.20230113T110236Z-220900-PRERELEASE, 2023.1.10912.20230130T173736Z-220900
- Core Components version: 2.21.2

**Possible Solution**

**Additional context / Screenshots**
Steps to replicate
1. Add "Experience Fragment (v2)" component from "Core Content" group to any page and author "Variation".
2.  Check the behavior on click of  left/right arrows or home/end keys

**Comment by bpauli** [comment]
This issue will be fixed within one of the next AEMaaCS releases.

Internal reference SITES-12465
