### ISSUE TITLE
Customizing model logic issue

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#246]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior and your setup; if applicable, proxy component pattern and component version.

**Expected behavior/code**

**Environment**
- AEM version and patch level (e.g. AEM 6.3 SP1 CFP2)
- Core Components version (e.g. 2.0.4)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
I am trying to follow "Customizing the Logic" section in https://helpx.adobe.com/experience-manager/core-components/using/customizing.html.

When trying to use resourcetype with @Via annotation, I am getting compilation error saying that this attribute is not supported. Can you please assist on how to resolve this issue.

**Comment by vladbailescu** [comment]
@rajeevyadav2 Thanks for reporting the issue, are you following the example at https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/wiki/Delegation-Pattern-for-Sling-Models ?

Can you please post your class?

The @Via annotation should be imported as `import org.apache.sling.models.annotations.Via;`

**Comment by richardhand** [comment]
@rajeevyadav2 - due to lack of activity we will close this question for now. If you have any feedback based on @vladbailescu's previous comment that could help in analysing your issue then just let us know.
