### ISSUE TITLE
Teaser component - 404 documentation link

### ISSUE THREAD

**Issue by sschnoor** [adobe/aem-core-wcm-components#248]
Please see this page, https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser.

The Documentation link at the bottom of the page is an invalid/404 GO url, https://www.adobe.com/go/aem_cmp_teaser_v1

**Comment by vladbailescu** [comment]
@sschnoor Thanks for reporting this issue. The GO url should redirect back to the teaser.
