### ISSUE TITLE
HTML ID Validation - The validator should not throw error when ID field is empty

### ISSUE THREAD

**Issue by yash5728** [adobe/aem-core-wcm-components#2522]
## Feature Request

**Is your feature request related to a problem? Please describe.**
For the HTML ID page property uniqueness validation, the validation is executed even when ID field is not authored with a value. Unfortunately, in a scenario where the source html has an empty ID attribute anywhere (not an ideal scenario as id should never be empty), still the validator throws error and properties cannot be saved.

**Describe the solution you'd like**
Add a check that if current authored value of the id field is empty, return without validation.

**Are there alternatives?**
N/A

**Documentation**
If you can, explain how users will be able to use this and possibly write out a version of the docs.
<img width="834" alt="image" src="https://github.com/adobe/aem-core-wcm-components/assets/26405570/77795785-bc35-4e5c-b887-a369472b680e">

**Comment by vladbailescu** [comment]
Possibly caused by #2278
