### ISSUE TITLE
Release 2.6.0 source code in zip is not able to open

### ISSUE THREAD

**Issue by v-licynthia** [adobe/aem-core-wcm-components#2525]
I've trying to view source code for version 2.6.0 and the link doesn't work for me. Please take a look and fix this. Thanks!

https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.6.0
source code.zip
https://github.com/adobe/aem-core-wcm-components/archive/refs/tags/core.wcm.components.reactor-2.6.0.zip

**Comment by vladbailescu** [comment]
Looks good to me 
![image](https://github.com/adobe/aem-core-wcm-components/assets/3670963/171d8c5e-b828-4f46-92ef-08179bc5f972)
