### ISSUE TITLE
Disable all image modification features for GIF images

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#258]
In case a GIF asset is referenced or being locally uploaded to the Core Image Component any image transformation being defined on that image is disregarded by the `AdaptiveImageServlet` (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/54f5c002db11f34f9561a5eff09afa3af05741d9/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java#L279) as always the original is spooled. 
Therefore it doesn't make sense to offer any transformation options in case a GIF has been choosen.

The `supportedMimeTypes` in https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/image/v2/image/_cq_editConfig.xml should be adjusted accordingly or alternatively the image transformation should be enabled for GIFs as well.

**Comment by richardhand** [comment]
+1 for adding this to the `supportedMimeTypes` given the lack of support for GIF transformations

**Comment by richardhand** [comment]
This was added with the merge of https://github.com/adobe/aem-core-wcm-components/pull/355 and is on master. It will be available in the upcoming [2.2.2](https://github.com/adobe/aem-core-wcm-components/milestone/9) release.
