### ISSUE TITLE
Trying to disable Adobe PDF icon while pdf is displayed in AEM. 

### ISSUE THREAD

**Issue by gogsfundas** [adobe/aem-core-wcm-components#2635]
I have tried to disable pdf icon while displaying PDF in AEM site. Whole content is getting loaded into iframe , once content is loaded its not possible to update / apply anything on icon. 
it simply inbuild inside iframe, 

connected to adobe support , following are comments 

After reviewing the latest screenshot you provided, it's clear that you are using the WCM core component PDF viewer and not a custom-created component.

I've had a discussion about this with one of our senior engineers and our internal team. We've confirmed that there is no configurable way to disable the link. 

Given this, one option you can try would be to contact the WCM Core Components ACS team directly for further assistance.
This is something that falls beyond the scope of our team's support capabilities. You can get in touch with them through their GitHub issues page, available at: [https://github.com/adobe/aem-core-wcm-components/issues](https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3136d149-454455534531-baf248073f6d007c&q=1&e=b24d55cd-d56a-480e-a03c-409e5d2ecc4c&u=https%3A%2F%2Fgithub.com%2Fadobe%2Faem-core-wcm-components%2Fissues).

![pdficon](https://github.com/adobe/aem-core-wcm-components/assets/57860867/4fcbc93d-839d-4047-81eb-e0ada6e2a0c1)
,
![ad_2](https://github.com/adobe/aem-core-wcm-components/assets/57860867/e1c2c286-f687-4462-8844-3c3e5c642e18)
![ad_1](https://github.com/adobe/aem-core-wcm-components/assets/57860867/6811d704-c6fb-411e-b5a3-18d42e1e6e32)

Looking for some solution to disable the icon or redirecting url  for this. 

Regards
Govind

**Comment by vladbailescu** [comment]
@gogsfundas , not really sure what you're trying to achieve. Looking at the description it seems you would like to remove the PDF logo/icon from the PDF Viewer embedded in the page (noted 1 in screenshot). However, the screenshots show the `cq:icon` property that is used for the component in the editor (noted 2 in screenshot).

![image](https://github.com/adobe/aem-core-wcm-components/assets/3670963/75b91c1f-6965-43fa-8128-538e7826a657)

The PDF Viewer component is a convenient wrapper for the Adobe PDF Embed API https://developer.adobe.com/document-services/apis/pdf-embed/ and will not alter the contents (as you noted, it's embedded as an iframe). There are some configurations that might be helpful though, most notably switching to `Sized Container` embed type:

![image](https://github.com/adobe/aem-core-wcm-components/assets/3670963/a51d4c48-5e16-4f96-be5d-4c5df4f2716e)

This will display a header-less document as shown in the examples at https://www.aemcomponents.dev/content/core-components-examples/library/core-content/pdf-viewer.html

![image](https://github.com/adobe/aem-core-wcm-components/assets/3670963/947d7b04-e6db-4b43-a0bd-7067d1c86c41)
