### ISSUE TITLE
[Package] core.wcm.components.all bundle install problem

### ISSUE THREAD

**Issue by MrPoofy** [adobe/aem-core-wcm-components#272]
## Bug Report

**Current Behavior**

If we try to install **core.wcm.components.all** and **core.wcm.components.extension** at the same time using maven, during installation the package for **core.wcm.components.all** deletes the bundle inserted by **core.wcm.components.extension** in the **"/apps/core/wcm/install"** folder and because of it, the **core.wcm.components.extension** doesn't get installed properly.

**Expected behavior/code**

Both **core.wcm.components.core-2.1.0.jar** and **core.wcm.components.extension.contentfragment.bundle-1.0.6.jar** should be available in the **/apps/core/wcm/install** folder for installation.

**Environment**

- AEM 6.4 SP1
- Core Components version 2.1.0
- Core Components Extension version 1.0.6
- JRE version 8

**Possible Solution**

In the package **core.wcm.components.all** the filter for the **/apps/core/wcm/install/** folder should be something like **/apps/core/wcm/install/core.wcm.components.core-2.1.0.jar** instead of **/apps/core/wcm/install/** like it is at the moment.

**Additional context / Screenshots**

Parent POM
```
<dependency>
    <groupId>com.adobe.cq</groupId>
    <artifactId>core.wcm.components.all</artifactId>
    <type>zip</type>
    <version>2.1.0</version>
</dependency>
<dependency>
    <groupId>com.adobe.cq</groupId>
    <artifactId>core.wcm.components.extension</artifactId>
    <version>1.0.6</version>
    <type>zip</type>
</dependency>
```

Apps POM
```
<plugin>
    <groupId>com.day.jcr.vault</groupId>
    <artifactId>content-package-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <filterSource>src/main/content/META-INF/vault/filter.xml</filterSource>
        <verbose>true</verbose>
        <failOnError>true</failOnError>
        <group>TestApp</group>
        <embeddeds>
            <embedded>
                <groupId>${project.groupId}</groupId>
                <artifactId>core</artifactId>
                <target>/apps/test/install</target>
            </embedded>
        </embeddeds>
        <subPackages>
            <subPackage>
                <groupId>com.adobe.cq</groupId>
                <artifactId>core.wcm.components.all</artifactId>
                <filter>true</filter>
            </subPackage>
            <subPackage>
                <groupId>com.adobe.cq</groupId>
                <artifactId>core.wcm.components.extension</artifactId>
                <filter>true</filter>
            </subPackage>
        </subPackages>
    </configuration>
</plugin>

...

<dependency>
    <groupId>com.adobe.cq</groupId>
    <artifactId>core.wcm.components.all</artifactId>
    <type>zip</type>
</dependency>

<dependency>
    <groupId>com.adobe.cq</groupId>
    <artifactId>core.wcm.components.extension</artifactId>
    <type>zip</type>
</dependency>
```

core.wcm.components.all Package Filters
![image](https://user-images.githubusercontent.com/645789/44519164-1fac8180-a6c4-11e8-950a-3d2ddc72e1a5.png)

Small console log from the build
```
A /apps
A /apps/.content.xml
A /apps/core
A /apps/core/wcm
A /apps/core/wcm/install
A /apps/core/wcm/install/core.wcm.components.core-2.1.0.jar
A /apps/core/wcm/install/core.wcm.components.extension.contentfragment.bundle-1.0.6.jar
- Aggregation status: 14 of 10 prepared, 12 collected
A META-INF/vault/definition/.content.xml
Collecting import information... 
Installing node types... 
Installing privileges... 
Importing content... 
D /apps/core/wcm/install/core.wcm.components.extension.contentfragment.bundle-1.0.6.jar
- /apps/core/wcm/install/core.wcm.components.core-2.1.0.jar
```

**Comment by kwin** [comment]
Please compare with #159

**Comment by godanny86** [comment]
+1 to this issue. Seems like core.wcm.components.extension should have a dependency on core.wcm.components.all so that it gets installed **after**?

**Comment by gabrielwalt** [comment]
The plan moving forward is to move the Content Fragment component out of the `extension` folder.
(CQ-4255686)

**Comment by richardhand** [comment]
This will be available in the upcoming [2.3.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/10).

**Comment by richardhand** [comment]
(CQ-4263071)

**Comment by msagolj** [comment]
Verified it works as intended in CQ-4263071
