### ISSUE TITLE
Tracking events intended for GTM datalayer are being intercepted

### ISSUE THREAD

**Issue by kelly-howard-rh** [adobe/aem-core-wcm-components#2736]
## Bug Report

**Current Behavior**
Tracking events sent to GTM datalayer are not being recorded. Many errors appear in the browser console: core.wcm.components.commons.datalayer.acdl.lc-bf921af342fd2c40139671dbf0920a1f-lc.min.js:54 The following item cannot be handled by the data layer because it does not have a valid format: {"0":"set","1":"url_passthrough","2":false}

The error is coming from the Adobe datalayer script. These events are intended to be pushed to the GTM dataLayer variable. They are being intercepted by the Adobe datalayer.

**Expected behavior/code**
Events should be pushed to the GTM datalayer and not invoke Adobe code. 

**Environment**
- 
AEM Version 2024.4.15977.20240418T174835Z
Core components 2.24.6

**Possible Solution**
We believe this is due to the new variable dataLayer being declared at the global level. It is overwriting the GTM dataLayer variable which existed before.
`     var dataLayer = window[dataLayerName] = window[dataLayerName] || [];`
https://github.com/adobe/aem-core-wcm-components/pull/2724/commits/27fda047ff40ca7f7be8889320b428bf5adc3e4c

Code that was calling `dataLayer.push()` was previously hitting the GTM dataLayer and is now being sent to the Adobe datalayer. Possible solution would be to change the name of this variable to something like `adobeDataLayer`.

**Additional context / Screenshots**
![image](https://github.com/adobe/aem-core-wcm-components/assets/97986370/68bfc018-9ad6-46ec-974b-8ded37b6dfcd)

**Comment by kelly-howard-rh** [comment]
@vladbailescu If you could take a look. Thank you!

**Comment by kelly-howard-rh** [comment]
Thank you @vladbailescu ! Do you know what the timing is for this getting put into an AEM release?

**Comment by vladbailescu** [comment]
Current plan is to include this in upcoming Core Components release (ETA: end of April) and include it in AEM 2024.5 release (ETA: end of May)

**Comment by kelly-howard-rh** [comment]
Thank you @vladbailescu for the quick attention to this issue!
