### ISSUE TITLE
With Dynamic Media enabled, all the component referencing core image dialog has some pre authored image src attribute

### ISSUE THREAD

**Issue by mmohta20** [adobe/aem-core-wcm-components#2791]
**Current Behavior**
With Dynamic Media enabled, all the component referencing core image dialog has some pre configured image src attribute having below value.
**https://undefined/adobe/dynamicmedia/deliver?width=320&preferwebp=true**

**Expected behavior/code**
Src attribute should not be pre configured with broken image path.

**Environment**
- AEM Cloud( aem-sdk-2024.06.16647.20240607T103723Z-240500 )
- Core Components version 2.25.4
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Additional context / Screenshots**
<img width="253" alt="image" src="https://github.com/adobe/aem-core-wcm-components/assets/43404187/a2ec09c7-b779-4579-8259-7d5257e78e8e">

**Comment by mohiaror** [comment]
The fix for this goes into AEM specific content package and not core components. It has been fixed and should be part of next sites rotary release sometime in August.
