### ISSUE TITLE
Sources and Javadocs not available for Core Components

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#314]
Since release 2.0.4 sources should be published to the Adobe Maven Repository (#116).

But this does not longer work - no source or javadocs available e.g. for release 2.1.0:
https://repo.adobe.com/nexus/content/groups/public/com/adobe/cq/core.wcm.components.core/2.1.0/

For older releases the source jars are listed:
https://repo.adobe.com/nexus/content/groups/public/com/adobe/cq/core.wcm.components.core/2.0.8/

But when trying to download this old source jar only HTTP 404 is returned:
https://repo.adobe.com/nexus/content/groups/public/com/adobe/cq/core.wcm.components.core/2.0.8/core.wcm.components.core-2.0.8-sources.jar

Is this a misconfiguration in the artifact repository, or are the source and javadoc JARs missing?

Please make them available again, this is very important when developing projects using core components.

**Comment by vladbailescu** [comment]
@stefanseifert, we changed the way artifacts are deployed. We are now deploying to Bintray and Adobe Nexus proxies and caches the artifacts. As you can see at https://bintray.com/ref-squad/releases/aem-core-wcm-components#files/com%2Fadobe%2Fcq%2Fcore.wcm.components.core%2F2.1.0 they should be cached in Nexus too.

**Comment by stefanseifert** [comment]
that means we should use https://dl.bintray.com/ref-squad/releases as official maven repository URL for downloading core component artifacts?

the source jars are not available on https://repo.adobe.com/nexus/ (see above)

**Comment by vladbailescu** [comment]
The proxy was fixed and sources and javadocs should be available for download from `repo.adobe.com`.
