### ISSUE TITLE
[ContentFragment] Provide a list component for content fragments

### ISSUE THREAD

**Issue by philipmundt** [adobe/aem-core-wcm-components#340]
## Feature Request

Enable Core List Component to support Content Fragments, or create a separate Content Fragment List Component - to support the use case of gathering multiple content fragments in a component, by folder, or by tag, and delivered against single URL, HTML or JSON.

> As an author, I want to define a list of Content Fragments, so that they can be consumed by my App.

> As a front-end developer, I want to consume the authored list of Content Fragments as JSON, so that I can display them in my App.

The resulting output should be consistent with the already existing single content fragment component, the JSON that is output should be compatible. Ideally, code and API should be re-used.

**Comment by olimination** [comment]
I'm not sure, if I have understood the Asset Collection idea correctly, but would it be an option to use the "Asset Collection" feature? So we could simply point to some Asset Collection and this would load then the associated  content fragment assets?

**Comment by gabrielwalt** [comment]
Great idea @olimination, to pointing to an Asset Collection would be a very meaningful way to define and manage a list, I like it! For now, I don't think that this has been implemented yet, but let's keep this in mind for future list capabilities.

**Comment by jckautzmann** [comment]
The content fragment list component is now part of the Core Components:
https://github.com/adobe/aem-core-wcm-components/pull/502
