### ISSUE TITLE
[Carousel] Only one carousel allowed per page?

### ISSUE THREAD

**Issue by DorianDevelops** [adobe/aem-core-wcm-components#343]
When adding multiple carousel components to the page only the first carousel works. Is there a setting or known solution for this?

**Comment by msagolj** [comment]
Hi,

It has been tested and it works. Did you follow all the instructions mentioned [here](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel#enabling-carousel-editing-functionality) ?

you might also check #341 for some more info on what you might be missing.

Closing for now. If you still have the problem please create a new issue with details about your environment and steps to reproduce.

**Comment by DorianDevelops** [comment]
Hi @msagolj 

Thank you for the quick response! I am a bit confused on where to add the javascript data attribute bindings for the proxy component that I created. 

Do proxy components that require these bindings like the carousel and tabs need their own html and javascript files? 

Shouldn't it be referencing the resouceSuperType html and js if I don't provide any for the proxy component?

The tab and carousel components work when in edit and preview mode but when I view as published only the first component added to the page functions as expected. 

I also have no console errors when clicking the non-functioning tab and non-functioning carousel components.

I am working a fresh brand new instance of AEM 6.4.2 using Maven archetype 13 with core components 2.2.0 to reproduce add two carousel or two tabs components to the same page.

**Comment by richardhand** [comment]
@DorianDevelops - thanks for the report, we retested and found an issue related to a JS console error for a missing `Granite` global object in both the tabs and carousel. Do you see this console error?

**Comment by DorianDevelops** [comment]
Yes same error is present in my console. Forgot to mention that sorry. No errors on any event listeners.
![screen shot 2018-10-25 at 8 59 43 am](https://user-images.githubusercontent.com/21271869/47514967-7a826680-d836-11e8-993a-51d6a4eb2870.png)

Also other issues I've discovered when playing around with tabs and carousels on the the same page that are probably related.

- Drop a carousel and a tabs component on the page. The tabs component doesn't render when viewed as publish but the carousel does. Order of the components doesn't seem to affect which renders carousel seems to take precedence.

- Add a carousel as a nested tab item and the tab component only renders the tab titles but none of the items in the tabs. 

![screen shot 2018-10-25 at 9 32 54 am](https://user-images.githubusercontent.com/21271869/47515948-fed5e900-d838-11e8-9395-c7cf1d3c4ed6.png)

**Comment by richardhand** [comment]
@DorianDevelops - It seems that the others issues you reported are related to the same console error. It would be useful for us to know if the fix on the development branch at [0] fixes all of these. Would you be able to apply the fix and let us know? Can either be done via a build of the content package on the development branch [0] or by directly applying the fix to the site clientlibs for the Carousel / Tabs.

[0] - https://github.com/adobe/aem-core-wcm-components/tree/master/content
[1] - https://github.com/adobe/aem-core-wcm-components/commit/49de0fd53f8c4b2ef9d8a06c3156ff65e01e6f8c.patch

**Comment by richardhand** [comment]
This was added with the merge of #347 and is on master. It will be available in the upcoming [2.2.2 release](https://github.com/adobe/aem-core-wcm-components/milestone/9).
