### ISSUE TITLE
[Teaser] Call-To-Action not working

### ISSUE THREAD

**Issue by Evecreate** [adobe/aem-core-wcm-components#351]
**Description**
Using the teaser component (core/wcm/components/teaser/v1/teaser) as resourceSuperType, we have extended it with our own image component the rest we have kept the same. 

The issue we are facing is that the out-of-the-box Call-to-actions don't work for us. Any value we are filling into the dialog inside the "link" is not stored when we save the settings. The "label" of the link is being saved.

**What have tried?**
- Just extending the teaser component without any customisation and we are still getting this error.
- Adding the value directly into the CRXDE and the checking the value in the dialog and saving removes the value filled in.

**AEM version**
AEM 6.3.2.2 + Core Components 2.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/9678081/47657714-dda32e80-db91-11e8-9fe5-331f80670baf.png)

![image](https://user-images.githubusercontent.com/9678081/47657660-c19f8d00-db91-11e8-9e9c-a1aa6baaa40b.png)

**Comment by msagolj** [comment]
Hi @Evecreate ,

I was not able to reproduce your issue. What I did:
- Install AEM 6.3.0 + SP 2 + CFP 2 
- used [maven project archetype 15](https://github.com/Adobe-Marketing-Cloud/aem-project-archetype) to get teaser proxy 

I was able to add CTA's :
![teaserctas](https://user-images.githubusercontent.com/37147400/47710510-35de3d00-dc33-11e8-8632-a6d6d847786b.png)

I tested with Core Comp 2.1.0 and the latest 2.2.0 release. Can you maybe try with the latest archetype 15 (which also uses Core Comp 2.2.0 and has a teaser proxy) ?

**Comment by Evecreate** [comment]
Hi, I have it now working with the latest Core Components package so it doesn't work in 2.1.0 but it does work in 2.2.0
