### ISSUE TITLE
[Page] Allow Sling Model to export a hierarchy of child pages

### ISSUE THREAD

**Issue by pfauchere** [adobe/aem-core-wcm-components#352]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The SPA Editor SDK is a use case where we need to export a hierarchy of page models and their content - all at once.

**Describe the solution you'd like**
A configurable way to design the structure of an exported hierarchy of pages

**Are there alternatives?**
Calling all the page models individually

**Documentation**
The implementation is an extension of the current Page functionalities.

**Comment by gabrielwalt** [comment]
Closing this for now as there hasn't been activity on this for a long time.
