### ISSUE TITLE
Enhance Page Component to better support Experience Fragments

### ISSUE THREAD

**Issue by sixtrojans** [adobe/aem-core-wcm-components#357]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We re-use our content across many websites (some AEM, some third party) and mobile apps, so we are becoming heavy adopters of Experience Fragments for our articles. It’s important for the featured image, title and content tags to be part of the experience fragment so that they are available with the fragment. 

Unfortunately, every time an experience fragment gets reused on a new AEM page, the author has to manually add the title, featured image and tags. It's also challenging when we want to update the featured image or tags on an Experience Fragment because the individual pages using the fragment need to be manually updated as well.

**Describe the solution you'd like**
Please enhance the Page Component so that the title, featured image and content tags can be automatically synced from an experience fragment. 

This functionality could be similar to the dialog box on the teaser component which allows an author to tell the teaser component to fetch the title, description and image from a linked page. In the same way, the Page Component could be enhanced so that:

1. an author can associate a specific experience fragment with the page
2. if a primary experience fragment has been specified, the title, featured image and content tags would be pulled from the experience fragment and kept in sync with the fragment
3. an author can override the title, featured image and content tags as needed by unchecking the select box (just like they can with the teaser component)

**Drawback**
This may also require an enhancement to Experience Fragments so that a featured image can be set on the Experience Fragment page properties.

**Comment by gabrielwalt** [comment]
Hi @sixtrojans, thanks for your feature request. This would be out of scope for the main purpose of the Core Components, because this is a more specific use-case and we'd like to keep the components focused on the more common use-cases to avoid them becoming too complex.
However, since the components are open source, you can easily extend them in your project to add such a capability.
