### ISSUE TITLE
Teaser version 2.2.0

### ISSUE THREAD

**Issue by salman18j** [adobe/aem-core-wcm-components#371]
## Bug Report

**Current Behavior**
I am trying to use teaser component. 

**Expected behavior/code**
I am not able to see image on the teaser after configuring it.

**Environment**
- AEM version 6.4 service pack 2
- Core Components version 2.2.0
- JRE version 1.8

**Comment by vladbailescu** [comment]
@salman18j did you also setup the `imageDelegate` as documented at https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser#extending-the-teaser-component ?

https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/blob/master/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/teaser/.content.xml is a good example of how to do it.

**Comment by salman18j** [comment]
It works. Thanks for the quick reply.

**Comment by vladbailescu** [comment]
Glad to hear that!
