### ISSUE TITLE
[Content Fragment] 1.0.8 unresolved depndencies with AEM 6.3.3.0

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-core-wcm-components#389]
## Bug Report

**Current Behavior**
core.wcm.components.extension-1.0.8 Structured Content Fragment Bundle is in an installed state on AEM 6.3 + SP3 

`org.apache.commons.lang,version=[2.6,3) -- Cannot be resolved`

![image](https://user-images.githubusercontent.com/8974514/48811288-12228a00-ecfb-11e8-962a-bf8129104242.png)

**Expected behavior/code**
The release notes indicate 1.0.8 should work for AEM 6.3 + SP3

**Environment**
- AEM 6.3 + SP 3
- Content Fragment Extension 1.0.8
- JRE 1.8

**Comment by gabrielwalt** [comment]
Thanks for reporting this, we'll take a look at it.
(CQ-4257844)

**Comment by richardhand** [comment]
This was added with the merge of #391 and is on master. It will be available in the upcoming [2.2.2 release](https://github.com/adobe/aem-core-wcm-components/milestone/9).
