### ISSUE TITLE
Supported browser documentation

### ISSUE THREAD

**Issue by mateuszluczak** [adobe/aem-core-wcm-components#401]
Hi,

I really like the [Guidelines](https://github.com/adobe/aem-core-wcm-components/blob/master/Guidelines.md) checklist you have provided for the components.
I understand it's stated on the top of the file that it's "Work in progress", but I am missing key information about the browser support for site-oriented components functionality - Javascript and CSS (considering I've seen some newer APIs like `flexbox` being used).

I've looked also [here](https://helpx.adobe.com/experience-manager/core-components/user-guide.html) and found nothing. Can the documentation of the supported browsers be found somewhere else?

Thanks

**Comment by richardhand** [comment]
Hi @mateuszluczak thanks for your question! You're right that documentation of the sites client library browser support is missing in the project, we definitely plan to add this list. For now, it matches that of the AEM 6.3 authoring technical requirements [0]. In other words, we continue to support IE11. 

If you find any issues for newer features on a supported browser (e.g. flexbox on IE11, which definitely has potential quirks) then do let us know.

[0] - (https://helpx.adobe.com/experience-manager/6-3/sites/deploying/using/technical-requirements.html#SupportedBrowsersforAuthoringUserInterface)

**Comment by richardhand** [comment]
Tracked in https://github.com/adobe/aem-core-wcm-components/issues/403
