### ISSUE TITLE
Image Component throws an error after configuring widths

### ISSUE THREAD

**Issue by ravisurampudi** [adobe/aem-core-wcm-components#402]
I am using core components version 2.2.0 along with AEM 6.4.2 and am using both an extended image component and also We Retail Image component on a test website and am unable to load the image once widths are configured and am getting the following errors

![screen shot 2018-12-04 at 5 37 26 pm](https://user-images.githubusercontent.com/6342174/49484283-5463c500-f7eb-11e8-9a75-3b551a4af3a8.png)

My design dialog configuration is here

![screen shot 2018-12-04 at 5 38 38 pm](https://user-images.githubusercontent.com/6342174/49484321-752c1a80-f7eb-11e8-8ce5-298d0ebe8d5f.png)

I have followed all the steps that have been given in the documentation and have customlibs defined in my page component

![screen shot 2018-12-04 at 5 39 42 pm](https://user-images.githubusercontent.com/6342174/49484364-9db41480-f7eb-11e8-9c77-8ee5b78b1282.png)

Expected Behavior - Image should be rendered on my screen.

**Comment by vladbailescu** [comment]
@ravisurampudi , I cannot reproduce this issue. Since you seem to have a customised design dialog, are you sure you're populating the widths correctly in the policy?

Also, could you please check `error.log` for any related errors in the `AdaptiveImageServlet`?

**Comment by ravisurampudi** [comment]
@vladbailescu : Sorry for the confusion but i can confirm i do not have a customized design dialog.

Not sure what you meant by populating widths according to policy, I'm trying to follow the docs example and added widths to the design dialog as explained in the example.

Here is what I see in the error.log

When i set the image quality to 82 - I get the error

 GET /content/grid-demo/test2/_jcr_content/contentPar/core_image.coreimg.82.1024.jpeg/1544118146654.jpeg HTTP/1.1] com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServlet There's no content policy defined and the request provides a width selector (1024).

When I set the image quality to any number say 90 or 100 I get the following error

GET /content/grid-demo/test2/_jcr_content/contentPar/core_image.coreimg.90.1024.jpeg/1544118146654.jpeg HTTP/1.1] com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServlet The requested quality (90) is not allowed by the content policy.

Is there any specific configuration that i need to create to set this policy?

**Comment by ravisurampudi** [comment]
Closing this issue as i managed to set the content policies in the template configuration. Thanks
