### ISSUE TITLE
Prevent form and link from being emitted via the text component

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#404]
## Feature Request

The text component from https://github.com/adobe/aem-core-wcm-components/blob/cab65ccdd9fe6e94c9d36c1b306c987318e25787/content/src/content/jcr_root/apps/core/wcm/components/text/v2/text/text.html#L21. can be used from an editor to forge a login form which posts sensitive credentials from the end user to a malicious third party server

Although the rich text editing provides a lot functionalities at least `<link>` and `<form>` elements should not be given out even if the editor somehow managed to fill the underlying repository property with it. Unfortunately the HTL display context "html" does not prevent those from being emitted. So this may require additional escaping in a dedicated model.

**Comment by kwin** [comment]
Well, in this case the malicious person is indeed an editor (with according right on the repo). To make it as hard as possible to inject malicious code here (which is not detected during the reviews or the malicious editor had the right to publish directly).
IMHO it shouldn't be necessary for the rich text editor component to emit `link` and `form` tags. So those should be filtered out by some code.

The problem is that such a context is not yet defined by HTL, i.e. in this case it needs to be application specific. Or alternatively the AntiSamy rules leveraged by https://github.com/apache/sling-org-apache-sling-xss/blob/4434f309306116f674d682568be62de977ab25aa/src/main/java/org/apache/sling/xss/XSSAPI.java#L237 should be tightened.

**Comment by gabrielwalt** [comment]
Hi @kwin, I think that this is not a Core Component issue, and not even an HTL issue, but maybe an issue of the default AntiSamy policy rules. As documented [1], HTL's `context='html'` is applying the configured AntiSamy policy rules [2] that can be found at: `/libs/cq/xssprotection/config.xml`.

I'll close this issue for now, but please reopen it if what I described doesn't address the issue in a sufficient manner.

[1] https://docs.adobe.com/content/help/en/experience-manager-htl/using/htl/expression-language.html#display-context
[2] https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/security.html
