### ISSUE TITLE
[Content Fragment] GetParagraphs doesn't handle element attributes

### ISSUE THREAD

**Issue by tyge68** [adobe/aem-core-wcm-components#406]
If you apply styles to your paragraph, it won't be detected anymore as paragraph, thus the inbetween content will not be displayed as expected (in between)

It is simply due to the current implementation that only split on exact match "p", "h1" tags etc...

Instead it should allow attributes, so maybe parsing the html would be cleaner.

**Comment by tyge68** [comment]
@vladbailescu this is a bug not an enhancement

**Comment by andreeadracea** [comment]
(CQ-4259368)

**Comment by richardhand** [comment]
@tyge68 - do you have an update on this, are we still blocked? The original PR at https://github.com/adobe/aem-core-wcm-components/pull/414 was closed as the content fragment component moved location - do you plan to create a new PR in the near future? If not, I think we can move this one to `ice box` until it is ready to be worked on again.

**Comment by gabrielwalt** [comment]
Closing this for now as there's not activity on this since over 1 year.
Internally, this is also tracked via CQ-4259368.
