### ISSUE TITLE
Allow Authors to Select a Background Image

### ISSUE THREAD

**Issue by JasonUSC** [adobe/aem-core-wcm-components#413]
## Feature Request

**Is your feature request related to a problem? Please describe.**
While the style system is extremely powerful, we are encountering problems with core component adoption because authors cannot select background images.

**Describe the solution you'd like**
As an author, I need to be able to select a background image on more components than just the teaser component.

As a template author, I need to be able to enable/disable styles on components that include author-selectable background images.

As a front-end developer, I need to be able design parts of my page where an author can select a background image from Assets.

As an AEM developer, I need an out-of-the box solution for author-selectable background images.

**Are there alternatives?**
One solution would be to make the background image dialog from the teaser component available to the other components as an option controlled by template authors. This might be the quickest way to get the feature out to the community.

Another solution would be to include a background image dialog on the upcoming container component. Be sure to let template authors control whether or not to allow authors to add a background image. If this alternative is chosen, please move the container component up in the priority list. (The container component sounds really helpful!)

**Comment by andreeadracea** [comment]
@JasonUSC, thanks for bringing up this request. I've created a RTC in our backlog for this feature request and I linked your issue to it. 
https://github.com/adobe/aem-core-wcm-components/issues/415

**Comment by richardhand** [comment]
@JasonUSC, background images are available in the newly released [Container component](https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/container/v1/container), I believe that solves this issue. Please re-open if you see something missing.
