### ISSUE TITLE
[RTC] Container Component

### ISSUE THREAD

**Issue by andreeadracea** [adobe/aem-core-wcm-components#415]
**[Request To Comment]** To anybody who intends to use the Core Components, please provide your feedback about the following requirements. We want to make sure that we build a component that fits your needs, so don't hesitate to tell us how that component should work, so that you will be able to use it.

## User Story
As a page or template author, I need a component that allows me to select an image as background.

## Acceptance criteria
* Edit dialog
      * Asset picker for choosing the image for the background
      * Take the image from DAM, or allow it to be uploaded from the local file system to the component instance
* List child nodes 
* Set an image as background

**Comment by andreeadracea** [comment]
Feature request: Container Component #413

**Comment by JasonUSC** [comment]
1) From the roadmap backlog, these elements would be important to include as well:

- unified parsys
- optional responsive layout
- optional content inheritance

2) I could also see there being scenarios where we would want to group components together inside a container component and just apply a style (e.g., a background color or a border) to the container.

3) It might be helpful if the template author and/or page author could assign an html id to the container... that would come in handy for example when we need a hook for Target.

**Comment by JasonUSC** [comment]
Can we get an update on the timing for when this component might be released?

**Comment by JasonUSC** [comment]
I have a follow-up question about the container component listed on the roadmap... would this essentially be a replacement for the old foundations responsive grid component?  @andreeadracea @gabrielwalt

**Comment by abhishekagg19** [comment]
It would be good to add following capabilities as well:
1. Allow setting of background color using color picker
2. Default inclusion of following styles - dark/light theme
