### ISSUE TITLE
Teaser Component alt

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#422]
## Bug Report

**Current Behavior**
In Teaser component, provide option to set Alt & Title attribute on Image.
**Expected behavior/code**
As SEO best practice, we should have ALT attribute on image. Currently in Teaser  component when authoring image using dialog, there is no option available for setting up the Alt text. 

**Environment**
- AEM version and patch level - AEM 6.3 SP3
- Core Components version - 2.2.2
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by msagolj** [comment]
The current implementation is extracting the title and description from the selected DAM asset and adding it to the image alt (using DAM description) and title (using DAM title) attributes. 

If the DAM asset is missing the data you can simply click the edit button underneath the image in the dialog to add the missing information in the properties of the DAM asset.

Hope this solves your needs :) closing issue for now.

**Comment by rajeevyadav2** [comment]
Makes Sense. Thank you for prompt response. 👍
