### ISSUE TITLE
Allow deployment when the commerce APIs are not present

### ISSUE THREAD

**Issue by rombert** [adobe/aem-core-wcm-components#423]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The core components bundle currently has a hard requirement for the commerce APIs. There are circumstances where the commerce APIs are not available but it is desirable to deploy the core components.

**Describe the solution you'd like**
One option is to split out the bundle so that there would be both a 'main' and a 'commerce' bundle. This way deployments without commerce APIs can still work.

**Are there alternatives?**
Making the commerce imports optional can also work, but this leads to less-cohesive bundles.

**Documentation**
Documentation should be updated to clarifty that commerce-related classes are now in a separate bundle.

**Comment by bpauli** [comment]
@rombert the provided PR makes the import of the commerce API optional. Moving the sharing component in a separate bundle and to the extensions would be a cleaner solution but this can not be done in a break backward compatible way.

**Comment by rombert** [comment]
That works for me, thanks @bpauli !
