### ISSUE TITLE
[Search] Minimum term isn't configurable for an embedded component

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#427]
from @tim-merrillcorp via #426

When the core search component is embedded in the header, there isn't a way to update the Search Term Minimum Length from the default of 3. (We have Chinese customers who only need to type 2 characters for a search.)

We are on AEM 6.4, service package 6.4.2. Core Components version 2.0.4.

**Comment by richardhand** [comment]
@tim-merillcorp, would it be possible to provide a code example, or more detail as to how you are embedding the search component? 

The minimum search term is typically configurable from the component policy dialog in the template editor. If you have a policy in your content with the correct configuration, and it is mapped to your search component, even if the embedded component doesn't have an associated/accessible dialog in editing, the configuration should be applied.

We should be able to help with a little more information.

**Comment by tim-merrillcorp** [comment]
Thanks for getting back with me Richard. I'll look into adding a policy - sounds like that should do the trick.

**Comment by richardhand** [comment]
@tim-merrillcorp if you do have some success let us know and we can close this issue.

**Comment by gabrielwalt** [comment]
Assuming that this did the trick and closing this issue
