### ISSUE TITLE
Page Design Dialog missing for page component v1

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#428]
## Bug Report

**Current Behavior**

When a Template based on `/apps/core/wcm/components/page/v1/page` is edited in the template editor, it should show a "Page Design" entry in the menu of the template editor.

This works fine for `/apps/core/wcm/components/page/v2/page` and did work fine for `/apps/core/wcm/components/page/v1/page` as well before the commits of #114 - where the page design dialog was deleted for the v1 component. Without this dialog the "Page Design" entry is not available.

This is a problem e.g. when using https://adobe-marketing-cloud.github.io/asset-share-commons/ together with are core components version > 2.0.0.

**Expected behavior/code**

The "Page Design" features should also work for pages based on `/apps/core/wcm/components/page/v1/page`.

**Environment**
- AEM 6.3 SP3
- Core Components 2.2.2
- Java 8

**Possible Solution**

Add back the cq:design_dialog node deleted in https://github.com/adobe/aem-core-wcm-components/commit/57757061244b0721dd6a9a9674c0533fcc726912

**Comment by msagolj** [comment]
(CQ-4268676)

**Comment by richardhand** [comment]
This fix is available on the master branch and will be included in the upcoming [2.4.0](https://github.com/adobe/aem-core-wcm-components/milestone/11) release.
