### ISSUE TITLE
[Teaser] UOE is thrown during json serialization

### ISSUE THREAD

**Issue by pfauchere** [adobe/aem-core-wcm-components#431]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior and your setup; if applicable, proxy component pattern and component version.

When serialized by a tool like Jackson, the anonymous `ListItem` class used in the `getActions` function of the `TeaserImpl` class [0] doesn't implement all the default functions resulting in a UOE when automatically serialized.

[0] https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/TeaserImpl.java#L192
[1] https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/ListItem.java#L95

**Expected behavior/code**

An implementation that can be serialized

**Environment**
- AEM version and patch level (e.g. AEM 6.3 SP1 CFP2)
- Core Components version (e.g. 2.0.4)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Possible Solution**

- Implement the missing and mandatory functions
- Create and use a simpler class with a subset of fields that the `ListItem`class contains if you only need a few of the mandatory fields
- Have some function not mandatory by removing the Exception from the `ListItem` interface

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

The issue has been discovered while using the delegation pattern to extend the Teaser component.
A non-scalable workaround, at the project level, is to use a custom Jackson serializer on the `getActions` function.

**Comment by msagolj** [comment]
Created CQ-4263008

**Comment by jckautzmann** [comment]
Fixed in:
https://github.com/adobe/aem-core-wcm-components/pull/829

**Comment by andreeadracea** [comment]
Verified and it works as expected.

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
