### ISSUE TITLE
Unable to use Carousel v1

### ISSUE THREAD

**Issue by saulovenancio** [adobe/aem-core-wcm-components#434]
I cant use the Carousel after follow the instruction in the repo.
I have 6.4 , installed SP2 as requested for Core Cmpnts package 2.2.2 and installed the core cmpnts package but it didnt work. Nothing shows in the page.
I  then added a sample p paragraph in the carousel.html, and it showed. But when trying to edit it, I am not able to add slides. (when clicking Add)

![image](https://user-images.githubusercontent.com/493328/52060190-dace2600-2552-11e9-84ae-df48b8c695ac.png)

Please advise.

## Bug Report

**Current Behavior**
Carousel dont work.
**Expected behavior/code**
Carousel should work

**Environment**
AEM 6.4.2
Core Components version 2.2.2
Java 8

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by msagolj** [comment]
@saulovenancio looks like the same as #341. You probably forgot to follow the instructions mentioned in the readme for the carousel about [Enabling Carousel Editing Functionality](https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel#enabling-carousel-editing-functionality).

**Comment by saulovenancio** [comment]
Ok. Thanks for information.
