### ISSUE TITLE
[Content Fragment] Ability to reuse fields from content fragment in components

### ISSUE THREAD

**Issue by Lovivan** [adobe/aem-core-wcm-components#437]
## Feature Request

**Is your feature request related to a problem? Please describe.**
With content fragment models, structured content fragments can be created. Ideally you can reuse these content fragment in components and even better select which fields of the content fragment to reuse in which property of your component.

**Describe the solution you'd like**
Ideally you can reference a content fragment in a component dialog and reference properties in the dialog to data fields in the content fragment from a specific variation. This would also allow not to reference all properties of a component. You could compare this to providing some sort of mapping.

**Are there alternatives?**
None

**Documentation**
Idea is not final yet

**Comment by Lovivan** [comment]
Yes,

That’s exactly the feature i am talking about. Same could be implemented for a text-image component. Where you either can reference text, image, none or both from a data field in a structured content fragment.

This would enlarge the content re-use in components

**Comment by gabrielwalt** [comment]
I'm closing this for now as we won't have bandwidth to address this within foreseeable future.
