### ISSUE TITLE
[Form Container] Add ability to configure the method from the dialog

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#448]
There is currently no possibility to configure the method in the Form Container component. While this is configurable via the component `./method` property, it isn't available from the dialog.

PR: https://github.com/adobe/aem-core-wcm-components/pull/447

**Comment by brandonmaynard** [comment]
@gabrielwalt, I am going to close the PR. I agree with you, an author shouldn't be making this decision.
