### ISSUE TITLE
[Text] Flickering for the long list of styles/paragraph formats

### ISSUE THREAD

**Issue by SRK2019** [adobe/aem-core-wcm-components#451]
Hey Guys,

After upgrading to 2.2.2 or 2.3.0 we have observed that text component is continuously flickering for long list of styles. Add styles/paragraph formats more than the screen size and when you scroll down then text component continuously flickering. Please let us know if anyone is facing the same issue and fix for it.

**Comment by richardhand** [comment]
Hi @SRK2019, I moved the second issue to #452.

For this issue could you please provide more information (screenshots / videos) as to where you are seeing the flickering. Is the flickering seen when editing the text component inline on the page or via the dialog.

**Comment by SRK2019** [comment]
Hi @richardhand : You can see https://youtu.be/AMudhCUCN5U video to see flickering behavior. We are using  AEM 6.4.3 + Core 2.30.  If we add more styles or para formats than the screen size then we can see the issue. We are seeing this issue in both inline and full screen mode.

**Comment by msagolj** [comment]
This is actually not an issue of the Core Components but the Rich Text Editor  (RTE) plugin provided by AEM. So please contact the official Adobe support channels so you will be able to track its resolution.

https://helpx.adobe.com/contact/enterprise-support.ec.html
