### ISSUE TITLE
[Text] JQuery Validator warning when opening text component dialog

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#452]
from @SRK2019:

Also i have seen below warning in the browser console while opening the text component.

deprecated  $.validator ; use foundation-validation @ foundation.min.js:55
http://localhost:4502/etc.clientlibs/granite/ui/components/coral/foundation/clientlibs/foundation.min.js

**Comment by SRK2019** [comment]
Hi @richardhand : You can see https://youtu.be/AMudhCUCN5U video to see flickering behavior. We are using AEM 6.4.3 + Core 2.30. If we add more styles or para formats than the screen size then we can see the issue. We are seeing this issue in both inline and full screen mode.

**Comment by jckautzmann** [comment]
(CQ-4264382)

**Comment by margje-tempelaars** [comment]
Hi there,

We have the same issue as described here. Could you maybe give us an estimation on when this could be fixed? Thanks for your help!

**Comment by richardhand** [comment]
Hi @margje-tempelaars, are you referring to the issue described in the title and overview, or the flickering behaviour described in https://github.com/adobe/aem-core-wcm-components/issues/452#issuecomment-462785221 ? If it's the first, could you provide your AEM version and Core Components version?

@SRK2019, is this still an issue for you? I've been unable to replicate this console warning for `AEM 6.4.3.0` and `Core Components 2.3.0`. The warning is simply telling us that a validator is registered using an outdated method (JQuery validator versus the recommended granite foundation-validation approach) and shouldn't cause any actual problems in normal operation. In Core Components we don't have such a validator registered for the text component so if you do see this warning it is likely coming from product code (and will not be present in future versions of AEM) or from a validator that you have defined in your project code.

I did a full check on the Core Components code, and we do still have a validator registered in the Form Button component at [0] that uses the outdated method and therefore leads to the warning in the dialog as you describe. This reference should be updated.

[0] https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/form/button/v2/button/clientlibs/editor/js/button.js#L23

**Comment by gabrielwalt** [comment]
We cannot reproduce the validator warning issue.
