### ISSUE TITLE
How to implement a max limit of items in carousel

### ISSUE THREAD

**Issue by saulovenancio** [adobe/aem-core-wcm-components#471]
Hi, 
I need to implement a max/min limit on the Items that can be inserted in the carousel.
Can you give me a guidance on how to start?
Thanks

**Comment by jckautzmann** [comment]
hi @saulovenancio , what is your exact use case? Is it as follows?
- a superuser sets the max limit of slides in the policy dialog, e.g. 10
- the author tries to add an 11th slide in the dialog: a message warns him that the number of slides is limited to 10 slides and he's prevented from adding more

This could be achieved as follows:
- create a proxy carousel component
- add a tab to the policy dialog with a numberfield to set the max limit
- add a data attribute set with the max limit in the HTML of the proxy component
- in the clientlib of the proxy component, add the frontend logic that displays the warn message and prevents from adding more slides
- add the clientlib to the edit dialog of your proxy component

You may also want to submit a pull request to integrate this feature in the Carousel Core Component :)

I don't see the value of having a min limit of slides.

**Comment by jckautzmann** [comment]
Closing for now as we already provided an answer.
