### ISSUE TITLE
Add trackingFeature property to component dialog

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-core-wcm-components#477]
To be able to collect usage data from AMS customer we should add the tackingFeature property to the component dialog. The property should contain the component name and version.

(CQ-4263844)

**Comment by jckautzmann** [comment]
@bpauli Would this logic also work with custom components/dialogs that inherit from the Core Components?

**Comment by jckautzmann** [comment]
(CQ-4264376)

**Comment by bpauli** [comment]
@jckautzmann Yes, it will also work for proxy components or components which inherit from the core components as long as they don't override the edit dialog.

**Comment by paul-bjorkstrand** [comment]
Just noticing this on dialogs looking at core components, how does this exactly work, and where is `trackingFeature` used?

**Comment by keepthebyte** [comment]
Thanks for asking Paul. When customers opt-in for "Aggregated Usage Statistics Collection", the name of the component itself is collected. By default customers are opt-out - in that case the trackingFeature has no use.
