### ISSUE TITLE
Clarify and improve execution of backward compatibility strategy

### ISSUE THREAD

**Issue by HitmanInWis** [adobe/aem-core-wcm-components#480]
WCM Core components have introduced patterns in an attempt to maintain backward compatibility to ensure smooth, continuous, non-breaking upgrades to newer version of WCM Core components.  These patterns include component versioning (v1 vs v2) and enforcing a delegation pattern on custom Sling Model extension classes (https://issues.apache.org/jira/browse/SLING-8279).

However, these two patterns are either insufficient to accomplish the goals of backward compatibility, or are not being executed to the level required to accomplish it.

As an example, I just updated a codebase from 2.1.0 to 2.3.0 and there are new interface functions `Page`, `Image`, and `Title` that are littering the log file with `Caused by: java.lang.UnsupportedOperationException: null` due to new interface functions that are not yet implemented in my proxy extensions. Of course the updates to my proxy extensions are simple enough to make, but the proxy extension pattern is not automatically accomplishing backward compatibility.  I would argue that if my custom components were allowed to directly extend the WCM Core models it might actually solve this problem, but more can be found on that discussion on #466.

The backward incompatibility goes beyond dirtied logs, but includes real bugs.  As a concrete example, take the update to the `Title` component.

Use case:

- Starting with WCM Core 2.1.0
- `customtitle` component that extends `core/wcm/components/title/v2/title`
- No HTML or Dialog file in `customtitle`
- `CustomTitle` model that is a proxy extension of `Title` and always uppercases the title.
- Now upgrade to WCM Core 2.3.0
    - This adds a new "Link" field to the dialog, which is inherited by `customtitle`
    - This adds new link functionality to the `title.html` HTL, which is inherited by `customtitle`
    - This adds `default String getLinkURL() { throw new UnsupportedOperationException();  }` to the `Title` interface in WCM Core, which is inherited by `CustomTitle`
        - `CustomTitle` does _not_ inherit the functionality of `getLinkURL()` due to the proxy extension pattern
- Deploy to AEM without any code changes

The results of this use case are:
* All existing `customtitle` components litter the logs with `java.lang.reflect.InvocationTargetException: null` caused by `java.lang.UnsupportedOperationException: null at com.adobe.cq.wcm.core.components.models.Title.getLinkURL(Title.java:75)`
* Even more importantly (i.e. the "real" bug), authors have a new `Link` field on the `customtitle` dialog _that does nothing_ meaning we've introduced a bug.

**Comment by jckautzmann** [comment]
(CQ-4264375)

**Comment by vladbailescu** [comment]
@HitmanInWis , this is something we missed as potential use case: customizing the Sling model without overlaying the HTL script. Since what's done is done, I see two ways to go forward:
* For customers affected by these failures, they can either overlay the HTL script and dialog (copy pasting from the Core Components release that was working)
* In the future we should make sure we create a new version when adding new properties that are rendered in the HTL.

WDYT?

**Comment by HitmanInWis** [comment]
I agree that if someone does hit the issues I hit from 2.1 to 2.3, they should be able to solve the issue by temporarily doing what you mention (overlaying both the dialog and the HTL).

For the future, I think your plan is correct - version when adding new properties that are rendered in the HTL.

Before agreeing on that path, though, do we think this will result in an explosion of versions?

**Comment by vladbailescu** [comment]
We generally keep the components on the `development` branch for a while before they are stable for release. We even used to have `sandbox` package(s) but abandoned that project due to too much overhead when preparing for release.

We would not expect that many update once the component are out. Versions are cheap to create and expensive to maintain so we will try to limit the number (that's how we ended with the current _mess_).

**Comment by HitmanInWis** [comment]
Ok, sounds good.  Im cool with closing this if the new plan is documented or known by the repo maintainers.  I was actually asked to open this ticket within #466 so I'm not entirely sure what the closing criteria would be :).

**Comment by vladbailescu** [comment]
I'd leave this open for a few more days to gather more feedback from people keeping an eye on this repo.

**Comment by vladbailescu** [comment]
https://github.com/adobe/aem-core-wcm-components/wiki/Versioning-Policies/_compare/25ae8ed634580490e621fb70458070e0c2069ad6...089740f621468a6b1e403b1d0ba21977eae4000b
