### ISSUE TITLE
[Text] SourceEdit losing work

### ISSUE THREAD

**Issue by jozuman** [adobe/aem-core-wcm-components#488]
When I enable SourceEdit on the Text component, when clicking the edit pencil on a new instance of the component (not the wrench), then opening up the component dialogue full screen, then clicking the SourceEdit button in the RTE toolbar, and making source code changes, you can easily click the Minimize button and subsequently lose your source code changes without any error or warning. You have to hit the SourceEdit button again to turn source editing off before clicking the minimize button.

I'd expect a warning message that you need to close SourceEdit before minimizing or that my changes would actually save when minimizing.

**Comment by vladbailescu** [comment]
Hi Tim,

Thanks for reaching out. This is actually an issue with the Rich Text Editor (RTE) that's being used by the Core Components and I don't see a workaround that we could do in the components themselves. Is it ok if I open an internal issue for the team working on the RTE and you follow up with a Daycare issue and continue discussion there?

**Comment by jozuman** [comment]
Sounds good. I'll reach out to daycare. Thanks!

**Comment by vladbailescu** [comment]
(CQ-4264945)
