### ISSUE TITLE
[General] Support for JDK11

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-core-wcm-components#491]
Because of the removed package javax.annotation in JDK11 the core components project can't be build with JDK 11.

For future release of AEM the core components should also work with JDK 11

**Comment by kwin** [comment]
Similar to Sling (https://jira.apache.org/jira/browse/SLING-7798) and Oak (https://jira.apache.org/jira/browse/OAK-7511) I would recommend to migrate to IntelliJ null annotations.

**Comment by philipmundt** [comment]
Agree with @kwin for the JSR-305 approach, we did the same thing. However `javax.annotations.PostConstruct` seems to be another issue. I saw it was recommended to add a direct dependency to `javax.annotation:javax.annotation-api:1.3.2` but this only solve the compile time issues. As the annotation's `@PostConstruct` retention is runtime this will need to be solved for AEM globally!?

**Comment by kwin** [comment]
@philipmundt This is how it was solved for Sling: https://issues.apache.org/jira/browse/SLING-7312?focusedCommentId=16590839&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16590839.

**Comment by philipmundt** [comment]
Thanks @kwin for chiming in. My summary so far is the following:

### `javax.annotation` for annotations like `@PostConstruct`

Use re-packaged artifact from Sling (https://issues.apache.org/jira/browse/SLING-7135):

```
<dependency>
    <groupId>org.apache.sling</groupId>
    <artifactId>org.apache.sling.javax.activation</artifactId>
    <version>0.1.0</version>
    <scope>provided</scope>
</dependency>
```


### `javax.xml.bind`

Add direct dependency to (servicemix dependency is provided by Sling):

```
<dependency>
    <groupId>org.apache.servicemix.specs</groupId>
    <artifactId>org.apache.servicemix.specs.jaxb-api-2.2</artifactId>
    <version>2.9.0</version>
    <scope>provided</scope>
</dependency>
```


### JSR-305 for annotations like `@Nonnull` or `@Nullable`

Following the Sling way, see https://issues.apache.org/jira/browse/SLING-7798.
Add dependency to Jetbrains annotations (requires a patch version bump though):

```
<dependency>
    <groupId>org.jetbrains</groupId>
    <artifactId>annotations</artifactId>
    <version>16.0.2</version>
    <scope>provided</scope>
</dependency>
```
