### ISSUE TITLE
[ContentFragment] Move content fragment component from extension to core

### ISSUE THREAD

**Issue by philipmundt** [adobe/aem-core-wcm-components#493]
In order to tackle PR #340 and #360 the current content fragment component needs to moved from extension to core.

It was discussed to handle the move the following way:
* CF component code (model + servlets, datasources) and content will be moved to core; package `contentfragment` where applicable
* Paths will need to be adjusted to core (without `extension` – this will also allow for compatibility when someone still has the then legacy extensions installed)
* The "new" component will be handle as version 1 (v1) to prevent confusion in the future (and when the list component will be added)
* The extension module will then become obsolete and will be deleted (and not released in the future anymore)

**Comment by jckautzmann** [comment]
Pull request:
https://github.com/adobe/aem-core-wcm-components/pull/498

**Comment by jckautzmann** [comment]
The content fragment component has been moved from extenion to the Core Components.
