### ISSUE TITLE
[Navigation] Use the Navigation Title from the Page Properties if it is filled in

### ISSUE THREAD

**Issue by margje-tempelaars** [adobe/aem-core-wcm-components#501]
## Feature Request

**Is your feature request related to a problem? Please describe.**
For a client we would like to use the Navigation Title that you can set in the Page Properties so I can show another Title in the Navigation than the "Title" that you set in the Page when creating it.

**Describe the solution you'd like**
Standard the Navigation Component uses the Title that is set when creating the page. In case you need to show another name in the navigation than how the page is called, it should use the Navigation Title that you set in the Page Properties.

**Are there alternatives?**
Renaming the page to what it should show in navigation, but this is not an option for us.

**Comment by vladbailescu** [comment]
Hi @margje-tempelaars and thanks for reaching out!

The navigation component already uses the navigation title, if set:

https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageListItemImpl.java#L59

Do you have an use case where this is not working as expected?

**Comment by Evecreate** [comment]
Hi,

We have same issue, for the navigation this doesn't return the navTitle, pageTitle, as a fix we updated the html of itemContent.html. Looks like the item itself returns an object of page instead

`<template data-sly-template.itemContent="${@ item='The navigation item'}">
    <a href="${item.URL}" title="${item.navTitle || item.pageTitle || item.title || item.name}"
       class="cmp-navigation__item-link">${item.navTitle || item.pageTitle || item.title || item.name}</a>
</template>`

**Comment by vladbailescu** [comment]
@Evecreate , what version of the components are you using?

**Comment by richardhand** [comment]
@Evecreate, @margje-tempelaars - do you have any feedback here based on @vladbailescu's questions?

**Comment by Evecreate** [comment]
I fixed it locally on our project. No need to look into this anymore

**Comment by vladbailescu** [comment]
@Evecreate, is it an improvement you think others would benefit from and want to contribute? If not, I will close the issue.
