### ISSUE TITLE
[RTC] Footer

### ISSUE THREAD

**Issue by kweku5** [adobe/aem-core-wcm-components#506]
## Feature Request

As a Content Author, I want to be able to create a global header persists through all my child content pages.

Footer component should allow the author to add core components to achieve all the following variation elements:

List 
Text
Image
Columns
The author should be able to place each element with in the grid system so that they align and adhere to the desired structure. 

The components added to the footer should adhere to the styling system selected. 

The draft image below will be annotated but represents the elements that should be added.

![image](https://user-images.githubusercontent.com/5545584/54395970-9912be00-466e-11e9-869b-a298f791fc3f.png)

## Acceptance Criteria:

AEM Author is able to:

Add/Remove a footer component to a page Template
Component displays on all page created with that template
Define columns number of columns that adheres to layout grid
Add/Remove components to parsys
Add/Remove Experience Fragments to parsys
Notes:

Alternative thoughts on this could be built a just a bucket that contains the ability to add a experience fragment, and the fragment contains the elements described in the story. Should the footer simple be a fragment?

**Comment by kweku5** [comment]
@gabrielwalt Just added one of the component stories

**Comment by gabrielwalt** [comment]
Hi @kweku5,

I'm not sure to understand what the Footer component would allow to do more than what is possible already by just placing some ~List~ Navigation, Text, Image components on the page, and positioning them with the responsive grid. If it is that this group of components can be reused with the same layout across different templates, then could we use Experience Fragments for that?

**Comment by abhishekagg19** [comment]
@gabrielwalt 
The only thing which looks common across various footer design is the Copyright year.
It can either be authored manually or displayed via JS. if it's authored as a text, then it will require an update at the start of the year followed by flushing of the pages.
If it gets displayed via JS, then it will get updated automatically without any manual intervention.

Copyright can have the following formats:
2019 ©
© 2019
© 2010 - 2019

**Comment by JasonUSC** [comment]
We would want a footer component that is authored once and reused across multiple pages. An experience fragment dropped into the footer component would be great for that from my POV.

**Comment by gabrielwalt** [comment]
@abhishekagg19, if the copyright year is a text component inside an Experience Fragment, then all it would need is to edit that one place and to schedule its activation towards the end of the year. Not automatic, but at least a minimal effort. To make it a JS variable, we'd need something like variables in the RTE that can be placed, which is something that I'd like to have a well, but probably rather a topic of its own.

If we go the route of the Experience Fragment dropped on the template, then we'll have to make its reference smart to handle tranlated/localized content, because the templates are not tranlated/localized, but the text in has to be. We have done such a logic already for the Navigation component, which can be pointed in the template to a root like `/content/we-retail/language-masters/en`, and for the pages under `/content/we-retail/ca/fr`, it will automatically consider the corresponding pages.

**Comment by ynakagawa** [comment]
@gabrielwalt Can Experience Fragments handle 3rd party JS resource file references?

**Comment by ynakagawa** [comment]
I created an RTC on the project archetype issue.  https://github.com/adobe/aem-project-archetype/issues/174

Assuming we go with Experience Fragments that get put into a page template (and locked).  it would be nice for the project archetype to create a skeleton that can be easily stylized.

**Comment by gabrielwalt** [comment]
Hi @ynakagawa, loading 3rd party JS should be handled I think through Client Libraries which get deployed to the instance. It is then possible per template to load additional Client Libraries. This can be done by a template author on the page policy: one can define which additional Client Libraries get loaded [1].

**Comment by abhishekagg19** [comment]
Feedback comment:
1. Need to check the experience fragment with one more level of the hierarchy
2. Test with various locale/language format for the exp fragment hierarchy structure

**Comment by gabrielwalt** [comment]
Closing this issue as it's not directly related to the Core Components, but rather to the Archetype.
