### ISSUE TITLE
Release artifacts not found on Nexus

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-core-wcm-components#508]
## Bug Report

**Current Behavior**
I don't see many of the latest releases of Core Components on the public nexus repo: https://repo.adobe.com/nexus/content/groups/public/com/adobe/cq/core.wcm.components.all/

Please make them public so that customers can include the latest and greatest in their project.

**Expected behavior/code**
versions 2.2.2, 2.3.0, and 2.3.2 should be publicly available.

**Comment by bpauli** [comment]
@godanny86 instead of the adobe public nexus the Core Components are now getting deployed to maven central [1] .
[1] https://repo.maven.apache.org/maven2/com/adobe/cq/core.wcm.components.all/2.3.2/

**Comment by godanny86** [comment]
ah even better. Thanks!
