### ISSUE TITLE
Create a Mailing List for Core Components

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#513]
i think it would be very useful to have a mailing list for the core components project.
of course it's possible to (mis)use github issues for it (like this one), but that's not always adequate.

bigger discussions about architectural aspects like #503 or #496  would be better in a mailing list.

additionally i would like to see more discussion about features, architectural discussion etc. of the core components in the public with the community, and not only hidden inside adobe ...

**Comment by bpauli** [comment]
Thank you for this useful idea @stefanseifert. Indeed we shouldn't use GH issues for design discussions and Q&A. From now on we can use https://groups.google.com/forum/#!forum/aem-core-components-dev for this purpose.

**Comment by stefanseifert** [comment]
thanks, that was fast!
