### ISSUE TITLE
[RTC] Download

### ISSUE THREAD

**Issue by kweku5** [adobe/aem-core-wcm-components#518]
## Feature Request

As an author, I want to add a download link to a page, so I can provide links to files that can be downloaded from the page.

## Acceptance Criteria:
Author is able to add a download component to parsys
Author is able to navigate to an asset and select as target
File in the local DAM
Should accept any file in the DAM
Author is able to optionally add a url (external to the site) that points to a file as the target download
Author is able to add download link text/label (mandatory) 
Text becomes link to download
Text limit max 256 characters
If more restrictive character count is required, it should be controlled by CSS.
Author is able to add (optional) image to represent the download
Image becomes link to download
Display/format be controlled by CSS
When user selects link text or image link dialog opens to "save file as"
Leveraging the browse settings of the user (whatever it's set to)
User is able to download file.

**Comment by kweku5** [comment]
Appears to be a duplicate of #217.

I think adding the ability to associate an image/thumbnail would be nice addition to 217 as well :-)

**Comment by vladbailescu** [comment]
@kweku5 , please also check the code contribution from @bkheadwire in https://github.com/adobe/aem-core-wcm-components/tree/feature/download . It would be great if we could build/improve on top of that.

**Comment by richardhand** [comment]
@kweku5 - I added your feedback as a comment in [the other download RTC](https://github.com/adobe/aem-core-wcm-components/issues/217#issuecomment-479873678). Closing here as duplicate.
