### ISSUE TITLE
[ContentFragment][ContentFragmentList] Add JUnit tests

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#521]
Add JUnit tests for the Content Fragment and the Content Fragment List component.

CQ-4266568

**Comment by jckautzmann** [comment]
Pull request:
https://github.com/adobe/aem-core-wcm-components/pull/540

Following has been done as part of the PR:
- add tests to test the JSON export of the CF and CF list component
- refactor the JUnit tests of the CF list component
- mock the missing `DataType#getTypeString` by adding the `typeString` property to the mock
- add a context path to the tests

- refactor ContentFragmentUtils.getGridResourceType to get the resolver from the resource argument
- set copyright to 2019 for all code related to CF list
- improve javadocs in DAMContentFragment

- add a link to the Summit lab

**Comment by richardhand** [comment]
This is available on the master branch and will be included in the upcoming [2.4.0](https://github.com/adobe/aem-core-wcm-components/milestone/11) release.
