### ISSUE TITLE
[Image] Enhance Documentation around AdaptiveImage Servlet for Conditional Requests

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#530]
## Feature Request

Although Conditional-Requests via `Last-Modified` header are supported with the AdaptiveImageServlet (https://github.com/adobe/aem-core-wcm-components/blob/db0bac1041c1a554dfae5549aece3329c1d6553e/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java#L621) the [caching of the `Last-Modified` header](https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html#caching-http-response-headers) needs to be enabled in the Dispatcher to fully leverage that. This should be properly documented to allow customers to more easily fully-leverage the `AdaptiveImageServlet`.

**Comment by vladbailescu** [comment]
The archetype already has an example: https://github.com/adobe/aem-project-archetype/search?q=%22last-modified%22&unscoped_q=%22last-modified%22

**Comment by bohnertchris** [comment]
This has been documented in commit ddc970cc3ca21fac5d1f0078837cfd091ec0dccb of the core components documents and is now published as part of the Image Component docs.

https://docs.adobe.com/content/help/en/experience-manager-core-components/using/components/image.html

Also updated the wiki of the AIS to reflect this information as well.

https://github.com/adobe/aem-core-wcm-components/wiki/The-Adaptive-Image-Servlet
