### ISSUE TITLE
[RTC][Architecture] Configurable IDs for all components

### ISSUE THREAD

**Issue by shsteimer** [adobe/aem-core-wcm-components#535]
**[Request To Comment]** To anybody who intends to use the Core Components, please provide your feedback about the following requirements. We want to make sure that we build a component that fits your needs, so don't hesitate to tell us how that component should work, so that you will be able to use it.

**User Story:**

As a content author, I want to configure specific unique IDs for all form components (button, container, hidden, text, options) so that we can set up more advanced validation

**Acceptance Criteria:**

- Each form component has a configurable text field for the ID
- If the ID field is empty, the auto-generated ID (current behavior) is used
- IDs are not validated to be unique, it is left to the author to set unique, meaningful IDs
- The ID is validated to contain only allowable characters for an html ID (basically, no spaces)

**Comment by shsteimer** [comment]
Per conversation with @gabrielwalt we wold eventually like to extend this to all core components, and do it in a way that it can be had "for free."  The idea would be to implement this as a dialog tab similar to how the style system works, that can be included in any component.  Once that tab is included, the author can populate a value which would be used by the layout container when the component is rendered.

We can start with the form components, but once those are done and working, it can be easily added to other components as well.

**Comment by gitrajat** [comment]
> Per conversation with @gabrielwalt we would eventually like to extend this to all core components, and do it in a way that it can be had "for free." The idea would be to implement this as a dialog tab similar to how the style system works, that can be included in any component. Once that tab is included, the author can populate a value which would be used by the layout container when the component is rendered.
> 
> We can start with the form components, but once those are done and working, it can be easily added to other components as well.

@shsteimer As suggested, dialog tab would have only one 'id' field. Is it fine or should we add it as a property in the existing Properties tab?

**Comment by vladbailescu** [comment]
I would add it as a property and skip the auto-generated part for the beginning (as it's really not that useful: when moving components around the id might change).

**Comment by jckautzmann** [comment]
Fixed. Will be part of release 2.9.0.
