### ISSUE TITLE
[RTC] Gated Content Download Component

### ISSUE THREAD

**Issue by shsteimer** [adobe/aem-core-wcm-components#542]
**[Request To Comment]** To anybody who intends to use the Core Components, please provide your feedback about the following requirements. We want to make sure that we build a component that fits your needs, so don't hesitate to tell us how that component should work, so that you will be able to use it.

**User Story:**

As a content author, I want to setup a lead generation form that must be submitted by users prior to downloading a file such as a brochure or white-paper so that I can capture and generate sales leads

**Acceptance Criteria:**

- Form can use all existing form body components (button, hidden, text, options)
- On form submission a cookie will be set to enforce the download restriction
- Author can specify how long in days the cookie should be set for, default is 1 day but can be set in the design dialog
- Author can select the file to download from the DAM
- Author can specify the title to show on the download link or use the title of the selected file
- form will render if the cookie does not exist or has an invalid value
- download link will render if the cookie exists and is valid
- author can select a form action (similar to the existing form container component) to specify what should happen with the form data
- file download must go through a servlet that also enforces a cookie check and obfuscates the path to the file being downloaded
- The cookie's value should be a two-way hash (eg. base 64) of the current UTC date stamp + a seed value, which is configurable in the design dialog

**Notes**
- To keep pages cacheable, form view should always render by default server side.  Javascript can execute to call the download portion with a selector on the component resource (basically just a htl script within the component).  That will either return the html for the download portion if the cookie is valid, which can then be inserted to the page replacing the form.  If the cookie is missing or invalid, that request will return a 404 status code, which javascript can detect and keep the form displayed.

**Comment by gabrielwalt** [comment]
For now, we have released a [Download component](http://opensource.adobe.com/aem-core-wcm-components/library/download.html) that is a first step towards solving this RTC.

It doesn't yet allow to do properly gated content, but one way to solve this is to simply create a page that visitors only get redirected to after filling out a lead generation form.

I'm therefore closing this RTC for now, but we can create a more specific follow-up issue if we need to enhance specific aspects of this Download component.
