### ISSUE TITLE
[Form] Option Entries have two 'Active' fields

### ISSUE THREAD

**Issue by arnkrist** [adobe/aem-core-wcm-components#543]
## Bug Report

**Current Behavior**
The option entries in the Form options have both a checkbox and a radio button labeled 'Active'

**Expected behavior/code**
Only one field should be labeled 'Active'

**Environment**
Core Components version 2.3.2

**Possible Solution**
Remove the `selected` radiogroup and rename the `checked` checkbox to `selected`.

**Additional context / Screenshots**
![form_options_field](https://user-images.githubusercontent.com/49564750/56049053-f753bf00-5d48-11e9-93b0-0e18debe90f5.png)

**Comment by richardhand** [comment]
@thanks @arnkrist. There's an additional issue here whereby multiple radio buttons can be selected in the dialog for single select types (radio, select).

**Comment by richardhand** [comment]
This is available on the master branch and will be included in the upcoming [2.4.0](https://github.com/adobe/aem-core-wcm-components/milestone/11) release.
