### ISSUE TITLE
[RTC] Social List Component

### ISSUE THREAD

**Issue by kweku5** [adobe/aem-core-wcm-components#548]
## Feature Request

As an AEM Author, I want to list my social networks on my page, so I can provide links to my social networks on my site.
![image](https://user-images.githubusercontent.com/5545584/56212327-a2e16580-600e-11e9-99d3-b79bd5e03057.png)

## Acceptance Criteria

* User should be able to drag social list component on a page
* User should be able to configure page urls for the following social networks
   * Facebook (required for MVP)
   * LinkedIn (required for MVP)
   * Twitter (required for MVP)
   * YouTube (required for MVP)
   * flickr (Required for MVP)
   * Pinterest
   * Instagram
   * Tumblr
* User should be able to select default icons or upload their own
* User should be able to order the list

**Comment by jckautzmann** [comment]
When you say `User`, which one do you mean exactly: author or template-author?
IMHO all should be template-author except for the first one which should be author.

**Comment by JasonUSC** [comment]
To be really useful, this component should be configurable at the site level and respect country/language localizations. For example, our site for Mexico inherits content from the US through live copy and translations but they have their own social networks. A social media component on the /us/en/... pages that is live copied to /mx/es/... should automagically pull in the localized social media network urls.

**Comment by davidjgonzalez** [comment]
Surely Flickr is not MVP; perhaps you meant to mark Instagram as MVP.

**Comment by gabrielwalt** [comment]
I'm closing this one: we already have two similar components that allow to solve this use-case in a more generic way:
* The [Button component](http://opensource.adobe.com/aem-core-wcm-components/library/button.html) supports an icon, text and link. It requires some CSS to display the icon, and to align multiple Download components one next to the other.
* The [Image List component](https://github.com/adobe/aem-core-wcm-components/issues/578) is in progress and lists multiple images with a link test and path. It requires no CSS to display the images as they can be picked from the DAM. It only requires some CSS to align the different list items one next to the other.
