### ISSUE TITLE
AdaptiveImageServlet with static templates

### ISSUE THREAD

**Issue by kunalgaba** [adobe/aem-core-wcm-components#551]
Does AEM image core component works with static templates ? As per the servlet code, it does not render the image if the image quality and width settings are not defined in component policy. The policies are defined in Editable Templates and not in static templates. How can we get it working with static templates ?

**Comment by vladbailescu** [comment]
All Core Components are designed to be used with [Editable Templates,](https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/page-templates-editable.html) which is the recommended way to create websites with the current AEM version.

**Comment by kalva2290** [comment]
@vladbailescu if that's true can someone please update the getting started documentation, it specifically states that core components are compatible with both...

https://docs.adobe.com/content/help/en/experience-manager-core-components/using/get-started/using.html
