### ISSUE TITLE
[RTC] Experience Fragment (XF) component

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#557]
AEM provides an XF component that is based on the Javascript Use API.
It should be part of the Core Components and be rewritten following the Core Component best practices  (Sling Models, BEM, etc).

**Comment by jckautzmann** [comment]
(CQ-4269919)

**Comment by gabrielwalt** [comment]
Not considering a rewrite needs a specific RTC, closing this as this can be handled via #558.
