### ISSUE TITLE
[RTC] Experience Fragment Component with Localization Logic

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#558]
As an author I would like to select an experience fragment (XF) on a page or on a template. The XF component will render the XF that fits the localization format of the requested page.

The XF component should comply with the following localization formats:

**1. No localization**

site structure:
/content/my-site/...

experience fragment structure:
/content/experience-fragments/my-site/…

requested page:
/content/my-site/men/t-shirts

configured XF:
/content/experience-fragments/my-site/.../xf

-> rendered XF:
/content/experience-fragments/my-site/.../xf

**2. Regional localization (Live Copy only)**

site structure:
/content/my-site/master/...
/content/my-site/paris/...  (live copy of master)
/content/my-site/lyon/...   (live copy of master)

experience fragment structure:
/content/experience-fragments/my-site/master/...
/content/experience-fragments/my-site/paris/...  (live copy of master)
/content/experience-fragments/my-site/lyon/...   (live copy of master)

requested page:
/content/my-site/lyon/.../foo/bar

configured XF:
/content/experience-fragments/my-site/master/.../xf

-> rendered XF:
/content/experience-fragments/my-site/lyon/.../xf

**3. Language localization (Language Copy only)**

site structure:
/content/my-site/en/...
/content/my-site/fr/... (language copy of en)
/content/my-site/sp/... (language copy of en)

experience fragment structure:
/content/experience-fragments/my-site/en/...
/content/experience-fragments/my-site/fr/... (language copy of en)
/content/experience-fragments/my-site/sp/... (language copy of en)

requested page:
/content/my-site/fr/.../foo/bar

configured XF:
/content/experience-fragments/my-site/en/.../xf

-> rendered XF:
/content/experience-fragments/my-site/fr/…/xf

Note: the locale could also have the following format: ca-fr or ca_fr

**4. Multi-country localization**

site structure:
/content/my-site/master/en/...
/content/my-site/master/fr/... (language copy of master/en)
/content/my-site/master/sp/... (language copy of master/en)
/content/my-site/us/en/... (live copy of master/en)
/content/my-site/us/sp/... (live copy of master/sp)
/content/my-site/ca/en/... (live copy of master/en)
/content/my-site/ca/fr/... (live copy of master/fr)

experience fragment structure:
/content/experience-fragments/my-site/master/en/...
/content/experience-fragments/my-site/master/fr/... (language copy of master/en)
/content/experience-fragments/my-site/master/sp/... (language copy of master/en)
/content/experience-fragments/my-site/us/en/... (live copy of master/en)
/content/experience-fragments/my-site/us/sp/... (live copy of master/sp)
/content/experience-fragments/my-site/ca/en/... (live copy of master/en)
/content/experience-fragments/my-site/ca/fr/... (live copy of master/fr)

requested page:
/content/my-site/ca/fr/.../foo/bar

configured XF:
/content/experience-fragments/my-site/master/en/…/xf
or
/content/experience-fragments/my-site/us/en/…/xf

-> rendered XF:
/content/experience-fragments/my-site/ca/fr/.../xf

**5. Multi-country localization (optional)**

site structure:
/content/master/my-site/en/...
/content/master/my-site/fr/... (language copy of master/my-site/en)
/content/master/my-site/sp/... (language copy of master/my-site/en)
/content/us/my-site/en/... (live copy of master/my-site/en)
/content/us/my-site/sp/... (live copy of master/my-site/sp)
/content/ca/my-site/en/... (live copy of master/my-site/en)
/content/ca/my-site/fr/... (live copy of master/my-site/fr)

experience fragment structure:
/content/experience-fragments/master/my-site/en/...
/content/experience-fragments/master/my-site/fr/... (language copy of master/my-site/en)
/content/experience-fragments/master/my-site/sp/... (language copy of master/my-site/en)
/content/experience-fragments/us/my-site/en/... (live copy of master/my-site/en)
/content/experience-fragments/us/my-site/sp/... (live copy of master/my-site/sp)
/content/experience-fragments/ca/my-site/en/... (live copy of master/my-site/en)
/content/experience-fragments/ca/my-site/fr/... (live copy of master/my-site/fr)

requested page:
/content/ca/my-site/fr/.../foo/bar

configured XF:
/content/experience-fragments/master/my-site/en/…/xf
or
/content/experience-fragments/us/my-site/en/…/xf

-> rendered XF:
/content/experience-fragments/ca/my-site/fr/.../xf

**Comment by jckautzmann** [comment]
(CQ-4269920)

**Comment by JasonUSC** [comment]
I have some questions/concerns about this logic. Experience fragments are supposed to be content that gets reused across sites and apps, and the variants between each of those uses have been living within each fragment. With this proposed structure, do variations become obsolete? I had been expecting something more like this:

XF Master:
/content/experience-fragments/shared-library/language-masters/en/about-us/about-us

XF Variants:
/content/experience-fragments/shared-library/language-masters/en/about-us/my-site1
/content/experience-fragments/shared-library/language-masters/en/about-us/my-site2
/content/experience-fragments/shared-library/language-masters/en/about-us/my-app1

/content/experience-fragments/shared-library/language-masters/fr/about-us/my-site1
/content/experience-fragments/shared-library/language-masters/fr/about-us/my-site2
/content/experience-fragments/shared-library/language-masters/fr/about-us/my-app1

I do see an advantage with the new model proposed here in that it would be easier to control permissions for authors, but the tradeoff is losing the elegance of seeing all the variations of a fragment within its node.

It would help to have clarification around the purpose of variations if they are not to be used like this.

**Comment by jckautzmann** [comment]
@JasonUSC Thx for your feedback. Yes variants would still be possible, but not the way it is described in your example. Let me give you an example for #4 above (4. Multi-country localization) with variants:

requested page:
/content/my-site/ca/fr/.../foo/bar

configured XF:
/content/experience-fragments/my-site/master/en/…/xf/variant1

-> rendered XF:
/content/experience-fragments/my-site/ca/fr/…/xf/variant1

In the above requirements we assume that the localization structure of the site and the localisation structure of the experience fragments are the same, as they would both be achieved by using the AEM ootb features of the language copy and/or the live copy. Your example with several sites on the same AEM instance (BTW I don’t think that multi-tenancy is a recommended design) should probably be structured differently. For example:
/content/my-site1/us/en
/content/my-site2/us/en
/content/experience-fragments/my-site1/us/en
/content/experience-fragments/my-site2/us/en

**Comment by abhishekagg19** [comment]
@jckautzmann 
As per following region path - /content/my-site/lyon/.../foo/bar
Do we need to auto detect the region or the root path containing all the regions will be configured by the author?

**Comment by jckautzmann** [comment]
@abhishekagg19 This could be configured with the following properties:
- localizationRoot = /content/my-site
- localizationDepth = 1

**Comment by abhishekagg19** [comment]
@jckautzmann 
Is this localizationRoot and localizationDepth w.r.t XF or page? And we need to deduce one from another?
Also, for following samples, is localizationDepth specification correct? - 
/content/experience-fragments/my-site/us/en/...     (2)
/content/experience-fragments/my-site/us/sp/...     (2)
/content/experience-fragments/my-site/master/en/...     (2)
/content/experience-fragments/my-site/master/...     (1)

**Comment by jckautzmann** [comment]
@abhishekagg19 The properties `localizationRoot` and `localizationDepth` relate to the site page. The values in your examples are correct.
Please refer to my comment on your pull request. I attached some code for the localization logic:
https://github.com/adobe/aem-core-wcm-components/pull/541#issuecomment-487636705

**Comment by gabrielwalt** [comment]
My feedback regarding the current implementation, is that it should work more like the Navigation component (not the Language Navigation component), so that it auto-detects which parts of the path need to be localized, which would allow us to not require a `navigationRoot` nor a `structureDepth` configuration in the edit dialog.

Trying to translate that into requirements:
1) As a Template Author, I want be able to link to an XF language master, so that the localized pages resulting from this template automatically convert the configured path (without the need of additional configurations) to their localized versions, when the localized XF exists.
2) As a Page Author, from a language master or live-copy master page, I want be able to link to an XF language master, and have the language copies or live-copies automatically automatically convert the configured path (without the need of additional configurations) to their localized versions, when the localized XF exists.

**Comment by richardhand** [comment]
Code is merged to [master](https://github.com/adobe/aem-core-wcm-components/commits/master) and will be available in the upcoming [2.6.0 Release](https://github.com/adobe/aem-core-wcm-components/milestone/16).
