### ISSUE TITLE
[Link Handling][List] Apply URL mapping and vanity URLs to list links

### ISSUE THREAD

**Issue by juliaetate** [adobe/aem-core-wcm-components#559]
## Bug Report

When adding a page to a Fixed List using the List Component v2, if the page has a vanity URL, the list component is replacing the normal page name + .html with the vanity name. 

When clicked, this generates a 404 error because the URL generated by the component includes the full path to the page which is not part of the vanity URL. The correct vanity URL is http;//site.com/vanity while the full path is http://site.com/content/site/folder1/folder2/vanity.html. My link URL is being output as http://site.com/content/site/folder1/folder2/vanity instead of a functional URL.

When I remove the vanity URL, then the full path URL is used, and the link will work correctly.

Is there a way to override this or tell it not to use the vanity URL?

**Environment**
- AEM 6.3.3.3
- Core Components version 2.3.0 and 2.3.2
- Java(TM) SE Runtime Environment(build 1.8.0_171-b11)

**Comment by margje-tempelaars** [comment]
hi all,

we have the same issue with both the list component and the navigation component. Can you let us know what the best case solution will be to fix this?
![Uploading Screen Shot 2019-06-26 at 09.21.52.png…]()

**Environment**
- AEM 6.4
- Core Components version 2.3.0

Thanks in advance

**Comment by gabrielwalt** [comment]
We should test this as well with all other components, including for example Navigation, Breadcrumb, Quick Search and Content Fragment.

**Comment by shamrox** [comment]
Hey All,

The actual problem is in com.adobe.cq.wcm.core.components.internal.Utils.getURL .. below is the code

`    /**
     * Given a {@link Page}, this method returns the correct URL, taking into account that the provided {@code page} might provide a
     * vanity URL.
     *
     * @param request the current request, used to determine the server's context path
     * @param page    the page
     * @return the URL of the page identified by the provided {@code path}, or the original {@code path} if this doesn't identify a
     * {@link Page}
     */
    @NotNull
    public static String getURL(@NotNull SlingHttpServletRequest request, @NotNull Page page) {
        String vanityURL = page.getVanityUrl();
        return StringUtils.isEmpty(vanityURL) ? request.getContextPath() + page.getPath() + ".html" : request.getContextPath() + vanityURL;
    }`

Doesn't look like there is an override to this. it is being called in PageListItemImpl  and other components extend that. I am working on fixing this or creating an overloaded method

**Comment by margje-tempelaars** [comment]
Thanks for your comment. Can you let us know when you think this issue will be fixed? As we use the vanity urls frequently in our project and currently this forces us to use static 301/302 redirects on the server instead of using vanity urls (which is more work for us). 

Thank you for replying in advance!

**Comment by gabrielwalt** [comment]
This should be fixed by #713.

**Comment by josephh** [comment]
Hi we are seeing similar issues with navigation component - vanity url appearing in place of the page's actual path in the CMS.  
@gabrielwalt if #713 is sitting in the 3.0.0 milestone does that mean it will stay in that milestone release and when might 3.0.0 get a due date? thanks

**Comment by kavinmehta-work** [comment]
@vladbailescu  Based on comment by @gabrielwalt this will be fixed in #713 which is part of 2.16.0 release, however you have marked this ticket as [3.0.0](https://github.com/adobe/aem-core-wcm-components/milestone/19), just wondering which one is correct.
