### ISSUE TITLE
Responsive Grid is not working in teaser component

### ISSUE THREAD

**Issue by vivekdhiman** [adobe/aem-core-wcm-components#561]
Hi,
I am trying to use responsive behaviour of core components via proxy components. I am using OOTB teaser component. 

- In editable template, I have added teaser component which have resourceSuperType core/wcm/components/teaser/v1/teaser 
- I am in the layout mode and see the resposive layout.
- I tried to set the viewport of teaser component via dragging. It shrinks but when I release the key of mouse, it again take the default position. PFA

I am refering the wknd codebase.
AEM Env :  6.5.0

![img-1](https://user-images.githubusercontent.com/7066652/56961898-5bea8880-6b55-11e9-92f0-c3b5b0949b2a.JPG)

Regards,

**Comment by richardhand** [comment]
Hi @vivekdhiman, this seems to be an issue in the responsive grid and edit mode of the AEM editor, it can be reported via Adobe Enterprise Support.

See also our [Reporting Bugs](https://github.com/adobe/aem-core-wcm-components/blob/development/CONTRIBUTING.md#reporting-bugs-) guidelines.

**Comment by vivekdhiman** [comment]
Not related with this forum
