### ISSUE TITLE
[Image] PNG with transparency has gray edge on resize

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#564]
Some PNG images with transparency get a border / edge added to them by AEM when they are added to the page with the core image component or resized using the foundation image component.

(CQ-4270419)

**Comment by gabrielwalt** [comment]
This is affecting the underlying AEM GFX library, not the Core Components. Therefore closing this issue.

**Comment by jckautzmann** [comment]
After investigating I found out that this issue is not in the Core Components code: it is in the code in CQ/Granite that resizes the image (`com.day.image.ResizeOp`). 
We will close this issue and create an internal issue.
