### ISSUE TITLE
[Image] Support multiple file references in AdaptiveImageServlet

### ISSUE THREAD

**Issue by kunalgaba** [adobe/aem-core-wcm-components#566]
We have extended image core component which allows authors to drop multiple images for multiple viewports or screen sizes. The image references are stored as separate file nodes under the component node. We are not able to use adaptive image servlet to render the different images as we see that it always looks for the image file reference property under the component in a fixed path.

**Comment by gabrielwalt** [comment]
Hi @kunalgaba, as we're not able to implement all enhancement requests, we rely on your contributions to make them happen: please create a pull request, we'll be supportive of this enhancement. I'm closing this issue for now, but please reopen it as soon as you have a pull request for it, and link the two.
