### ISSUE TITLE
[Content Fragment List] Tag filtering not working in AEM 6.3

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#567]
The Tags section of the Content Fragment List page [0] displays the "Adobe Research Schweiz AG" location whereas it should only display offices from North America (`tagNames=[core-components-examples:region/north-america]`).

[0] http://localhost:4502/content/core-components-examples/library/content-fragment-list.html

**Comment by gabrielwalt** [comment]
Closing this for now.
