### ISSUE TITLE
[RTC] Embed Component

### ISSUE THREAD

**Issue by shsteimer** [adobe/aem-core-wcm-components#571]
**[Request To Comment]** To anybody who intends to use the Core Components, please provide your feedback about the following requirements. We want to make sure that we build a component that fits your needs, so don't hesitate to tell us how that component should work, so that you will be able to use it.

**User Story:**

As a content author, I want an embed component so that I can easily add third party widgets (ex. chat bot, lead gen form, social pixels, videos, etc.) to my website

**Acceptance Criteria:**

- Component must support 2 input modes
  - **HTML**: allows the input of free-form html, but is restricted only to safe tags by using the HTL output context of "html"
  - **Selection**: the author can select from a set of pre-configured trusted embeddable snippets.  These snippets can be parameterized, and can include unsafe tags such as <script>
- The template editor can make one, or both, modes of input available to the page author
- If the template editor makes selection mode available, they must also select which embeddable snippets to allow

** Notes:**

Creation of the trusted pre-configured embeddable snippets I envision this working similar to how custom form actions work.  The flow would be roughly as follows:
- A developer creates a hidden component with a certain sling:resourceSuperType (core/wcm/components/embed/embeddable).
- Embed design dialog can query for components with this resource type so template author can select them to allow
- The embeddable component can have a custom dialog to allow specifying parameters.  When the embeddable is selected, this dialog is rendered inside the embed component dialog for specifying any parametrized parts of the embeddable
- The embed component renders the embeddable using data-sly-resource for the current resource, but specifying the resource type of the embeddable.  This gives the embeddable access to the embed resource properties for reading and displaying the parameterized values

**Comment by vivekanand-mishra** [comment]
**Decision Taken On 5/22-** 
1. After Dialog Update (Embed Component) page should reload itself so that any javascript initialization takes places automatically and author does not have to refresh page manually.
2.  Embeddable components delivered with core Embed component (e.g. YouTube, Marketo etc.) will be placed under "/apps/core/components/embeddables". Earlier it was decided to put under- "/apps/core-components-examples/components/embeddables".

**Comment by gabrielwalt** [comment]
See also the discussion on #219.
