### ISSUE TITLE
Update README.md For New Maven Archtype

### ISSUE THREAD

**Issue by asharron** [adobe/aem-core-wcm-components#576]
## Request

Currently the Readme says to place your subpackage of the core-components with the content-package-maven-plugin subpackages section, however, with the new maven archetype, I believe the subpackage should be placed under the filevault-package-maven-plugin subpackages section. 

## Suggestion 

Just update the readme to include where to place the subpackage for older Maven archetypes and where to place it for the most current version of the maven archetype. 

I don't mind making a PR myself to update the docs, but just wanted to open an issue first to bring it to the core-devs attention. Just to double check that I am correct in my line of thinking.

**Comment by richardhand** [comment]
Hi @asharron - thanks for the suggestion, feel free to go ahead and create a Pull Request for this.
