### ISSUE TITLE
[Navigation] Navigation is missing the role attribute

### ISSUE THREAD

**Issue by jakublamprecht** [adobe/aem-core-wcm-components#584]
## Bug Report

**Current Behavior**
Navigation component does not add `role="navigation"` on \<nav> element as suggested by W3C here:

https://www.w3.org/WAI/GL/wiki/Using_HTML5_nav_element#Example:The_.3Cnav.3E_element

**Expected behavior/code**
Navigation has a role attribute on \<nav> element.

**Environment**
- Core Components version 2.3.0

**Comment by richardhand** [comment]
@jakublamprecht - this also makes sense, again feel free to create a pull request to add this!

**Comment by richardhand** [comment]
@jakublamprecht - on second thoughts, is this still necessary nowadays? The HTML validator fires a warning if you do:

`<nav role=navigation></nav>`:

<img width="584" alt="Screenshot 2019-05-20 at 14 38 40" src="https://user-images.githubusercontent.com/25616660/58022108-fd3d7c80-7b0c-11e9-883f-10548255b656.png">


See also:
• https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role

**Comment by jakublamprecht** [comment]
@richardhand I guess I didn't really explain my case correctly - while submitting this I though about supporting older agents, which might not support the semantic value of `<nav>` (that's what is suggested in the source I linked in the issue). If there's no need to worry about `<nav>` el not being supported, feel free to close this issue :)

**Comment by richardhand** [comment]
We still support IE11 for publish side code, so we should probably still add this, looks like IE doesn't map these roles still, even if that means we have to again remove it in the near future.

**Comment by richardhand** [comment]
https://github.com/adobe/aem-core-wcm-components/pull/594
