### ISSUE TITLE
[Navigation] Navigation does not specify currently active item for screen readers

### ISSUE THREAD

**Issue by jakublamprecht** [adobe/aem-core-wcm-components#585]
## Bug Report

**Current Behavior**
Navigation component does not provide information about currently active item/link for screen readers as suggested by W3C here:

https://www.w3.org/WAI/tutorials/menus/structure/#indicate-the-current-item
https://www.w3.org/WAI/tutorials/menus/structure/#using-wai-aria

**Expected behavior/code**
Navigation component provides the user with information about currently active item/link.

**Environment**
- Core Components version 2.3.0

**Possible solution**
In itemContent.html:

```
<a href="${item.URL}"
     title="${item.title}"
     data-sly-attribute.aria-current="${item.active && 'page'}"
     class="cmp-navigation__item-link">
    ${item.title}
</a>
```

**Comment by richardhand** [comment]
Thanks @jakublamprecht for the suggestion, this makes sense. Please feel free to go ahead and create a pull request. One point, I don't believe you need to use `data-sly-attribute` in the above example.

**Comment by jakublamprecht** [comment]
That's right @richardhand, works the same without `data-sly-attrbiute`
