### ISSUE TITLE
[Page] Lack of media viewport

### ISSUE THREAD

**Issue by rogemus** [adobe/aem-core-wcm-components#587]
hi, 
is lack of
```
<meta name="viewport" content="width=device-width, initial-scale=1">
```
in 
```
https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/head.html
```
is intetional?

**Comment by richardhand** [comment]
Hi @rogemus - I don't believe this is intentional and the viewport you recommend is a sensible default. The question is more whether this should also be configurable in the Page.

**Comment by rogemus** [comment]
hi :) i don't think this need any configuration for that. I think every project will be creating some kind of responsive site for client, so this can be in `head.html` by default.

**Comment by bpauli** [comment]
+1 to have this as a meaningful default. 

@rogemus may I ask you to create a PR for this?

**Comment by henrykuijpers** [comment]
This fix was done a bit short-sighted: There should have been an include for the view-port tag with the current tag as a sensible default. 

Currently, with this solution, a developer is not able to override this behaviour if needed, without overriding head.html completely.

@bpauli should I create a new ticket for this?

**Comment by vladbailescu** [comment]
@henrykuijpers, a PR that improves this would be greatly appreciated. I don't think you need to create a new issue, we will add the PR to the milestone it gets released in, so we can track changes.

**Comment by vladbailescu** [comment]
Or, better yet, include it in a PR for #685 ;)
