### ISSUE TITLE
[Link Handling] Link Tracker Capability

### ISSUE THREAD

**Issue by kmurugulla** [adobe/aem-core-wcm-components#592]
**User Story**

As a Content Author, I want to enable Link Tracking for the following list of Call to Action category of components.

1. Carousel
2. Teaser
3. Button (Form component?)
4. Image (Links)
5. List (Links

**Acceptance Criteria**

1.  The component must have Link tracking checkbox in the edit dialog and design dialog. Design dialog is fall back (picks up default value from design dialog, if not explicitly set) for edit dialog
2. The template editor must have an option to make the Link Tracking property available or not through a design dialog
3. The component must have an option for the author to enter a unique attribute name that holds the link value ( e.g: data-birf-cmp )
4. The component must have an option for the author to enter a unique value for the data attribute
5. The component must have an option to overwrite auto generated unique value for each link's s_objectID (e.g: prod 123789 home page)
6. The component must auto-generate a unique value ( one option is to get component path , strip out root path "/content/<site>" and then replace "/" in the patch with " ") 
7. The component must generate onClick="s_objectID='prod 123789 home page'; and add that to anchor tag ( e.g: <a href="/home.jsp" onClick="s_objectID='prod 123789 home page';">Home</a>)

**Sample Link with tracking enabled**
`<a href="${linkItem.linkPath}" data-analytics-track="true" data-analytics-custom-link-name="${currentPage.parent.title}: ${currentPage.title}: ${linkItem.linkText}: footer" target="${linkItem.linkTarget}" title="${linkItem.linkText}" onClick="s_objectID='prod 123789 home page';">${linkItem.linkText} </a>`

**Comment by vladbailescu** [comment]
-1 for the `onClick` part. I'm generally ok with adding custom data-attributes but I don't think they are necessary. A DTM solution can just register event listeners for link clicks and get all the rest of the needed information from the [datalayer](https://github.com/adobe/aem-core-wcm-components/issues/228)

**Comment by tjameswhite** [comment]
@vladbailescu I don't disagree with you on the `onClick`, but we have the exact same implementation, which was provided to us by Adobe. We're looking at the same issue as @kmurugulla -- all of our old, custom components have the `data-track` attributes and our analytics team would like everything to be consistent.

**Comment by tjameswhite** [comment]
Correcting myself -- I was going from memory. Our implementation is similar, but not identical. Our `data-` names are slightly different, and we don't have the `onClick`. the `onClick` is part of the implementation for image insights, which we haven't implemented. I'm working on an initial version based off the code we are using.

**Comment by tjameswhite** [comment]
I see that there is a a pull request addressing some of this (https://github.com/adobe/aem-core-wcm-components/pull/661) -- though it seems to have some deficiencies. 

I compared our implementation with the proposal in this issue. The "Combined" column is my proposal to normalize our two instances. The only real difference is the inclusion of the component name. Other elements have been dropped as unnecessary.

Comments?

Our implementation | Issue 592 Proposal | Combined
-- | -- | --
  |   |  
data-event="track-component" | data-analytics-track="true" | data-analytics=track="true"
data-component-name="[component name]" |   | data-component-name="[component name]"
data-component-link="${currentPage.parent.title}: ${currentPage.title}: ${action.title}" | data-analytics-custom-link-name= "${currentPage.parent.title}: ${currentPage.title}: ${linkItem.linkText}: footer" | data-analytics-custom-link-name ="${currentPage.parent.title}: ${currentPage.title}: ${linkItem.linkText}: footer"
data-component-link-placement="[number]" |   | remove
data-component-link-type="link \| button \| etc" |   | remove
  | title="${linkItem.linkText}" | not recommended - remove
  | onClick="s_objectID='prod 123789 home page';" | remove

**Comment by ynakagawa** [comment]
the combined view does not have an s_objectID.  how does the s_objectID get set?

**Comment by bstopp** [comment]
I was under the impression that `onClick` (inline JS) is a bad practice.

**Comment by tjameswhite** [comment]
@bstopp  -- it is, that's one reason I removed it from the proposal.

@ynakagawa  -- We currently use what is in "our implementation" column, no s_objectID is set. We are looking for the data-event, then grabbing the other data- attributes.

**Comment by gabrielwalt** [comment]
This should now be solved by the HTML ID and Data Layer capability that has been added to the Core Components
