### ISSUE TITLE
[Content Fragment] Insert parsys in-between all selected fields

### ISSUE THREAD

**Issue by hebikidesignworks** [adobe/aem-core-wcm-components#595]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, when a content fragment points to a rich text field, a parsys is inserted inbetween all the P tags/paragraphs. But if all fields are selected from the content fragment, no parsys are inserted.

**Describe the solution you'd like**
When authoring a content fragment on a page, a parsys should be inserted inbetween all the rendered fields

**Are there alternatives?**
None

**Documentation**
Attachments for current content fragment and proposed improvements.

Current: Content fragment with description field selected - renders with parsys inbetween paragraphs:
![cf-descriptionfield](https://user-images.githubusercontent.com/25228858/58042644-1a178700-7af0-11e9-9db5-da3bd5a9ff4b.png)

Content fragment showing all fields rendered
![current-contentfragment](https://user-images.githubusercontent.com/25228858/58042692-361b2880-7af0-11e9-9785-982a9be7d7c5.png)

Proposed Content fragment - all fields selected with parsys inbetween each field.
![proposed-contentfragment](https://user-images.githubusercontent.com/25228858/58042716-429f8100-7af0-11e9-88e2-e8caa389d314.png)

**Comment by gabrielwalt** [comment]
That might make sense indeed.

Unfortunately, we won't have the bandwidth to address this in the next months; feel free to contribute such an enhancement if you have the opportunity to do so.

**Comment by gabrielwalt** [comment]
Closing this as there hasn't been activity for over a year.
