### ISSUE TITLE
[ContentFragment] Content Fragment showing model titles when used on the pages

### ISSUE THREAD

**Issue by sharadkap** [adobe/aem-core-wcm-components#596]
## Bug Report

**Current Behavior**
The content fragment component renders out the labels (titles) from the content fragment models. 
![image](https://user-images.githubusercontent.com/5682531/58066455-bc0ca180-7bcc-11e9-866d-a586f87f960a.png)

**Expected behavior/code**
There shouldnt ideally be any titles displayed and this is coming from the line of code in 
/apps/core/wcm/components/contentfragment/v1/contentfragment/element.html 
`<dt class="cmp-contentfragment__element-title">${element.title}</dt>`
and
/apps/core/wcm/components/contentfragment/v1/contentfragment/templates.html
` <h3 class="cmp-contentfragment__title">${fragment.title}</h3>`

This wouldnt be needed in the ideal world. 

**Environment**
- AEM version and patch level - AEM 6.4 SP4
- Core Components version 2.4.0
- JRE version 1.8

**Possible Solution**
I need to overlay this on my custom components which is not ideal if we are using AEM Core Components. We should remove the line of code as stated above from the templates and iff needed by anyone, it can be easily overlaid. 

**Additional context / Screenshots**

**Comment by richardhand** [comment]
@sharadkap - these titles can be useful if you want to display key value pairs where the title is important in the rendering, such as in an address or FAQ. I agree that in some use cases they won't be necessary. Perhaps it should possible to hide these title via a configuration option. Rather than overlaying the template it's also possible to hide these elements client side with CSS, but it's not ideal.

**Comment by gabrielwalt** [comment]
I'd not allow authors to remove these labels from the markup output as they are necessary to understand the semantics of what is being displayed, for accessibility and SEO purpose.

If these labels are visually not desired, I'd recommend you to hide them with some CSS, but then avoid to use `display: none` and rather use some accessible CSS hiding technique [1].

If the author should have an option to choose whether to display or not the labels, then create corresponding styles with the Style System [2].

However, in the example shown in your screenshot, the best solution might be to extend the Content Fragment component to create a component that can specifically render your model. Typically, you might want to put the title into a proper `<H1-6>` element.

Closing this issue as the component works as expected, and your need rather is to configure or extend the Content Fragment component to match your needs, which is possible already. I could however imagine that we better document this and verify that there's a good extension pattern to just create a custom HTL output for a specific model.

[1] for eg: https://cloudfour.com/thinks/see-no-evil-hidden-content-and-accessibility/
[2] https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/style-system.html
