### ISSUE TITLE
Core Components are not compatible with Static Templates

### ISSUE THREAD

**Issue by kalva2290** [adobe/aem-core-wcm-components#597]
@vladbailescu and @gabrielwalt both state in several issues that core components will not work with static templates, but the documentation specifically reads that it would work for both. Please update the docs to reflect the current state of affairs.

https://docs.adobe.com/content/help/en/experience-manager-core-components/using/get-started/using.html

See below issues describing that Static Templates are not supported:
adobe/aem-core-wcm-components#100
adobe/aem-core-wcm-components#551

**Comment by vladbailescu** [comment]
Hi Kevin and thanks for bringing this up! I suppose you're referring to wording related to design mode, such as: 

> Following steps are typically done in the Template Editor, for existing setups however, this might be done in Design mode:

We'll try to improve the docs!

**Comment by bohnertchris** [comment]
Thanks, @kalva2290! I already addressed in the issue that you opened in the Core Components docs repository.

https://github.com/AdobeDocs/experience-manager-core-components.en/commit/632d6abb1f13667cc0457152268d50af3bfabfc4

**Comment by kalva2290** [comment]
@vladbailescu @bohnertchris @richardhand Thank you all for the quick response! I reviewed the docs I was referencing before and they're fine now. Thanks.
