### ISSUE TITLE
[Content Fragment List] Max display of 10?

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-core-wcm-components#598]
## Bug Report

**Current Behavior**
When experimenting with the Content Fragment List component I cannot configure the filters to return more than 10 fragments (even though more than 10 exist).

**Expected behavior/code**
I would expect the component to return all content fragment fragments based on the configured filters. Ideally, a user has a way to configure the max amount of items as either a policy or dialog configuration.

**Environment**
- AEM 6.5
- Core Components version 2.4.0
- JRE version 1.8

**Possible Solution**

Update https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentListImpl.java#L120 to include an explicit `p.limit` parameter that is configured at the component's policy/component level...

Otherwise, I think the QueryBuilder API defaults to a limit of 10...

**Comment by richardhand** [comment]
This is available on the `master` branch and will be included in the upcoming `2.5.0` release.
