### ISSUE TITLE
Component code generator

### ISSUE THREAD

**Issue by HitmanInWis** [adobe/aem-core-wcm-components#611]
## Feature Request

Should WCM Core include a bundled code generator to assist with developers creating components according to the WCM Core standards?

Bounteous has open sourced an AEM component code generator at https://github.com/Bounteous-Inc/bounteous-aem-commons but I'm curious if it would make sense to incorporate into WCM Core Components or another Adobe-sanctioned project, so that it can be more widely adopted and contributed to by the greater community.

Generated code includes:
- `cq:dialog` for component properties
    - `dialogshared`/`dialogglobal` for shared/global component properties
    - Supports all basic field types, multifields, and image upload fields
- Sling Model
    - Includes fully coded interface and implementation classes
    - Follows WCM Core component standards
    - **Enables FE-only development for most authorable components**
- HTL file for rendering the component
    - Includes an object reference to the Sling Model
    - Includes the default WCM Core placeholder template for when the component is not yet configured
- Stubbed clientlib (JS/CSS) following component client library patterns of WCM Core 

The code generator could easily be extended to serve more use cases, such as generating custom component extensions from WCM Core components, including Sling Models that follow the proxy extension pattern of functions that delegate to the wrapped parent.

Thoughts?

**Comment by HitmanInWis** [comment]
Forgot to add quick visuals to convey the generated files/structure:

![Screen Shot 2019-05-30 at 6 20 11 PM](https://user-images.githubusercontent.com/972809/58738154-2cd06c80-83ca-11e9-8c3a-f7ffe2fedd98.png)

![Screen Shot 2019-05-30 at 6 20 24 PM](https://user-images.githubusercontent.com/972809/58738155-2cd06c80-83ca-11e9-941f-07088e3ab940.png)

**Comment by brandonmaynard** [comment]
@HitmanInWis, per out internal conversation, I wonder if this makes more sense to be a part of ACS Commons rather than WCM Core? What are other people's thoughts?

**Comment by vladbailescu** [comment]
This looks like an excellent way to scaffold a component. I do wonder what would be the best workflow for people (with possibly different backgrounds) to use this tool. Your approach to create a descriptive JSON and then run a java program against it is pretty cool, just thinking that we could make this even easier. Perhaps packing it as a maven plugin or even a node.js command might make it simpler to use.

I would keep this project separate from the Core Components themselves. Adobe would probably accept this project as an open-source contribution under https://github.com/adobe , if you think it would make sense to have it on "neutral grounds".

**Comment by HitmanInWis** [comment]
I dont think we'd have any problem with contributing it as a new project under https://github.com/adobe - who would we need to talk to about that?

**Comment by HitmanInWis** [comment]
Any other opinions from the community?  We'd like to share the AEM Component Generator as a community project owned by Adobe to encourage community use and contribution. We're more than happy to maintain the repo as Bounteous, but at the same time that makes it look like it's "our" tool and it feels like that's a big detractor to any project in the AEM community.

The AEM component generator is a coding efficiency tool that we see as very desirable to *anyone* coding AEM components as it reinforces best practices established by Adobe through WCM Core.  There's nothing "Bounteous" specific about it.

**Comment by vladbailescu** [comment]
@HitmanInWis , I created https://github.com/adobe/aem-component-generator . Please let me know if you think this is a good location!

**Comment by vladbailescu** [comment]
I also wonder if it would sense to pack this generator in a Maven plugin so that it can be more easily invoked by developers.

**Comment by HitmanInWis** [comment]
Hi Vlad, that location will work just fine!  I'll get a PR up hopefully this week.

Regarding packaging as a Maven plugin, I'm certainly not opposed if that's what the community finds even more helpful.  Perhaps once we have the project contributed, someone (perhaps devs at Bounteous) can make that update.

**Comment by HitmanInWis** [comment]
Initial version of the AEM Component Generator has been submitted for PR (https://github.com/adobe/aem-component-generator/pull/1).
