### ISSUE TITLE
[Link Handling][Image] Add target _blank support to link

### ISSUE THREAD

**Issue by rubnig** [adobe/aem-core-wcm-components#612]
## Feature Request

Add the option to open the link set through `linkURL` in a new tab.

**Comment by andreeadracea** [comment]
@rubnig - thank you for the feature request. For the near future I don't think we will have bandwidth to add this feature so we would really appreciate your contribution.

**Comment by andreeadracea** [comment]
(CQ-4264381)

**Comment by gabrielwalt** [comment]
This same feature would also make sense on following components:
- Title
- Teaser

**Comment by gabrielwalt** [comment]
This should be fixed by #713.
