### ISSUE TITLE
[Tabs] Sling Resource Merger properties breaks item add button

### ISSUE THREAD

**Issue by A30001907** [adobe/aem-core-wcm-components#618]
## Bug Report

**Current Behavior**
I have extended the core Tabs component by overlaying it in my app with sling:resourceSuperType="core/wcm/components/tabs/v1/tabs". I have modified the tabs.html and written my own clientlib to make it function like an accordion, as such I do not want authors to be able to set the activeItem as I want all accordions to be collapsed by default. Adding sling:hideChildren="properties" on the tab/items node in the dialog successfully achieves the hiding of the 'properties' tab however the 'Add' button on the Items tab is no longer functional. Clicking Add button no longer opens the Add New Components popover. To further prove this is a bug I also tried added sling:hideResource="{Boolean}true" on the properties node itself and experience the same behaviour. Likewise adding sling:hideResource on the activeItems node also breaks the Add component functionality.

eg:
`<tabs jcr:primaryType="nt:unstructured"
                sling:resourceType="granite/ui/components/coral/foundation/tabs"
                maximized="{Boolean}true">
                <items jcr:primaryType="nt:unstructured" sling:hideChildren="properties">`

**Expected behavior/code**
I would not expect hiding either the 'properties' tab nor any of its child properties to have any affect on the functionality of the Add component button. The Add component button on the Items tab should still function as normal.

**Environment**
- AEM 6.4 SP3
- Core Components version  2.4.0
- JRE version (e.g. `Java(TM) SE Runtime Environment build 1.8.0_211-b12

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
<img width="592" alt="Screen Shot 2019-06-07 at 1 51 20 pm" src="https://user-images.githubusercontent.com/50309377/59080310-6d306d00-892b-11e9-9a64-da346a621cee.png">

**Comment by richardhand** [comment]
Thanks @A30001907 for the bug report and sharing details of how you are using the core components! Provided a fix at #622 that makes the tabs dialog handling more robust - it no longer assumes that both tabs are available.

Regarding accordion, we have an [Accordion component](https://github.com/adobe/aem-core-wcm-components/tree/development/content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion) in progress on the development branch that is due in our next release, it might be more suitable to your needs.

**Comment by richardhand** [comment]
This is available on the `master` branch and will be included in the upcoming [`2.5.0` release](https://github.com/adobe/aem-core-wcm-components/milestone/13).
