### ISSUE TITLE
[Wiki] Code example is incorrectly closing a <section> tag

### ISSUE THREAD

**Issue by jurgenbrouwer** [adobe/aem-core-wcm-components#630]
## Bug Report

**Current Behavior**
The code example in the Wiki at [Place Use Data-sly-use Statements On Top-level Elements](https://github.com/adobe/aem-core-wcm-components/wiki/HTL-Style-Guide#place-use-data-sly-use-statements-on-top-level-elements) is incorrectly closing a `section` tag

**Expected behavior/code**
The code example should close a `div` tag.

**Environment**
n/a

**Possible Solution**
Change `</section>` to `</div>`

**Comment by richardhand** [comment]
Thanks @jurgenbrouwer for the report! This is now fixed, closing.
