### ISSUE TITLE
[Content Fragment List] Variation Selection

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-core-wcm-components#633]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, the Content Fragment List only returns the master variation of a content fragment. A valid use case would be to choose a different variation than the master one.

**Describe the solution you'd like**
In the Content Fragment List dialog, a user can select a variation from a dropdown. The dropdown should only display variations that are possible based on the filter criteria of the content fragment model. The list of content fragments displayed uses the variation selected in the dialog.

Potential drawbacks:

* Variations are managed on individual content fragments. It is possible that not every content fragment returned by the query has the selected variation. Should the behavior default to the master in these cases? Or should no content fragment be returned?

**Are there alternatives?**
The alternative is to manage individual content fragments but this is not a scalable option for Content Services/ headless use cases...

**Comment by godanny86** [comment]
Seems like the team thinks this is a valid enhancement. I can pick it up. 

For the behavior, if the specified variation cannot be found I would have it default to using the master variation.

**Comment by richardhand** [comment]
An alternative would be to populate the variation select only with variations common to all those returned by the query.

**Comment by godanny86** [comment]
ah, yes @richardhand that makes sense.

**Comment by godanny86** [comment]
Although, this will only cover the case when the component is being authored. There is the potential that new Content fragments are added (after the component has been authored) that match the model/tag filter criteria but do not contain the specified variation. If that is the case I think it makes sense **not** to include those content fragments. I'll experiement a bit, as I don't want to over-ly compicate the logic...

**Comment by gknobloch** [comment]
> An alternative would be to populate the variation select only with variations common to all those returned by the query.
I don't think this is a good solution. Knowing that variation node name is created from initial variation display name, which can be renamed, deleted (with a component initially configured - so what would happen if a CF List that used to display that CF no longer having the variation), etc.

Anything done with current architecture would be very fragile IMO.
Proper solution would require a product enhancement, to define "locked variations" (i.e. variations defined at model level - that can't be renamed/deleted in CF), where we could guarantee, and only suggest those variations in the dropdown.

cc @stefangrimm

**Comment by godanny86** [comment]
> Proper solution would require a product enhancement, to define "locked variations" (i.e. variations defined at model level - that can't be renamed/deleted in CF)

Great points @gknobloch. I won't actively work on anything in the short term. I do think this is a valid use case though and something to consider prioritizing if we want to promote the use of the CF List as a best practice for delivering headless content...

**Comment by gabrielwalt** [comment]
While it's correct that the variation is specific to the CF instance, I think that if authors follow some conventions in the naming of variations, it could still make sense for the CF List component to retrieve a specific variation when it exists. We could even have an option that specifies what to do when the given variation doesn't exist: ignore that CF or fallback to the master variation.

However, we don't intend to work on this in the next 3 months or so, so I'm closing this issue for now. @godanny86, or anybody else, feel free to reopen this issue if you have the opportunity to contribute such an enhancement.

**Comment by morgank-atl** [comment]
2021 and we are full speed ahead with headless content delivery to mobile and we cannot send the Spanish variation. I can't believe there isn't even a "dump it all" for a JSON endpoint.
