### ISSUE TITLE
Giving credit where credit is due - squash merges

### ISSUE THREAD

**Issue by HitmanInWis** [adobe/aem-core-wcm-components#650]
Hey all, want to bring to the attention a common issue I've started noticing in this project as well as other Adobe open source projects such as ACS AEM Commons.

It appears that it has become a standard that PR commits are squash merged, creating a single commit in the `master` branch for any given PR.  I imagine this is done to keep a clean git history, among potential other reasons.  However, one of the downsides of this approach is that only a single committer is then given credit for the contributed code.

Reason I bring this up is that recently a co-worker of mine at Bounteous created an extensive PR for a feature in WCM Core components.  Another dev leveraged my co-worker's PR to create a new PR, which was eventually merged.  In the end, the 2nd dev (who definitely deserves some credit) gets 100% credit for the contribution to WCM Core, whereas my co-worker receives none.  A bit of a slap in the face (though not intentional by anyone) if you ask me.

This might not seem like a big deal to some folks that maintain or contribute often to these projects, but I'd like to posit that it really is a big deal if we want more new people to contribute.  Open source development offers no direct "payment" or "benefit" so why do people do it?  If there's nothing to be gained personally, why not just create a private library keeping our features to ourselves?  The reason many people contribute is they want to be part of something, have their name stamped on some of the biggest open source projects in our industry.  They want to feel that their code and expertise is equivalent to others who are considered the best in the industry.  When we take that motivation away (or treat it as if it's not really that important by doing squash merges of multiple-contributor PRs) we undermine that motivation whether people talk about it or not (my co-worker would never make this post).

Curious what others' thoughts are on this topic?

**Comment by joerghoh** [comment]
agree on that. If you squash you should at least give all authors who's commit you squash proper credit.

**Comment by gabrielwalt** [comment]
+1 agreed.

Our sincere apology for this @HitmanInWis! Not keeping your name on the lines of code that you contributed was an unintentional side effect or our process, and we'll see how we can best remedy to this going forward so that you and all other contributors get proper credits. We are really thankful for the all contributions from the community, and for yours in particular as it had a very good level of quality. Thank you for your great work on the Accordion component!

**Comment by HitmanInWis** [comment]
Thanks @gabrielwalt except it wasn't me who this post was for.  I actually dont think it's happened for me yet except the opposite direction - a commit was merged as me where some of my co-workers were involved but lost their name on the squash commit, giving me more credit than due.

@joerghoh is it as simple as adding multiple authors to the squash commit?  Does each line of code then simply get credited to all of the people involved?

**Comment by joerghoh** [comment]
@HitmanInWis at least if you merge&squash via the github UI you get the list of commit messages, and there you can add the name of the individual committers. I haven't thought of an automated process yet.

**Comment by vladbailescu** [comment]
As @gabrielwalt said, we're really sorry for not paying enough attention to this. We will be more careful in the future to assign the proper author to the commit. We also decided to provide credits to contributors in the component's readme: https://github.com/adobe/aem-core-wcm-components/commit/3c0117c625d5acadefe4bfc68660af640e14cc28

**Comment by HitmanInWis** [comment]
Thanks @vladbailescu.  What is the consensus on how multi-author commits are squashed in the future?  Seems clicking "Squash and merge" via the interface only credits one author.  Do those need to be merged instead at command line, adding co-authors to the merge commit?

Reason I ask is that as a maintainer of ACS AEM Commons I want to make sure I do it correct in that project as well.

**Comment by richardhand** [comment]
The `Co-authored-by` GitHub trailer feature seems to do what we're looking for here [0][1] although I've never tried it out. Looks like you can just drop them into to a commit message on squash and merge. Does anyone have experience with it?

[0] https://github.blog/2018-01-29-commit-together-with-co-authors/
[1] https://help.github.com/en/articles/creating-a-commit-with-multiple-authors
