### ISSUE TITLE
[Teaser] linkURL not updated when CTA is active

### ISSUE THREAD

**Issue by arnkrist** [adobe/aem-core-wcm-components#652]
## Bug Report

**Current Behaviour**
If the link is edited and then call-to-action enabled, the new value of the now disabled link is not saved. Upon opening the dialogue, the link is unchanged.
This behaviour is not documented in the info bubbles.

**Expected behaviour/code**
Changes to disabled values should be saved

**Possible Solution**
To document the current behaviour in the info bubble: 
`
fieldDescription="Link applied to teaser elements. URL or path to a content page. This field is disabled if CTA is enabled."
`

**Environment**
- AEM version AEM 6.3
- Core Components version 2.4.0
- OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_05_19_02_01-b00)

**Comment by richardhand** [comment]
@arnkrist - thanks for the report! Do you think this is really necessary? The link field is clearly disabled (greyed out) if CTAs are enabled. I think I would prefer to keep these info bubbles succinct, only with information that isn't already obvious.

**Comment by gabrielwalt** [comment]
I'm not considering it to be expected that changes to disabled field get saved. In my opinion, this is an edge case, and improving this behavior wouldn't be the best invested effort.

I'm therefore closing the issue for now, but @arnkrist, feel free to reopen it if this is causing real impediments in your authoring workflows. In that case, please describe why you think that this is necessary.

**Comment by arnkrist** [comment]
Hi @richardhand , @gabrielwalt ,
Thank you for your feedback. I have further discussed this with the client who agree that it is not a critical issue but an outdated link in the disabled field still confuses them.
Best regards,
Arnór

**Comment by gabrielwalt** [comment]
Thanks Arnór for the feedback and information!
