### ISSUE TITLE
[Container] Get children from effective resource

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#655]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When a Container component is used in an editable template as a structural component, it can not be made editable by setting editable="{Boolean}true" on the structure node. The component always renders its own children, which in this case is the nodes children under the template structure.

**Describe the solution you'd like**
Take a page from the responsivegrid behaviour and use the "effective resource" (TemplatedResource) to fetch the children items. If this is done, then the content of the container may either be structural (in the case of non-editable structural Container), or found in the content (in the case of an editable structural Container).

**Are there alternatives?**
Use the OOTB responsivegrid component, this is undesireable because it defeats the purpose of having a Container component, especially when all you want is a Simple Container.

**Example solution**
I have an example of how this can be implements.
I will not submit a PR because I have not fully tested or considered the implications of the following changes; however, it does accomplish the desired outcome:

https://github.com/ky940819/aem-core-wcm-components/commit/fc0120aa3cf6d6a47f2207e6e63b83b1d47e37aa

**Comment by gabrielwalt** [comment]
Hi @ky940819, this sounds very much like a bug as in that case, we want the Container component to have the same behavior than the Layout Container, like you also expect it. Many thanks for having reported it and even proposed a way to fix it! We'll look into this and hopefully solve it for the next release.

If this is blocking your project, please also create a Daycare issue for us to be able to help you in a timely manner.

**Comment by vladbailescu** [comment]
Close by https://github.com/adobe/aem-core-wcm-components/commit/f3fe23361e30e90aa342750251e547617ffa0a90

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
