### ISSUE TITLE
Cannot add components to Accordion (6.4.2)

### ISSUE THREAD

**Issue by wrandall22** [adobe/aem-core-wcm-components#659]
## Bug Report

**Current Behavior**
When I add an Accordion core component to either a static template or a dynamic template, I get javascript errors when clicking `Add`. I have already chosen components to allow either in Design mode (static template) or in the template editor (dynamic template).

**Expected behavior/code**
I expect to be able to add components to the Accordion.

**Environment**
- AEM 6.4 SP2
- Core Components 2.5.0
- Java(TM) SE Runtime Environment (build 1.8.0_211-b12)

**Possible Solution**
It seems the `allowedComponents` parameter being passed in is not being properly populated.

**Additional context / Screenshots**
I tried this on my local and our staging environment as well as spinning up a vanilla 6.4 environment with SP2 applied (the screenshots are from the vanilla).

![Screen Shot 2019-06-27 at 3 41 51 PM](https://user-images.githubusercontent.com/2905714/60295958-03d0c800-98f3-11e9-9c01-55b33bc1db1e.png)

![Screen Shot 2019-06-27 at 3 38 53 PM](https://user-images.githubusercontent.com/2905714/60295948-fddae700-98f2-11e9-9bc9-fe61cf16873d.png)

![Screen Shot 2019-06-27 at 3 38 44 PM](https://user-images.githubusercontent.com/2905714/60295993-11864d80-98f3-11e9-8649-642260f04be7.png)

![Screen Shot 2019-06-27 at 3 39 07 PM](https://user-images.githubusercontent.com/2905714/60295938-f6b3d900-98f2-11e9-936b-d7c940b0b6c6.png)

**Comment by jckautzmann** [comment]
hi @wrandall22 , thx for reporting here. 
I was not able to reproduce this issue. I tested as follows:
Core Components 2.5.0
AEM 6.4 SP2
I also tested with the latest released SP (AEM 6.4 SP4) and with a latest AEM build (6.6)

I tested with a We.Retail page (Equipment) and with the Library Accordion page:
I added an accordion component to the template and I was able to add items (image components) to the accordion. There were no javascript errors in the console.

Could you please detail the exacts steps you used?

**Comment by wrandall22** [comment]
Thanks for the quick response! I also tested this on AEM 6.5 and it worked fine (with the exact same steps).

1. Start up AEM 6.4 with the `aem-author-4502.jar`
2. Close AEM once it is loaded to configure the `crx-quickstart/bin/quickstart` file as follows:
  - Set the JAR location
  - Set the run modes to `author, local`
  - Set the JVM options as such: `CQ_JVM_OPTS='-server -Xmx1024m -XX:MaxPermSize=256M -Xdebug -Xrunjdwp:transport=dt_socket,address=8765,suspend=n,server=y`
3. Run AEM using the quickstart
4. Upload 6.4.2 service pack
5. Upload core components 2.5.0
6. Overlay the `Accordion` core component into the `/apps/weretail/components/content`
  * `jcr:primaryType = "cq:Component"`
  * `sling:resourceSuperType = "core/wcm/components/accordion/v1/accordion"`
  * `jcr:title = "Accordion"`
  * `jcr:description = "Displaying accordion"`
  * `componentGroup = "We.Retail"`
7. Add the accordion clientlib (`core.wcm.components.accordion.v1`) to the embed for `/apps/weretail/clientlibs/clientlib-base`
8. Create a new page using the `/conf/we-retail/settings/wcm/templates/experience-page` template
9. Edit Template
10. Configure the Accordion to allow `General > Experience Fragment` and `We.Retail` components
11. Add an Accordion to the page
12. Refresh the page (because the Accordion doesn't show up at first)
13. Click on the wrench for Accordion
14. Click `Add` button -> javascript error shown above

I also tried a new page using the `/conf/we-retail/settings/wcm/templates/content-page` template.

**Comment by jckautzmann** [comment]
Thx @wrandall22 for the detailed steps. I noticed that the proxy component is missing the following property:
`cq:isContainer="true"`
Could you please add this property and retry?

Note: you should use the latest released Service Pack 6.4.4 instead of SP 6.4.2.

**Comment by wrandall22** [comment]
This property works! Thanks!

**Comment by wrandall22** [comment]
For future people who don't read the documentation well like me, [here](https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion#enabling-accordion-editing-functionality) is the specific line that mentions that.

**Comment by jckautzmann** [comment]
Glad to hear that it now works!
