### ISSUE TITLE
Captcha Component should display placeholder content when authored  - Adobe Forms

### ISSUE THREAD

**Issue by jaydubb12** [adobe/aem-core-wcm-components#662]
## Feature Request

**Description**
As a content  author, I should be able to clearly see that the Captcha component has been authored / configured within and Adobe Forms Container

**Current State**
When the Captcha component is authored, and user is viewing the Form / Form Container in the Forms Authoring View (not the sites authoring view), in "Edit" Mode,  there is no place holder content, only a blank white space between the other components.

Only way an author knows that there is a Captcha component authored is by hovering over the parsys or by looking at the content tree (see screenshot).

Recommend using a simple solution such as the Component Tile as a placeholder to show something has been authored there, given the JS / page will typically not call external services in Edit Mode. That said, other cloud configurations such as Dynamic Media do get called via a Servlet, therefore the ideal state would be to have Captcha Cloud Service config get called on page load within Author to show the widget, with the known domain tradeoff as discussed below.

**Describe the solution you'd like**
Placeholder content to show that a component has been authored / configured

**Potential Trade-offs**
In the author environment, the placeholder content for Captcha already displays an error in "Preview", given the UI is loading using the author domain vs the domain configured for Captcha. Given this is already how the author environment behaves, anticipate an enhancement to improve the view when editing would be a minor, but helpful change.

**Are there alternatives?**
Yes, but none that are value added for authors

**Documentation**
![Captcha Authoring2](https://user-images.githubusercontent.com/21325640/60903887-21315a80-a240-11e9-9796-6e1a2104bc73.png)

**Comment by richardhand** [comment]
Hi @jaydubb12, thanks for the report, these suggestions make sense, but are related to AEM Forms and AEM authoring. There isn't currently have a Form Captcha component in the AEM Core Components project. The same issue can be reported via [Adobe Enterprise Support](https://helpx.adobe.com/contact/enterprise-support.ec.html).
