### ISSUE TITLE
[Text] Set lang attribute in blockquote paragraph style

### ISSUE THREAD

**Issue by patrycjakurkowiak** [adobe/aem-core-wcm-components#669]
## Bug Report

**Current Behavior**
As an author I would like to add information about language used in blockquote in Text component. When I try to configure Text component I can choose 'blockquote' paragraph style but cannot configure this to define the used language. Cannot see possibility for that in policy of this component.

**Expected behavior/code**
When I add blockquote paragraph style (by Text component) on my page I would like to define the language for this quote (lang attribute).
It is related to 3.1.2 WCAG 2.0 accessibility standard
https://www.w3.org/TR/WCAG20/#meaning-other-lang-id
Is there any alternative way to do this?

**Environment**
AEM version 6.5.0
Core Components 2.5.0

**Comment by richardhand** [comment]
@patrickheinzelmann - I believe this is possible if the `sourceedit` feature of the `misctools` plugin in the richtext editor is enabled. That way you can enter source editing mode and add the `lang` attribute as you require:

<img width="867" alt="Screenshot 2019-07-18 at 13 39 52" src="https://user-images.githubusercontent.com/25616660/61454623-acf26780-a961-11e9-9cdf-b313201ac0b6.png">

<img width="876" alt="Screenshot 2019-07-18 at 13 38 49" src="https://user-images.githubusercontent.com/25616660/61454631-b24fb200-a961-11e9-9efc-ac8c147a2eba.png">

<img width="639" alt="Screenshot 2019-07-18 at 13 40 34" src="https://user-images.githubusercontent.com/25616660/61454638-baa7ed00-a961-11e9-997c-aa47c4f0a616.png">


The core component consumes the AEM richtext editor in its dialog, more info on the rich text editor  and its options at https://helpx.adobe.com/experience-manager/6-5/sites/administering/using/rich-text-editor.html.

**Comment by patrycjakurkowiak** [comment]
Thanks for your answer.
I checked that and I can add this attribute in this way.
Thanks.
