### ISSUE TITLE
[Form Container] - Component Throws Error On Submission

### ISSUE THREAD

**Issue by brian-langeland** [adobe/aem-core-wcm-components#674]
## Bug Report

**Current Behavior**
Upon submission of the WCM Core Form Container component, an error appears in the logs. We first experienced this error with our Form Container wrapper of the V2 core version.  I then created the environment referenced below, and recreated the issue with both V1 and V2 versions of the Form Container directly from WCM Core. Each container was configured to "Store Content" and had a Thank You Page configured to redirect to a different page on the site. Each container held a single text field and a submit button of the same version.

V2 Error:
`25.07.2019 10:52:18.665 *ERROR* [0:0:0:0:0:0:0:1 [1564069938642] POST /content/we-retail/language-masters/en/experience/hours-of-wilderness.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource ResourceWrapper, type=foundation/components/form/actions/store, path=/content/we-retail/language-masters/en/experience/hours-of-wilderness/jcr:content/root/responsivegrid/contentfragment/par0/container, resource=[JcrNodeResource, type=core/wcm/components/form/container/v2/container, superType=null, path=/content/we-retail/language-masters/en/experience/hours-of-wilderness/jcr:content/root/responsivegrid/contentfragment/par0/container]`

V1 Error:
`25.07.2019 11:46:18.424 *ERROR* [0:0:0:0:0:0:0:1 [1564073178401] POST /content/we-retail/language-masters/en/experience/hours-of-wilderness.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource ResourceWrapper, type=foundation/components/form/actions/store, path=/content/we-retail/language-masters/en/experience/hours-of-wilderness/jcr:content/root/responsivegrid/contentfragment/par0/container_1506752090, resource=[JcrNodeResource, type=core/wcm/components/form/container/v1/container, superType=null, path=/content/we-retail/language-masters/en/experience/hours-of-wilderness/jcr:content/root/responsivegrid/contentfragment/par0/container_1506752090]`

**Expected behavior/code**
There should not be an error in the logs related to the POST of the form.

**Environment**
- AEM 6.4.5.0
- Core Components version 2.5.0 (tag core.wcm.components.reactor-2.5.0)
- We Retail 3.0.0 (tag we.retail.reactor-3.0.0)
- JRE version (Zulu 8.23.0.3-macosx) (build 1.8.0_144-b01)

**Possible Solution**
N/A

**Additional context / Screenshots**
This error seems fairly similar to an earlier issue reported by a different member of Bounteous.  That issue was when the component was added to the page, and was resolved by following a suggestion in the comments. https://github.com/adobe/aem-core-wcm-components/issues/209

Here are screenshots of the Form Container dialog and components within the container:
![form-container-1](https://user-images.githubusercontent.com/19827408/61901313-1126a580-aee5-11e9-98d4-e8da66bfde7b.png)
![form-container-2](https://user-images.githubusercontent.com/19827408/61901314-11bf3c00-aee5-11e9-87c2-9792d2a4357b.png)

**Comment by brian-langeland** [comment]
I'm also running into an additional issue on form submission where a much lengthier stacktrace is being generated due to `org.eclipse.jetty.io.EofException: Closed`. Not sure if it is related, but it may be. Full stacktrace is attached.
[stacktrace.log](https://github.com/adobe/aem-core-wcm-components/files/3433278/stacktrace.log)

**Comment by andreeadracea** [comment]
Hi @brian-langeland,

Thank you for reporting this problem. I investigated the error and it is generated by an issue from the product and not from form core component. I've prepared a fix for this issue which will be apply on the next version of AEM. If you would like the fix to be applied also on 6.4 version, please contact customer support which can help you with this request.

**Comment by brian-langeland** [comment]
Great. Then I will close this issue and look forward to the hotfix/update in a service pack for AEM 6.5.
