### ISSUE TITLE
[Form] Posted content should not be stored in /content/usergenerated

### ISSUE THREAD

**Issue by HitmanInWis** [adobe/aem-core-wcm-components#676]
Please correct me if I'm wrong and missing out on some inherent security features of AEM or the Forms Container itself - in fact, I hope I'm dead wrong on this all, because I want to believe this is not a "smoke and mirrors" product that we are promising clients but then have to re-implement with custom development for any of them that want to use it.

The Forms Container seems to be a pretty huge security risk waiting to happen for any site that authors use it on.

For starters, content saved from the forms is fully readable to anonymous traffic to the URL
- At best this is "security by obscurity"
    - In cases where `.1.json` or `.xml` are enabled (they shouldn't be in prod, but I've seen it on non-Bounteous projects) this content can easily be fetched by starting from the known `/content/usergenerated/*` path and drilling down.
- At worst an author chooses a predictable URL that can be guessed OR
- At worst an internal user (either malicious or after being let go by a company) leaks the information to the internet or even keeps for their own purposes

Even if the `/content/usergenerated` path is secured by the dispatcher (which it isn't by standard configs documented by Adobe), the Forms Container does nothing to validate that the author has chosen a path under that URL, so even protecting via the dispatcher is no guarantee.  That said, the OOTB AEM permissions do seem to prevent saving of form data to an unexpected place by limiting the permissions of the service user saving the data, but relying on that as the only line of defense and allowing authors to try to put form data in disallowed locations is an incomplete implementation.

On top of this all, authorable forms give authors a loaded gun to shoot themselves in the foot with in terms of PII data and regulations like GDPR.  I know there's no fool-proof way to programmatically prevent authors from saving private content unknowingly and illegally in AEM, but giving them a Form component in WCM Core that says absolutely nothing about it can only give the impression to authors that whatever they want to do with it must be okay.  This is especially true when Adobe makes claims such as the system being GDPR compliant, because one false move by an unknowing junior author is going to subvert that claim.  At the very least it feels like the component should:
- Have some documentation around it regarding the high risk of untrained authors storing inappropriate data paired with the ease in which it can be done.
- Restrict form components to a special role that indicates "power user" or even something along the lines of "data-privacy-manager".
- Adding warnings to the authoring dialog to remind authors of the security implications of what they choose to save
- Add warning to the Form Container configured to "Store" mode when rendered in Edit mode to remind the author (since they wont be opening the container dialog to add a new field)

I've not even yet checked the other form modes (e.g. Email) to see if they temporally save their data in AEM, creating even further PII/GDPR concerns.

Want to get some thoughts on this all from others in the community.  Again, really hoping I'm just overlooking something and making a bigger deal of this than I really am, because if not I think the form components should be removed until the issues are addressed.

**Comment by stefanseifert** [comment]
what you are referencing to is the old "foundation forms backend" implementation, a relic of the old foundation components from the days of geometrixx. the core components currently only provide a new set of HTML components that send or store the data using this old backend. there are plans to replace it (see #56, but i'm not sure how high it is on the priority list).

this old forms backend provides other ways than storing the data in the repository, and i agree that storing the data in the publish instance is a very bad idea and should not be used at all. it's up to the developer who sets it up in which way the data is processed. sending the data per mail may be better when you have full control over the mail server an can ensure it's not sent anywhere unencrypted.

btw, imho a better place for high-level discussions like this is the [mailing list](https://github.com/adobe/aem-core-wcm-components#mailing-list).

**Comment by HitmanInWis** [comment]
Interesting - didnt know about the mailing list - maybe I will put this out to there.

I understand that the Forms implementation here is simply pointing back to an old backend, but I dont think that absolves the library from responsibility.  The component should not be labeled "production-ready" if it *requires* significant development (none of which is noted) to avoid security vulnerabilities.  I'll go so far as to say it's borderline unethical to promote that WCM Core has Forms support in its current state.

Ideally something like #56 would be fixed in the core AEM platform. Until then, I still feel that something should be done with the WCM Core implementation, else people are going to unknowingly be adding this vulnerability to their platform.

**Comment by gabrielwalt** [comment]
Hi @HitmanInWis,

I think that we'll need to deprecate the storage handler that stores it it `/content/usergenerated`, because this is not recommended anymore. And on the other hand, we'll have to document how to implement a POST handler that sends the data to the customer's marketing automation or CRM tool.

Best,
Gabriel

**Comment by HitmanInWis** [comment]
Thank you @gabrielwalt for your quick response.  I agree with the plan forward.

**Comment by JasonUSC** [comment]
Maybe the documentation could show how to implement a POST handler that sends the data to Adobe Campaign as an example? ;-)

**Comment by vladbailescu** [comment]
A proper fix would require adding a new POST option for the form content and providing some support/scaffolding for implementing a POST handler. Most probably, we will need a new version of the Form Container. I'll mark this issue to be tackled when we decide to rework the form components.

**Comment by bpauli** [comment]
Handler to post form data to remote endpoint was implemented in https://github.com/adobe/aem-core-wcm-components/issues/1154. Please create follow up issue if needed.
