### ISSUE TITLE
Form Container - "store" mode not production-ready - data not auto-sync'd across publish servers

### ISSUE THREAD

**Issue by HitmanInWis** [adobe/aem-core-wcm-components#677]
**NOTE: This is in addition to security concerns: https://github.com/adobe/aem-core-wcm-components/issues/676

The default "Store" mode for the Form Container simply saves the submitted content to the current publish server, which is not sync'd with the other publish servers.  As far as I'm aware, this is not documented anywhere in WCM Core, but what it means that for any implementation on a standard AEM architecture (which has at least 2 publish servers) Forms will likely require additional engineering before they can be used.

Unless I'm mistaken on this, Adobe should be more transparent on components such as the Form Container that *require* additional engineering, else implementors end up taking the heat when clients who purchased AEM with the promise of new WCM Core components that do everything they need turns out to be untrue and require budget and time to resolve.  And that's actually the best case scenario - worst case is an unfamiliar/less experienced implementor that doesnt catch this fact until deployed to production and then has to scramble to resolve.

Beyond documentation of the fact that development is required, a standard process for this to be implemented would be ideal.  There's no reason that the process for sync'ing submitted form data across all publish servers shouldn't be standardized, even if there are caveats for sites with extreme amounts of traffic/data.

**Comment by gabrielwalt** [comment]
I'm closing this as the resolution will be to deprecate this storage handler. See #676.
