### ISSUE TITLE
Does AEM provide Text direction (from right to left)?

### ISSUE THREAD

**Issue by patrycjakurkowiak** [adobe/aem-core-wcm-components#678]
## Question
Hi,
Do you provide some option related to text direction? Is there option to insert text from right to left?

**Environment**
AEM version 6.5.0
Core Components 2.5.0

**Comment by gabrielwalt** [comment]
This question is not related to the Core Components, but to AEM in general. There's no specific text direction option, but with Unicode, this shouldn't be much of an issue. If you need more specific help around this, please open a Support ticket to request for help.

**Comment by gabrielwalt** [comment]
In case you also need more explicit text editor features than relying on Unicode to control the text direction, you can also have such things in AEM's Rich Text Editor (RTE):
https://forums.adobe.com/message/10478347

And the following might also help:
https://stackoverflow.com/questions/38048330/how-to-enable-right-to-left-support-in-adobe-aem-text-component
