### ISSUE TITLE
[Image] Broken image when the quality property is set without smart widths

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#679]
## Bug Report

**Current Behavior**
When setting only the JPEG quality without setting any smart widths, the image is broken.
Note: when setting one or more smart widths, the image renders correctly.

Steps to reproduce:
1. Go to the We.Retail Experience Page template.
2. Add policy to heroimage component at the top (not to the one inside the Layout Container. Select jpegquality as ‘100’.
3. View content/we-retail/language-masters/en/experience/arctic-surfing-in-lofoten.html after clearing browser cache. Notice Hero Image is broken.
4. If you had 82 for image quality, the image renders correctly.

I was able to reproduce this issue with the v2 image component from the Component Library:
http://localhost:4502/editor.html/content/core-components-examples/library/image.html

**Expected behavior/code**
When setting only the JPEG quality without setting any smart widths, the quality property should be applied to the original image.

**Environment**
- current AEM build
- Core Components version: 2.5.0

This issue was created following some feedback from the following thread in our email list:
https://groups.google.com/d/msgid/aem-core-components-dev/b51aa3db-a151-42e1-87ce-0a238ab06c18%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by kwin** [comment]
Please note that the quality is anyways only effective under certain conditions: https://github.com/adobe/aem-core-wcm-components/issues/472.

**Comment by richardhand** [comment]
Verified, code is merged to master and will be available in the upcoming [2.7.0 release](https://github.com/adobe/aem-core-wcm-components/milestones).
