### ISSUE TITLE
[Carousel][Accessibility] Rotation control buttons are not the first element in carousel and pause on focus issue

### ISSUE THREAD

**Issue by jakublamprecht** [adobe/aem-core-wcm-components#681]
## Bug Report

**Current Behavior**
It seems that based on this: 

https://www.w3.org/TR/wai-aria-practices/#carousel
https://www.w3.org/TR/wai-aria-practices/examples/carousel/carousel-1/carousel-1.html

carousel component has some accessibility issues that might require new version of carousel to be released:

- Rotation control buttons (play/pause) are not the first elements in markup of carousel, which requires the user to tab though all of the content before they can pause the carousel
- carousel does not pause when elements inside carousel (Except rotation control buttons) get focus.

**Expected behavior/code**

- Rotation control buttons are the first elements of carousel when we tab through the page
- Carousel pauses if it was playing automatically and an element inside carousel which is not rotation control button gets focused

**Environment**
- Core Components version (e.g. 2.5.0)

**Possible Solution**

Fixing the issue with pause on focus might require changing markup in such a way, that the rotation control buttons are outside of the `cmp-carousel__content`, so that checking whether the focus is inside carousel and not on the rotation control buttons can be done on the `cmp-carousel__content` wrapper instead of on each of elements separately. This also will make sure that these buttons are first in the tab order. Here's a sample markup structure:

```
<div class="cmp-carousel">
  <div class="cmp-carousel__actions cmp-carousel__actions--rotation-control>
    <play/pause buttons here>
  </div>
  <div class="cmp-carousel__content">
    <div class="cmp-carousel__actions cmp-carousel__actions--slide-control>
      <next/prev buttons here>
    </div>
    ...rest of the markup
  </div>
</div>
```

**Additional context / Screenshots**
If these changes are to be made and a new version of carousel would be to be released, the issue with wrapper (#573 ) could also be applied.

**Comment by gabrielwalt** [comment]
Let's try to fix this as follows:
* try to set the tab index so that the play/pause buttons are navigated to first.
* fix the play/pause when tabbing through the content, ideally rotating the carousel to the item that gets tabbed to.
