### ISSUE TITLE
[Teaser] Configure title type on component dialog

### ISSUE THREAD

**Issue by bmalecki** [adobe/aem-core-wcm-components#684]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Teaser component allows authors to select `Title Type` only on policy dialog.

**Describe the solution you'd like**
As an author I would like to have the possibility to change `Title Type` on component dialog. Please consider adding this field.

**Are there alternatives?**
- Adding styles in the policy (requires writing some specific css classes)
- Creating templates with different polices
- Creating proxy components form Core Components Teaser

**Comment by nathanmckean** [comment]
Agree. This functionality should be universal across any components using headings (h1-6) not just teasers. The heading that I need is contextual to where it sits in the page. Placed under an H2, the titles should be H3. Placed under an H3, the titles should be H4, etc.

**Comment by gabrielwalt** [comment]
+1, this would make sense! Your contribution is welcome if you have the possibility to create a PR for improving this.

**Comment by nathanmckean** [comment]
Im an UX guy and a Github noob. I know what PR stands for, but that's about it sorry :(

**Comment by cjelger** [comment]
Fixed by #1199
