### ISSUE TITLE
[Page] Make head more customizable

### ISSUE THREAD

**Issue by henrykuijpers** [adobe/aem-core-wcm-components#685]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When trying to override the title, description and keywords, we have to override the whole https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/head.html file. We would however like to override only the specific parts that we want to customize, so we can still leverage all other code OOTB.

**Describe the solution you'd like**
More fine-grained control in overriding parts of the header/footer/...

For example:
* Make the page component, instead of putting the title etc. in head.html, include page-metadata.html (that includes title etc)
* Do the same for other things
* Then we can, in our page component, override page-metadata.html and do our custom title etc over there.

**Are there alternatives?**
* Overriding head.html, but this will make us do that only to customize 3 lines + we will have to maintain that override to be in-sync
* Writing a transformer to remove title, description and keywords, and then use customheaderlibs.html to add our custom title logic -- but this feels so very wrong I cannot even explain it

**Documentation**
Technical

**Comment by henrykuijpers** [comment]
I agree, @vladbailescu , this ticket could also create a better overriding mechanism for the viewport logic. 

Any input on this ticket, though? I was thinking of the following solution:
* `head.html` does not include `<title>`, `<meta description>` and `<meta keywords>` anymore
* `head.html` instead includes `head.metadata.html`, which makes a template called `headMetadata` available, that then is called in `head.html` with the `page` object as an argument
* Users can overwrite head.metadata.html in any page component to supply a new template with additional / replacing logic

The same could be done for the viewport tag.

Any comments?

**Comment by vladbailescu** [comment]
Or we could break it down into `head.charset.html`, `head.title.html` and `head.metadata.html`. We could even add a `custommetadata.html` to make it easier to append.

**Comment by bpauli** [comment]
We should avoid to break down the page component in even more HTL files. Otherwise we will end up like the old foundation page component which is splitted in 17 JSP files which makes it really hard to understand and to maintain. I don't understand why this is not a valid use case to override the head.html file. With the versioning we can make sure that the custom head.html file will work with future versions of the core-components as well.

**Comment by richardhand** [comment]
I'm also with @bpauli that we shouldn't introduce too many templates to the point where the component isn't readable at a glance / is hard to understand.

If we do want an extension point for metadata however, I'm +1 for a single `head.metadata.html` rather than a full fine-grained approach.

**Comment by henrykuijpers** [comment]
Ok, so how do you have the extension point in mind then? 

It's pretty common to have a project where aem functions as a proxy for rendering content inside its templates etc. To do everything right, you want to influence i.e. the title tag, the breadcrumb, etc. 

Overriding the page component could be an option, but in our case we want to replace the <title> tag with a SSI include tag. Something that can't be done by just overwriting the page model.

**Comment by gabrielwalt** [comment]
Closing this as there doesn't seem to be a consensus on how the extension points should work.
