### ISSUE TITLE
[Image] Property isDecorative should be exposed by getter

### ISSUE THREAD

**Issue by bmalecki** [adobe/aem-core-wcm-components#686]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Protected field `isDecorative` is used in ImageImpl's but is not exposed by getter in Image service. When I want to override Image model using ResourceSuperType pattern I need to get this property one more time from JCR.

**Describe the solution you'd like**
Add isDecorative getter to Image.java service and implement it in v1/ImageImpl.java

**Are there alternatives?**
- getting isDecorative property from JCR in own Image model.

**Comment by harshsingla** [comment]
hi @bmalecki  ,can you please explain more about the problem

**Comment by AayushG159** [comment]
I would like to take up this issue.

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
