### ISSUE TITLE
[Architecture] Allow context aware config for edit dialogs

### ISSUE THREAD

**Issue by peterps-health** [adobe/aem-core-wcm-components#69]
Given I am a content author in US
Then all my /content/company/locales in all components are pre-filtered to US

Given I am a content author in Japan
Then all my /content/company/locales in all components are pre-filtered to Japan

Currently, we need to overlay dialog to have different starting path. Which is kind of inefficient as we end up with lots of overlays that all do the same thing, change paths.

It would be much more efficient to define context aware configs for dialogs.

**Comment by jmanuelbr** [comment]
It would be great to include this feature as I am facing the same issue: white label components reused in specific regions need to overlay component's dialog merely to customise the rootpath of pathbrowser, etc.

**Comment by henrykuijpers** [comment]
+1! Customizing the root paths for example would be very nice.

**Comment by gabrielwalt** [comment]
(CQ-4247363)

**Comment by gabrielwalt** [comment]
Closing this issue for now as it is inactive.
