### ISSUE TITLE
Edit content fragment/ content fragment list directly from template

### ISSUE THREAD

**Issue by surya057** [adobe/aem-core-wcm-components#690]
Problem statement:
If the author wants to change the content in content fragment in the page means, He needs to search for that particular content fragment in the DAM and edit it. 
This searching task will become more complex when the number of content fragments increases.

Solution:
In page, In the content fragment component toolbar, a new option will be added and onclick that icon will take the author to content fragment edit mode in the new tab.

I have above implementation with me. Please let me know if there is any other way to achieve this.

**Comment by surya057** [comment]
Hi Team,
I am trying to commit my changes but I am getting permission denied message as below.
what I should do for this? Please suggest.
![image](https://user-images.githubusercontent.com/12661298/62793394-6bb92780-bac9-11e9-9b3a-507a36801968.png)

**Comment by vladbailescu** [comment]
@surya057, you can fork the project to your account, push the changes to a branch into your fork and then submit a pull request.

**Comment by surya057** [comment]
@vladbailescu Thank you.

**Comment by surya057** [comment]
@vladbailescu: The enhancement which has provided is project-specific, So I gave fix in the we-retails project. Please let me know this can be added. 
I created new PR - https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/pull/164

**Comment by surya057** [comment]
Hi, My enhancement is project-specific so added in we.retails code.

https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/pull/164

**Comment by msagolj** [comment]
@surya057, I'm not sure I understand what you try to achieve. This PR and the one to We.Retail are basically the same, either applied to the core comp or the We.Retail proxy. So I guess one or the other should be closed, no ?

If you plan to add it only to We.Retail then: Whats to the point of showing a feature that is not available in the product but only on an example site ?

**Comment by msagolj** [comment]
Closing this issue as @surya057 moved the code to we.retail, and there is already an edit button for editing the content fragment from the toolbar.
