### ISSUE TITLE
[Teaser] Description is editable even though "Get description from linked page" is checked

### ISSUE THREAD

**Issue by PublicisMaikLindner** [adobe/aem-core-wcm-components#693]
## Bug Report

**Current Behavior**
In a teaser it is possible to click into and change the description-field (under text) even though "Get description from linked page" is checked:

<img width="516" alt="Bildschirmfoto 2019-08-14 um 12 55 35" src="https://user-images.githubusercontent.com/52775439/63016279-8dccf400-be93-11e9-8e62-3898695890d5.png">

This only happens after setting that option, click on done and then reedit the teaser. Any text, which is entered, also is saved when you click on done (even if it's not visible).

**Expected behavior/code**
The description-field should be initialized correctly in dependency of the checkbox "Get description .." (like it is done when you click it in the teaser):

<img width="516" alt="Bildschirmfoto 2019-08-14 um 12 54 54" src="https://user-images.githubusercontent.com/52775439/63016413-e8fee680-be93-11e9-9d97-94f79ab18ca9.png">

**Environment**
- AEM version and patch level: 6.4.2.0
- Core Components version: 2.5.0

**Possible Solution**
Check the status of the checkbox while opening the configuration dialog and call the same code which is called when pressing that checkbox.

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
