### ISSUE TITLE
[Download][Page] Locale issues when parsing dates in Java test cases

### ISSUE THREAD

**Issue by msagolj** [adobe/aem-core-wcm-components#697]
## Bug Report

**Current Behavior**
```DownloadServletTest#tesNotModifiedResponse``` fails, because parsing of the Header ```If-Modified-Since``` fails in
https://github.com/adobe/aem-core-wcm-components/blob/e4eee2388bb413bff85669f0b9753d15938f6cd6/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/DownloadServlet.java#L176

This is due the locale not being explicitly set to ```Locale.US``` causing it to fail on my machine.

**Expected behavior/code**
- All request headers containing dates should be properly parsed.

**Environment**
- Core Components 2.5

**Possible Solution**
Wherever ```new SimpleDateFormat(RFC_DATE_FORMAT) ``` is used, explicitly set the locale e.g. ```new SimpleDateFormat(RFC_DATE_FORMAT, Locale.US) ```

see also 
https://github.com/adobe/aem-core-wcm-components/blob/e4eee2388bb413bff85669f0b9753d15938f6cd6/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/DownloadServlet.java#L166

- Also the typo in the test name can be fixed
- maybe the catch for the ParseException should log an error

**Comment by msagolj** [comment]
(CQ-4277341)

**Comment by Patil2099** [comment]
@msagolj  Can I Work on this?

**Comment by msagolj** [comment]
@Patil2099 sure :)

**Comment by richardhand** [comment]
Reopening here as the issue still requires verification

**Comment by richardhand** [comment]
Code is merged to [master](https://github.com/adobe/aem-core-wcm-components/commits/master) and will be available in the upcoming [2.6.0 Release](https://github.com/adobe/aem-core-wcm-components/milestone/16).
