### ISSUE TITLE
[Content Fragment List] Display in a specific order

### ISSUE THREAD

**Issue by surya057** [adobe/aem-core-wcm-components#698]
## Bug Report

**Current Behavior**
When author configured content fragment list, Content fragments displayed in desc order of lastModified. Whenever the author updated the content fragments inside the content fragment list this display order will change. 

**Expected behavior/code**
When the author updates the content fragment inside the content fragment list. Display order should not change it should remain the same. 

**Environment**

**Possible Solution**
To provide a consistent display order, Have to add orderby predicate in query builder that generates content fragment in ContentFragmentListImpl.java.

**Comment by msagolj** [comment]
verified on master branch
