### ISSUE TITLE
DownloadServlet loads complete assets into heap

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-core-wcm-components#700]
## Feature Request

The DownloadServlet is loading the complete asset into memory (a byte[] array) before it is written to the OutputStream of the response.
This allocation requires a huge memory block, which can lead to massive GC activity with potential OutOfMemory situations.

The DownloadServlet should be improved so it streams the asset directly from the repository to the response, without allocating large portions of memory.

**Comment by joerghoh** [comment]
See https://github.com/adobe/aem-core-wcm-components/pull/701 for a PR

**Comment by msagolj** [comment]
Verified on master branch
