### ISSUE TITLE
Request WebFonts from AEM instead of from Google CDN

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#707]
## Feature Request

**Is your feature request related to a problem? Please describe.**
GDPR compliance of Google Fonts hosted by Google is at least questionable (https://github.com/google/fonts/issues/1495)

**Describe the solution you'd like**
By default the web fonts should be hosted in AEM. Only optionally (via page content policy) requesting them from the Google CDN should be possible.

**Are there alternatives?**
None I could think of.

**Comment by richardhand** [comment]
Code is merged to [master](https://github.com/adobe/aem-core-wcm-components/commits/master) and will be available in the upcoming [2.6.0 Release](https://github.com/adobe/aem-core-wcm-components/milestone/16).
