### ISSUE TITLE
[Download] Ensure download component has a valid asset reference or file upload

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#712]
evaluate if download has content by checking the "filename" property - it contains only a value if an asset reference or upload is present and valid
eliminate the checks for title, description and action text - a download component without any of these is fine, but any of these without a valid download does not make sense

**Comment by richardhand** [comment]
Fixed in #706

**Comment by msagolj** [comment]
Code is merged to [master](https://github.com/adobe/aem-core-wcm-components/commits/master) and will be available in the upcoming [2.6.0 Release](https://github.com/adobe/aem-core-wcm-components/milestone/16).
