### ISSUE TITLE
Restrict what to install from ACS Commons

### ISSUE THREAD

**Issue by niksvers** [adobe/aem-core-wcm-components#714]
### Query
I'm new to using ACS Commons in a project and was wondering if there's way I can restrict/filter what I want to install from ACS Commons.

### Example
For example, I want to install the OSGi bundle & certain resources under '/var/acs-commons/reports', but not other resources such as : '/apps/cq/core/content/nav/tools/acs-commons'. Is there a way to do this?

### Background
I'm installing ACS Commons via maven as a subpackage. I think the best would be if such filters could be added under the maven POM <subpackage> tag where one can specify what to path(s) to install from the subpackage. Kind of like a way to override the filters specified in the ACS Commons package itself.

**Comment by msagolj** [comment]
Hi @niksvers , i think your posting this to the wrong git project , this is AEM Core Components :)

I guess you wanted to post it here maybe ? : 
https://github.com/Adobe-Consulting-Services/acs-aem-commons

**Comment by niksvers** [comment]
Ah damn! Wake up Nikhil! [X.X]
