### ISSUE TITLE
[Teaser] Title changes reset after adding a link

### ISSUE THREAD

**Issue by PublicisMaikLindner** [adobe/aem-core-wcm-components#719]
## Bug Report

**Current Behavior**
When I configure a teaser-component and I edit the title (the checkbox "Get title from linked page" is not activated), it is reseted after I choose a link:

1. <img width="550" alt="Bildschirmfoto 2019-08-30 um 15 20 49" src="https://user-images.githubusercontent.com/52775439/64024201-1e652e80-cb3a-11e9-999e-279ce7c3f215.png">
2. <img width="550" alt="Bildschirmfoto 2019-08-30 um 15 21 01" src="https://user-images.githubusercontent.com/52775439/64024225-2c1ab400-cb3a-11e9-82e6-fbc7e141f7da.png">
3. <img width="550" alt="Bildschirmfoto 2019-08-30 um 15 22 02" src="https://user-images.githubusercontent.com/52775439/64024237-3472ef00-cb3a-11e9-8519-9a01beaf51d3.png">
4. <img width="550" alt="Bildschirmfoto 2019-08-30 um 15 22 12" src="https://user-images.githubusercontent.com/52775439/64024250-3b016680-cb3a-11e9-80fb-ebba6c97f640.png">
5. <img width="550" alt="Bildschirmfoto 2019-08-30 um 15 20 49" src="https://user-images.githubusercontent.com/52775439/64024256-40f74780-cb3a-11e9-80da-30b926668d0e.png">

It doesn't matter if I use the picker or just type the link into the field.

**Expected behavior/code**
Changes to the link should not reset the title.

**Environment**
- AEM version: 6.4.2.0
- Core Components: 2.5.0

**Comment by richardhand** [comment]
Thanks @PublicisMaikLindner for the bug report, I've been able to confirm the behaviour.

**Comment by niranjanib** [comment]
Hi I would like to take a shot on this bug, if that's okay?

**Comment by msagolj** [comment]
verified on master branch
