### ISSUE TITLE
[Accessibility] Support setting Anchor target attribute for all editable links

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#725]
currently several components allow to define a link target (internal page or external URL) in their edit dialogs, but it's not possible to define a "target" attribute for the anchor tag e.g. to open the link in a new tab/window.

the following components are affected:
* Button
* Image
* Teaser and Teaser Actions
* Title

proposal for the implementation:
* add a common/shared dialog fragment currently consisting of the link URL page field and a select field to select from "self" (default) or "new tab/window" option.
* this shared dialog fragment is included in the edit dialogs of the mentioned components, preferably in a new tab to separate it from the other edit options, and it's possible that new features are added to it in the future or by downstream libraries/applications
* the JS logic that currently hides/displays the link URL field currently in some dialogs needs to be adapted as well
* the window target needs to be stored in the property already added in #713 - then is should work without any further markup changes

this makes #625 obsolete

**Comment by stefanseifert** [comment]
i will come up with a PR for this in the next time.

**Comment by stefanseifert** [comment]
with the new features from #713 underneath this should be easy. what is the exact property you expect to be set on the anchor tag?

**Comment by jakublamprecht** [comment]
I think that the title attribute would be the best way to do this, as it is read additionally, right after the text defined within the link.

**Comment by richardhand** [comment]
As I understand, the `title` attribute is no silver bullet solution here, due to it only being surfaced on pointing devices for visual users and having inconsistent screen reader support (although I don't have a full idea of how that support looks).

The HTML spec [0] discourages its use for this purpose:

> Relying on the title attribute is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification (e.g. requiring a pointing device such as a mouse to cause a tooltip to appear, which excludes keyboard-only users and touch-only users, such as anyone with a modern phone or tablet). 

[0] - https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute

**Comment by tjameswhite** [comment]
@jakublamprecht is correct, there needs to be some mechanism to let assistive technology users know the link opens in a new window/tab. I'm implementing a solution for our custom components and was trying to figure out how to get it on Core as well. 

I'm currently adding `aria-describedby="new-window"` to the `<a>` which then references this block hidden in the page template: 
```
<div hidden>
 <span id="new-window">${'opens in new window' @ i18n}</span>
</div> 
```

This lets me translate the text and provide accessibility. Obviously this works for our situation and components -- I'm not sure how to extend it for Core Components.

Additionally, links that open in a new windows should have `rel="noopener"` on them. 
https://web.dev/external-anchors-use-rel-noopener/

**Comment by rajeevyadav2** [comment]
@vladbailescu : When this feature will be released?

**Comment by glasert** [comment]
@adobe export issue to Jira project SITES as Story
