### ISSUE TITLE
[Accordion][Carousel][Tabs] ./cq:isContainer="true" is in String format, should be Boolean

### ISSUE THREAD

**Issue by surya057** [adobe/aem-core-wcm-components#732]
## Bug Report

**Current Behavior**
Current "cq:isContainer" property of the Carousel component is a String type.

**Expected behavior/code**
This property should be Boolean

**Environment**
- AEM 6.5
- Core Components version - 2.6
- build 1.8.0_152

**Possible Solution**
Change the property type to boolean.

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by surya057** [comment]
My mistake please ignore this. I will check and get back.

**Comment by surya057** [comment]
Hi, Adobe help doc says this property is the type of string. But when I try to add this property to my component, I am unable to add this property. Getting an error message saying "property must be of type Boolean" in crx/de. Can someone please clarify this?.

![image](https://user-images.githubusercontent.com/12661298/64690253-d920f500-d487-11e9-93a2-19b21f3959c3.png)

**Comment by richardhand** [comment]
@surya057,

> Adobe help doc says this property is the type of string
Could you please post the help doc you are referring to, according to [0] they should be `Boolean` as you describe.

> Change the property type to boolean.
Agree, but we should update all component that use this property: Accordion, Carousel, Tabs, and the Component Library Demo component.

[0] - https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/custom-nodetypes.html

**Comment by surya057** [comment]
Yes, I will share PR. 
This is the helpx doc i mentioned - https://helpx.adobe.com/uk/experience-manager/6-3/sites/developing/using/components-basics.html.

Thank you,
@richardhand

**Comment by richardhand** [comment]
@bohnertchris - seems like these docs should be in line with each other:
• https://helpx.adobe.com/uk/experience-manager/6-5/sites/developing/using/components-basics.html
• https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/custom-nodetypes.html

with regard to the `./cq:isContainer` format being Boolean.

**Comment by msagolj** [comment]
verified on master branch

**Comment by bohnertchris** [comment]
> @bohnertchris - seems like these docs should be in line with each other:
> • https://helpx.adobe.com/uk/experience-manager/6-5/sites/developing/using/components-basics.html
> • https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/custom-nodetypes.html
> 
> with regard to the `./cq:isContainer` format being Boolean.

Thanks for pointing this out, @richardhand. This was addressed in CQDOC-14959 and the corrections are now live, but might take a bit to propagate to the 6.4 content.
