### ISSUE TITLE
[Image] Getting 404 response for SVG assets when image quality is not set to default

### ISSUE THREAD

**Issue by mmange** [adobe/aem-core-wcm-components#735]
## Bug Report

**Current Behavior**
Enable Image component for an editable template (in layout container)
Create a page using the template and Add Image component
Add an SVG Image from DAM to the image component
 - The SVG Image will display
Now go to template, and add a policy for the image component
In the image policy - quality is required field so configure 100 on the quality. 
Reload the page, you'll see the image will not show (it gets a 404)

Upon inspecting the logs, I noticed 

com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServlet The requested quality (82) is not allowed by the content policy.

I updated the JPEG Quality on policy to 82 and the image started showing (not getting a 404 anymore). 

**Expected behavior/code**
The svg image should show regardless of what is set on the quality 

**Environment**
- AEM 6.5.0
- Core Components version: 2.6.1-SNAPSHOT

**Comment by bpauli** [comment]
This issue is also related to #679

**Comment by richardhand** [comment]
Verified, code is merged to master and will be available in the upcoming [2.7.0 release](https://github.com/adobe/aem-core-wcm-components/milestones).
