### ISSUE TITLE
[Container] Not possible to define policies for allowed components in editable template

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-core-wcm-components#736]
## Bug Report
**Current Behavior**
Scenario: A proxy component of the Container v1 component is created like this:
```javascript
{
  "jcr:primaryType": "cq:Component",
  "jcr:title": "Container",
  "componentGroup": "my-component-group",
  "sling:resourceSuperType": "core/wcm/components/container/v1/container",
  "cq:isContainer": true
}
```
It is defined as unlocked structure component in an editable template, and some components are allowed in it's component dialog.
But although the component is unlocked it shows no "button" for the allowed components, and thus does not allow to define policies for the allowed components in the container.

The problem is not visible in the component library because there the container component is not inserted as structure component in the editable template.

**Expected behavior/code**
The container should behave exactly the same as the General / Layout Container component in editable template mode, allowing to define policies for the allowed components.

**Environment**
- AEM 6.5.0
- Core Components 2.6.0

**Possible Solution**
If i statically change the container.html to only include responsiveGrid.html _and_ if i remove the surrounding DIV with class=cmp-container in responsiveGrid.html the allowed component buttons are displayed. The same "hack" does not work with simple.html. And it is no solution anyways as it breaks the markup and background features.

**Additional context / Screenshots**
See screenshot for comparison:
![container-allowed-components](https://user-images.githubusercontent.com/5614031/64820155-197b9280-d5b0-11e9-8bd8-22fc045a27bc.png)

**Comment by richardhand** [comment]
This is verified, merged to master and will be included in the upcoming [2.7.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/17).
