### ISSUE TITLE
[Teaser] Image path is pointing to component location not image location

### ISSUE THREAD

**Issue by surya057** [adobe/aem-core-wcm-components#738]
## Bug Report

**Current Behavior**
In teaser component's JSON structure, "imagepath" is pointing to teaser component location, not image location.

 Sample output:
{
  "title": "Teaser Title",
  "description": "<p>Teaser Description</p>\r\n",
  "actionsEnabled": false,
  "imageLinkHidden": false,
  "titleLinkHidden": false,
  "actions": [],
  "imagePath": "/content/core-components-examples/library/teaser/jcr:content/root/responsivegrid/demo_1160408466/component/teaser",
  ":type": "core/wcm/components/teaser/v1/teaser"
}

**Expected behavior/code**
"imagepath" in JSON should show image location not component location.

**Environment**
- AEM 6.5
- Core Components version 2.6.1
- Java(TM) SE Runtime Environment (build 1.8.0_152-b16

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

Even in the documentation, I can see the same behavior.
https://opensource.adobe.com/aem-core-wcm-components/library/teaser.html

In JSON I should see image location in "imagepath" property,
But I am seeing the component location in "imagepath" property. I think this is a bug.  
Please confirm this request.

**Comment by surya057** [comment]
Hi,
Can someone please update is this valid or not.
Thank you

**Comment by bpauli** [comment]
@surya057, Indeed this make no sense. I create a PR to fix the issue at https://github.com/adobe/aem-core-wcm-components/pull/743. Thanks for the hands up!

**Comment by surya057** [comment]
@bpauli Thank you.

**Comment by msagolj** [comment]
verified on master branch
