### ISSUE TITLE
Richtext configuration to send text alone in JSON exporter without any HTML tags

### ISSUE THREAD

**Issue by surya057** [adobe/aem-core-wcm-components#746]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When we export a richtext component through JSON, we could see HTML tags getting added to richtext value. Can we add an option to remove that HTML tags from JSON alone, please?

**Describe the solution you'd like**
Add checkbox in a dialog and when the author enabled that option and when we call the model.json page where richtext is configured, TextImpl.java getter method should give trimmed text without any HTML tags in it. 

Can we use this for all places where rich-text is available in core components?, like- "Teaser" component. 

**Are there alternatives?**
No

**Documentation**
If you can, explain how users will be able to use this and possibly write out a version of the docs.
Maybe a screenshot or design?

**Comment by bpauli** [comment]
@gabrielwalt Can you please provide your input on this? Instead of inside the edit dialog I would prefer a checkbox in the design dialog so that a template author can create policy to remove the HTML tags in the JSON output. WDYT?

**Comment by gabrielwalt** [comment]
This would rather require a Markdown mode for the rich text editor, which isn't a Core Component module. Closing this issue for now.
