### ISSUE TITLE
[Embed] Invalid Pinterest ID makes component uneditable

### ISSUE THREAD

**Issue by msagolj** [adobe/aem-core-wcm-components#750]
## Bug Report

**Current Behavior**
- you can set an invalid Pin ID
- the embed component wont render anything anymore
- you can no longer edit the component

**Expected behavior/code**
The Pinterest implementation should either:
- like the oEmbed implementations, do a check if there is a valid response when validating the URL in the edit dialog
- show an error message in HTML 
- show the url (gets replaced by Pinterest script if valid)

**Additional context / Screenshots**
See attached video
[embed_gone.zip](https://github.com/adobe/aem-core-wcm-components/files/3631577/embed_gone.zip)

(CQ-4279920)

**Comment by richardhand** [comment]
This is verified, merged to master and will be included in the upcoming [2.7.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/17).
