### ISSUE TITLE
Content fragment list to show more than 10 models in dialog

### ISSUE THREAD

**Issue by surya057** [adobe/aem-core-wcm-components#758]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In the content fragment list, Under "properties" tab, "model" dropdown only shows the first 10 content fragment model names. when AEM has more than 10 content fragment models, author unable to see the remaining.

**Describe the solution you'd like**
Update the query builder logic with predicate "p.limit=-1" in "ModelDataSourceServlet.java".
So when datasource request call is been made all the models will be displayed in dropdown.

**Are there alternatives?**
No

**Documentation**
Screenshot of component:
![image](https://user-images.githubusercontent.com/12661298/65428317-16806d80-de0c-11e9-8c5a-6f30b6e1297b.png)

**Comment by richardhand** [comment]
Code is verified, merged to master and will be available in the upcoming [2.7.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/17)
