### ISSUE TITLE
[Embed] 6.3, 6.4 failing - bundle resolution exception for javax.xml.bind

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#761]
The Core Components are failing on AEM 6.3, 6.4 due to a resolution exception for `javax.xml.bind`.

Since commit:
https://github.com/adobe/aem-core-wcm-components/commit/fcf28dd899b91ddcd58185264d5351f8ea82244d

CQ-4280267

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-core-wcm-components/commit/6e5d09c819c7984d6395c68de4e6475d961abda7
