### ISSUE TITLE
[Content Fragment List] Order by dropdown gets not updated after changing the cfm model

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-core-wcm-components#768]
**Current Behavior**
The new order by drop down inside of the edit dialog of the content fragment list component does not get updated after a different cfm model is selected. This leads to an invalid component configuration.

**Expected behavior/code**
After an author has changed the model of the cfm the order by drop-down should only provide values from model which is currently selected.

**Comment by msagolj** [comment]
Verified on development branch

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
