### ISSUE TITLE
[Accordion] function `onDocumentReady` called before `DOMContentLoaded`

### ISSUE THREAD

**Issue by Andrew-Cottrell** [adobe/aem-core-wcm-components#769]
https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/accordion/v1/accordion/clientlibs/site/js/accordion.js#L510

    if (document.readyState !== "loading") {
        onDocumentReady();
    } else {
        document.addEventListener("DOMContentLoaded", onDocumentReady());
    }

When `document.readyState === "loading"` the `onDocumentReady` function is executed immediately, before the `DOMContentLoaded` event is fired. A reference to the `onDocumentReady` function should be passed to `document.addEventListener`, *not* the return value.

**Comment by richardhand** [comment]
Thanks very much @Andrew-Cottrell for spotting this!

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
