### ISSUE TITLE
[List] Use image of linked page as thumbnail

### ISSUE THREAD

**Issue by JasonUSC** [adobe/aem-core-wcm-components#770]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Authors often want an image to go with their linked content, not just the title and description. Since images aren't part of the list component, authors have to manually create a list of articles using the teaser component which can be tedious. 

**Describe the solution you'd like**
At a minimum, there should be a checkbox to use the image from the list item's linked page as the thumbnail. A slightly more advanced implementation would be to allow an author of a static list to also select an image from the dam for each list item.

**Are there alternatives?**
When an image is needed to go with each item in the list, manually build each list item with a teaser component.

**Comment by thinkstainless** [comment]
+1 on this feature request. List component has been ideal for contacts lists, but we need an option to include a thumbnail image. 

<img width="825" alt="Screen Shot 2019-11-01 at 8 42 53 PM" src="https://user-images.githubusercontent.com/4670448/68063524-37c85980-fce8-11e9-94e7-f18c7fff3e9e.png">

**Comment by nathanmckean** [comment]
In this use case, you'd expect (like teasers) to be able to link the image. This would make it functional, so any existing alt text from the DAM should be overridden to describe the destination of the link. At the very least to not link the image and have is set as decorative. If inking the image and title then the 'duplicate links' issue for accessibility mentioned in order posts comes up again. Two links to the same place, one is redundant.

**Comment by gabrielwalt** [comment]
I agree the list component must become a list of teasers, possibly even using the teaser to render the list items.

To summarize, we need all of the following: 
* Capability to render items with the Teaser component
* Capability to override the item title, description, or image
* Capability to list items that are not in AEM, with external data sources or manual list items (see #57).
* Capability to show pagination (see also #184).

**Comment by gabrielwalt** [comment]
Available now as tech preview on the new list component thanks to the option to list items as teasers.
