### ISSUE TITLE
[Container] Documentation: Add cq:isContainer="{Boolean}true" for proxy component in README

### ISSUE THREAD

**Issue by juliahchen** [adobe/aem-core-wcm-components#771]
Container component is missing a section in the README for setting up the proxy component user must add cq:isContainer="{Boolean}true" to enable full functionality. Similar how section "Enabling Tabs Editing Functionality" in the Tabs component is described in the README.

**Comment by richardhand** [comment]
Thanks @juliahchen for spotting this, makes sense to add it. Feel free to create a pull request against `development`. :)

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
