### ISSUE TITLE
[Page] Allow to obtain Page-model outside the Page-component scripts

### ISSUE THREAD

**Issue by henrykuijpers** [adobe/aem-core-wcm-components#772]
## Bug Report

In various locations in the codebase, there could be a need to obtain the Page-model, so we do not have to repeat logic that is inside that model, or even content policies that are loaded inside that model. For example the appResourcesPath, the language, etc.

**Expected behavior/code**
`<sly data-sly-use.page="com.adobe....Page"/>` should return the Page v2 model, because it should be able to match the resource type of the current page with the resource type of the Page v2 model. Then `${page.appResourcesPath}` should return the resources path that is configured through the content policies. And also, `${page.language}` should return the language of the page, obtained through the logic in the Page-model.

**Current Behavior**
In fact, we see that `${page.appResourcesPath}` returns null, because it is actually returning the Page v1 model to us. Upon further investigation, we noticed that not the current page is being used as an adaption source, but the current resource, which of course does not contain a page resource type. So it will revert to the "first implementation picker" and that will result in the Page v1 model. We noticed that `${page.language}` *is* working, but that's because that is implemented in the Page v1 model.

**Environment**
- AEM 6.3-6.5
- Core Components 2.5.0
- JRE version 1.8

**Possible Solution**
Ensure that adaption to the Page model will always be done through the jcr:content of the current page, including the proper injection of the Style-classes, containing the content policies for the page, instead of the current resource.

**Comment by henrykuijpers** [comment]
@jurgenbrouwer

**Comment by henrykuijpers** [comment]
We had a look at the default use providers registered in HTL. We noticed that the request is being tried, then the resource and then it stops. So currently, there doesn't seen to be a way to have data-sly-use use the page content, instead of the current resource / request.

**Comment by jurgenbrouwer** [comment]
Example use-case:
- Using an SVG logo that's inside the design's resources folder. Our logo component is not in the page model but in a separate header component on the page. There's no proper way to get this resource path in our components (using the existing logic in the Page model).
- Using SVG icons in several components (like buttons). These icons are also stored in our design's resources folder. Again, we cannot leverage the existing logic to get this path in components which are not a page component.

**Comment by vladbailescu** [comment]
As per https://github.com/adobe/aem-core-wcm-components/discussions/1509, closing to icebox.

**Comment by bpauli** [comment]
Just want to add that we added a latest version implementation picker for sling models with 2.16 https://github.com/adobe/aem-core-wcm-components/pull/1497

**Comment by henrykuijpers** [comment]
Now that I read this ticket again: I think `data-sly-use.model="${'tld.something.Model' @ adaptable = currentPage.contentResource}"` should be able to work?
