### ISSUE TITLE
Form Container - Resizable parsys

### ISSUE THREAD

**Issue by AntonValadzko** [adobe/aem-core-wcm-components#775]
## Bug Report

**Current Behavior**
Currently, parsys inside Form Container component could be resized that creates redundant nodes on the same level. 
For Responsive Grid component, there is a logic in responsive.Overlay.js for making drop zones not resizable. 

` // the responsive grid drop zones are not resizable
            if (editable.type !== 'wcm/foundation/components/responsivegrid/new') {`

It goes without saying that it doesn't work due to inheritance and different resource type.

**Expected behavior/code**
I shouldn't be able to change the width of parsys as it is currently designed for Layout Container

**Environment**
- AEM 6.4 SP 6.4.5
- Core Components version 2.5

**Additional context / Screenshots**
![image](https://user-images.githubusercontent.com/6346581/65958550-5244b400-e458-11e9-8f68-154e2bcbd258.png)

**Comment by andreeadracea** [comment]
The problem is solved and the solution will be available in the new release of core components.
