### ISSUE TITLE
[Carousel] Button elements have role button

### ISSUE THREAD

**Issue by jakublamprecht** [adobe/aem-core-wcm-components#783]
## Bug Report

**Current Behavior**
In the current markup of Carousel, button elements for rotation and slide control have additional attribute `role="button`. This is not required, since buttons get this role by default. This causes W3C validators to report warnings. That's nothing major, but might be worth addressing.

**Expected behavior/code**
No role="button on button elements

**Environment**
- Core Components version 2.6.0

**Comment by richardhand** [comment]
Thank @jakublamprecht, I agree we can remove these.

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
