### ISSUE TITLE
[Library] Missing wrapper element for component inside the Demo component

### ISSUE THREAD

**Issue by ataimussova** [adobe/aem-core-wcm-components#784]
**Current Behaviour**
If there is a component dragged and dropped into Demo component from Core WCM Components Examples and there are styles applied to that component from AEM style system, these styles are not applied in the html as the component's wrapper div is missing. In the properties tab of the Demo component there are styles ids listed, though in the markup tab there is no wrapper div with those css classes from selected styles. 

When component is edited and there is no page refresh these styles look like being applied. Though after page refresh and whenever that page is opened again, there is no wrapper div for the component in the Demo component's parsys.

**Expected Behaviour**
Wrapper element is forced to be present for the component in the Demo component from Core WCM Components Examples by setting `decoration=true`. 

**Environment**
- AEM 6.5
- Core WCM Components Examples 2.5.0

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
