### ISSUE TITLE
[Teaser] Blank lines in teaser description when "Link" or CTA is filled

### ISSUE THREAD

**Issue by rzasap** [adobe/aem-core-wcm-components#788]
## Bug Report

**Reproduction steps**
1. Navigate to http://localhost:4502/editor.html/content/core-components-examples/library/teaser.html
2. Go to teaser below "Call To Action Button"
3. Open the dialog
4. Focus on "Description" richtext area after the last character
5. Invoke backspace button 18 times (exact umber of char in "Teaser Description")
6. Confirm the dialog
 

**Current Behavior**
The empty "&nbps;" is present in description

**Expected behavior/code**
No additional white space characters should be visible as the user already deleted all the chars.

**Environment**
- Windows 10, Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- AEM version and patch level - AEM 6.3 SP3 CFP5
- Core Components version 2.6.0
- JRE version: Java(TM) SE Runtime Environment (build 1.8.0_171-b11)

**Possible Solution**
https://github.com/adobe/aem-core-wcm-components/pull/789

**Additional context / Screenshots**
![teaser](https://user-images.githubusercontent.com/18657753/66392339-d86c7780-e9cf-11e9-9ff0-3b5261362c72.gif)

**Comment by rzasap** [comment]
Please note that the issue does not occur for Teasers without "Link" filled or with link pointing to absolute urls. It looks like checkboxTextfieldTuple.js is messing here (teaser call retrievePageInfo on dialog load which invokes checkboxTextfieldTuple for description)

**Comment by msagolj** [comment]
fixed with #824

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
