### ISSUE TITLE
Title component NPE

### ISSUE THREAD

**Issue by Umirov** [adobe/aem-core-wcm-components#791]
## Bug Report

**Current Behavior**
I have a proxy title component based on v2 title. I am overriding its dialog to hide linkUrl. 
I have custom banner component. Inside of it i am including title component: 
`<div data-sly-resource="${'title' @ resourceType='mysite/components/content/title', decoration=true}" ></div>`
I also have parsys:
`<div data-sly-resource="${'par' @ resourceType='wcm/foundation/components/parsys', decoration=true}" ></div>`

So i drag and drop banner component on a page. It already has title component inside of it. But when i try to open dialog of title it throws NPE. 

![IMG_20191010_112009](https://user-images.githubusercontent.com/4797786/66529913-0200dc80-eb51-11e9-8917-c5c6834a5354.jpg)

I guess it is because there is no title node, it is "synthetic" it will appear only when i configure and save it. But i cant do that because of npe. There is no null check after getResource call inside AllowedTitleSizesDataSourceServlet

**Expected behavior/code**
Title component should be editable when included as data-sly-resource. 

**Environment**
- AEM version and patch level (AEM 6.4.4)
- Core Components version (2.4.0)
- JRE version ( `Java(TM) SE Runtime Environment (build 1.8.0_181-b13)`)

**Possible Solution**
Check for null and if resource is null(synthetic) return some predefined allowed types

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by archanasmsharma** [comment]
I am also trying to use the Core component v2 <div data-sly-resource="${'title' @ resourceType='core/wcm/components/title/v2/title'}"></div> directly in my HTL file of my component. 
While trying to open the dialog, I get the same NPE

**Comment by auschris** [comment]
I am also facing the same issue while trying to embed Title component.
To add more context to the above issue.
PFB screenshot FYI...

AEM Version : 6.5.2
Core Components Version : 2.7.0

<img width="1628" alt="Screen Shot 2019-10-21 at 4 26 39 PM" src="https://user-images.githubusercontent.com/6603406/67240534-a9b6be00-f41f-11e9-9473-f253fea1c4dd.png">

**Comment by andreeadracea** [comment]
The solution of the issue is now on development branch and will be available on next release of core components
