### ISSUE TITLE
📖 Missing AEM WCM Core Components JavaDocs

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-core-wcm-components#794]
Can someone please point me to where the current AEM WCM Core Components JavaDocs are (ie. what are the public Sling Model interfaces), or if they don't exist, can they be published and the link provided in this project?

**Comment by vladbailescu** [comment]
@davidjgonzalez , the JavaDocs are available through Maven Central https://repo1.maven.org/maven2/com/adobe/cq/core.wcm.components.core/2.7.0/

**Comment by msagolj** [comment]
I added the javdocs jar as an asset to the release : 

https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.7.0

We will do this for future releases as well to make it easier to find.
