### ISSUE TITLE
Pattern for Touch UI Cloud Services

### ISSUE THREAD

**Issue by klcodanr** [adobe/aem-core-wcm-components#806]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Creating Cloud Services in Touch UI requires significant development effort vs the Classic UI /etc/cloudservices. It would be great to have a "quickstart" to create a Cloud Service integration with Touch UI, especially for the embeds.

**Describe the solution you'd like**
Create a console and a creation wizard for TouchUI Cloud Services which allows the users to see a list of the instances of a cloud service and then create, modify and delete these instances. 

**Are there alternatives?**
Incorporate this as a product feature. Go through a painful, lengthly development process per cloud-feature. 

**Documentation**
https://imgur.com/a/Q9onSGX

**Comment by msagolj** [comment]
@klcodanr your request is outside of the scope of this project, which is to provide 'A set of standardized components for AEM' . As you mentioned above under 'Alternatives' this is product feature request.
