### ISSUE TITLE
Check against Adobe AMS/Cloud SonarQube rules

### ISSUE THREAD

**Issue by msagolj** [adobe/aem-core-wcm-components#813]
In preparation for hosting the Component Library on Adobe AMS/Cloud I ran the core components code through their code scan step which is required to pass.

While nothing blocking was found, at the moment it only passes 'partially'. Since this project serves as  a 'good practice' reference, it should pass the step.

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
