### ISSUE TITLE
[ExperienceFragment] "Edit in New Tab" action does not work

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-core-wcm-components#815]
## Bug Report

**Current Behavior**
When an Experience Fragment component is placed on a page, and a variation is selected, the "Edit" action does not open the experience fragment editor. Instead, it displays the error "The experience fragment doesn't have an associated variation"

**Expected behavior/code**
The edit button should open the experience fragment in the experience fragment editor.
This is the behavior of the OOTB vanilla XF component, and is the obvious intent of the editInNewTab action config.

**Environment**
- AEM version: AEM-6.4.6.0
- Core Components version: 2.7.0
- JRE version: 1.8.0

**Root Cause**
The issue is introduced at [/apps/core/wcm/components/experiencefragment/v1/experiencefragment/cq:editConfig/cq:actionConfigs/editInNewTab](https://github.com/adobe/aem-core-wcm-components/blob/6ab01a4f737b9a397fb8a0f56aa845bd940ac076/content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/_cq_editConfig.xml#L36).

This action config causes the following JS to be called:
/libs/cq/experience-fragments/editor/clientlibs/experiencefragments/js/component/actions/edit.xf.NEWTAB.js

That action explicitly opens in a new tab the fragment referenced by the "fragmentPath" property.
The problem is that the core components XF component does not use the "fragmentPath" property, instead it uses a property named "fragmentVariationPath" (see [dialog](https://github.com/adobe/aem-core-wcm-components/blob/6ab01a4f737b9a397fb8a0f56aa845bd940ac076/content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment/_cq_dialog/.content.xml#L54))

**Possible Solution**
There are several options for resolving this issue.
The first possible solution is to just change the property name from "fragmentVariationPath" -> "fragmentPath". If this change is made then the properties mirror the vanilla OOTB XF component properties, and therefore the clientlib for the edit action still works. This is probably the "cleanest" solution, but would be a breaking change because existing components would cease to work unless the content is updated.

Another solution is to copy the edit.xf.NEWTAB.js file into a clientlib and modify the function to load the "fragmentVariationPath" property instead. This JS function would have to have a different name, or the OOTB and core-wcm-components would conflict.

I would lean towards the first solution unless there is a valid reason that the property name is different, or if the desired behavior is different than the vanilla OOTB XF component.

**Comment by msagolj** [comment]
@ky940819 thank you for reporting. Yes the property name was changed before 2.6.0 release to make it more clear that it's pointing to a variation. The connection to the edit action depending on this specific name was unfortunately missed.

- Your first approach : Yes , simplest and straight forward but as you said a breaking change, not desirable.
- Second approach: valid approach, but if XF makes some changes to it we might miss and end up with a broken button. Maybe better to stay in sync.
- A third approach might be to make the ``ns.experienceFragments.actions.editInNewTab`` more flexible by accepting both property names or pass the prop name as a param to the edit function if that's possible and use 'fragmentPath' as default.

**Comment by ky940819** [comment]
@msagolj 
The third approach you suggested would be a good solution, as it would allow overlays to use different properties.

However, would that solution not require an official update from Adobe, as the JS file that needs to be modified is part of the AEM core code (under /libs)?

A fourth idea, is there any validity to using the "model.json" instead of just ".json" and reading the "localizedFragmentVariationPath" property? I'm not super familiar with localization, but it does look like there are situations under which the "localizedFragmentVariationPath" might not match the path in the properties. If the derived "localizedFragmentVariationPath" actually points to the variant that is rendered, would it not make more sense to load the same fragment variation in the editor?

**Comment by msagolj** [comment]
Yes, approachj 3 would require a change in AEM, with backport to 6.4 and 6.3 , and it would add a dependency to the CFP or SP containing that fix. So not a simple solution either.

And yes, using model.json and 'localizedFragmentVariationPath' would actually be more accurate (the localisation is explained [here](https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment#features)) but that assumes core components is used. 

So maybe your second approach, creating our own action might actually be the best solution.

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).

**Comment by frappierer** [comment]
The issue is still there. A fix would be great.
