### ISSUE TITLE
content fragment list dialog - how is the model list generated?

### ISSUE THREAD

**Issue by leoxy520** [adobe/aem-core-wcm-components#816]
I overlay'd the core components, which includes the content fragment list, but its dialog doesn't display all the models I expect. Looking at the dialog code, the data source that generates the dropdown list points to "core/wcm/components/contentfragmentlist/v1/datasource/models", but I am not able to find where this is. Could you please point me to the right location or explain the logic behind the generation of the model list? Thanks.

**Comment by msagolj** [comment]
Hi @leoxy520 , `core/wcm/components/contentfragmentlist/v1/datasource/models` maps to a Servlet, see: 

https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/contentfragment/ModelDataSourceServlet.java#L49-L63
