### ISSUE TITLE
[Teaser] Add Pretitle text

### ISSUE THREAD

**Issue by thinkstainless** [adobe/aem-core-wcm-components#823]
## Feature Request

**Is your feature request related to a problem? Please describe.**
It's common to see a pre-title, or category tag used in conjunction in teaser type of content. It would be ideal to see an additional dialog field to include this option for the teaser core component. A few examples as shown:

<img width="1266" alt="Screen Shot 2019-11-01 at 8 29 36 PM" src="https://user-images.githubusercontent.com/4670448/68063443-6560d300-fce7-11e9-9623-040e62c5779e.png">

<img width="1281" alt="Screen Shot 2019-11-01 at 8 28 56 PM" src="https://user-images.githubusercontent.com/4670448/68063441-63970f80-fce7-11e9-97e9-8a597b1fe5a5.png">

<img width="311" alt="Screen Shot 2019-11-01 at 8 31 15 PM" src="https://user-images.githubusercontent.com/4670448/68063446-698cf080-fce7-11e9-8a0d-a6a92e51c377.png">

**Comment by gabrielwalt** [comment]
That would make sense, I agree.

**Comment by brunob15** [comment]
I would like to take this issue. Is it ok?

@gabrielwalt @thinkstainless

**Comment by msagolj** [comment]
@brunob15 please go ahead :) thank you.

**Comment by msagolj** [comment]
@brunob15 are you still working on this, otherwise we would like to tackle this issue.

**Comment by brunob15** [comment]
Yes, I didn't have much time but I'm working on this. Feel free to take it if you prefer.

**Comment by dymitrs** [comment]
Hey, found some time and added the missing field. PR above.

**Comment by vladbailescu** [comment]
Merged to `master` in cc0a04168a7605297033c0f0ef0ffee28073228a
