### ISSUE TITLE
[Embed] Youtube Embeddable doesn't support full screen

### ISSUE THREAD

**Issue by abhishekagg19** [adobe/aem-core-wcm-components#843]
## Bug Report

**Current Behavior**
When we use OOTB Youtube embeddable then we don't get the option to watch video in full screen.

**Expected behavior/code**
Youtube embeddable should provide an option to enable fullscreen mode for playing videos.

**Environment**
Using the latest Core components release

**Possible Solution**
Provide a configurable option for Youtube embeddable to allow/enable fullscreen. Based on the settings add "allowfullscreen" to the iframe.

**Additional context / Screenshots**
Overlaying of OOTB Youtube embeddable can be used for custom implementation, but it leads to listing of both the components in the Embeddable dropdown - Youtube and Custom Youtube. Since embeddable datasource servlet is looking for all the components of type embeddable and there is no way to exclude overlaid parent component.

**Comment by jckautzmann** [comment]
This has been implemented in https://github.com/adobe/aem-core-wcm-components/pull/845
and will be available in the next release of the Core Components.

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
