### ISSUE TITLE
[Accordion] ScriptEvaluationException thrown on publish system

### ISSUE THREAD

**Issue by jetimme** [adobe/aem-core-wcm-components#852]
## Bug Report

**Current Behavior**
HTL script accordion.html is getting an error on publish system. 

```
18.11.2019 10:03:40.540 *ERROR* [10.10.40.4 [1574067820402] GET /content/wine/de/investor-relations/ir-contact.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught SlingException
org.apache.sling.scripting.sightly.SightlyException: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.scripting.ScriptEvaluationException: item.name in accordion.expandedItems: extraneous input 'in' expecting {'}', '.', '&&', '||', '[', '@'} in /apps/core/wcm/components/accordion/v1/accordion/accordion.html at line number 24 at column number 41
```

See [Full Stack Trace](https://github.com/adobe/aem-core-wcm-components/files/3864286/script_error_accordion_on_publish.txt)

The same script/page is working on the author system without any problems. 

I found out that the "in" operator is causing the problem here. I double checked the versions of HTL extension, core components, etc. I cannot find the reason why the publish system has a different behavior and problem with the "in" operator. 

**Expected behavior/code**
The accordion is rendering on both systems (author and publish) in the same way without any errors.

**Environment**
- AEM 6.4.3.0
- Core Components 2.5.0
- Java(TM) SE Runtime Environment(build 1.8.0_161-b12)

**Comment by bpauli** [comment]
As we don't support AEM 6.4 anymore with latest version of the Core Components I'll close this issue. Please reopen the issue if you see the same bug on AEM 6.5
