### ISSUE TITLE
[Teaser] Drag & drop SVG on teaser component doesn't work

### ISSUE THREAD

**Issue by bmalecki** [adobe/aem-core-wcm-components#857]
## Bug Report

**Current Behavior**
Direct drag & drop from the content finder onto the teaser component doesn't work. This bug is related to [issues/825](https://github.com/adobe/aem-core-wcm-components/issues/825)

**Expected behavior/code**
Drag & drop from the content finder onto the teaser component should work.

**Environment**
- AEM version and patch level (AEM 6.5 SP2 )
- Core Components version (2.7.0)

**Possible Solution**

Add `image/svg\\+xml` to `accept` property in `cq:editConfig` for teaser component

**Comment by richardhand** [comment]
The code for this issue is merged to master and will be available in the upcoming [2.8.0 release](https://github.com/adobe/aem-core-wcm-components/milestone/18).
