### ISSUE TITLE
Need Policy delegation Feature when upgrading the versions

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#870]
## Feature Request
Content Policy Delegation during version upgrade

**Is your feature request related to a problem? Please describe.**
Below is the use case for the issue faced with style systems  during version upgrade:
1. Version 1 of the component is used on editable template
2. Style systems are applied on this component on editable template
3. V2 gets released for the component and author wants to use V2 on editable template
4. Author want to reuse the styles that were applied on V1 but currently can't do it until he/she copies all the styles from v1 and applies on v2.

There should be style delegation mechanism that can be configured on new versions. This delegation property should being the styles from delegated component (v1 in this case).

**Describe the solution you'd like**
We need a delegation mechanism for style systems so that one component on editable template can reuse the styles applied on another component.

**Are there alternatives?**
Only alternative is to reapply styles manually.

**Documentation**
If you can, explain how users will be able to use this and possibly write out a version of the docs.
Maybe a screenshot or design?

**Comment by rajeevyadav2** [comment]
@vladbailescu : Can you please confirm if if any progress has been done for this enhancement?

**Comment by vladbailescu** [comment]
@rajeevyadav2 , This is not on our roadmap for now (see https://github.com/adobe/aem-core-wcm-components/wiki) though we would very much appreciate a contribution in this regard.

**Comment by gabrielwalt** [comment]
Closing this for now as this is not on our roadmap for now, and there doesn't seem that there's a contribution being prepared.
