### ISSUE TITLE
Need details about contentPolicyDelegatePath

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#871]
I see contentPolicyDelegatePath property being used in image component. Could you please explain the usage of this property.

**Comment by richardhand** [comment]
Hi @rajeevyadav2,

as I understand this was added (at [0]) as a mechanism for delegating the resolution of the image content policy to another content resource. It was specifically added for a targeted images use-case whereby for a targeted image resource (resources under /content/campaigns/...) , the content policy cannot be found using the default handling and therefore a specific policy delegate must be supplied.

[0] - https://github.com/adobe/aem-core-wcm-components/commit/ebc8d9f4a880d99fe26a1f34734f2d1970394442

**Comment by rajeevyadav2** [comment]
Hi Richard,

Is it only for Image content policy delegation or else it can be used for any other component as well?

If there are 2 versions of any component. Eg.
Teaser V1
Teaser V2

If I configure this property on V2 to point to V1, will Teaser V2 display policies from V1? Is there any additional configuration that need to be done for this property to work on other components?

**Comment by richardhand** [comment]
@rajeevyadav2,

> If I configure this property on V2 to point to V1, will Teaser V2 display policies from V1? Is there any additional configuration that need to be done for this property to work on other components?
This property isn't available in other components, and it's a request parameter rather than a JCR property.

**Comment by rajeevyadav2** [comment]
@richardhand :  In model it has been used as request parameter but i see this being configured as property on teaser component.
https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/teaser/v1/teaser/.content.xml

**Comment by rajeevyadav2** [comment]
@richardhand Thanks for clarification. If we pass contentPolicyDelegatePath request attribute in any component as path pointing to another component, will it pick the styles list from that component or else it is just specific to image?

**Comment by rajeevyadav2** [comment]
@richardhand Is there any mechanism in core components where we can force new versions/extended version to pick style list configured on older version or another component in same editable template?

**Comment by richardhand** [comment]
@rajeevyadav2,
 
> If we pass contentPolicyDelegatePath request attribute in any component as path pointing to another component, will it pick the styles list from that component or else it is just specific to image?

No it won't, this is specific to the image component.

> Is there any mechanism in core components where we can force new versions/extended version to pick style list configured on older version or another component in same editable template?

No there isn't currently a mechanism (as far as I'm aware) for picking content policy properties from a previous version or for sharing the styles between policies. We also generally don't recommend having multiple versions of the same component on the page, rather that the latest is used where possible.
