### ISSUE TITLE
[Accordion] Difficulties with accessing configuration after panel selection

### ISSUE THREAD

**Issue by michaltobiasz** [adobe/aem-core-wcm-components#872]
## Bug Report

**Current Behavior**
The issue can be reproduced on the core components example page in the authoring mode. 
/editor.html/content/core-components-examples/library/accordion.html

Steps (See attached video):
1. Select First Accordion component
2. Choose panel - Item 2 and add Image v2 component
3. Add Image to the Image component
4. Choose panel - Item 1 of the accordion
5. Try to open accordion configuration

Behavior:
In step 5 it is hard to get to Accordion configuration because Image from item 2 overlaps accordion component. I need to go with the pointer to the right border of the Accordion component to trigger configuration tabs to show up.

**Expected behavior/code**
In step 5 configuration should appear whenever I click on the Accordion component.

**Environment**
- AEM version and patch level: 6.5.2.0
- Core Components version: 2.7.0
- JRE version: Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)

**Possible Solution**

**Additional context / Screenshots**
Video: [core-accordion-issue.zip](https://github.com/adobe/aem-core-wcm-components/files/3926634/core-accordion-issue.zip)

**Comment by richardhand** [comment]
Thanks @michaltobiasz for the issue report, I can confirm the behaviour. At first glance seems that the overlays require updating on item switch to hide them for non-active items.

**Comment by larsvanpoucke** [comment]
Are there any updates on this?

**Comment by msagolj** [comment]
Hi @larsvanpoucke, I tried to reproduce this issue with the current version using the steps described above but its no longer reproducible, so i would recommend you update to the latest version. Closing this issue.
