### ISSUE TITLE
[Page] Add HierarchPage for SPA Editor support

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-core-wcm-components#877]
## Feature Request

**Is your feature request related to a problem? Please describe.**

In the merged PR (https://github.com/adobe/aem-project-archetype/pull/283) the SPA Editor Page/PageImpl which is exposed via the closed-source `aem.spa.project.core` is introduced, which is used to generate Templates/Types/etc. for SPA projects.

**Describe the solution you'd like**
The Core Components Page/PageImpl should absorb the code of the `aem.spa.project.core`'s Page/PageImpl, so that the Core Components v2 Page works for BOTH "traditional" Web Pages and SPA Editor pages.

**Are there alternatives?**
n/a

**Documentation**
Users would be able to use any page whose super-type is the v2+ Page component for SPA Editor. This would (likely) require a Page Policy level flag indicating if the Template is intended to be used for traditional or SPA purposes (as it would toggle the output of the `body.html`). There would also need to be a review/consideration of exposing the SPA Page Policy related properties (isRoot, Depth, Patterns, etc.) ... these actually feel like they should be a CA Config, not a Page Policy).

**Comment by gabrielwalt** [comment]
See also corresponding PR #373.

**Comment by vladbailescu** [comment]
There are no plans to work on this currently. As per https://github.com/adobe/aem-core-wcm-components/discussions/1509, closing to icebox.
