### ISSUE TITLE
[Embed] URL check is failing for youtube URLs

### ISSUE THREAD

**Issue by abhishekagg19** [adobe/aem-core-wcm-components#881]
## Bug Report

**Current Behavior**
Unable to configure Youtube URL in the Embed - URL section.
https://youtu.be/58AEa-pBd44

**Expected behavior/code**
Should be able to configure youtube URLs in the URL section as well.

**Environment**
- AEM version and patch level (e.g. AEM 6.5 SP2)
- Core Components version (2.7.0)
- JRE version (JDK 11)

**Possible Solution**

**Additional context / Screenshots**
Screenshot:

![image](https://user-images.githubusercontent.com/29771785/71243503-7ec0eb80-2336-11ea-817d-d03200d959b8.png)

**Comment by abhishekagg19** [comment]
As per documentation it should support - The Embed Component ships with processors for the following types of resources:
Resources that comply with the oEmbed standard including Facebook Post, Instagram, SoundCloud, Twitter, and YouTube

**Comment by vladbailescu** [comment]
@abhishekagg19 , that particular video/URL seems to not be allowed to be embed as https://www.youtube.com/oembed?url=https://youtu.be/58AEa-pBd44 returns `401 Unauthorized` (as opposed to something like https://www.youtube.com/oembed?url=https://youtu.be/aaikjMiq8es)

**Comment by kwin** [comment]
Would it be possible to improve the author experience for those cases? Some validation message explicitly linking to "https://support.google.com/youtube/answer/6301625?hl=en" would help a lot here.

**Comment by vladbailescu** [comment]
@kwin Right now we don't have a mechanism in place to notify what the potential failure is: wrong url, unauthorized and so on. We would appreciate contributions on this.
