### ISSUE TITLE
Access PanelContainerImpl in custom bundle

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#882]
Hi Team,
I want to reuse PanelContainerImpl implementation in my external custom bundle to create my own custom container component. I want to extend this class in my sling model. Right now I don't see it in exported packages in core bundle. Could you please suggest on how this class can be used in external bundle. 

Thanks.

**Comment by bpauli** [comment]
Hi @rajeevyadav2,
Thank you for the interest in our container component!
We don't want to expose our internal classes as internal behaviour might change and this could lead to breaking changes. The only extension point we currently support is by using the Delegation Pattern [1].

For general questions or future discussion on this topic we kindly ask to use our mailing list at [2] to keep our issue list clean for bugs and feature requests. Thanks!

[1] https://github.com/adobe/aem-core-wcm-components/wiki/Delegation-Pattern-for-Sling-Models
[2] https://groups.google.com/forum/#!forum/aem-core-components-dev

**Comment by rajeevyadav2** [comment]
Thanks @bpauli  for the response. Right now all external consumers need to extend from Tabs, Carousel or Accordian (Concrete components) in order to develop containerpanel. It would be good to have an abstract component for just PanelContainer so that external consumer can use it directly for any component that needs panel container. They don't need to be dependent on any concrete implementation for like tabs, accordion etc.

**Comment by Jdruwe** [comment]
@bpauli @rajeevyadav2 I was looking for the exact same thing! Sad to see it is not possible :(

**Comment by Jdruwe** [comment]
I am going to start from com.adobe.cq.wcm.core.components.models.Container there maybe should be a 'clean' container or something like that.
