### ISSUE TITLE
Image attribute not decoded with .atoffer.html extension

### ISSUE THREAD

**Issue by tyge68** [adobe/aem-core-wcm-components#883]
## Bug Report

**Current Behavior**
When exporting Experience Fragment to target which is using ".atoffer.html" extension, it rewrite attribute like "data-img-src". Which then get URL encoded characters. Thus the ".{width}." may become ".%7Bwidth%7D."

**Expected behavior/code**
Image component should support export to target use case and the javascript should handle URL encoded attribute.

**Environment**
- AEM version and patch level (e.g. AEM 6.4.3.0)
- Core Components version (e.g. 2.5.0)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_181)`)

**Possible Solution**
add a "transform" function to handle the decode of the value

**Additional context / Screenshots**
Image got  broken links as the url is not generated properly in this context.
[Screenshot 2020-01-06 at 11 30 10](https://user-images.githubusercontent.com/8066508/71812645-fbaecd80-3077-11ea-9090-31683703270e.png)

**Comment by gabrielwalt** [comment]
Thanks for your PR, we'll review it, and if positive, ideally merge it in the next few days.

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-core-wcm-components/commit/0f65b622f944de9d5bedb18ca29d821740eeb750

@tyge68 Thank you for the contribution!
