### ISSUE TITLE
[Accordion] Mandatory items

### ISSUE THREAD

**Issue by danijelbasic** [adobe/aem-core-wcm-components#886]
Is it possible to extend this component, so the title for the items is mandatory?

As far as I can see, this component is using the shared script `/apps/core/wcm/components/commons/editor/dialog/childreneditor/v1/childreneditor`
(among others), which does not have the logic for setting Coral input field used as required.

**Comment by gabrielwalt** [comment]
I agree, making the title mandatory makes sense, also for the Tabs component. Maybe even for the Carousel component, in order to make sure that it's accessible.
