### ISSUE TITLE
[Library] Visual bug on Firefox/Safari for categories in side navigation

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#891]
## Bug Report

**Current Behavior**
Following 41e83c29b85659eb3c7d that introduced UX changes in the component library, there is a visual bug on Safari, whereby all category toggles always have a grey background in their default state.

**Expected behavior/code**
That the category toggles have a white background in their default state.

**Environment**
- Core Components `development` latest
- Safari (12.1.1)
- Firefox (72.0.2)

**Additional context / Screenshots**
<img width="1155" alt="Screenshot 2020-01-22 at 14 22 21" src="https://user-images.githubusercontent.com/25616660/72897610-a1259a80-3d22-11ea-8783-a0becaa06dd9.png">

**Comment by vladbailescu** [comment]
Fix merged to `master` in 45c804f4bc471c2a1fac37663caa2c4797042c5a
