### ISSUE TITLE
Table Component

### ISSUE THREAD

**Issue by tjameswhite** [adobe/aem-core-wcm-components#894]
## Feature Request
Would like to see a stand-alone Core Table component. Currently, the only way to construct a table is using the table editor inside the Core Text component. 

**Is your feature request related to a problem? Please describe.**
We currently have 5 different styles that authors can apply to the old OOTB table component. Options are:

- no styles
- border 
- row borders (top and bottom borders only)
- striped (alternating colored rows)
- comparison table (customized styles for headers)
 
With no native Table component, we have no way of applying those styles. The only controls are the very simple and limited table controls in the dialog box (width, height, border).

**Describe the solution you'd like**
Core Table component. By separating it out, we can use Style System to add custom styles beyond the very basic. User and developers would be able to develop custom tables, such as striped rows, custom colors to header, etc. 

**Are there alternatives?**
Currently using the old table component which is deprecated as of 6.4. The suggested replacement is the Core Text component, using the table option. As noted, this is very limited in scope and does not allow for styles to be applied directly to the table.

**Comment by jckautzmann** [comment]
@tjameswhite Thx for your feedback. Would you be able to provide a pull request?

**Comment by tjameswhite** [comment]
@jakublamprecht  for the component? At the moment we don't have anything. I ran across the issue yesterday. We are considering working on it; wondering if anyone else has the same idea?

**Comment by jakublamprecht** [comment]
I guess this was a call to @jckautzmann and not me :)

**Comment by jckautzmann** [comment]
@tjameswhite yes I meant a PR for this new component as we won't have any bandwidth in the coming weeks to work on it. And as you pointed it would be nice to hear from others about such a component.

**Comment by tjameswhite** [comment]
@jakublamprecht  -- ack, sorry. 
@jckautzmann  -- It's certainly something we need at my company. I posted on Slack and haven't seen any feedback there. If someone else is working on it, I don't want to double up work; but if not, I'll see if we can get it into my team's backlog.

**Comment by glasert** [comment]
@tjameswhite nobody is working on this on our side - did you manage to get it into your team's backlog?

**Comment by tjameswhite** [comment]
@glasert -- yes, it's in our backlog. Not sure when we can get to it, but I'm pushing for it.

**Comment by rajeevyadav2** [comment]
Hi All,

Is any work started on Table component?

**Comment by tjameswhite** [comment]
We got hit with other work, but with the little bit of research my devs did, we hit on an idea. 

Since the table editor is part of the rich text editor, all we would be doing is finding a way to call that piece directly. That didn't seem worth the effort. 

Instead, I simply created a new proxy component based on Core Text:
```
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
    cq:isContainer="true"
    jcr:description="Generic table component built on Core Text v2"
    jcr:primaryType="cq:Component"
    jcr:title="Core Table (beta)"
    sling:resourceSuperType="core/wcm/components/text/v2/text"
    componentGroup="Your Group"/>
```
Also using `_cq_htmlTag` to wrap with a custom class
```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    cq:tagName="div"
    jcr:primaryType="nt:unstructured"
    class="our-table"/>
```

Finally, created a Policy for it with the following:
- Plugins > Formatting > enable "Show table options" only
- Plugins > Paragraph Styles > deleted everything

This gives me a hook for the stylesheets, I can create as many custom table styles as needed (we have 5... i know... ), and authors can't do much else with it. It is still possible for them to enter text above the table, but it isn't obvious.

**Comment by tjameswhite** [comment]
We have no plans to pursue this as a discreet component. Instead we will be using our proxy of Text with policies. 

Unless someone else wants to pursue this issue, I would consider it closed.

**Comment by tjameswhite** [comment]
We are currently satisfied with our solution. I am closing the issue. If anyone is interested in creating a bespoke version, feel free to reopen.

**Comment by rajeevyadav2** [comment]
I feel that we should add table component. This component should be able to populate the table from any resource's children nodes as well as csv/xls from dam. I can work on this component if needed.

**Comment by tjameswhite** [comment]
@rajeevyadav2 -- I reopened the issue. I like your idea.

**Comment by rajeevyadav2** [comment]
@tjameswhite : should I start adding it in contr repo or else should raise OTC?

**Comment by aacesco** [comment]
@rajeevyadav2 I agree with your idea. It allows more flexibility

@tjameswhite  do you have any update about this new table component? Do you know its progress?

Thank you!

**Comment by tjameswhite** [comment]
@aacesco I am not working on this solution. The solution of just extending the Text component I mentioned above solved our needs. I had closed this issue, but @rajeevyadav2 had the idea for a standalone component.

**Comment by gabrielwalt** [comment]
Closing this as there is now #1039.
