### ISSUE TITLE
[Navigation] Issue with Navigation.getItems() for non-language live copy

### ISSUE THREAD

**Issue by LSantha** [adobe/aem-core-wcm-components#897]
## Bug Report

**Current Behavior**

I create a live copy of a site where the name of the live copy is not a language code. If I access the root page of the live copy the navigation items provided by the navigation component placed on the page will be the children of the source of the live copy and not the children of the actual live copy.
If I access a child page of the live copy then I get the correct items, only the root page has an issue.
If the name of the live copy is a language code then I get the correct items as well.

So the issue is observed only for the root page of a non-language live copy.

**Expected behavior/code**

If I access the root page of a non-language live copy, the navigation items provided by the navigation component placed on the page should be the children of the actual live copy and not the children of the source of the live copy. This will be consistent with current behavior when accessing a child page of the live-copy, which is the expected behavior.

**Environment**

- AEM 6.6 QS build form the 7/1/2020
- Core Components version 2.8.0
- Java(TM) SE Runtime Environment (build 1.8.0_202-b08)

**Possible Solution**

Change line at [1] from 

`if (currentPage.getPath().startsWith(relationship.getTargetPath() + "/")) {`

to be

`if ((currentPage.getPath() + "/").startsWith(relationship.getTargetPath() + "/")) {`

When the incorrect results are observed in the above comparison currentPage.getPath() is the same as relationship.getTargetPath(). The comparison still fails because relationship.getTargetPath() is appended a path separator. So the condition is true when current page is a child pages but is false when the current page is the root page page. 
The condition will be true for root page as well with the proposed solution.

[1] https://github.com/adobe/aem-core-wcm-components/blob/f9faa9c3b21c245d920f59579b02b3d22719c758/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImpl.java#L139

**Comment by vladbailescu** [comment]
Merged to `master` in a1f7ace
