### ISSUE TITLE
buttons are not displaying on permission tab on experience fragment permission tab

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-core-wcm-components#90]
Below buttons are missing on permissions tab on experience fragments properties tab when core.wcm.components.all-1.1.0.zip is installed in aem:
Add Permissions
Edit Closed user Group
Effective Permissions

AEM version impacted is 6.3.0+

**Comment by gabrielwalt** [comment]
(CQ-4247360)

**Comment by vladbailescu** [comment]
We can no longer observe this issue with later releases. Closing this, please reopen if you're still having issues while using the latest versions.
