### ISSUE TITLE
Use cq/gui/components/coral/common/form/pagefield instead of granite/ui/components/coral/foundation/form/pathfield for all page references

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#904]
Currently a lot of dialogs still use `granite/ui/components/coral/foundation/form/pathfield` (for just any resource) instead of `cq/gui/components/coral/common/form/pagefield` (targeted for page resources).

Almost all hits of https://github.com/adobe/aem-core-wcm-components/search?q=granite%2Fui%2Fcomponents%2Fcoral%2Ffoundation%2Fform%2Fpathfield&unscoped_q=granite%2Fui%2Fcomponents%2Fcoral%2Ffoundation%2Fform%2Fpathfield should IMHO be replaces by `pagefield`

**Comment by richardhand** [comment]
@kwin - totally agree, feel free to create a PR for the switch to page fields.

**Comment by ky940819** [comment]
Just a note of caution, I wouldn't blanket change every path picker; I would only change the ones where it doesn't make sense to pick anything but a page. 

An example of where this could be an issue would be links where someone might pick a DAM asset or a page.

**Comment by richardhand** [comment]
Created a pull request for this at #921

**Comment by vladbailescu** [comment]
Fix merged to `master` in c8cdd34

**Comment by fahol-coop** [comment]
@vladbailescu Please revert this change. At least create a V2 for this breaking change, it's the basic Rule for versioning, or do you not agree that this was a breaking change?
