### ISSUE TITLE
[Button] Rename component to call to action

### ISSUE THREAD

**Issue by nathanmckean** [adobe/aem-core-wcm-components#905]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The button core component allows for a title, and icon and a link. Semantically, this is a link and not a button, they are different things. Links go somewhere, buttons do something. (https://a11y-101.com/design/button-vs-link) 

**Describe the solution you'd like**
Rename the button component to link (or if confusing to some, perhaps Call to Action). If people choose to style links as buttons (of which the increasing commonality has probably resulted in this core component being called 'button') then it is up to them, but it is materially dishonest.

**Are there alternatives?**
Keep as is. However this is far from best practice and perpetuates the misused and misstyling of links as buttons.

**Comment by bpauli** [comment]
@gabrielwalt Can you please provide your input to this issue? Thanks!

**Comment by gabrielwalt** [comment]
+1 to rename this component to "Call to Action", which relates more to a use-case than to an HTML element that can be used for 1000 different things. @nathanmckean, would you be ok if we keep the technical name "button", and just rename the title of the component to "Call to Action"? This would allow to remain compatible and would make it a trivial change.

**Comment by gabrielwalt** [comment]
When the author provides no link URL, it renders a <button>; when providing a link, it renders a <a href="…">. So technically, the Button component allows doing both: Call to Actions and Buttons. Calling it a Call to Action component would be just as wrong as calling it a Button component.

Also, given that we didn't get a PR for this yet, I'll close this issue for now. Please add your comments here if you feel otherwise.

**Comment by nathanmckean** [comment]
Its all about terminology. As you've rightly suggested, the component allows to outcomes, not a 'button' and a 'call to action' but a 'button' and a 'link'. Calling it a button is a stylistic assumption that it will look like a button, semantically it is not always a button.

'Call to Action' was one suggestion of a common term that can cover both a button function (Save, Print, etc) or a link (Visit xyz, Learn More etc). They are both calling the use to conduct an action which is delivered through either a button (do something) or a link (go somewhere).

I realise it doens't seem like a big deal, but HTML is a language (the L) and using correct semantics is more important now than ever.
