### ISSUE TITLE
[Teaser] Improve HTML semantics: display the content before the image

### ISSUE THREAD

**Issue by nathanmckean** [adobe/aem-core-wcm-components#906]
The teaser component lists the HTML order as image, title, description, CTA - with the title being a heading.

Semantically, headings are designed to start a content. Screen-reader users use headings for navigation so they would start a section with related child content underneath them (in this case, the image).

The markup should place the title first. If users want to reposition the image, they can do so with CSS.

There is a great article here for reference re: the future of the teaser component in general, including options to make the whole card clickable, etc. (https://inclusive-components.design/cards/) 

NB: I've referenced this as a comment in another thread, but this is standalone for easy locating.

**Comment by gabrielwalt** [comment]
For teaser v3, let's move the `cmp-teaser__image` div after the `cmp-teaser__content` one.
