### ISSUE TITLE
[Image] The image of the image component placed in the accordion of the template editor is not displayed.

### ISSUE THREAD

**Issue by honda-kazuo** [adobe/aem-core-wcm-components#907]
## Bug Report

**Current Behavior**
This problem only occurs in the template editor.

Steps (See attached video):

1. Place the Accordion component.
2. Select the image component for item 1.
3. Sets an image to an image component.

Behavior:
The image set in the image component is not displayed.

**Expected behavior/code**
The image set in the image component is displayed.

**Environment**
- AEM version and patch level: 6.5.0.0
- Core Components version:2.5.0
- JRE version: Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)

**Possible Solution**

**Additional context / Screenshots**
Video:[Content Page.mp4.zip](https://github.com/adobe/aem-core-wcm-components/files/4184373/Content.Page.mp4.zip)
errorlog:[errorlog.zip](https://github.com/adobe/aem-core-wcm-components/files/4184291/errorlog.zip)

**Comment by richardhand** [comment]
Thanks @honda-kazuo for the bug report, I've created a pull request for a fix here at https://github.com/adobe/aem-core-wcm-components/pull/914

**Comment by honda-kazuo** [comment]
Thank you @richardhand for responding.

**Comment by vladbailescu** [comment]
Fix merged to `master` in ba49f13
