### ISSUE TITLE
[Teaser] Make image clickable also with multiple CTA buttons

### ISSUE THREAD

**Issue by vineetkaushikmca** [adobe/aem-core-wcm-components#908]
1. entire image is clickable when CTA button is not authored
2. But target foes to CTA button only if CTA button in teaser component is authored
3. CTA button along with Image should be clickable when CTA button is also authored

**Comment by bpauli** [comment]
@vineetkaushikmca Thank you for the hands up. We'll have a look to this in #906

**Comment by ky940819** [comment]
It maybe should be optional.
If you have more than one CTA then the action performed by the image link would be ambiguous.

Also, if the CTA buttons overlay the image then there would be no buffer between click areas, which would be a usability issue. 

I don't know if this is possible the way that the aem style/policy system works, but I'd personally love to see the CTA buttons decoupled from the teaser component and replaced with a container that could accept the standard button/link component component. That would solve this issue as well as #838

**Comment by gabrielwalt** [comment]
Having duplicate links on images and titles are causing accessibility issues. Instead of making the image more consistently linked, we're rather moving away from linking the image and we're rather only linking the title or CTA (unless no title nor CTA are provided).
