### ISSUE TITLE
Form Container Component:  It would be good to show response on same page after submitting form

### ISSUE THREAD

**Issue by vineetkaushikmca** [adobe/aem-core-wcm-components#910]
Form Container Component:  It would be good to show response of page submission on same page after submitting form

**Comment by bpauli** [comment]
@vineetkaushikmca, Can you please provide some more details on the requirements? Thanks!

**Comment by gabrielwalt** [comment]
Hi @vineetkaushikmca, as we cannot address all feature requests, we count on your contributions in the form of pull requests. I'm therefore closing this issue for now, but please reopen it if you have more detailed requirements that you want to discuss, or if you have a corresponding pull request.
