### ISSUE TITLE
[RFC] Email Components

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#916]
A set of core email components that render email-compliant HTML output to deliver the content via Adobe Campaign.

User Story: As an author, I want to create emails in AEM from an editable template and a set of core components so that I have the flexibility to assemble a layout that fits my needs, but also enough governance to not deviate from the brand guidelines. I then want to send out these emails via Adobe Campaign.

# Phase 1

Basic email editing capability.

## CSS Inliner Rewriter

Takes the HTML output of the page and inlines all CSS in as HTML attributes:
* Rewrite the output to move every CSS ruleset to the targeted elements as an HTML `style` attribute.
  - Properly handle quotes, like: `font-family: 'Timmana', "Gill Sans", sans-serif;`
  - Accept also browser-specific rules, like: `-ms-interpolation-mode: bicubic;`
  - Preserve duplicate properties, like: `display: inline-block; display: block;`
  - Preserve capitalization as-is, like: `Margin: 0px;`
* Keep the original `style` element in the HTML as-is in order to:
  - Preserve media queries, web fonts, and animations by not removing from the style element any “@” declaration.
  - Preserve unmatched CSS rules, like the Outlook `.ExternalClass` class name.
  - Preserve CSS pseudo-selectors, like `a:hover` or `p::before`.
* Leave client-specific comments untouched, like:<br/>`<!--[if mso]><style>.hide-mso { display: none; }</style><![endif]-->`

## Page component

Provides the following edit dialog options:
* Main tab
  - Email subject (`jcr:title`)
  - Pre-header (RTE with capability to use the Campaign personalization fields)
  - Description
  - Language + language root
  - Tags
  - HTML ID
* Advanced
  - Cloud configuration
  - Template settings
  - Authentication requirement
  - Export configuration
* Thumbnail

Provides the following page policy (aka design dialog) options:
* Main tab
  - Client libraries
* Styles tab

Requirements:
* Extends the base or core page component.
* Functions with Editable Templates.
* Inlines all CSS into the HTML output on a STYLE element that is then further inlined as STYLE attributes on the individual elements by the CSS inliner rewriter.
* Includes no JS from any of the included clientlibs.
* Pre-header adds the entered content at the top of the page body as follows:<br>`<span style="display: none; …">${page.preheader}</span>`

## Container component

Provides a simplified responsive grid behavior that is made out of 6 columns.

Provides the following edit dialog options:
* Main tab
  - Layout that is limited to following column split-up:
    - full-width (1)
    - half | half (3-3)
    - one-third | two-third (2-4)
    - two-third | one-third (4-2)
    - third | third | third (2-2-2)
  - Background color
  - Background image
  - HTML ID

Provides the following page policy (aka design dialog) options:
* Allowed components
* Default components
* Responsive
  - Maximal page width in pixels (defaults to 640px)
  - Breakpoint below which the layout is made linear (defaults to 480px)
* Background
* Styles

Requirements:
* All components on the page must be placed inside a grid to ensure consistent rendering on email clients.
* The grid is not allowed of being nested.
* The grid has a fixed number of 6 columns and a limited number of ways to distribute them into 2 or 3 columns (see edit dialog options).

The grid would not allow being nested and would have the following breakpoints:
* Above the maximal width configured in the policy (e.g., above 640px): The content doesn't further extend and is centered in the middle of the viewport.
* Between the maximal width and the breakpoint width (e.g.: between 640px and 480px): The layout is stretched down to the viewport width.
* Below the breakpoint width (e.g., below 480px): The layout breaks into a linear representation where the columns displayed one after the other vertically, and the content continues to be stretched down.

This typically is achieved with the following markup for an example one-third two-third ratio:

```html
<!-- In the page head: -->
<style>
    @media screen and (max-width: 640px) {
        .layout {
            width: 100% !important;
        }
    }
    @media screen and (max-width: 480px) {
        .layout-column {
            display: block !important;
            width: 100% !important;
        }
    }
</style>

<!-- In the page body: -->
<center>
    <table class="layout" width="640" border="0" cellpadding="0" cellspacing="0" role="presentation">
        <tr>
            <td width="33.33%" class="layout-column">
                One Third
            </td>
            <td width="66.67%" class="layout-column">
                Two Third
            </td>
        </tr>
    </table>
</center>
```

## Title component

Same as the core title component.

## Text component

Same as the core text component.

Requirement:
* Capability to use the Campaign personalization fields in the RTE.

## Image component

Simple image element.

Provides the following edit dialog options:
* Asset tab
* Metadata tab
  - Image is decorative (when checked, adds `role="presentation"` to the `img` element)
  - Alternate text (with an option to get it from DAM)
  - Link (adds `<a href>`)
  - Width (in pixels)
  - Scale image to available width (when checked, adds `style="width: 100%;"`)
  - HTML ID

Provides the same page policy (aka design dialog) options as the core image component, minus the smart and lazy loading options with responsive resizing.

Requirements:
* The image must not require any JavaScript on the publish instance.
* It must allow specifying a width in pixels and it will compute the corresponding height in pixel for the HTML output.

## Button component

A call-to-action link.

Edit dialog options:
* Text (capability to use the Campaign personalization fields)
* Link (capability to use the Campaign personalization fields)

# Phase 2

More advanced email editing capability.

## General

* Avoid any DIV output as much as possible as they add uncontrolled spacing in several email clients.

## Content fragment component

Allows embedding a Content Fragment in structured or text format.

Requirements:
* Option to embed the CF as single or as multiple elements.
* Disallow the possibility to insert in-between content.
* Avoid any DIV to be added to the output.
* Capability to use the Campaign personalization fields in the RTE of the CF.

## Experience fragment component

Allows embedding an Experience Fragment in the email.

Requirements:
* Limits to the maximum the number of DIV inserted in the output by the XF component.
* This also requires an XF Page component that is adapted for email.

## Teaser component

A combination of title, text, image and call-to-action.

Requirements:
* Capability to display the image as a background image or as a regular image.
* Capability to use the Campaign personalization fields in the RTE for the description.

**Comment by chrisjejbrown** [comment]
Any idea what the target delivery date for email components is?

**Comment by user37user37** [comment]
@chrisjejbrown This is still under discussion with no info on dates etc. If you have customers requiring this reach out to your Adobe Account team for your feature requests and business case.

**Comment by gabrielwalt** [comment]
This has been moved to its specific GitHub, and the content of this issue has been copied over to its wiki: https://github.com/adobe/aem-core-email-components/wiki
