### ISSUE TITLE
[Download] title is taken from properties title when asset title is empty 

### ISSUE THREAD

**Issue by natashadark** [adobe/aem-core-wcm-components#919]
## Bug Report
**Steps to reproduce:**
1. Go to assets 
2. Hover on some file and click "Properties" button
3. When your navigate to metadataeditor page, DELETE the TITLE of the asset 
4. Click "Save & Close" button 
5. Go to the Download component
6. Select the component and click "Configure" button
7. In Asset tab, Upload the asset
8. Click the "Properties" tab and populate Title input
9. Click "Submit" button 
10. Select again the Download component and click "Configure" button
11. Select the "Properties" tab 
12. Click the checkbox "Get title from DAM asset"

**Current Behavior**
Title from "Title - Properties tab" is shown 

**Expected behavior/code**
Title form page properties shouldn't be shown, as asset title is empty

**Environment**
- AEM version and patch level (e.g. AEM 6.5 SP1 CP3)
- Core Components version (e.g. 2.8.0)
- JRE version (e.g. `Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)`)

**Comment by jakublamprecht** [comment]
As far as I know the same happens for alternative text in Image component - if alt property is added on image component node, and it's checked to get value from DAM, then if value in DAM is empty, the value from node propety will be used instead.

**Comment by vladbailescu** [comment]
Fix merged to `master` in f9a69b8
