### ISSUE TITLE
[Embed]  Allowed Embeddables are not supported in Design Mode

### ISSUE THREAD

**Issue by manojBabuDev** [adobe/aem-core-wcm-components#931]
When I am trying to author embed component. In"embeddable" tab I don't see any options available. According to Embed Core component documentation. YouTube has to show up by default
https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/embed/v1/embed

So I debugged a bit in the dialog it's trying to get options form "core/wcm/components/embed/v1/datasources/allowedembeddables" , "core/wcm/components/embed/v1/datasources/allowedembeddables" which is registered as a servlet.

In servlets, I see the current source is expecting a content policy. or else empty list is returned

https://github.com/adobe/aem-core-wcm-components/blob/fcf28dd899b91ddcd58185264d5351f8ea82244d/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/AllowedEmbeddablesDataSourceServlet.java

https://github.com/adobe/aem-core-wcm-components/blob/fcf28dd899b91ddcd58185264d5351f8ea82244d/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/embed/EmbeddableOptionsDataSourceServlet.java

In our case, We do not have editable templates yet. So will the dropdown always be an empty list? 

**Expected behavior/code**
Work for regular page templates.

**Environment**
- AEM 6.4.4
- Core Components version 2.8.0

![embed component error](https://user-images.githubusercontent.com/45601335/75052889-f675d880-5495-11ea-918d-8be057800e95.PNG)

**Comment by bpauli** [comment]
I was able to reproduce the issue. Even when youtube is added to the Allowed Embeddables in Design Mode, it's not provided in the Edit Dialog of the component.

**Comment by manojBabuDev** [comment]
Thanks for looking into this.
