### ISSUE TITLE
[Accordion] Unable to add items into Accordion component in SPA Editor (Angular)

### ISSUE THREAD

**Issue by claudiab** [adobe/aem-core-wcm-components#934]
Issue with proxy version of the Accordion component in Angular SPA Editor. The child does not load and  I'm unable to new add components. Is this related to Edit configs (eg. listeners) not being supported in the SPA Editor?  Is there a possible workaround?

**Current Behavior**

Proxy Component:  core/wcm/components/accordion/v1/accordion

1. Create an Angular Front-End project with archetype 23

mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=23 \
 -D aemVersion=6.5.2 \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
 -D frontendModule=angular \
 -D includeExamples=y

1a.  Navigate to ui.frontend
2. Create a dummy component for accordion 
ng g c components/accordion --module app.module

2a. [Map AEM Accordion Component](https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-spa-wknd-tutorial-develop/angular/chapter-3.html) to Sample Angular Accordion component 

<img width="688" alt="Screen Shot 2020-02-24 at 1 35 21 PM" src="https://user-images.githubusercontent.com/773758/75184913-cbe08580-570a-11ea-874f-111900e6dd20.png">

2b. Add AccordionComponent to entryComponents

<img width="1194" alt="Screen Shot 2020-02-24 at 1 34 09 PM" src="https://user-images.githubusercontent.com/773758/75185219-4e694500-570b-11ea-9a16-220bb2d18bd3.png"> 

3. Enable All "My Site - Content" components at http://localhost:4502/editor.html/conf/mysite/settings/wcm/templates/spa-page-template/structure.html

4. Drop Accordion into SPA Editor

![Screen Shot 2020-02-24 at 1 35 21 PM (2)](https://user-images.githubusercontent.com/773758/75185394-a011cf80-570b-11ea-936e-6f93f93f1e5a.png)

View from CRX
<img width="961" alt="Screen Shot 2020-02-24 at 1 50 38 PM" src="https://user-images.githubusercontent.com/773758/75186497-98ebc100-570d-11ea-92c1-37c3ca185a68.png">
<img width="846" alt="Screen Shot 2020-02-24 at 1 50 33 PM" src="https://user-images.githubusercontent.com/773758/75186507-9d17de80-570d-11ea-95f2-5fbb4cd135e8.png">

**Expected behavior/code**

I'm able to run AEM Core Components (2.8.0) locally to test expected functionality.
http://localhost:4502/editor.html/content/core-components-examples/library/accordion.html

![Screen Shot 2020-02-24 at 1 25 49 PM (2)](https://user-images.githubusercontent.com/773758/75185545-e830f200-570b-11ea-9657-aab41d44300b.png)

**Environment**

AEM (6.5.2.0)
Core Components version 2.8.0
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)

**Comment by gabrielwalt** [comment]
Hi @claudiab, thank you for the detailed bug report! We'll have to investigate this issue as it seems likely that it is located in the SPA Editor rather than in the Core Component. For this reason, and if this issue is blocking your project, I'd recommend to also open a DayCare issue for it; you can just link to this one issue if you don't want to repeat the same details there.

**Comment by pfauchere** [comment]
@claudiab here are quick hints. 

* In 2a, you'll probably have to provide the logic and presentation of the frontend Accordion component.
* Under step `View from CRX`, I am not expecting the listeners to be of any help with the SPA Editor. Once the dialog is submitted the Editor is supposed to fetch the new model of the Accordion component and pass it to the SPA Model Manager that will trigger the component to be redrawn. Furthermore, I would say that using the listeners may actually be counter-productive as the SPA framework should have total control over the lifecycle of its components.

Looking at the ticket, I am expecting that what you actually are missing is the implementation of the Accordion Front-End component, how it consumes the model and how it displays the content.

**Comment by gabrielwalt** [comment]
It seems that this is working as designed and that there are parts missing on your client-side implementation, @claudiab. I'm therefore closing this issue for now, but please reopen it if if you encounter further issues.
