### ISSUE TITLE
Authoring UI functionality is included in "site"-clientlib for carousel

### ISSUE THREAD

**Issue by henrykuijpers** [adobe/aem-core-wcm-components#936]
https://github.com/adobe/aem-core-wcm-components/blob/c69fdc63fc0f2fb122d65eb4091d9bef872e09fb/content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/clientlibs/site/js/carousel.js#L124

This functionality should be removed from this clientlib, since it is specific for the author environment.

**Comment by gabrielwalt** [comment]
Hi @henrykuijpers,

You're right that this code should be broken apart in a way that it is not be loaded on the publish instances. This would require the creation of a new set of a `sites-editor` client libraries that are loaded on the site, but only on the author instance. However, I'd rather consider this a nice-to-have improvement, which means that it won't be our priority to address this request.

I'd like to encourage you to make a pull request to improve this, or else we will close this issue.

**Comment by gabrielwalt** [comment]
I'm closing this issue for now as we don't have the bandwidth to address it in the foreseeable future. Please reopen this issue if you have a PR.
