### ISSUE TITLE
[Accordion] Allow link configuration for Accordion Headings

### ISSUE THREAD

**Issue by abhishekagg19** [adobe/aem-core-wcm-components#938]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, Accordion Heading is displayed as text. Sometimes accordion is used in footer and Heading needs to be a configurable link.

**Describe the solution you'd like**
Enable configuring of heading link through Design Dialog. If Heading link is enabled, author should get a path browser field to configure the URL and an optional dropdown to select target window.

**Are there alternatives?**
No alternate available

**Documentation**
If you can, explain how users will be able to use this and possibly write out a version of the docs.
Maybe a screenshot or design?

**Comment by gabrielwalt** [comment]
Hi @abhishekagg19, I’m not sure to understand what use-case you’re intending to require the accordion headings to also provide a link. The headings are meant to fold and unfold their containers, not to link to anything else. Maybe you’re attempting to build a collapsible menu with the accordion? But this is not the intended use for the accordion component, and if that’s the case, you should probably use the navigation component and augment it with some custom JS code that adds the collapsing behavior.
