### ISSUE TITLE
[RTC] PDF Viewer Component

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-core-wcm-components#944]
## Description

As an author, I want to insert a PDF on a page, so that the visitors can easily view it without having to download it.

A PDF Core Component that uses the Document Cloud View SDK:
https://www.adobe.io/apis/documentcloud/dcsdk/viewsdk.html
This component should mostly generate the well-defined HTML embed markup:
https://documentcloud.adobe.com/view-sdk-demo/index.html

This should be a dedicated component and not use the embed component, because we want to have the possibility to add more features to this component than the embed component might allow: it will require to centrally configure the API for a site (via an OSGi or a cloud configuration), and later we may want to add more than one edit dialog tab, or to configure and to define defaults in a design dialog.

## Edit Dialog Properties

* PDF Path Selector (to PDF stored in AEM Assets)
* Embed Mode: Full-Size, Sized Container, In-Line
  * Full-Size case:
    * Default View: Fit Width, Fit Page
    * Annotation Tools: On, Off
    * Left Hand Pane: On, Off
    * Download PDF: On, Off
    * Print PDF: On, Off
    * Page Controls: Dock, Undock, Off
  * Sized Container case:
    * Display Height (px)
    * Download PDF: On, Off
    * Print PDF: On, Off
    * Full Screen Mode: On, Off
    * Page Controls: Dock, Undock
  * In-Line case:
    * Download PDF: On, Off
    * Print PDF: On, Off

## OSGi Configuration Panel

* Document Cloud View SDK Client ID Input
* Adobe Analytics Report Suite ID “reportSuiteId” Input

**Comment by l-c** [comment]
Could I get access writes to push my branch and create the PR ?
