### ISSUE TITLE
[Navigation] Navigation doesn't show original title of redirecting page

### ISSUE THREAD

**Issue by 3ch023** [adobe/aem-core-wcm-components#945]
## Bug Report

**Current Behavior**
For redirecting page Navigation shows target page title instead of the original page title.
When PageA redirects to PageB it is displayed in the Navigation as a PageB.
This leads to unexpected behavior when the Author configures the parent page to redirect to a child page.
 
Without redirect:
- Parent
    - Child

With redirect:
- Child
    - Child

**Expected behavior/code**
It should be possible to reflect real Site Structure in Navigation, even when using a redirect.
Redirecting page title is displayed in Navigation, while the link is a redirect target. 

**Environment**
- AEM 6.5.3.0
- Core Components version 2.8.0
- JRE 1.8.0

**Possible Solution**

One of the solutions is to add a checkbox to Navigation component dialog, which will prevent Navigation to treat the redirecting page as a redirect target. Something like "Disable Shadowing".
When the checkbox is checked the Navigation will display:
- Parent 
    - Child

Where parent link target is Child.

**Additional context / Screenshots**
This behavior happens in PageListItemImpl.java, line 45.
I assume it's needed for [Shadow Redirect Pages](https://docs.adobe.com/content/help/en/experience-manager-core-components/using/components/navigation.html#shadow-structure) to work. 

```
public PageListItemImpl(@NotNull SlingHttpServletRequest request, @NotNull Page page) {
        this.request = request;
        this.page = page;
        Page redirectTarget = getRedirectTarget(page);
        if (redirectTarget != null && !redirectTarget.equals(page)) {
            this.page = redirectTarget;
        }
    }
```

**Comment by vladbailescu** [comment]
Thank you for reporting this issue. We would greatly appreciate a contribution in form of a pull request for this as we currently don't have capacity to address this request in the near future.
