### ISSUE TITLE
[Teaser] - Title is not linked if first call-to-action is an external URL

### ISSUE THREAD

**Issue by kamalc007** [adobe/aem-core-wcm-components#948]
## Bug Report

**Current Behavior**
If the first call-to-action is an external link, Title is not linked. If the Link field is used instead of Call-to-action it works as expected.

**Expected behavior/code**
Title needs to be linked irrespective of whether the link is internal or external when using call-to-action.

**Environment**
- AEM 6.5.2
- Core Components version 2.8

**Possible Solution**
TeaserImpl.java lines 174-175. Defect could be in Utils.java

**Comment by vladbailescu** [comment]
@kamalc007 , thanks for the report. We will have a look at this. Meanwhile, we would greatly appreciate a contribution for fixing this, as a pull request; it will help speed things up.

**Comment by dymitrs** [comment]
@kamalc007 Are you sure that external links are properly working even when using Link field? For me that is not working. Only internal pages "/content/..." are resolved as they're using PageManager.
@vladbailescu Are you okay with reading <title> tag from an external link/page?

**Comment by vladbailescu** [comment]
@dymitrs, I think automatic title loading should only happen for internal/JCR content.

**Comment by bpauli** [comment]
merged to master in https://github.com/adobe/aem-core-wcm-components/commit/dc8a52b47180b2e9b636bfee553b7b29e200d880
