### ISSUE TITLE
Each clickable item should have an html ID

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#953]
All clickable items should have an html ID:
- links
- links added by authors with RTEs
- CTAs in a teaser
- buttons (carousel, accordion, tabs, ...)
- ...

This is needed when tracking data with a data layer.

The concept for generating such an ID might affect the deep-linking ID at:
https://github.com/adobe/aem-core-wcm-components/pull/946

This issue is about extending the concept that was applied in the PR #946 to fix ##942.

**Comment by jckautzmann** [comment]
Teaser

For the CTAs in a teaser component, we could add an ID to the HTL template using following format: `<teaser-ID>-action-<action-path-name>`.

cc: @rajramo61 @gabrielwalt @bpauli

**Comment by rajeevyadav2** [comment]
@jckautzmann : The static part of ID "-action-", can we have it consitent everywhere Eg. "-item-" or else this will Accessibility issue?

**Comment by jckautzmann** [comment]
This feature has been implemented as part of the data layer support in PR#949.
See details at:https://github.com/adobe/aem-core-wcm-components/pull/949#issuecomment-601652230

**Comment by rajramo61** [comment]
@jckautzmann Is someone already working on this issue?

**Comment by jckautzmann** [comment]
@rajramo61 yes, this issue has been fixed as part of PR #949 and will be available as soon as the PR is merged.

**Comment by jckautzmann** [comment]
This feature is now available on the `development` branch and will be released soon as part of 2.9.0.
