### ISSUE TITLE
[Search] Steals tab focus when in AEM Edit mode

### ISSUE THREAD

**Issue by CezCz** [adobe/aem-core-wcm-components#957]
#809  Bug Report

Reproduction steps:

- Go to /content/wknd/language-masters/en.html in edit mode (component is unclickable, because of editing overlay, you can try clicking on Editor global bar to speed up the process. The Search input should be then a few tabs away)
  - alternatively create a page with wcm/components/search/v1 and tab to it.
- Tab until you focus on the Search component 
- Notice you cannot escape with focus from the component

**Current Behavior**
After tabbing(focusing) to the search control, we cannot tab out of it.

**Expected behavior/code**
After subsequent tabs we would like to tab to next focusable elements.

**Environment**
- AEM version - Any
- Core Components version - 2.8.0
- Chrome 80.0.3987.149
- Firefox 73.0.1

**Possible Solution**
https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/clientlibs/site/js/search.js#L264

value of this._elements.results.style.display is "" in edit mode. 

This causes:

https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/search/v1/search/clientlibs/site/js/search.js#L210

To pass, and trigger preventDefault.

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by vladbailescu** [comment]
Fixed by #1487
