### ISSUE TITLE
Image lazy loading not working correctly with Panel Containers

### ISSUE THREAD

**Issue by msagolj** [adobe/aem-core-wcm-components#966]
Images lazy loading works incorrectly on a tab that is initially hidden. the image is not shown until you scroll the page (although it's in the viewport from the very beginning)

**Steps to reproduce**

* Add a Tabs core component to a page
* Create at least 2 tabs in the component
* Put an Image core component to the tab that's initially hidden
* Set the image's lazy loading to true (This can be done by editing the page template, then set the Lazy loading to true in the Image component policy)
* View the page as published; the tab with the image is initially inactive
* Switch to the tab with the image

**Expected Behavior**
The image is shown

**Experienced Behavior**
The image is not shown until you scroll the page (although it's in the viewport from the very beginning)

Environment Details: vanilla OOTB AEM 6.5.3

Affected AEM release ID: AEM 6.5.3, 6.5.4
Tested with AEM release ID: AEM 6.5.3, 6.5.4

(CQ-4292328)

**Comment by godanny86** [comment]
@msagolj I also believe the Carousel component has a similar problem. Should I file a second issue or can it be covered in this one?

**Comment by msagolj** [comment]
@godanny86 thx for the info. I assume its the same issue, so lets keep only this one for now. I will also check the other panel container, accordion, but it looks like this one is working ok.

**Comment by nishi0309** [comment]
Is this issue resolved? Image lazy loading in Tabs/Panel containers?
