### ISSUE TITLE
Experience Fragment not picked up by the Publish Page workflow/logic

### ISSUE THREAD

**Issue by robertbita** [adobe/aem-core-wcm-components#967]
**Issue**
Experience Fragment doesn't get picked up by the Publish workflow if the Experience Fragment is not Published yet. The foundation/general Experience Fragment works as expected.

**Steps to reproduce**
Add the core Experience Fragment component to a page and pointed to an Experience Fragment which was not published. 
Publish the page.
You should get prompted if you want to publish the Experience Fragment as well.  

I have uploaded two screenshots: one that uses the foundation/general EF and one with the core EF.
<img width="1434" alt="Screenshot 2020-04-01 at 17 48 47" src="https://user-images.githubusercontent.com/35493523/78164210-53738f80-7441-11ea-9fa5-52ec6d4e29a7.png">
<img width="1431" alt="Screenshot 2020-04-01 at 17 52 12" src="https://user-images.githubusercontent.com/35493523/78164475-b49b6300-7441-11ea-876d-52567e4f6f17.png">

**Comment by msagolj** [comment]
Hi @robertbita,
I tried to reproduce your issue but it seems to work for me. I attached a video of my steps. Will close issue for now, please free to reopen if i missed/missunderstood something.

[unpublished_fragment.zip](https://github.com/adobe/aem-core-wcm-components/files/4421402/unpublished_fragment.zip)

**Comment by robertbita** [comment]
Hi @msagolj ,
Thanks for your response and time.
After updating to Service Pack 6.5.5.0 it's working, so yes happy to be closed :)
