### ISSUE TITLE
Link Core Component XD UI Kit from Core Component Library

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-core-wcm-components#971]
The Core Components XD UI Kit [1] should be hosted on and linked from the Core Components Library site and/or a more obvious/official place than the AEM Sites tutorial [1] overview page. It makes sense that the Web site dedicated to the visualization of the Core Components would have the XD UI Kit. (its the first place I looked, and then only saw "buried" it in in this README later on)

Also, this XD UI Kit probably should be hosted someplace more centrally (ex. This project Github, or on the Core Component Library page site [2]) 

[1] https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/assets/overview/AEM-CoreComponents-UI-Kit.xd
[2] https://www.aemcomponents.dev/

**Comment by gabrielwalt** [comment]
+1, I agree, we'll do that!

**Comment by thinkstainless** [comment]
On another note, we should have the UI styles shown in the sample aemcomponents.dev site match the visuals for what is displayed in the UI Kit for consistency and clarity for users.

**Comment by gabrielwalt** [comment]
Closing this for now as this is part of a larger effort that is tracked separately.
