### ISSUE TITLE
Wrong packageType given in core.wcm.components.config-2.8.0.zip 

### ISSUE THREAD

**Issue by kwin** [adobe/aem-core-wcm-components#973]
Although there is no explicit package type given in https://github.com/adobe/aem-core-wcm-components/blob/55c282f9e4a4eaf89f0cf8fea3914ebca4a69a28/config/pom.xml#L54 the underlying maven plugin sets `<entry key="packageType">application</entry>` in `META-INF/vault/properties.xml` of the ZIP uploaded to Maven Central (https://repo.maven.apache.org/maven2/com/adobe/cq/core.wcm.components.config/2.8.0/core.wcm.components.config-2.8.0.zip) which violates the package type spec at https://issues.apache.org/jira/browse/JCRVLT-170. Instead OSGi configs are only allowed in packages of type `container`!

**Comment by kwin** [comment]
Compare with https://issues.apache.org/jira/browse/JCRVLT-431

**Comment by kwin** [comment]
This should be fixed by https://github.com/adobe/aem-core-wcm-components/pull/955/files#diff-d900a6fa9652d119b25489783f0162c3R59 as well!

**Comment by msagolj** [comment]
@kwin thx for the update. As it will be fixed as part of #955 I set it in review.
