### ISSUE TITLE
[Form] Option Fields is missing required constraints

### ISSUE THREAD

**Issue by PPoetsch** [adobe/aem-core-wcm-components#984]
## Feature Request
Form options should have also the possibility be a required field.

**Is your feature request related to a problem? Please describe.**
It's a business requirement for my current project.

**Describe the solution you'd like**
Like in the text form field the tab required should be available.

**Are there alternatives?**
None

**Documentation**
I thinks it's not necessary.

**Comment by msagolj** [comment]
@PPoetsch without knowing your business requirement, I assume you mean required when using type `Checkbox` or `Multi-select drop-down`, as the other two, `Radio Button` and `Drop-down` are 'required' since they enforce a choice.

In that context e.g. of checkbox group, what would required mean ? at least x selected ? Maybe you can provide an example of your business requirement to better understand your needs.

**Comment by PPoetsch** [comment]
Thanks @msagolj for you fast reply. 
Yes, we need the checkbox field type a lot for things like confirmation of legal things like data privacy. So the most often use case it's only one checkbox which has to be a required field

**Comment by msagolj** [comment]
@PPoetsch thanks for explaining your use cases. I agree, the 'confirmation of legal things' is a common use case for required checkboxes. Might even be worth to get his own core component. We will have a look at it in the next sprint planning. Marking as enhancement with milestone 'future' for now.

**Comment by satishkumarjadhav** [comment]
@msagolj  : Could you please let us know if this enhancement was prioritized in your sprint planning ?   Because we are in-process of development for this enhancement and would like to contribute .

**Comment by vladbailescu** [comment]
@satishkumarjadhav , we haven't prioritised this yet. We would greatly appreciate a contribution on this.

**Comment by gabrielwalt** [comment]
Closing this as #1153 duplicates this with a pull request.
