### ISSUE TITLE
[Container] Make the panel items editor available on containers

### ISSUE THREAD

**Issue by yeshwanth-peddireddy** [adobe/aem-core-wcm-components#985]
## Feature Request
<strong>Is your feature request related to a problem? Please describe.</strong>
I'm trying to use the children editor of the core carousel with my own component which is a container component with children in it. I'm not able to use this unless I use the core Carousel, Accordion as the supertype. 
![Screen Shot 2020-04-14 at 1 12 35 AM](https://user-images.githubusercontent.com/56695368/79201675-49f90880-7ded-11ea-84eb-1cf794de533b.png)
![Screen Shot 2020-04-14 at 1 15 18 AM](https://user-images.githubusercontent.com/56695368/79201776-6bf28b00-7ded-11ea-950f-115dfc98d0ab.png)

**Comment by msagolj** [comment]
@yeshwanth-peddireddy can you please check #696 and #882, maybe they already answer your question ?

**Comment by yeshwanth-peddireddy** [comment]
#882 is what I'm looking for. I've tried #696 and the issue posted there is same as mine. The Panel Container by itself would we very useful. Using accordion,tabs, or carousel forces me to use something I don't need.

**Comment by msagolj** [comment]
@yeshwanth-peddireddy thanks for checking. Marked this issue as an enhancement.

**Comment by yeshwanth-peddireddy** [comment]
@msagolj Thank you

**Comment by DavidAtWorking** [comment]
May I ask the status of this ticket? Is this component fixed?

**Comment by jckautzmann** [comment]
Our team is not planing to work on this feature in the near future.
@DavidAtWorking If you have a pressing need for it, you may want to provide a pull request.

**Comment by gabrielwalt** [comment]
The core component team currently doesn't have the bandwidth to address this issue in the foreseeable future. Please clone or reopen this issue in case you'd like to contribute such a feature to the Core Components.
