### ISSUE TITLE
Snapshot version in the Maven artifactory

### ISSUE THREAD

**Issue by AntonValadzko** [adobe/aem-core-wcm-components#987]
## Bug Report

**Current Behavior**
Our application started to download 2.8.1-SNAPSHOT-20200410121300 version during the build. Was it expected to have this version in the artifactory? 

![image](https://user-images.githubusercontent.com/6346581/79267429-cf3df500-7ea1-11ea-817c-0e27f84f3418.png)

Maven dependency:
```
           <dependency>
                <groupId>com.adobe.cq</groupId>
                <artifactId>core.wcm.components.all</artifactId>
                <version>[2.2,3)</version>
                <type>zip</type>
                <scope>provided</scope>
            </dependency>
```

**Comment by vladbailescu** [comment]
That was me trying to do a locked snapshot deployment for a test project. Unfortunately it ended up in the releases repo, instead of the snapshot one. I don't have any way to remove it now but you could update your version range to `[2.2,2.8.1)`. Sorry for the inconvenience!

**Comment by kwin** [comment]
@vladbailescu You can open a ticket with https://issues.sonatype.org/projects/OSSRH/issues to get that wrong version being removed!

**Comment by vladbailescu** [comment]
@kwin They can probably remove it from OSSRH but it might still be cached elsewhere. See also  https://issues.sonatype.org/browse/OSSRH-35544?focusedCommentId=443339&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-443339
